### ISSUE TITLE
Asset Subdirectory only - without the project files

### ISSUE THREAD

**Issue by xfleckx** [ValveSoftware/steamvr_unity_plugin#10]
Hy,

nice job so far, thanks for publishing and maintaining this package. :)

Is there a reason why we need the Unity project folders (Assets & Project Settings)?

What would speak against just using the SteamVR directory? 
So it could be used as a git submodule, which is not possible with the current structure of the repository!?

kind regards
M

**Comment by aleiby** [comment]
I just took what was included in the SteamVR plugin on the Asset Store.  If it'll make it easier to strip off that top level, then I can do that in the next update.
