### ISSUE TITLE
Fixed: Unity SteamVR emulator can publish webGL

### ISSUE THREAD

**Issue by jensteinkamp** [ValveSoftware/steamvr_unity_plugin#1003]
Here is how you can publish webGL with Unity and the steamVR emulator:
This uses the steamVR tools to make cool webGL interactive web pages.

webGL should be installed from the Unity Hub
1) Fix SteamVR Newton script
Under the Project tab select Assets/SteamVR/Input/Plugins/JSON.NET/Valve.Newtonsoft.Json.dll  (search for Newton)
In the Inspector put a checkmark next to WebGL

2) Remove OpenVR XR Plugin
Select Window->Package Manager
     Select and Remove the OpenVR XR Plugin
(You can always reinstall for VR)

3) Build Your Scene for WebGL Publish
Select File->Build Settings...

Fix some issues:
Select Player Settings... Button 
  Select Player Section
     Under Other Settings
          Select Color Space to Gamma   (default Linear)
          Make sure Auto Graphics API is selected (default selected)
          Change Lightmap Encoding to Normal Quality   (default High Quality)
     Under Publishing Settings
          Change Compression Format  to Disabled  (default Gzip)
     Close Project Settings

Select WebGL
     Select Switch Platform

Select the Build And Run button

Complete directions:
http://users.design.ucla.edu/~cariesta/MayaCourseNotes/html/unity_steamvr_setup_from_scratch.html

**Comment by kisak-valve** [comment]
Hello @jensteinkamp, this feedback is more suitable for the forums instead of this issue tracker.

**Comment by jensteinkamp** [comment]
Thanks I left a note here since I reported the bug last month. I also just posted on the SteamVR forum. FYI SteamVR is a really good way to make 3D interactive web pages.
