### ISSUE TITLE
Black screen with Unity 2019.4 using latest Steamvr version

### ISSUE THREAD

**Issue by dpggit** [ValveSoftware/steamvr_unity_plugin#1004]
Hello,
I am seeing a black screen in Unity, gives me a "Failed to load OVRPlugin.dll", seems it is trying to use the oculus plugin and SteamVR doesn't load as it did before updating to Unity 2019.4 and to the new Steamvr version too, so now i just can see the default black screen cause didnt load SteamVR

**Comment by duckingwhimsical** [comment]
Hiya, have you updated your version of the SteamVR Unity Plugin from the asset store as well as SteamVR from Steam? What version does your SteamVR Plugin say it is? (/Assets/SteamVR/readme.txt)

**Comment by zite** [comment]
Hiya, have you updated your version of the SteamVR Unity Plugin from the asset store as well as SteamVR from Steam? What version does your SteamVR Plugin say it is? (/Assets/SteamVR/readme.txt)

**Comment by kisak-valve** [comment]
Closing pending feedback.
