### ISSUE TITLE
Fully disable SteamVR Unity plugin so it doesn't mess with other platforms?

### ISSUE THREAD

**Issue by ThomasMountainborn** [ValveSoftware/steamvr_unity_plugin#1005]
I'm using Unity's cross platform tools and OpenXR for my game, Vermillion. However, to record LIV footage, I've had to implement OpenVR, and thus the SteamVR SDK. Now though, it's no longer possible to run on OVR - SteamVR always starts itself up, playing "Oculus Plugin", causing the game to not function (laggy HMD tracking, no controller tracking). Unity is set to only use the Oculus plugin, not OpenVR. The SteamVR settings object is set not to start VR automatically. How do I keep it from interfering when it's unwanted?

**Comment by zite** [comment]
Hi, sorry to hear about this. If you can let me know what versions of everything you're using I'll investigate. SteamVR, SteamVR Unity Plugin (first line in the readme), and Unity

**Comment by ThomasMountainborn** [comment]
Hi, thanks for your response! SteamVR 1.20.4, SDK v2.7.3 (1.14.15), Unity 2021.2.6f1

**Comment by ThomasMountainborn** [comment]
Just dug into this more. It only happens when using the OpenXR backend of OVR, by activating the OpenXR libraries using the Oculus SDK, with Oculus selected as the XR provider in Unity, but SteamVR as the system OpenXR runtime. With Oculus as the system OpenXR runtime, it does run without SteamVR, and when using the libOVR backend it again runs as a classic OVR app. So I guess the issue does not lie with the SteamVR SDK!

**Comment by zite** [comment]
Ah thanks for figuring this out!
