### ISSUE TITLE
Open VR API not working on Mac OS Unity

### ISSUE THREAD

**Issue by mikevadeyo** [ValveSoftware/steamvr_unity_plugin#1009]
Constant error...
DllNotFoundException: openvr_api assembly:<unknown assembly> type:<unknown type> member:(null)

Starting late 2021 Steam VR plug-in has stopped working for me. I am getting multiple console error messages and cannot create a build of the project. I have swapping the project for older versions but nothing has helped. I'm running the project on Mac OS 10.15.7 on Unity 2021.2.9f1 I have tried uninstalling and re-installing Steam VR through the package manager, back end drag, and drag git repository files in project assets folder. 

The package brings up errors when I bring in the camera/controls prefab object. This package asset did work for me at one time but is now dysfunctional in this project and another dummy project I made. 

<img width="1440" alt="Screen Shot 2022-01-28 at 12 56 43 PM" src="https://user-images.githubusercontent.com/70594442/151597751-f47eaf49-fd05-4d3c-a42b-bdac3609f3ee.png">

Not sure what to do here? Everything is prefab still. I have not edited any of the source code for these assets.

**Comment by zite** [comment]
Unfortunately this plugin, and SteamVR in general, no longer support Mac OS. https://store.steampowered.com/news/app/250820/view/2216278054495230717
