### ISSUE TITLE
scene loading issue ( freeze in 99% progress bar)

### ISSUE THREAD

**Issue by BellachhebKhalid** [ValveSoftware/steamvr_unity_plugin#1010]
- Hey Guys! I'm working on a VR game and i get this problem when using SteamVR_LoadLevel script.I set up everything correctly but when i want to move from Scene1 to Scene2, I can't, I still in transition scene with 99 % in progress bar.

- Please find attached the link to this problem : https://drive.google.com/file/d/1g5sRSeJzmQgLfmqgnngyKAarhxVXO_Hw/view?usp=sharing

- for information : 
    - OS : Windows
    - Unity : 2020.3.13f1
    - steamvr : SteamVR Unity Plugin - v2.7.3 (sdk 1.14.15)
    
- Any help or suggestion will be appreciated 

- Thank you a lot for your help :)

**Comment by zite** [comment]
DId you end up getting this resolved? Were there any errors / warnings in the console?

**Comment by BellachhebKhalid** [comment]
Thank you for reply, i finished up by solving this problem, it was an error bug.
