### ISSUE TITLE
Controllers (and trackers) become offset - only way to fix is to leave the room so they lose tracking, then re-enter the room.

### ISSUE THREAD

**Issue by guiglass** [ValveSoftware/steamvr_unity_plugin#1013]
sometimes if my controllers loose tracking they return but are offset randomly. They often stay that way requiring me to leave the room for ten seconds then re-enter, or I can throw a blanket over the wonky tracker to force it to re-calibrate. 

I am a indie game dev and am working on a game that requires reliable tracker positions, especially just as the game starts. I was wondering if there are any commands I could send to OpenVR to force all trackers to recalibrate either by the user's request or at a critical time in the game. 

What is happening to the trackers when a blanket covers them momentarily? I mean it fixes them every time! I want to invoke this behavior programmatically from Unity. Is it possible ??

**Comment by zite** [comment]
Sounds like you have a bad base station or tracker. I'd recommend contacting steam support and asking them for a fix. There is no command that will recalibrate bases or trackers from unity.

**Comment by zite** [comment]
Are you saying that the error is not tracker specific? That the issue happens on all of your trackers, just at different times? If that's the case an isolated SteamVR System Report would be helpful. If you can, start up steamvr, don't launch anything, get into a situation where the tracker is offset significantly, fix it, then create a steamvr system report. Also a report where you don't fix it would be helpful to compare.

I can get this information and pass it on to someone who may be able to look in to it but unfortunately there is no OpenVR API call to recalibrate lighthouse devices. And as trackers are not made by Valve if it is a hardware issue we likely can't fix it.
