### ISSUE TITLE
Use legacy input bindigs as fallback to unbinded controllers

### ISSUE THREAD

**Issue by kfird214** [ValveSoftware/steamvr_unity_plugin#1019]
On our game, we are migrating to use the latest steam VR plugin.
We didn't update it for years... 😐

It seems like I have to have all of the controllers possible just so I can bind them to my custom action set (please tell me I'm wrong).
We created custom bindings set because the default is missing some simple bindings we miss.

Is there a way to use the legacy input actions as a fallback, I know that there is a way to define your controller with legacy input bindings.
And for all of those VR headsets we don't provide our own bindings to, I want to still make them work the first time opening the game.

I didn't find any way to define a default input scheme for all controllers.
Say our game is out with those bindings, and there is a new VR headset on the market.
Our game would just not work on it?

Kinda a big issue, I didn't found any thig about it.
So I've thought I would post an issue here.

Thanks.

**Comment by roundyyy** [comment]
Same  problem and the same question here

**Comment by zite** [comment]
There are two options here. If you don't have a binding for a common controller, like Windows Mixed Reality, when you game launches SteamVR will inform the user that they don't have a binding and that they need to create one. It will show them the same input binding screen it shows developers. It will also let them pick from bindings that other users have created and saved.

Additionally, you can create bindings for controllers you don't have in the binding UI, you just won't be able to test them.

If it is a less common controller, like a Pico Controller for example, the manufacturer of that controller has the option to let it use bindings from another, like the Oculus Touch. In that scenario SteamVR will seamlessly use the oculus touch binding for the player's pico controller.
