### ISSUE TITLE
Is there an update route line available? (Considering the latest update was 23 Feb 2021)

### ISSUE THREAD

**Issue by genglyu** [ValveSoftware/steamvr_unity_plugin#1027]
Hi guys.
I am working on a VR project and I like SteamVR as a unity plugin a lot.
However, my team is concerned about whether SteamVR will keep on supporting its Unity plugin, which make it a little bit hard for me to convince the team we should use SteamVR.

And I am also curious about whether the update for SteamVR Unity plugin will keep on going. (Well, the features I was using work fine, maybe there is not a need to update?)

So will this keep going, or there will be no newer version of the SteamVR Unity plugin?

**Comment by zite** [comment]
If you're starting a new project we generally advise people to use Unity's OpenXR plugin. All of the major XR hardware vendors have committed to supporting OpenXR and are moving their runtimes in that direction. We'll generally do bug fixes for this plugin but we don't have plans for new features at this time.

**Comment by genglyu** [comment]
> If you're starting a new project we generally advise people to use Unity's OpenXR plugin. All of the major XR hardware vendors have committed to supporting OpenXR and are moving their runtimes in that direction. We'll generally do bug fixes for this plugin but we don't have plans for new features at this time.

Hi there.
Thank you for the information.
Em... then I guess it is better for us to stick with the OpenXR.
However, I do like the interaction system of SteamVR a lot, and the hand animation support for index controllers. Is there any realiable way to use them in the future?
