### ISSUE TITLE
Our app has VR and Desktop capabilities. closing SteamVR closes our app when we want to keep it open.

### ISSUE THREAD

**Issue by blackpandastudios** [ValveSoftware/steamvr_unity_plugin#103]
Basically we have a tool for architects that allows both desktop and vr users to interact with an environment simultaneously. However, when the architect has finished demo-ing the proposed project, and close steamVR. Our software will exit.

Is there a way to simply break the link between the app and steamVR and treat it just like a desktop application again? I think closing the window should be down to the developers, not brute forced by SteamVR.

Any advice?

**Comment by bddckr** [comment]
Depending on the application type you called
https://github.com/ValveSoftware/openvr/blob/6aacebd1246592d9911439d5abd0c657b8948ab0/headers/openvr.h#L4242-L4251
with the runtime won't quit your process:
https://github.com/ValveSoftware/openvr/blob/6aacebd1246592d9911439d5abd0c657b8948ab0/headers/openvr.h#L1245-L1261

That being said what works for me is polling the events, then responding to `VREvent_Quit` telling us about SteamVR shutting down first calling
https://github.com/ValveSoftware/openvr/blob/6aacebd1246592d9911439d5abd0c657b8948ab0/headers/openvr.h#L1868-L1870
to buy some time to call the following that in turn let's the runtime now we're no longer connected to it
https://github.com/ValveSoftware/openvr/blob/6aacebd1246592d9911439d5abd0c657b8948ab0/headers/openvr.h#L4253-L4255

**Comment by blackpandastudios** [comment]
Thank-you for the prompt reply!

So the only version of that event I can find is in the openvr_api.cs class:

`[UnmanagedFunctionPointer(CallingConvention.StdCall)]
	internal delegate void _AcknowledgeQuit_Exiting();
	[MarshalAs(UnmanagedType.FunctionPtr)]
	internal _AcknowledgeQuit_Exiting AcknowledgeQuit_Exiting;`

And the VR_Shutdown method cannot be found in code as it only exists in the .dll.
Any tips on how to achieve the same steps you listed above, but with the C# openvr_api?  

If i'm in the wrong place for asking this question let me know, I appreciate the help.

**Comment by bddckr** [comment]
It's just `OpenVR.Init`, `OpenVR.Shutdown` and the acknowledge method is here:
https://github.com/ValveSoftware/openvr/blob/6aacebd1246592d9911439d5abd0c657b8948ab0/headers/openvr_api.cs#L2003

It's pretty much the same through C# 😄

**Comment by blackpandastudios** [comment]
Ohhhh my bad! My search query for the method was just off so I didn't see it.

But yeah that is super simple. I don't know how I overlooked it.

Thanks again for the support. Feel free to mark this as closed I am fairly confident in sorting out the rest now. 😄

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by wuxiao0468** [comment]
Have you done it?
