### ISSUE TITLE
Assets\ThirdParty\SteamVR\Editor\SteamVR_AutoEnableVR_2019plus.cs(17,16): error CS0234: The type or namespace name 'InteractionSystem' does not exist in the namespace 'Valve.VR' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by Rail9** [ValveSoftware/steamvr_unity_plugin#1034]
https://github.com/googlevr/tilt-brush#enabling-native-oculus-support

If you open this project (Unity Version 2018.4.11f1) and upgrade to 2020.3.33f1

CS0117: 'VREditor' does not contain a definition for 'GetVREnabledDevicesOnTargetGroup'

The above error occurs, so I looked it up on Google: https://forum.unity.com/threads/steamvr-does-not-work.928503/

The solution is on this page? I found the solution on this page.

https://github.com/ValveSoftware/unity-xr-plugin
When I import this one and import the latest version of SteamVR, I get the error in the title.

Is there a solution?

**Comment by zite** [comment]
Open Brush is a community led fork, I'd recommend using that project. https://github.com/icosa-gallery/open-brush

**Comment by Rail9** [comment]
Thank you very much.

The problem has now been solved as I have created my own similar
application on my own due to the puzzling internal structure of OpenBrush.

Thank you for your attention to this question, which was asked quite some
time ago.

2022年10月11日(火) 18:18 Keith Bradner ***@***.***>:
