### ISSUE TITLE
Controller Initialization Issue on Build. 

### ISSUE THREAD

**Issue by theepicninja** [ValveSoftware/steamvr_unity_plugin#1051]
So I've created a game that functions perfectly in the editor, however when I build it, it throws me a NullReferenceException error. The Log tells me it is within the Initialize() function but since it is only an issue on build I don't
 really have any clue on how to fix it. I dont know what would be different between the build and the editor so I don't know how to bug test it effectively.

The issue begins at "<b>[SteamVR]</b> System.NullReferenceException: Object reference not set to an instance of an object."

Log Included. Any help would be greatly appreciated.
 
[Log.txt](https://github.com/ValveSoftware/steamvr_unity_plugin/files/8895083/Log.txt)

**Comment by zite** [comment]
Did you get this issue resolved?
