### ISSUE TITLE
Secandory action on button while other button is held down

### ISSUE THREAD

**Issue by Wildimp** [ValveSoftware/steamvr_unity_plugin#1056]
My goal is to have two different actions mapped on the same button and differentiate between them based on the state of another button. Basically the same as holding down the ctrl key on a keyboard alternates between copying and the letter c for example. (On windows). I want to achieve that i can use the GrabPinch for grabbing objects on the trigger but also a custom action while the left stick is pressed upwards.

I am using the latest version of the steamvr plugin (2.7.3) in unity 2020.3.8f1.

I tried to use the action sets but they are not meant to be used for holding down a button but instead for toggling between sets with the press of a button.

Is there any easy way to achieve this that i am missing?

**Comment by zite** [comment]
Sounds like a Chord might be what you want. You can create a chord in the binding UI to bind an action to a combination of multiple inputs.

**Comment by Wildimp** [comment]
Thanks a lot. That was excatly what I was looking for :)
For other people that might stumble over this thread here is some further information on how to use the chords:
https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/blob/master/docs/SteamVRInputGuide.md
