### ISSUE TITLE
OpenXR initialization issue

### ISSUE THREAD

**Issue by AleksanderPietrzak95** [ValveSoftware/steamvr_unity_plugin#1057]
While using Index HMD with knuckles controllers everything works until SteamAPI.Init(); was called. After this controllers return to zero position and are no longer tracked. Not initializing Steam makes everything work perfectly. We are using OpenXR with all necessary interaction profiles. What can be checked to fix the problem?

**Comment by AKATheBoss** [comment]
Did you solve this issue?
I'm having the same problem

**Comment by zite** [comment]
This is outside the scope of the SteamVR Unity Plugin. I'd recommend posting on the SteamVR Developer forums here: https://steamcommunity.com/app/250820/discussions/7/
