### ISSUE TITLE
SteamVR_ExternalCamera prefab has unreference script

### ISSUE THREAD

**Issue by chengnay** [ValveSoftware/steamvr_unity_plugin#106]
Since SteamVR_ControllerManager script is deleted in SteamVR 2.0, the SteamVR_ExternalCamera prefab is broken at this time.

**Comment by zite** [comment]
Thanks for the report. I believe I fixed this issue in one of the recent RCs. Let me know if this is still an issue and I'll reopen it.

**Comment by chengnay** [comment]
I just double check with the release version of SteamVR 2.0, the ExternalCamera.prefab is still has missing Mono script. Can you double check it? Thanks!
