### ISSUE TITLE
How can I find the audio driver/device names for a headset?

### ISSUE THREAD

**Issue by GabrielHare** [ValveSoftware/steamvr_unity_plugin#1061]
PROBLEM: I would like to find the speaker and microphone device/driver names for an attached VR headset.

EXAMPLE: My Vive Index headset has:
- Speakers = "Index HMD (NVidia High Definition Audio)"
- Microphone = "Digital Audio Interface (Valve VR Radio & HMD Mic)"

PROBLEM: Searching for "HMD" in the name is unreliable.

EXAMPLE: My Samsung Odyssey headset (WIndows Mixed Reality) has:
- Speakers = "Realtek USB2.0 Audio"

WORKAROUND: Ask users to select the correct audio devices, and then save that data.

**Comment by zite** [comment]
SteamVR itself should handle changing audio devices for the user. If you want to change them outside SteamVR that's outside the scope of the SteamVR Unity Plugin. I'd recommend you ask on the SteamVR Developer forums: https://steamcommunity.com/app/250820/discussions/7/
