### ISSUE TITLE
Error in GetScale method in SteamVR_Utils class

### ISSUE THREAD

**Issue by RomanArcadiaVR** [ValveSoftware/steamvr_unity_plugin#1062]
Hi!
I think the method GetScale from SteamVR_Utils class contains Error. Scale components should be calculated via Matrix4x4  as follows:
		var x = Mathf.Sqrt(m.m00 * m.m00 + m.m10 * m.m10 + m.m20 * m.m20);
		var y = Mathf.Sqrt(m.m01 * m.m01 + m.m11 * m.m11 + m.m21 * m.m21);
		var z = Mathf.Sqrt(m.m02 * m.m02 + m.m12 * m.m12 + m.m22 * m.m22);

**Comment by zite** [comment]
You're correct, I believe this has been fixed.
