### ISSUE TITLE
Wrong tracker center in rendermodel

### ISSUE THREAD

**Issue by biosmanager** [ValveSoftware/steamvr_unity_plugin#1065]
When using the rendermodel for either the 2.0 or 3.0 Vive tracker, it shows a wrong center point.
The manual clearly states that the tracking origin of the tracker is on the top of the ring surface around the camera screw.
<img width="611" alt="vive_tracker_manual" src="https://user-images.githubusercontent.com/9850952/184096315-47e8d413-e821-4c2c-8267-7fe989333777.png">

However, when loading the render model in Unity, it uses a different origin inside of the tracker body. I even checked the obj file in Blender and it seems the origin is also wrong for the mesh.

<img width="370" alt="vive_tracker_wrong_center" src="https://user-images.githubusercontent.com/9850952/184096493-72686708-83fd-412a-805e-0727fc41eb4f.png">
<img width="271" alt="vive_tracker_blender" src="https://user-images.githubusercontent.com/9850952/184096501-c6fc8d80-dcde-41ba-afbd-0363e5f90d3e.png">

Does anybody know if this is a bug? Or am I doing something wrong?

**Comment by zite** [comment]
I believe this is a problem with the manual and not SteamVR. The render model's pivot point is not necessarily what the driver reports.
