### ISSUE TITLE
How to remove SteamVR entirely

### ISSUE THREAD

**Issue by osorioavatar** [ValveSoftware/steamvr_unity_plugin#1066]
I have a game that's near completion and I wanted to add a VR mode so I imported everything into my project and tried playing but  I get these errors (The crossed out messages are of my game not VR)
![removevr](https://user-images.githubusercontent.com/112322750/187072403-0faf6462-cb22-4bec-af59-5f65a7106c1f.PNG)

I made a new HDRP project and added steamvr to it and it works properly there, so I don't know why it won't work on mine. The only think I can think of is I messed up the setup. If anyone knows how to fix those erros or alternatively, how to completely remove steamvr and adding it again it would be really helpful. I tried just deleting the steamvr folders but when importing again I don't get the prompts I got the first time to set up default settings.

**Comment by zite** [comment]
To get the defaults back copy the folder in \Assets\SteamVR\Input\ExampleJSON to \Assets\StreamingAssets\SteamVR. Then open the SteamVR Input window (in the Window toolbar) and click Save & Generate.

You'll also want to make sure you have the OpenVR package added in your package manager. If you're running Unity 2020+ add the tgz package in \Assets\SteamVR\OpenVRUnityXRPackage\Editor. If you're running a unity version before that (not using Unity XR) then add the OpenVR Desktop package from unity.

If using Unity XR make sure you have OpenVR selected in the XR Manager section of your project settings.

**Comment by osorioavatar** [comment]
Thank you! I don't know what I did wrong the first time but now I managed to make it work properly for my game. https://www.youtube.com/watch?v=ISVXOAiyB94

**Comment by osorioavatar** [comment]
> To get the defaults back copy the folder in \Assets\SteamVR\Input\ExampleJSON to \Assets\StreamingAssets\SteamVR. Then open the SteamVR Input window (in the Window toolbar) and click Save & Generate.
> 
> You'll also want to make sure you have the OpenVR package added in your package manager. If you're running Unity 2020+ add the tgz package in \Assets\SteamVR\OpenVRUnityXRPackage\Editor. If you're running a unity version before that (not using Unity XR) then add the OpenVR Desktop package from unity.
> 
> If using Unity XR make sure you have OpenVR selected in the XR Manager section of your project settings.


Thank you! I don't know what I did wrong the first time but now I managed to make it work properly for my game. https://www.youtube.com/watch?v=ISVXOAiyB94
