### ISSUE TITLE
SteamVR breaks rendering Gizmos

### ISSUE THREAD

**Issue by Erhannis** [ValveSoftware/steamvr_unity_plugin#1067]
Windows 10
Unity 2022.1.14f1
SteamVR Plugin 2.7.3 (sdk 1.14.15)

I've noticed that when I have a project with SteamVR in it, and the game is able to connect to the headset, then OnDrawGizmos is no longer called (and Debug.DrawLines no longer show up).  It's still called from the Scene view, but not from the Game view.  If I disconnect my headset so the game can't connect to it, then Gizmos and Debug lines show up fine.

Here's a video:

https://youtu.be/3QaXmOQFvrQ

(I forgot to mention the OnDrawGizmos thing specifically in the video.  Also, FYI, Gizmos / Debug lines are missing in normal VR scenes, too.)

**Comment by Erhannis** [comment]
To anyone in my shoes - I still haven't figured out the problem with Gizmos or Debug, BUT both [Fast Line Renderer](https://assetstore.unity.com/packages/tools/particles-effects/fast-line-renderer-for-unity-gpu-line-and-particle-system-54118) and [IMDraw](https://assetstore.unity.com/packages/tools/particles-effects/imdraw-59805) work IF you switch to multi pass rendering.  (Stop running the game.  Go to: Build Settings > Player Settings > XR Plug-in Management (in the left list) > OpenVR or OpenXR > Stereo Rendering Mode or w/e., set it to Multi Pass.)  Maybe depends on system details.

**Comment by zite** [comment]
Since other packages work, I believe this is a unity issue with single pass rendering. Closing for now.
