### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by mariannapizzo97** [ValveSoftware/steamvr_unity_plugin#1075]
Hello everyone,

It's just that I happen to have the some problem in  Building and Running for Android with Unity 2021.371f1 
Does anyone know how to solve or troubleshoot this problem ?
Thanks in advance.

Have a good day !
![ErrorInBuilding](https://user-images.githubusercontent.com/117294467/204344589-f4f5e916-9603-42ab-99e2-2bcf023b365d.PNG)

**Comment by zite** [comment]
This plugin is not compatible with Android devices as SteamVR only runs on windows / linux. Many of the scripts in the Interaction System rely on SteamVR features, so they're not cross-platform compatible.
