### ISSUE TITLE
SteamVR_Behaviour_Skeleton : rangeOfMotion doesn't work 

### ISSUE THREAD

**Issue by RomainDelaplaine** [ValveSoftware/steamvr_unity_plugin#1080]
Hello, everyone!

I'm trying to use the Steam VR plugin in my project, especially the hand from the Player prefab. My issue is that no matter which value I use for the range of motion for my hand, the animation will not consider the controller. I have no errors in the console when I'm in play mode, but the animations are broken.

Here is the result :
![GameWinow](https://user-images.githubusercontent.com/124575463/216955919-00bfcf15-26af-4e78-9963-71b5c886be1f.png)
![Inspector](https://user-images.githubusercontent.com/124575463/216955925-e1b7ddce-e9e8-4826-b997-b88e257ca7c6.png)

(the problem don't come from the version but I'm using unity editor 2019.4.28)

**Comment by zite** [comment]
Do you have this behavior in the test scene as well? Did you copy over the whole player? There are other scripts that work with the hand script to get this functionality.

**Comment by RomainDelaplaine** [comment]
Thanks for your answer, I found what was missing, in the binding the hand skeleton was missing in the default action set

**Comment by zite** [comment]
Great, thanks for the update
