### ISSUE TITLE
Tracker Manager

### ISSUE THREAD

**Issue by duartejuca** [ValveSoftware/steamvr_unity_plugin#1083]
I made this code to setup Trackers in unity to any TrackedObject more easely.
I hope help someone. The code still WIP, but already works, just extend some points and finish readme.

TrackerManager
https://github.com/duartejuca/HTC-VIVE-Unity-TrackerManager.git

**Comment by kisak-valve** [comment]
Hello @duartejuca, this appears to be a PSA and not an actionable issue for a SteamVR Unity Plugin dev to ponder.

Closing as invalid.

**Comment by duartejuca** [comment]
Hi @kisak-valve sorry about that, and thank you.
