### ISSUE TITLE
Bugs with hands. Need help.

### ISSUE THREAD

**Issue by Danila24ru** [ValveSoftware/steamvr_unity_plugin#109]
1. When I detach object from hand and destroy this object, hand sometimes stuck with "hover locked = true" and I can't do anything with this hand anymore. I can't find in SteamVR code where problem.
2. When I press Steam Home button and close it, hands disappear and I can't do anything. (In hierarchy I see "left/right controller (hidden)".
3. Sometimes when scene loaded my hands reversed "left = right, right = left". When I pick up some object with left hand it attaching to right hand. How I can fix it?

**Comment by zite** [comment]
Thanks for the report. These issues should be fixed with the most recent version of the plugin released today. Let me know if you're still having this issue and I can reopen this.
