### ISSUE TITLE
Binding HeadsetOnHead not working for Pico 4

### ISSUE THREAD

**Issue by DimitriGavotto** [ValveSoftware/steamvr_unity_plugin#1092]
# Binding HeadsetOnHead not working for Pico 4

Hi our QA team found out that the HeadsetOnHead state when using Pico 4 always returns false. This means that if a user uses a Pico headset on our live  Steam build the app will stay in a constant pause state. I thought it was because we did not have an input binding for Pico but the issue persisted even after creating one. We  tried to do a workaround and detect when a Pico headset is connected and disable the pause functionality for Pico however SteamVR believes the headset is a quest:
[SteamVR] Initialized. Connected to oculus : Oculus Quest2 : WMHD315M3010GV :: rift

 We would love any help to find a fix or a workaround for this issue. Thank you in advance!

here is our code in case it helps:

```
private readonly SteamVR_Input_ActionSet_default m_defaultActions = new SteamVR_Input_ActionSet_default();

                protected void Update()
		{
			if (!SteamVR_Input.initialized)
			{
				return;
			}


			if (HasVrFocus != m_defaultActions.HeadsetOnHead.state)
			{
				HasVrFocus = m_defaultActions.HeadsetOnHead.state;
				SetPaused(!HasVrFocus);
			}
		}
```

**Comment by zite** [comment]
Hi, if you still have this issue you can either ask pico to fix what sounds like a bug with their proximity sensor reporting, and/or you can check for that serial number explicitly. That's the serial number we use when simulating a oculus headset. However, that will be the serial number for any other headsets that are simulating an oculus headset.
