### ISSUE TITLE
Scene view almost entirely breaks after installation

### ISSUE THREAD

**Issue by Lionmeow** [ValveSoftware/steamvr_unity_plugin#1093]
Using at least Unity 2022.1.0 and any future versions, I am unable to move in the editor anymore. I can use the pan tool, as well as look around, but the WASD and arrow keys do nothing. Furthermore, if I try to adjust between isometric and perspective, the two perspectives fully break, and sometimes stop letting me switch between. If I press the F key to focus on an object, it switches between perspectives instead. The axes in the top right are not aligning me to their respective faces, and also disappear occasionally. All of these issues make the editor unusable in this state.
![image](https://github.com/ValveSoftware/steamvr_unity_plugin/assets/49107380/b4854995-7386-4e7a-9a92-c058ed2837ea)

**Comment by zite** [comment]
This sounds like a Unity issue, have subsequent versions fixed this?
