### ISSUE TITLE
We need an OpenXR pluggin for index controllers or no new games will be made for the hardware!

### ISSUE THREAD

**Issue by Giantbean** [ValveSoftware/steamvr_unity_plugin#1097]
OpenVR is depreciated in Unity and while Steam VR has been able to work in Unity with OpenXR it's not working in recent versions. Unity seems to have some sort of agreement with Meta and their support just says sorry we can't recreate your issue on the quest. This is obvious as the issue is the lack of finger tracking for the index in Kronos openXR.

Valve please, please, please make an openXR unity plug-in to bring back the index/knuckles controller input. I have to use new versions of Unity and OpenXR due to business requirements but this means I can no longer develop for index controllers; which is sad as they are the best controllers out there. Maybe play nice and send Kronos some code as they likely don't have anything for the PSVR2 either.

**Comment by zite** [comment]
Finger tracking with Index (and controllers through SteamVR) should be available with OpenXR through Unity's new XR Hands package or the Windows Mixed Reality feature set.
https://docs.unity3d.com/Packages/com.unity.xr.hands@1.2/manual/index.html
https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/new-openxr-project-with-mrtk#download-and-install-the-mixed-reality-feature-tool

**Comment by Giantbean** [comment]
From what I have seen the new XR hands only work in the editor and Steam VR has been failing in 2022+ but I will give it yet another try.

**Comment by Giantbean** [comment]
@keithbradner  To be clear if I get index finger tracking with either of the links you shared working I don't need SteamVR asset installed in Unity at all?

**Comment by zite** [comment]
That's correct. Though there are features in OpenVR that OpenXR doesn't have yet. Controller render models and controller based finger tracking for all controllers being the main ones. In OpenVR with a oculus controller we attempt to approximate finger tracking on the controller. OpenXR only exposes (oculus) finger tracking when not using controllers.

**Comment by zite** [comment]
Sorry about the delay, fortunately those are pretty outdated responses. Hand tracking via OpenXR has worked for at least a year now. Both unity and microsoft have packages to support OpenXR hand tracking data, which index controllers provide.
Unity: https://docs.unity3d.com/Packages/com.unity.xr.hands@1.3/manual/project-setup/install-xrhands.html
Microsoft: https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-input/packages/input/hand-tracking
