### ISSUE TITLE
Vive hands are not tracked in Unity 5.6

### ISSUE THREAD

**Issue by efruchter** [ValveSoftware/steamvr_unity_plugin#11]
SteamVR camera no longer updates hands unless an UpdatePoses component is added to it. It's an unexpected change from unity 5.5.

[http://answers.unity3d.com/questions/1299567/vive-controllers-not-tracking-in-unity-560b3.html](http://answers.unity3d.com/questions/1299567/vive-controllers-not-tracking-in-unity-560b3.html)

**Comment by bddckr** [comment]
This is explicitly stated [in the SteamVR readme](https://github.com/ValveSoftware/steamvr_unity_plugin/blob/master/Assets/SteamVR/readme.txt#L44-L45).

**Comment by aleiby** [comment]
Yeah, we are waiting for a fix from Unity in the 5.6 beta before I can re-enable the auto add that it does elsewhere.  We are seeing a GL.End error pop up because the dummy camera that is being used has its clear flags set to Nothing.

**Comment by bddckr** [comment]
Should be fixed by #14 for every Unity version.

**Comment by tairk** [comment]
I am not able to see my vive controllers even with steamvr 1.2.2 and unity 5.6.1f. I may be doing something wrong but i can't figure what. Any clue to help me ?
