### ISSUE TITLE
Longbow arrow not aligning with the tracked hand

### ISSUE THREAD

**Issue by blazing-panda** [ValveSoftware/steamvr_unity_plugin#1102]
I am running into a weird issue where the arrow from the longbow (Intercations_Example scene) does not align with the tracked hand. 
I am using Unity version 2023.1.11f1, but it also happens on the latest lts release.

![image](https://github.com/ValveSoftware/steamvr_unity_plugin/assets/30294275/7bc48a59-7d8a-4217-971b-54b5867a24f2)

**Comment by zite** [comment]
Thanks for the report folks, this should be fixed in the latest release (2.8.0)

**Comment by kisak-valve** [comment]
Closing per the last comment.
