### ISSUE TITLE
Binding controllers you don't have?

### ISSUE THREAD

**Issue by MiddleManGames** [ValveSoftware/steamvr_unity_plugin#1103]
My app got rejected because bindings weren't set for Vive, Index and WMR controllers.

In Unity when I open the binding UI I can click on the current controller and change it to Oculus, Vive or Index and set them, but nothing else.

In my folder with the json files there is one there for Vive Cosmos, but that doesn't even come up.

How do I set bindings for any other controllers?

**Comment by zite** [comment]
Late reply, sorry, this is more of a question for the developer forums at: https://steamcommunity.com/app/250820/discussions/7/

This was likely already resolved, but for other people: You'll need to download the driver for other controllers you want to setup bindings for. For WMR the driver is here: https://steamcommunity.com/app/719950
