### ISSUE TITLE
x86/libopenvr_api.so and x86/libopenvr_api.so.dbg has no meta filebut it's in an immutable folder. The asset will be ignored.

### ISSUE THREAD

**Issue by muraqqi** [ValveSoftware/steamvr_unity_plugin#1108]
Hello, i am new and try to using steamvr and encountered these errors:

Asset Packages/com.valvesoftware.unity.openvr/Runtime/x86/libopenvr_api.so has no meta file, but it's in an immutable folder. The asset will be ignored.

Asset Packages/com.valvesoftware.unity.openvr/Runtime/x86/libopenvr_api.so.dbg has no meta file, but it's in an immutable folder. The asset will be ignored.

i was thinking maybe unity not generated the meta files, but have no understanding from me how to regenerate meta file.

Thank you for helping.

**Comment by kisak-valve** [comment]
Hello @muraqqi, this issue is already being tracked at #1107. Closing as a duplicate.
