### ISSUE TITLE
2 compiler errors in Unity after installing SteamVR2.0 RC3 plugin in Unity 2018.2.6f1

### ISSUE THREAD

**Issue by cryoknight** [ValveSoftware/steamvr_unity_plugin#111]
I removed the prior SteamVR plugin.
Installed the RC3 version.  Deleted Library folder for my project.
When Unity rebuilds the project, it shows these 2 errors, and cannot continue.
I also do not see the SteamVR window under the Window menu, perhaps because this does not compile.

Using Unity 2018.2.6f1

Assets/SteamVR/InteractionSystem/Core/Scripts/Throwable.cs(43,13): error CS0246: The type or namespace name `VelocityEstimator' could not be found. Are you missing an assembly reference?

Assets/SteamVR/InteractionSystem/Longbow/Scripts/Arrow.cs(30,10): error CS0246: The type or namespace name `PlaySound' could not be found. Are you missing an assembly reference?

**Comment by cryoknight** [comment]
In order to fix this, I had to manually find 3 files in the SteamVR github project and copy them into the SteamVR\InteractionSystem\Core\Scripts folder:
VelocityEstimator.cs
PlaySound.cs
Util.cs

It looks like these are not installed via the unity package.

**Comment by zite** [comment]
Sorry I can't seem to repro this. When I download rc3 from the releases section and when I pull down the zip of the whole project I get the files you mention with it, and no errors. Can you try loading the plugin into a new project?

**Comment by cryoknight** [comment]
Yeah, had some weirdness there.  I tried it again in a different project and all of the files installed properly.
Thanks for checking!
