### ISSUE TITLE
Interactions Example: Bug when Teleporting while holding an object with VelocityEstimator component

### ISSUE THREAD

**Issue by LucidDreamsVR** [ValveSoftware/steamvr_unity_plugin#115]
To reproduce: 

1. Open Interactions Example Scene in latest Beta branch.
2. Teleport to the Equippable station
3. Pick up the Equippable sphere with either hand
4. Teleport to other locations and watch the sphere's movement
(Note: same thing occurs for other objects with VelocityEstimator)

[Video of issue](https://youtu.be/E8kjBZ47Dpk)

Initial guess is that the Velocity Estimator script is not accounting for teleportation and that it should ignore any position delta caused by a teleport action. (confirmed)

**Comment by LucidDreamsVR** [comment]
Confirmed that this occurs with other objects that have the VelocityEstimator component and the code does not consider teleportation. Updated the issue title to reflect this info.

**Comment by timetosmile** [comment]
I wanted to ask carefully how the current status is and whether it will work.

**Comment by zite** [comment]
Unfortunately I didn't fix this in the latest release. I'd like to get this fixed still but in the meantime: the way to fix this is on teleport to check if the current interactable is using velocity movement, and if so teleport it to the new location.
