### ISSUE TITLE
Interactions Example: Triggering TargetHitEffect while holding the object prevents any further hand interactions

### ISSUE THREAD

**Issue by LucidDreamsVR** [ValveSoftware/steamvr_unity_plugin#116]
Throwing an object with the TargetHitEffect at the defined target works fine, but if it hits the target while still being held in the user's Hand then no other interactions are possible for that Hand after that.

Steps to reproduce:
1. Open Interactions Example Scene in latest Beta branch.
2. Teleport to the Throwables area between the target and the tables
3. Pick up any of the cubes or spheres with either hand 
4. Touch the held object to the target until it turns into a colored arrow
5. Try interacting with anything else in the scene using the same hand, nothing works

[Video of issue](https://youtu.be/QPPf4KFIUL0)

Initial guess is that the TargetHitEffect script does not look to see if the object is being held and trigger a release of the object from the hand before doing the rest of its behavior to delete the original object and instantiate the new object (the colored arrow in this case) and therefore the Interactable script is blocked from working for that hand.

**Comment by zite** [comment]
Thanks for the report, I believe this issue was fixed in the release today. Let me know if it's still an issue and I'll reopen.

**Comment by LucidDreamsVR** [comment]
Could not reproduce in the 2.0 release. Thanks! :)
