### ISSUE TITLE
When you go to SteamVR and come back, you lose your hand models.

### ISSUE THREAD

**Issue by danielkariv** [ValveSoftware/steamvr_unity_plugin#118]
Using Oculus Rift, when you press the menu button ( called Button.Start) to get to SteamVR menu, and come back, the glove/hand models cannot be seen, not from the HDM and not from the editor.
Sames happens if you take off the HDM and put on. 
before:
![1](https://user-images.githubusercontent.com/38776931/45918372-bb313d80-be8e-11e8-9ad8-6dd669dad933.png)
after:
![2](https://user-images.githubusercontent.com/38776931/45918371-bb313d80-be8e-11e8-9768-9b16a6282a33.png)

To test it, all you need to do is put the player prefab on a new scene, and run the game. open and close steamvr menu and it would happen.

**Comment by zite** [comment]
Thanks for the report. I'll get this fixed for the next version.

**Comment by Cluster7ck** [comment]
@keithbradner kinda related: Can you turn the hand models off? When you assign no hand prefab in the inspector there is just no controller model at all.

**Comment by zite** [comment]
This should be fixed this in the version released today. Let me know if you still see the issue.

To not show hands try going into the hand prefab, the RenderModel component, and removing the prefab for the skeleton in that component.
