### ISSUE TITLE
If the controllers aren't power on, FPS is drops to under 90 fps ( around 25 for me)

### ISSUE THREAD

**Issue by danielkariv** [ValveSoftware/steamvr_unity_plugin#119]
Using Oculus Rift.
When the controllers aren't power on, one of the scripts (SteamVR_Action_Skeleton.cs) sends a Debug.LogWarning and a Debug.LogError. The problem that I think the error is sent every update call , which drops performance. The interaction scene would be running on 20 fps, while if I connect the controllers, the fps goes back to normal (90 fps). 
It is more annoying that a problem, but it is can be avoided.

**Comment by zite** [comment]
I believe this is a problem with default SteamVR. Can you try subscribing to the SteamVR Beta and testing again?

**Comment by danielkariv** [comment]
I just switched over to "beta - SteamVR Beta Update". Tried it again, same thing. the gloves are disappearing when moving to SteamVR or putting on the HDMI. Test it on a clean scene with only the Player prefab and on the interaction demos scene.

**Comment by danielkariv** [comment]
Okay i tested it with SteamVR Beta, it fix it. 
So this issue wont exist when this version of SteamVR Beta would become the normal version.
