### ISSUE TITLE
Interactions Example: Adding an interaction while already interacting with Linear Drive freezes interaction

### ISSUE THREAD

**Issue by LucidDreamsVR** [ValveSoftware/steamvr_unity_plugin#120]
If the Linear Drive is being interacted with by using either the Grip or Trigger (tested on Vive), then pressing the other control (Grip or Trigger) on the same Hand freezes the Linear Drive and the Hand.

Steps to reproduce:

1. Open Interactions Example Scene in latest master branch.
2. Teleport to the Linear Drive station
3. Interact with Linear Drive using either Grip or Trigger - works fine
4. While still interacting, press the other control (so now Grip & Trigger are pressed)
5. See that hand pose changes to pinch, freezes in place, and no longer interacts
6. Interacting with the other hand releases the frozen hand and everything works from there

[Video of issue](https://youtu.be/hRHvrzab8_0)

Initial guess is that the Linear Drive needs to ignore the duplicate action from the Hand already interacting and only respond to that action from the other Hand.

**Comment by zite** [comment]
Thanks for the report, I'll get this fixed for the next version.

**Comment by zite** [comment]
This should be fixed this in the version released today. Let me know if you still see the issue.
