### ISSUE TITLE
Interactions Example: Releasing Buggy Remote and returning to equipped Bow causes NullRefException

### ISSUE THREAD

**Issue by LucidDreamsVR** [ValveSoftware/steamvr_unity_plugin#121]
Didn't have time to make a video, but this one is easy to repro:

1. Teleport to Bow station and pick it up with left hand
2. Teleport to Remotes station
3. Using left hand again, pick up the Buggy Remote using Grip (Vive)
4. Controls for Buggy work fine
5. Release Grip to put Buggy Remote down and return to Bow
6. Editor breakpoints with the exception below

NullReferenceException: Object reference not set to an instance of an object
Valve.VR.InteractionSystem.Interactable.OnDetachedFromHand (Valve.VR.InteractionSystem.Hand hand) (at Assets/SteamVR/InteractionSystem/Core/Scripts/Interactable.cs:253)

Previous RCs (I think 2 and maybe even 3) had no problem with this set of actions and dropping the Remote would simply return you to having the Bow equipped.

In general it seems like having the Grip and Trigger do the same actions is causing problems. For example, if you pick up the Buggy Remote with the Trigger, you then can't control the acceleration of the Buggy because letting go of the Trigger releases the Remote. Picking it up with the Grip then allows you to use the Trigger to control acceleration and you can still drop it by releasing the Grip.

**Comment by zite** [comment]
Thanks for the report. I'll get this fixed for the next version.

**Comment by zite** [comment]
This should be fixed this in the version released today. Let me know if you still see the issue.
