### ISSUE TITLE
In the interaction scene, the "Velocity Movement" throwable objects lose gravity if you hold them with two hands.

### ISSUE THREAD

**Issue by danielkariv** [ValveSoftware/steamvr_unity_plugin#122]
Basically the title. 
It seems that if you hold the object in one hand, and than trying holding it with another, the object lose it gravity when you release it.
I think i fix it by just selecting "DetachFromOtherHand" in the attachment flags ( in Throwable component).

**Comment by zite** [comment]
Ah, thanks for the report. Yeah the objects gets the gravity state it should release with when it initially attaches, and if it's already attached, gravity would be off. I'll get that fixed for the next version.

**Comment by zite** [comment]
Fixed this in the version released today. Let me know if you still see the issue.
