### ISSUE TITLE
WEB UI for new action bindings is broken 

### ISSUE THREAD

**Issue by Abnormalia** [ValveSoftware/steamvr_unity_plugin#123]
Unity 2018.2.8 + Plugin 2.0

Works fine with default action sets.
Try to add new actions sets. "Open binding UI" -> "Open current bindings" -> Empty page
Web debug tools show: 
"controllerbindingui.c74584deb0c5e9f7d59d.js:5 Uncaught (in promise) TypeError: Cannot read property 'find' of undefined
    at controllerbindingui.c74584deb0c5e9f7d59d.js:5
    at Array.forEach (<anonymous>)
    at t.<anonymous> (vrwebui_core.fad85b136c0042a040e9.js:60)
    at e.GetActionByName (controllerbindingui.c74584deb0c5e9f7d59d.js:5)
    at e.GetActionForInputType (controllerbindingui.c74584deb0c5e9f7d59d.js:5)
    at e.GetPullAction (controllerbindingui.c74584deb0c5e9f7d59d.js:5)
    at t.render (controllerbindingui.c74584deb0c5e9f7d59d.js:5)
    at w (vrwebui_core.fad85b136c0042a040e9.js:46)
    at vrwebui_core.fad85b136c0042a040e9.js:18
    at st (vrwebui_core.fad85b136c0042a040e9.js:46)"

Is there alternate way to make bindings? Or where is it saved ? Maybe we can edit them manually until fixed ?

**Comment by zite** [comment]
Ah, that's unfortunate. We'll look into what's causing this. But for now, yeah you can manually edit the json files in the root of your project. The actions.json defines your actions and the controller_binding.json connects actions to buttons.

**Comment by TesseractCat** [comment]
I get a similar error:
```Source map error: request failed with status 404
Resource URL: http://localhost:8998/dashboard/controllerbindingui.9fb2f6537fb847fecdc7.js
Source Map URL: controllerbindingui.9fb2f6537fb847fecdc7.js.map```

and

```Source map error: request failed with status 404
Resource URL: http://localhost:8998/dashboard/vrwebui_core.fad85b136c0042a040e9.js
Source Map URL: vrwebui_core.fad85b136c0042a040e9.js.map```

**Comment by zite** [comment]
@TesseractCat are you sure you're on the latest version of SteamVR? Maybe try the beta branch?

**Comment by zite** [comment]
This should be fixed now. Are you still seeing the issue?

**Comment by ggggabe** [comment]
@keithbradner Just wanted to confirm that updating to the beta branch resolved this issue for me. Also regarding editing the json files themselves, are there docs anywhere for them? They're pretty self explanatory but if there was a reference we could use that'd be sick.

**Comment by zite** [comment]
@crumplepunch The OpenVR SDK should have the info you're looking for. https://github.com/ValveSoftware/openvr/wiki/Action-manifest
