### ISSUE TITLE
Wont build in Unity.

### ISSUE THREAD

**Issue by SamR77** [ValveSoftware/steamvr_unity_plugin#124]
Get the following console errors after downloading and bringing version 2.0 into Unity.

Assets/VRTK/Source/SDK/SteamVR/SDK_SteamVRBoundaries.cs(21,19): error CS0246: The type or namespace name `SteamVR_PlayArea' could not be found. Are you missing `Valve.VR' using directive?

Assets/VRTK/Source/SDK/SteamVR/SDK_SteamVRBoundaries.cs(123,27): error CS0246: The type or namespace name `SteamVR_PlayArea' could not be found. Are you missing `Valve.VR' using directive?

**Comment by zite** [comment]
Sorry, the current version of VRTK does not support the SteamVR Unity Plugin. They are working on v4 of their framework, which should work with this new version fine. In the meantime you're welcome to use SteamVR Unity Plugin v1.2.3 here:  https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/1.2.3

**Comment by SamR77** [comment]
ok thanks
