### ISSUE TITLE
CVRSystem.GetControllerState no longer working

### ISSUE THREAD

**Issue by lawwong** [ValveSoftware/steamvr_unity_plugin#128]
Tested on
Unity 2017.1.0 + Plugin 2.0
Unity 2017.4.3 + Plugin 2.0
Unity 2018.2.8 + Plugin 2.0

CVRSystem.GetControllerState returns true but the controller state not filling with correct values.
I know that it is recommended to use CVRInput to retrieve input but I think the alternative way should also work as well.

**Comment by zite** [comment]
GetControllerState will require you to not make any calls to the new input system. The two types of calls cannot be used at the same time. To make this easier we recommend you use the older version of the plugin in the releases section (v1.2.3). That version will continue to work as you're intending.
