### ISSUE TITLE
ArgumentNullException on creating SteamVR Input when not in root folder

### ISSUE THREAD

**Issue by grofie** [ValveSoftware/steamvr_unity_plugin#129]
We usally put our 3rd party plugins in the "Plugin" or "Standard Assets" folder to save compilation time. 

But this breaks the SteamVR plugin on creating the SteamVR Input:

```
Valve.VR.SteamVR_Input_Generator:OnEditorUpdate() (at Assets/Plugins/SteamVR/Input/Editor/SteamVR_Input_Generator.cs:139)
Valve.VR.SteamVR_Input_EditorWindow:OnInspectorUpdate() (at Assets/Plugins/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:246)
UnityEditor.HostView:OnInspectorUpdate()
```

```
ArgumentNullException: Argument cannot be null.
Parameter name: baseType
System.CodeDom.CodeTypeReference..ctor (System.Type baseType)
Valve.VR.SteamVR_Input_Generator.CreateField (System.CodeDom.CodeTypeDeclaration inputClass, System.String fieldName, System.Type fieldType, Boolean isStatic) (at Assets/Plugins/SteamVR/Input/Editor/SteamVR_Input_Generator.cs:1309)
Valve.VR.SteamVR_Input_Generator.GenerateActionSetsHelpers (System.String actionSetsClassFileName) (at Assets/Plugins/SteamVR/Input/Editor/SteamVR_Input_Generator.cs:1160)
Valve.VR.SteamVR_Input_Generator.GenerationStep_CreateHelperClasses () (at Assets/Plugins/SteamVR/Input/Editor/SteamVR_Input_Generator.cs:221)
Valve.VR.SteamVR_Input_Generator.ExecuteNextStep (GenerationSteps currentStep) (at Assets/Plugins/SteamVR/Input/Editor/SteamVR_Input_Generator.cs:183)
Valve.VR.SteamVR_Input_Generator.CheckForNextStep () (at Assets/Plugins/SteamVR/Input/Editor/SteamVR_Input_Generator.cs:167)
Valve.VR.SteamVR_Input_Generator.OnEditorUpdate () (at Assets/Plugins/SteamVR/Input/Editor/SteamVR_Input_Generator.cs:139)
Valve.VR.SteamVR_Input_EditorWindow.OnInspectorUpdate () (at Assets/Plugins/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:246)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:295)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:288)
UnityEditor.HostView.OnInspectorUpdate () (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:175)
```

**Comment by zite** [comment]
I believe this is an issue because putting scripts in a Plugins folder changes the order they compile in. If you name the folder "ThirdParty" or something different it should work. Is that an acceptable solution for your scenario?

**Comment by grofie** [comment]
Hm, the solution is not really satisfying: The point of moving the steam vr plugin into the "Plugin" or "Standard Assets" folder is to skip the re-compiling for this assets and therefor to reduce compilation time when working on the actual project code. 

We use quite a lot third party plugins and keeping them all in the root folder will result in a long coffee break each time we need to comile. And I dont even drink coffee.  ;-)

But of course, on or two plugins in the root folder won't be that bad.

**Comment by bddckr** [comment]
The plugins folder is meant for native plugins, which this obviously isn't. If you want to improve your compile times don't resort to this hack,, instead use Assembly Definition Files or use the experimental Incremental Compiler Unity provides.

**Comment by grofie** [comment]
Thank @bddckr for your lecture. But we made bad experiences with the incremental compiler, specially when it comes to editor scripts. Assembly Definition Files are definitly an alternative, but a bit harder to setup. 
> It is highly recommended that you use assembly definition files for all the scripts in the Project, or not at all

IMHO, just using the Standard Assets folder is not a hack, it is using a [feature ](https://docs.unity3d.com/Manual/ScriptCompileOrderFolders.html) of unity. Fine for me, if you cannot or dont want to support that. 

I dont want to blame, request or order anything here. I found the solution on my own, I simply post it here as a start for other people with a similar issue.

**Comment by mbadawi-artefacto** [comment]
Was just about to post a similar issue. We also use the "Standard Assets" folder for all our third party plugins and have the exact same problem.

@grofie did you manage to find another way around this besides Assembly Definition Files?

**Comment by grofie** [comment]
Sorry @mbadawi-artefacto but we end up keeping the steam vr plugin in the root folder. 
I hate it too but we cannot spend any more time on this.

**Comment by mbadawi-artefacto** [comment]
This is the current approach we're using too... And all our automated pipeline scripts now have a hardcoded line to correctly manage the SteamVR Plugin. Such a pain!

**Comment by mbadawi-artefacto** [comment]
@bddckr Right clicking and creating an Assembly definition file creates an empty file, with no dependencies. But it seems that, if I want to indicate dependencies, I also need to create ADF files for the stuff Steam VR plugin depends on...
Or I must have missed or misunderstood something in your previous answer to @grofie.

So getting back to essentials: how can I solve the problem of moving the Steam VR plugin to the "Standard Assets" folder by using ADF files? And why would it be so complicated for you guys to address this problem?

Thanks for your time and patience.

**Comment by mbadawi-artefacto** [comment]
Forget about ADF, it created a whole bunch of new problems and is definitely not the way to go... Just creating it in the "normal" Steam VR folder I get errors like : _Assets/Standard Assets/SteamVRPlugin/Editor/SteamVR_UpdateModeEditor.cs(5,17): error CS0234: The type or namespace name `CSharp' does not exist in the namespace `Microsoft'. Are you missing an assembly reference?_
So for now, it is impossible to move the plugin to the Standard Assets folder... unlike all the other 146 Unity plugins we use.

**Comment by mbadawi-artefacto** [comment]
@keithbradner What "more information" do you need for this issue?
Here are the steps to reproduce it:

1. Install the Steam VR 2.0.1 plugin.
2. Close Unity.
3. Move the "Assets/SteamVR" folder to "Assets/Standard Assets/SteamVR".
4. Open Unity.
5. Open Steam VR Input Window and click on "Save and generate".

**Comment by cpetry** [comment]
It seems to work if you:  

- Create an assembly for SteamVR + Editor
- Reference the Editor assembly to SteamVR
- Change the SteamVR Input Path to a path inside your SteamVR assemble
- Hit generate

I did not get any errors with this.

**Comment by mbadawi-artefacto** [comment]
Thanks @cpetry I'll try this when I have some time. For now, we've gone back to 1.2.3 and switched to VRTK...

**Comment by lostinplace** [comment]
> It seems to work if you:
> 
> * Create an assembly for SteamVR + Editor
> * Reference the Editor assembly to SteamVR
> * Change the SteamVR Input Path to a path inside your SteamVR assemble
> * Add an Editor assembly inside SteamVR\Input\Editor and reference to SteamVR
> * Hit generate
> 
> I did not get any errors with this.

would you mind giving a little more detail on this?   My attempts to reproduce have only yielded errors

**Comment by cpetry** [comment]
Folder structure:

- Assets:
  - SteamVR
    - Editor
       - SteamVR_Editor.asmdef
    - Input
       - Editor
         - Steam_VR_Input_Editor.asmdef
    - SteamVR.asmdef

SteamVR.asmdef:
![image](https://user-images.githubusercontent.com/3867700/53492301-d08f4100-3a98-11e9-9a81-02d4d41ea140.png)
SteamVR_Input_Editor.asmdef:
![image](https://user-images.githubusercontent.com/3867700/53492320-dc7b0300-3a98-11e9-96f7-38509d1c5bc2.png)
SteamVR_Editor.asmdef:
![image](https://user-images.githubusercontent.com/3867700/53492379-03393980-3a99-11e9-84cb-5d73cf323207.png)

I hope this clarifies this. For me this works.

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
