### ISSUE TITLE
Headset view in mixed reality mode is cropped rather than scaled

### ISSUE THREAD

**Issue by cjwills** [ValveSoftware/steamvr_unity_plugin#13]
In mixed reality mode (with an externalcamera.cfg file) the headset view (lower right quadrant) is being cropped rather than scaled, so it just shows the lower right quarter of the view rather than the whole thing.

**Comment by aleiby** [comment]
The mixed reality support is intended to be output at 4k so each quadrant gets a 1080p view.  If you provide a pull request for how you'd like to see this work, I'll go ahead and integrate it in the next update.
