### ISSUE TITLE
FallbackHand grabbing doesn't work

### ISSUE THREAD

**Issue by tettogreen** [ValveSoftware/steamvr_unity_plugin#130]
**1) There is no SteamVR_Behaviour_Pose component attached to object.** That's easy to fix.
**2) Mouse click grab doesn't work at all.** It seems there's no such call and new input system hasn't been finished to work with fallback hand.
3) Have been trying to find a way to invoke action manually for 2 days already - am I missing something?

It's important for devs like me, who develop remotely and has no hmd with them.

**Comment by tettogreen** [comment]
@keithbradner Hi! Could you please tell how to trigger input actions through API?

**Comment by zite** [comment]
This should be fixed in the next version of the plugin. If you would like you can check out the beta here: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.1b2
