### ISSUE TITLE
SteamVR Input menu item crashes Unity editor on OSX

### ISSUE THREAD

**Issue by tshead** [ValveSoftware/steamvr_unity_plugin#134]
Like it says, when I choose Windows > SteamVR Input, the Unity editor immediately disappears.

* SteamVR plugin 2.0.1 (installed via asset store)
* Unity 2018.2.10f1 (also tried 2018.2.1f1)
* SteamVR Version 2018-09-27 / 1538082325
* OSX 10.13.6

Thanks,
Tim

**Comment by ronpetit** [comment]
@tshead I found a workaround for this.

On the folder, SteamVR/Input/EXAMPLEJSON/ there is a file called actions.json, put that file on the root of your project (not in the assets folder), and the input menu will popup.

However this input system still have bugs. I will keep using the 1.2.3 version.

All of this was tested using the following:

- SteamVR plugin 2.0.1
- Unity 2018.3.0b6
- SteamVr Version 2018-09-27
- Ubuntu 16.04 LTS

**Comment by chilton** [comment]
This works on the latest beta, here in v2.2b4. Without putting a copy of actions.json in the root directory, it crashes.

**Comment by brainyclown10** [comment]
Just want to say that I have the same issue as the original poster.

Versions:
Steam VR plugin 2.2.0 (installed via asset store)
Unity 2018.3.4f1
macOS Mojave 10.14.3
SteamVR 1.2.10

Will report back after I try the work around.
