### ISSUE TITLE
Binding UI Javascript Errors

### ISSUE THREAD

**Issue by momo-the-monster** [ValveSoftware/steamvr_unity_plugin#136]
I'm getting an error trying to open up the binding UI. 

Here's what I did:
- Started new project in Unity 2017.4.10
- Imported SteamVR Unity Plugin 2.0.1 from releases
- Opened SteamVR Input Window
- Accepted default mapping generation
- Pressed 'Save and Generate' 
- Pressed 'Open binding UI'

Chrome Version 69.0.3497.100 (Official Build) (64-bit) opened up to http://localhost:8998/dashboard/controllerbinding.html?app=application.generated.unity.steaminput201.exe but showed only a black screen.
Error in the console: 
```
TypeError: Cannot read property 'forEach' of undefined
    at e.UpdateContainer (controllerbindingui.9fb2f6537fb847fecdc7.js:5)
    at y (vrwebui_core.fad85b136c0042a040e9.js:46)
    at e.n (vrwebui_core.fad85b136c0042a040e9.js:46)
    at controllerbindingui.9fb2f6537fb847fecdc7.js:5
    at Array.forEach (<anonymous>)
    at e.<anonymous> (controllerbindingui.9fb2f6537fb847fecdc7.js:5)
    at r (vrwebui_core.fad85b136c0042a040e9.js:24)
    at Object.next (vrwebui_core.fad85b136c0042a040e9.js:24)
    at a (vrwebui_core.fad85b136c0042a040e9.js:24)
```

**Comment by zite** [comment]
Hi, thanks for the report. Unfortunately I am not able to reproduce this. Do you have controllers on at this time? If so, which ones? Are you on the latest SteamVR Beta? Can you send a system report? 

![systemreport](https://user-images.githubusercontent.com/198704/46379712-91c59e00-c654-11e8-94f6-7ef56ac7ae7f.png)

**Comment by momo-the-monster** [comment]
Hm - it's possible that I did not have any controllers connected/tracking at the time when I opened up this window. I'm away from the machine where I was having this issue, I'll test it tonight with my mobile setup. Thanks for the quick follow-up!

**Comment by momo-the-monster** [comment]
Aha! Indeed - this error shows up when I don't have a headset attached. That makes sense since you're detecting headset and controllers. So I instead suggest a warning that you cannot change controller mappings without a headset and controllers attached.
