### ISSUE TITLE
NullReferenceException for SteamVR_Behaviour_Pose, also a lot of InvalidHandle!

### ISSUE THREAD

**Issue by ChiefBreakeverything** [ValveSoftware/steamvr_unity_plugin#138]
Without doing any customization - just installing the plugin and running an empty scene with the rig prefab in it - I get a lot of errors saying some sort of variation of the following:

GetDigitalActionData error (/actions/default/in/GrabPinch): InvalidHandle handle: 1152982544682057874
UnityEngine.Debug:LogError(Object)
Valve.VR.SteamVR_Action_Boolean:UpdateValue(SteamVR_Input_Sources) (at Assets/SteamVR/Input/SteamVR_Action_Boolean.cs:60)
Valve.VR.SteamVR_Input:UpdateNonVisualActions(SteamVR_Input_Sources) (at Assets/SteamVR/Input/SteamVR_Input.cs:536)
Valve.VR.SteamVR_Input:UpdateNonVisualActions() (at Assets/SteamVR/Input/SteamVR_Input.cs:508)
Valve.VR.SteamVR_Input:Update() (at Assets/SteamVR/Input/SteamVR_Input.cs:322)
Valve.VR.SteamVR_Behaviour:Update() (at Assets/SteamVR/Scripts/SteamVR_Behaviour.cs:219)

It's happening on Update so there's a lot of it; it looks like there's one for each 'in' action.

Also, there's a few of these when starting:

NullReferenceException: Object reference not set to an instance of an object
Valve.VR.SteamVR_Behaviour_Pose.OnEnable () (at Assets/SteamVR/Input/SteamVR_Behaviour_Pose.cs:105)

Leads to this:

poseAction.AddOnDeviceConnectedChanged(inputSource, OnDeviceConnectedChanged);

If anything, it seems poseAction is null.

**Comment by zite** [comment]
Did SteamVR ask you to generate actions? And did that process complete successfully?

**Comment by cocapasteque** [comment]
Hello, same problem here. A lot of NullRefs and I can't get the demo Interaction_Examples scene to work at all. 
I don't think SteamVR asked me anything about generating actions. I will try to reimport it and post the details here.

**Comment by zite** [comment]
It's been a month and hopefully this has been fixed. Closing the issue.
