### ISSUE TITLE
Thumbstick button not recognised as a Thumbstick input by GetDeviceComponentName

### ISSUE THREAD

**Issue by RohanCruickshank** [ValveSoftware/steamvr_unity_plugin#142]
An action has been created that uses the thumbstick's button as the input.
I've been trying to refer to the specific GameObject that relates to the action's button (using SteamVR_Action_In.GetDeviceComponentName), and found that the thumbstick button isn't seen as part of the thumbstick.
```
Hints: Looking for action: Teleport
Can't find component transform for action: Teleport. Component name: "" 
```
And using the GetDeviceComponentName method simply returns an empty string.

An alternative feature that would solve my problem would be to have a way to refer to an action's input GameObjects directly from the action (provided the model is loaded etc.) 
(I am also unsure if GetDeviceComponentName currently works with Chords).

**Comment by RohanCruickshank** [comment]
![bindingui](https://user-images.githubusercontent.com/34473220/46392246-12070480-c724-11e8-86b2-f277a8c0b88a.PNG)

Current binding from the UI

**Comment by zite** [comment]
Unfortunately it looks like this feature is broken right now. We'll get it fixed soon.

**Comment by zite** [comment]
I believe this should be fixed in recent versions of SteamVR
