### ISSUE TITLE
Accessing raw controller data SteamVR 2.0 / Dynamic binding from the code

### ISSUE THREAD

**Issue by Frooxius** [ValveSoftware/steamvr_unity_plugin#145]
Hello,

I am still trying to wrap my head around the way the new Input system is supposed to work and integrate with the project and how have all the API's changed and what do I need to do to get a basic version working.

One issue I have with the system is that it's for fairly high level actions, as my project lets people build own tools, behaviors and scripts and gives access to the controller inputs, so I'd probably have to define very general actions, like "Primary trigger", "Secondary axis" and such.

I'd like to ask if there's still a way to access the raw controller data with the new version so I can expose those directly, without the abstraction layer in between?

I would also like to update the controller model (to make the trigger on the controller move as it does on the original for example) in my own code, but I deciphered yet how is that achieved in the provided example.

Alternatively, is it possible to use the new Action binding dynamically purely from the code, without having to generate the binding classes? So I would call some API to notify of the actions and then read those and possibly expose this functionality to the users as well, so they could create their own sets of actions and read those.

**Comment by KavanBahrami** [comment]
I second everything above! I’m also having issues with raw input and how to properly use the new system. Would LOVE more detailed documentation since this is core functionality.

**Comment by zite** [comment]
Hey @Frooxius, @KavanBahrami, it is technically possible to create an actions manifest at runtime and then load it. It would override whatever actions you have setup for the current application are though. My recommendation would be to either create an action for each button you'd like the user to be able to use, or to dynamically create and load an actions manifest (and corresponding binding jsons). Unfortunately currently there is not an easy way to simply load an individual additional action or binding at runtime.

Alternatively you can continue using the old SteamVR Unity Plugin v1.2.3 that we have on our github releases page. https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/1.2.3

**Comment by johnrreyna** [comment]
Thanks for your answer, @keithbradner. I don't know if you answered the first part of the question; is it impossible to access in code the raw input from the controllers, which then can easily be adapted to controller configurations for any VR device depending on what hardware is running, also in code, without having to go through window UI's, and the binding UI page where you have to assign actions to buttons and triggers? Not providing raw input access sounds crazy. And the solution of staying a full version behind sounds crazier. Am I missing something? This really only seems easier for non-coders who like to look at several UI windows, but for coders, that can cause many layers of bugs. Thanks again

**Comment by johnrreyna** [comment]
Just saw #253, thanks for your answer there. I'll give feedback to the link provided there, raw access really is so much easier for simple inputs, for many developers, but I'll read more about the reasons for the change
