### ISSUE TITLE
Where is SteamVR_LaserPointer.cs

### ISSUE THREAD

**Issue by nitpum** [ValveSoftware/steamvr_unity_plugin#147]
I can't find SteamVR_LaserPointer.cs in SteamVR v2.0.1

**Comment by zite** [comment]
This script was not upgraded to the new version and so it was removed. I'll readd it in the next version though since people seem to want this functionality.

**Comment by KavanBahrami** [comment]
@keithbradner It makes sense to me that anything that is 'default' in the SteamVR Home scene would also be default with the SteamVR Unity Plugin.

**Comment by zite** [comment]
I've readded this script in the beta version of the plugin. If you'd like you can test it before proper release here: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.1b2

**Comment by shiena** [comment]
@keithbradner 2.0.1 tag and 2.1b2 tag point to the same commit.
Do not you publish the 2.1 source yet?

https://github.com/ValveSoftware/steamvr_unity_plugin/tree/2.0.1
https://github.com/ValveSoftware/steamvr_unity_plugin/tree/2.1b2

**Comment by zite** [comment]
No, haven't published the source yet. All of it is in the linked unitypackage though

**Comment by zite** [comment]
Added in the latest release, and up on main as well.
