### ISSUE TITLE
Does not contain a definition for GetVREnabled Devices

### ISSUE THREAD

**Issue by GeoffreyPen** [ValveSoftware/steamvr_unity_plugin#149]
![errors](https://user-images.githubusercontent.com/25274253/46588896-231f8080-ca58-11e8-859c-1bb80dbae2d7.PNG)

Importing the plugin and trying to run it fails with the errors above.

**Comment by zite** [comment]
Hi @GeoffreyPen, that file should be empty now. I'd recommend you delete the steamvr folder before importing the new plugin.
