### ISSUE TITLE
Better Documentation! How do to simple stuff?

### ISSUE THREAD

**Issue by superjayman** [ValveSoftware/steamvr_unity_plugin#150]
Can someone outline the workflow required just to do simple thing as read button states?

Please explain the usage of this Version. Where is the proper usage documentation?

Show an example of Laser pointer interacting with objects and UI.

This version is NOT robust and messy in it's structure..

**Comment by chisely** [comment]
Very much agree with superjayman.

Its cool to have this advanced actions system, but there are still uses for the basic 

SteamVR_Controller.Input(index).GetPressDown(SteamVR_Controller.ButtonMask.Trigger)

There was no reason to completely remove this functionality, even if you want to promote the actions system.

**Comment by Frooxius** [comment]
Agreed as well, I think it would be beneficial for many applications to be able to work with the controllers directly, one of the reasons being that the abstraction can get in the way for some control schemes, particularly when you have different control schemes optimized for different controllers ( I've written a bit more here https://github.com/ValveSoftware/steamvr_unity_plugin/issues/146#issuecomment-429630945 ) or when you have a dynamic application where you want your users to work directly with a particular controller too.

I have a suggestion for one way to possibly achieve this: In addition to app defined actions, provide actions under standardized path. For example something like "general/knuckles/buttonA" or "general/oculustouch/trigger". If there was a way to easily enumerate all available actions for a controller as well, it would help make things more general as well.

Additionally it might be useful to let the app indicate to SteamVR which controllers it has optimized control scheme for and let the user to either use that (meaning the app will work with the controller directly) or fallback to a more general abstract input scheme for controllers that aren't supported or when the user wants to customize the scheme anyway.

**Comment by chensida13** [comment]
if you are going to remove the buttons, you should at least provide the same functionalities to access them, all of them. How does this action system allow me to access **k_EButton_ProximitySensor**?

**Comment by bddckr** [comment]
@chensida13 https://github.com/ValveSoftware/steamvr_unity_plugin/issues/155#issuecomment-430731266

**Comment by ckorris** [comment]
+1 on adding the old functionality. I work on a Unity plugin where we need everything to work out of the box for the user, without having to configure input settings. At the moment this does not seem possible with the new system.

**Comment by ckorris** [comment]
Actually I got button detection working. I was testing it in the example scene in the new plugin, and for awhile I couldn't get it to run. But simply running it an empty scene instead made it work. The idea is to check the API directly, using code much like what StreamVR_TrackedController used to. 

This class lets you select a hand and a button, and will print when that button is down. You should be able to modify it for your purposes. 

```
using Valve.VR;

public class ForceControllerCheckSlim : MonoBehaviour
{
    public EVRButtonId ButtonToCheck = EVRButtonId.k_EButton_SteamVR_Trigger;
    public ControllerHand Hand = ControllerHand.Right;

    CVRSystem system = OpenVR.System;

    private uint deviceindex
    {
        get
        {
            ETrackedControllerRole role = Hand == ControllerHand.Left ? ETrackedControllerRole.LeftHand : ETrackedControllerRole.RightHand;
            return system.GetTrackedDeviceIndexForControllerRole(role);
        }
    }

    VRControllerState_t state = new VRControllerState_t();
    


    // Update is called once per frame
    void Update()
    {
        if (system != null && system.GetControllerState(deviceindex, ref state, (uint)System.Runtime.InteropServices.Marshal.SizeOf(typeof(VRControllerState_t))))
        {
            ulong trigger = state.ulButtonPressed & (1UL << ((int)ButtonToCheck));
            if(trigger > 0L)
            {
                print(ButtonToCheck + " on " + Hand + " controller is down.");
            }

        }
    }
}
public enum ControllerHand
{
    Left,
    Right
}
```

**Comment by ckorris** [comment]
One more update - it seems that it wasn't the test scene itself. I'm finding that once SteamVR is called by a script, enough to get the 4-5 lines in your console about loading actions, etc. then that script above will no longer work in any scene until you restart Unity. What I've had to do is remove most references to SteamVR (OpenVR is okay) in all scripts in the scene. 

It's not exactly _any_ call to SteamVR that causes this, though. For example, I had SteamVR_Render in the scene to test things, and it never interfered. A few other minor references here and there are also harmless. Maybe there's a Singleton somewhere that causes this?

**Comment by superjayman** [comment]
Hey Steam Dudes...Who Ever Is In Charge Of What You Guys Are Doing He Should Be Fired By Now.. What The Hell Is Going On VALVE?

**Comment by superjayman** [comment]
If you're going to introduce new features DO IT PROPERLY!!!

**Comment by zite** [comment]
This issue seems to be a catchall, if somebody has a specific issue please comment on existing issues or create a new one. There is now documentation online at https://valvesoftware.github.io/steamvr_unity_plugin/articles/SteamVR-Input.html
