### ISSUE TITLE
Using 2 Controllers + 2 Trackers In Hand and Missing Actions

### ISSUE THREAD

**Issue by nocanwin** [ValveSoftware/steamvr_unity_plugin#152]
I'm working on a training application and we run two controllers and two trackers at the same time. Our setup is unusual but fairly straightforward. We only care about trigger pulls on the controllers and have hardware hooked up to the trackers to do trigger pulls via the pogo pins. Using the new input system I'm only able to get actions on two of the devices, depending on which ones were powered on first. Input for all the devices shows up in the input debugger. 

I've tried every configuration I could think of, but nothing works. I'd at least expect adding actions for each controller/tracker and then checking using SteamVR_Input_Sources.Any to work, but unfortunately it does not.

Hopefully this is a bug and not a feature.

**Comment by nocanwin** [comment]
Any thoughts about this functionality returning  @zite ?

**Comment by nocanwin** [comment]
Figured out I could work around the issue by only having the controller/trackers powered on that are in use. Slightly annoying that powering on/off controllers/trackers will often sometimes popup the overlay so you're constantly hitting the little button on the hmd to hide it. Not ideal since most of the people using the device are non gamers.

Sure would be nice if having two ActionSets active, one for controllers and one for trackers in hand worked. :)

**Comment by zite** [comment]
I believe you should be able to bind actions to specific trackers with the new tracker update. You can call ActivatePrimary on the action sets you want to be active (unlimited active at a time).

**Comment by nocanwin** [comment]
Sorry, I don't think I'm explaining my situation clearly. I can bind the action to the tracker and controllers just fine, but if 4 devices are powered on, two trackers and two controller. I only get the action firing on two of the devices.

My guess is this is because you are filtering the raw input at some point. I can see it showing green for all devices in the input debugger. I assume you're filtering the raw input because you want to apply a Left/Right label to devices that are "InHand" and people don't have more than two hands! Ok so I tried to make two action sets. The first for the controllers and the second for the trackers, but this also fails. The pos/rot tracking works fine for all the devices, but trigger input will fail on two of the devices depending on the order they get powered on.

You can see what's going on in Unity using two controllers and a tracker. Setup an action set for the controllers and an action set for trackers. Make a Fire action for each action set. Open the binding ui and assign Fire to the controller trigger then change to the tracker and assign fire to the tracker trigger. It's role needs to be in hand. Make a script with this code.

void Start()
{
      SteamVR_Input.actionSets[0].ActivatePrimary(false);
      SteamVR_Input.actionSets[1].ActivateSecondary(false);
}
void Update()
{
       if (SteamVR_Input.controllers.inActions.Fire.GetStateDown(SteamVR_Input_Sources.LeftHand))
           Debug.Log("Controller Left");
       if (SteamVR_Input.controllers.inActions.Fire.GetStateDown(SteamVR_Input_Sources.RightHand))
           Debug.Log("Controller Right");
       if (SteamVR_Input.trackers.inActions.Fire.GetStateDown(SteamVR_Input_Sources.LeftHand))
           Debug.Log("Tracker Left");
       if (SteamVR_Input.trackers.inActions.Fire.GetStateDown(SteamVR_Input_Sources.RightHand))
           Debug.Log("Tracker Right");
}

Play the editor and then, this is important, power on the devices in this order: controller, tracker, controller. You'll never get a debug log for the last controller. Sorry for the hand holding, but I'm not sure how to communicate exactly what's going on. Thanks for your help!

**Comment by zite** [comment]
In your trackers action set try creating a FireLeft action and a FireRight action, then only bind the left tracker to the fireleft action and the right tracker to the fireright action. Then when you're querying GetStateDown pass in SteamVR_Input_Sources.Any.

**Comment by nocanwin** [comment]
Gave it a shot, but I still get the same behavior. Only the first two devices powered on will hit their debug.

**Comment by nocanwin** [comment]
As a side note. I hit play in the editor and then turn on the controllers/trackers. If they're on before you hit play it'll be a random two that work correctly.

**Comment by zite** [comment]
With the recent beta you can assign the trackers to distinct slots in the binding ui (like left shoulder / right shoulder) and then query those specific input sources on the action. Check out the beta here and let me know if this fixes your scenario: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.1b2

**Comment by nocanwin** [comment]
ok, I'll take a look, thanks.

**Comment by nocanwin** [comment]
SOLUTION: This issue is resolved by giving the trackers non handed assignments and then manually editing the generated json files and adding a input source you want. If you're not comfortable manually editing the generated file then see issue #232 for how to give the binding UI additional input assignments. Works on v2.0.1 of the plugin. @keithbradner Any chance we can get inputs for non handed trackers on by default?

**Comment by kisak-valve** [comment]
@keithbradner, do you want this issue report held open for the follow up question?

**Comment by CarlosMeloP** [comment]
Hi @keithbradner , any update in relation to being able to assign actions to non handed trackers? I am developing an application where we use 2 trackers on a custom controller where we use  the pogo pins for input and another 2 trackers on straps around the wrist to give positional hand, but we would like to attach flex sensors to the trackers on the hands to also get input.

Also, I tried contacting HTC support to ask about the haptic feedback for the trackers and they told me that I had to contact the developer forums, I can get haptic feedback working on the controllers but not on the trackers, and even after adding an out action of type vibration, I can't assign it on the binding input for the trackers.

Thanks!

![screenshot 56](https://user-images.githubusercontent.com/12722433/52640159-8f882000-2f21-11e9-88fb-0f8f10b55335.png)

**Comment by nocanwin** [comment]
Even though there is a workaround I wanted to bump this thread to again ask for official support for getting button presses from trackers with non-hand roles @keithbradner . I'm don't believe I'm the only dev that is running into this issue. See issue #484 & #381 . If we can't is there a reason why? Low priority, design decision? I'm nervous that the workaround will stop working one of theses days.

**Comment by zite** [comment]
I believe this has been fixed now, can someone confirm?

**Comment by kisak-valve** [comment]
Closing pending feedback.
