### ISSUE TITLE
VRControllerState_t EVRButtonId and k_EButton no longer work, can't read ProximitySensor.

### ISSUE THREAD

**Issue by tdbe** [ValveSoftware/steamvr_unity_plugin#155]
Since you've switched to the action system we can no longer detect if the user took the headset off their head. (in addition to other info)

It seems that the following stuff no longer works, and the scripts that used to have this logic, like "SteamVR_TrackedController.cs" have been removed. It might be that the C++ backend no longer provides these correctly? But the following no longer works, for any type of button or stat:

```
bool success = OpenVR.System.GetControllerState(controllerIndex, ref controllerState, (uint)System.Runtime.InteropServices.Marshal.SizeOf(typeof(VRControllerState_t)));
ulong prox = controllerState.ulButtonPressed & (1UL << ((int)EVRButtonId.k_EButton_ProximitySensor));

```

The only "alternative" is to use 
`OpenVR.System.GetTrackedDeviceActivityLevel(0) == EDeviceActivityLevel.k_EDeviceActivityLevel_UserInteraction`, but this is useless because the headset could be rolling on the floor for 10 hours and the app would think there was a user playing the game the  whole time ffs. We require to run aspects of apps only while human eyeballs are inside the headset.

`k_EDeviceActivityLevel_UserInteraction = 1,` means a union of either headset movement or prox sensor is true. And there's no way to poll just the prox sensor. The unity builtin `UnityEngine.XR.XRDevice.userPresence == UnityEngine.XR.UserPresenceState.Present` is the exact useless thing. Not to mention it takes like 15 seconds for `k_EDeviceActivityLevel_UserInteraction` to become 0, and only if the headset has been sitting 100% still (read: not bumped by anyone/anything or held in one's hand).

**Comment by lawwong** [comment]
https://github.com/ValveSoftware/steamvr_unity_plugin/issues/128

Seems like GetControllerState no longer working with the new input system...
But I still think that v2.0 should compatible with old APIs that are not obsoleted.

**Comment by chensida13** [comment]
any work around? solution? I've been trying to figuring this out.

**Comment by zite** [comment]
You can now bind the proximity sensor of each headset to a boolean action. Just like you would with controllers if you open the binding UI, click on your application, then under "Current Controller" click whatever's currently selected and it'll give you other options. One of those options should be the headset you currently have plugged in. Select that, create a binding for it, and then in it's list of bindable things you should see a Proximity Sensor. Then hit "Replace Default Binding" as you normally would.

One note about this, if you rename the json after saving you'll need to edit a line in the actions.json accordingly.

**Comment by visca-c** [comment]
> You can now bind the proximity sensor of each headset to a boolean action. Just like you would with controllers if you open the binding UI, click on your application, then under "Current Controller" click whatever's currently selected and it'll give you other options. One of those options should be the headset you currently have plugged in. Select that, create a binding for it, and then in it's list of bindable things you should see a Proximity Sensor. Then hit "Replace Default Binding" as you normally would.
> 
> One note about this, if you rename the json after saving you'll need to edit a line in the actions.json accordingly.

@keithbradner I tried what you said, but the proximity sensor didn't show up on the list. But it definitely triggers in the Input Debugger, as it lights up when I cover my finger on the sensor. 

![binding](https://user-images.githubusercontent.com/24884946/47113826-050c0a00-d228-11e8-9c76-7f3b53c972ec.PNG)

![inputdebugger](https://user-images.githubusercontent.com/24884946/47113778-e443b480-d227-11e8-897d-fb827906eeae.PNG)

**Comment by bddckr** [comment]
@keithbradner Sadly https://github.com/ValveSoftware/openvr/issues/628 still applies, making the proximity sensor unusable in production.

**Comment by tdbe** [comment]
> > You can now bind the proximity sensor of each headset to a boolean action. Just like you would with controllers if you open the binding UI, click on your application, then under "Current Controller" click whatever's currently selected and it'll give you other options. One of those options should be the headset you currently have plugged in. Select that, create a binding for it, and then in it's list of bindable things you should see a Proximity Sensor. Then hit "Replace Default Binding" as you normally would.
> > One note about this, if you rename the json after saving you'll need to edit a line in the actions.json accordingly.
> 
> I tried what you said, but the proximity sensor didn't show up on the list. But it definitely triggers in the Input Debugger, as it lights up when I cover my finger on the sensor.
> 
> ![binding](https://user-images.githubusercontent.com/24884946/47113826-050c0a00-d228-11e8-9c76-7f3b53c972ec.PNG)
> 
> ![inputdebugger](https://user-images.githubusercontent.com/24884946/47113778-e443b480-d227-11e8-897d-fb827906eeae.PNG)

How do you even get to this screen? I added a SteamVR_Behaviour_Boolean to my scene, InputSource: Any, Boolean Action: created a new action in the SteamVR Input tab called Prox_Test of Type boolean. Then if I click on Open binding UI it opens a local server webpage with "Choose an application to edit" and there's a bunch of VR games in that list (read: not dev projects) ("http://localhost:8998/dashboard/controllerbinding.html?app=application.generated.unity.basicvrguistarterpackage.exe")

So 1). Unity is not in that list. And 2). will this work without steam? If I were to create a binding here, would it be saved magically in my unity project? The UI looks like a per-application-setting menu for Steam/SteamVR for when you run a certain game locally and want to customize input for yourself as a user. Confusing and undocumented AF. Volvo, user test this stuff before pushing plzkthx

**Comment by chensida13** [comment]
@tdbe lucky for you man, at least your proximity_sensor shows up somewhere. On my part it just doesn't show up, not in the headset binding, not in the controller either.

![capture](https://user-images.githubusercontent.com/24884946/47160201-6e8a2800-d2bd-11e8-91b5-bb52f1cb5522.PNG)

**Comment by visca-c** [comment]
@keithbradner I am still not able to bind the proximity sensor (I'm using Vive Pro), it's really dragging down my team's development progress. Do you have any suggestion for solution? Workaround?

**Comment by zite** [comment]
For now you could manually create a headset binding file with the binding:

Create a file named binding_vive_pro.json in the root of your project directory (next to the actions.json.
In the file put the following:
`{
   "alias_info" : {},
   "bindings" : {
      "/actions/default" : {
         "sources" : [
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/default/in/[YOUR ACTION NAME HERE]"
                  }
               },
               "mode" : "button",
               "path" : "/user/head/proximity"
            }
         ]
      }
   },
   "controller_type" : "vive_pro",
   "description" : "",
   "name" : "Default configuration for vive pro",
   "options" : {},
   "simulated_actions" : []
}
`

Then open your actions.json and scroll down to where it lists "default_bindings" and add one for the vive_pro:

`
{
    "binding_url" : "binding_vive_pro.json",
    "controller_type" : "vive_pro"
}
`
If that's your last item in the list make sure there's a comma after the closing bracket above it and there is no comma after it. json is pretty picky about that.

**Comment by tdbe** [comment]
I also tested on an HTC Vive (not Pro) and (as opposed to the oculus which does have it) I could not find a proximity sensor binding, but the above workaround works. 

But if you're using this workaround **note** that hitting the Save and Generate button in Unity will reset your actions.json file so you'll have to re-edit it manually to reinclude your workaround references/entries.

**Comment by visca-c** [comment]
@keithbradner I added the lines into the json files as instructed. I named my Action Name "HeadSetOn". But i still cannot get the sensor to register. My debug message only gets triggered by the OnUpdate(). What's the next step to get this working?

![capture](https://user-images.githubusercontent.com/24884946/47458354-5592e280-d7a7-11e8-9c4e-bf09a87f2e97.PNG)

**Comment by visca-c** [comment]
@keithbradner If you could get back to me on this problem, it would be a great help. Thanks!

**Comment by zite** [comment]
I've got the beta version up here: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.1b2

There's a debug log in Player.cs that fires when the user puts on and takes off their headset. (triggering the proximity sensor). Unfortunately there's still some bugs in the binding UI so you do have to manually change jsons to get this working currently.

actions.json
* add a new action for proximity
* add default binding entries for the hmds (vive, vive_pro, holographic_hmd, rift)

binding_hmd.json
* a binding file needs to be created for each hmd to bind this action. See the jsons in the plugin for an example.

**Comment by zite** [comment]
This is now in 2.2b1: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.2b1

**Comment by zite** [comment]
Now in the latest release on the asset store.
