### ISSUE TITLE
If you are hovering an highlighted object and it is deactivated, the highlight keeps there

### ISSUE THREAD

**Issue by PabloVilas97** [ValveSoftware/steamvr_unity_plugin#157]
Hiya,

if you are hovering an object
![hovering](https://user-images.githubusercontent.com/44195379/47009065-d9135a80-d13b-11e8-9915-863491d98f0b.png)

and **it is deactivated**, the highlight keeps there
![highlight keeps](https://user-images.githubusercontent.com/44195379/47009130-08c26280-d13c-11e8-9c84-fa757c066031.png)

**Comment by zite** [comment]
I believe this has been fixed in the beta version of the plugin up here: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.1b2

**Comment by axandar** [comment]
Newest plugin version on assets store still contains this bug. I've made a pull request with the fix which seems to solve the problem in my case.
#283

**Comment by zite** [comment]
I believe this should be fixed on RC2 here: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.2RC2

**Comment by zite** [comment]
Should be fixed in the latest release
