### ISSUE TITLE
Knuckles EV3 raw data access

### ISSUE THREAD

**Issue by Frooxius** [ValveSoftware/steamvr_unity_plugin#158]
Hello,

I have recently received my Knuckles EV3 kit and I would like to integrate it into my project, at least as a controller for now (without the skeletal tracking). 

Is there a way to access the raw data with the older version of the SDK? From my tests it seems to act as a Vive controller, with the buttons automatically mapped, not giving me access to the joystick or the grip.

**Comment by zite** [comment]
That's about all the access you get with the old system unfortunately. There wasn't enough room to fit all the data the knuckles gives into the old structure.
