### ISSUE TITLE
Feature request: Way to import/sync new actions+their bindings from an external project/library etc

### ISSUE THREAD

**Issue by tdbe** [ValveSoftware/steamvr_unity_plugin#161]
The new Action based input system is conceptually really good and really powerful. But I noticed 3 problems.

1. Is there a way to migrate my actions from Unity project A to Unity project B? I tried copying actions.json to a new project and got loads of internal ID/reference errors until I reverted to default and manually added my actions from scratch. Which files do I have to copy for it to actually work?

2. There should be some kind of modularization to the actions jsons in a project so that you can bring in new actions from another utility project or library. Say I have my main project A, and a UI tool with 3 new bindings in project B. How do I import project B into project A?

3. After you import/sync actions, you should also be able to automatically import their key bindings without needing to manually assign them in the Binding UI. This should be possible if you know which files to copy over.

**Comment by zite** [comment]
For right now you probably need to copy the whole SteamVR_Input folder. Modular action manifests / bindings are in the works.

**Comment by zite** [comment]
I've implemented this functionality in the beta version of the plugin. Take a look and let me know if this works for your scenario: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.1b2

**Comment by zite** [comment]
This is now in 2.2b1: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.2b1

**Comment by zite** [comment]
Added in the latest release
