### ISSUE TITLE
Empty prefabs causes "Save and generate" to stall

### ISSUE THREAD

**Issue by blauwepiet** [ValveSoftware/steamvr_unity_plugin#162]
It took me quite a while to figure out why I couldn't save and generate my actions, but then when I started debugging I found out that the AssignDefaultsInPrefabs function goes through all prefabs and tries to make a Gameobject out of them. That is where an empty prefab breaks the code and raises the following exception:

> NullReferenceException: Object reference not set to an instance of an object
> Valve.VR.SteamVR_Input_Generator.AssignDefaultsInPrefabs () (at Assets/SteamVR/Input/Editor/SteamVR_Input_Generator.cs:280)
> Valve.VR.SteamVR_Input_Generator.GenerationStep_AssignDefaultActions () (at Assets/SteamVR/Input/Editor/SteamVR_Input_Generator.cs:258)
> Valve.VR.SteamVR_Input_Generator.ExecuteNextStep (GenerationSteps currentStep) (at Assets/SteamVR/Input/Editor/SteamVR_Input_Generator.cs:189)
> Valve.VR.SteamVR_Input_Generator.CheckForNextStep () (at Assets/SteamVR/Input/Editor/SteamVR_Input_Generator.cs:167)
> Valve.VR.SteamVR_Input_Generator.OnEditorUpdate () (at Assets/SteamVR/Input/Editor/SteamVR_Input_Generator.cs:139)
> Valve.VR.SteamVR_Input_EditorWindow.OnInspectorUpdate () (at Assets/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:246)
> System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
> Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
> System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
> System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
> UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:295)
> UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:288)
> UnityEditor.HostView.OnInspectorUpdate () (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:175)

The easy work around is not to have empty prefabs in your project ;). But otherwise it think it should be an easy fix.

**Comment by zite** [comment]
Thanks for the report! We'll get this fixed up.

**Comment by zite** [comment]
Please give the new beta a shot. We no longer iterate through all the scenes and prefabs so this shouldn't be an issue anymore.

https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.1b2

**Comment by zite** [comment]
This is now in 2.2b1 here: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.2b1

**Comment by dpggit** [comment]
i am still getting this error with 2.0.1 version, the latests in the Unity asset store, using Unity 2018.2
NullReferenceException: Object reference not set to an instance of an object
Valve.VR.SteamVR_Input_Generator.AssignDefaultsInPrefabs ()

**Comment by zite** [comment]
Fixed in the latest release
