### ISSUE TITLE
How to use the new EButtonIds for the Knuckles

### ISSUE THREAD

**Issue by AndersMalmgren** [ValveSoftware/steamvr_unity_plugin#163]
I'm on legacy Unity plugin, we have a very advanced custom Command <> Binding system in place that frankly is more flexible for our use cases as of now so we cant move to the new Input system for now. (I will create a separate Issue about this later when I have tried the new Input System more).

I have updated openvr_api.cs but calling ```SteamVR_Controller.Device.GetAxis(k_EButton_Knuckles_JoyStick) ``` returns a Vector2 that never changes. If I update the plugin to 2.1 the types to query the device is gone.

I understand the usefulness of the abstraction from the Hardware you gusy have made, but sofar our own abstraction is more flexible for our use case.

**Comment by Frooxius** [comment]
Apparently you can't access any of the new Knuckles inputs using the old SDK: https://github.com/ValveSoftware/steamvr_unity_plugin/issues/158

I have the same issue with the new abstraction layer. What I ended up doing is making optional actions for each raw input of each controller I have optimized support for and created default bindings for these for the corresponding controller.

It's kinda ugly, but I don't see any other approach right now.

**Comment by AndersMalmgren** [comment]
@Frooxius Ah ok, then I rather port it properly. :D I have created a github issue with the issues I have found with the new SDK, I hope they will look into it
