### ISSUE TITLE
Where is SteamVR_Controller class?

### ISSUE THREAD

**Issue by ahmadsay** [ValveSoftware/steamvr_unity_plugin#164]
It was removed? I can't find it in SteamVR 2.01.

Here is my outdated code: 

private SteamVR_Controller.Device controller2 { 
get {
 return SteamVR_Controller.Input((int)trackedObj.index); 
}
 }

**Comment by kisak-valve** [comment]
Hello @ahmadsay, this is already being discussed at #146. Closing as a duplicate.
