### ISSUE TITLE
Feedback from real world game.

### ISSUE THREAD

**Issue by AndersMalmgren** [ValveSoftware/steamvr_unity_plugin#165]
Hey guys. First I cant test the new SDK to the fullest because I get the blank screen bug #154 so maybe some feedback is not valid. Here comes a LOOONG wall of text, but I hope you guys value feedback from a released and out in the world game that as seen some polish passes over the years (And alot of that is interaction).

First let me show you guys how our own abstraction and binding works. We have two kinds of abstraction, Interaction abstraction and Command abstraction.

Interaction abstraction binding view

![image](https://user-images.githubusercontent.com/817577/47254208-1be87180-d45f-11e8-835e-0c028a06ef40.png)

This is the Vive Wands default bindings. We have 4 interaction classes (Called ItemType below), the last one here configured for using Toggle behavior which means when using trigger that you use the Grip button to let go of the item. I guess this could be mimicked with the new SDK by creating 4 Actions, GrabInteractible, GrabItem, GrabFrontgrip and GrabWeapon. I hope the toggle behavior can be abstracted into the binding, havent been able to test because of above mentioned binding bug. 

Though, our code has some smart logic to it. If you use Trigger for Weapons you cant select Hold, only Toggle (Since you use the trigger to fire the weapon), I guess if the user creates a faulty bindings that they should blame themself, but its a lot less snappy than that the game validates bindings like our current solution. Also when using trigger for weapons you need to wait until he releases the trigger until the trigger can be used to fire the weapon. This is pretty elegant handled by our abstraction.

```
if (!AttachedHand.InteractionUsesTrigger(ItemType) || AttachedHand.TriggerReleasedSincePickup) {
	if (AttachedHand.Trigger.PressUp) {
		firstShot = true;
	}
	SetTriggerAnimationRatio(AttachedHand.Trigger);
	if (CanFireNextShot(AttachedHand.Trigger)) {
		this.Fire ();
		firstShot = false;
	}
}
```

We check if current ItemType uses trigger to grab it using the ```AttachedHand.InteractionUsesTrigger``` method or if trigger was released since pickup. 

The ```InteractionUsesTrigger``` method could be replaced by a SDK method something like 
```SteamVR_Input.ActionsConflict(SteamVR_Input._default.inActions.TriggerPressed, SteamVR_Input._default.inActions.GrabWeapon)```

The ```TriggerReleasedSincePickup``` property is harder to replece I guess, maybe a TriggerReleased action that sets the ```TriggerReleasedSincePickup``` bool. It would be cool with something built in here, but I just cant see how that would happen.

Moving on to Command abstractions. Here is the default bindings for Vive Wand
![image](https://user-images.githubusercontent.com/817577/47254443-ef365900-d462-11e8-9e52-2ff69be5d673.png)

Here the user can select which button to use for a specific command. We also have Command groups as we call them, and if a user tries to use the same button twice within a command group he gets a error and cant proceed.

![image](https://user-images.githubusercontent.com/817577/47254468-5bb15800-d463-11e8-9911-0baf6e19f50a.png)

This is how we define command groups today, and it would be awesome if we can do the same for Actions.

```
private static readonly Command[][] commandGroups = new []
{
    new[] { Command.BoltRelease, Command.ChangeFireMode, Command.MagRelease },
    new[] { Command.ReleaseDrum, Command.CockHammer }
};
```

On the same subject, the Rift does not have a Application Menu button like the Vive wand. So to get into the in game menu we have some clever logic. Either the menu button is used distinct only for the Menu or you cant have a item in the hand while pressing the menu button to bring up the menu (It will instead be used to control the function on the firearm for example).  
```
if (hand.CheckForPlayerCommand(Command.ShowMenu) && (!hand.IsInteracting || !hand.ItemInHand.HasCommands || NVRPlayer.InputStrategy.ButtonIsUsedDistinct(Command.ShowMenu)))
```
So above code checks if the command for show menu is issued. Then it looks if the hand is not interacting or if the item has no commands or if the menu button is used distinct. This means even if the menu button is not used for this current item you still cant use the menu, a trade of we made at the time not making our domain too complex.

I can see a more elegant solution for this if we name above Command groups (Action groups). You could test if a action will conflict with a action group. Something like ```SteamVR_Input.ActionConflictsWithActionGroup(SteamVR_Input._default.inActions.ShowMenu, "FirearmGroup");```

Another cool and useful feature we have is a method for checking if a Command is Touched. Like
```
if (AttachedHand.CheckForPlayerCommandTouched(Command.CockHammer))
	AttachedHand.SetFingerIKState(Fingers.Thumb, true, 0.25f);
```

Here it is in action (click for youtube)
[![image](https://user-images.githubusercontent.com/817577/47255442-7d194080-d471-11e8-8f39-7bbc3514107d.png)](https://www.youtube.com/watch?v=W5U_dE2TpBU)

I guess this could be mimicked with the new SDK by creating two Actions, one CockHammer and one HammerTouched. But it would be cool if the Action could have multiple states somehow, just a side point.

Lastly in game tutorials. I see that you have some Hint example in the demo but it seems todo nothing when I press the buttons, plus I cant really understand the code. I tried ```GetDeviceComponentName``` but it just returns some gibberish numbers.  Our in game tutorials are pretty advanced.  Here is a example of a interaction text screen

![image](https://user-images.githubusercontent.com/817577/47254711-3d992700-d466-11e8-8630-51a7778ee550.png)

Its completely dynamic and reacts to your settings. Here same screen when using Grip/Hold binding
![image](https://user-images.githubusercontent.com/817577/47254735-789b5a80-d466-11e8-9f0d-69b990c78cc3.png)

```
    [CreateAssetMenu(menuName = "Tutorial/Interact")]
    public class InteractStep : TutorialStep
    {
        public string ItemType;
        
        public override IEnumerator Execute()
        {
           
            ShowPopup(Item.ColliderParent.transform, string.Format("Grab the {0} by {1}.", ItemType, GetInteractionCaption(Item.ItemType)));

            while (Item && !Item.IsAttached)
            {
                yield return null;
            }
            
        }
    }
```

I call the ```GetInteractionCaption``` to get the text, same for Commands

![image](https://user-images.githubusercontent.com/817577/47254817-3de5f200-d467-11e8-8056-6a620473c218.png)

I call ```GetCommandCaption``` to get the text

```
    [CreateAssetMenu(menuName = "Tutorial/ChangeFireModeStep")]
    public class ChangeFireModeStep : TutorialStep
    {
        public FireModes Firemode; 

        public override IEnumerator Execute()
        {
            var firearm = Get<Firearm>();

            ShowPopup(firearm.FireSelector.transform, string.Format("Press {0} to change fire mode to {1} auto.", GetCommandCaption(Command.ChangeFireMode), Firemode.ToString().ToLower()));

            while (firearm.FireSelector.Mode != Firemode)
                yield return null;

        }
    }
```

I hope we can have a discussion on howto get these features into the SDK, thanks!

edit: Added command touch section.

**Comment by AndersMalmgren** [comment]
I still cant work with the binding UI thanks to #154 but i noticed I can play around with the bindings from within the VR dashboard. So my first obstacle, I cant find a way to bind Bool action to be true when you press trigger and stay true until you press grip button. This is our default behavior for Vive wands and how most people want to play with it since its hard to keep the vive wand grip button pressed during the entire play session.

**Comment by AndersMalmgren** [comment]
One ugly workaround would be to create two actions Grip and GripReleased, in the case of the Vive wand then Grip would be bound to Trigger and the GripReleased to the Grip button. When Grip is true you also check if GripReleased is true, if its true than yuo use Hold behaviour, if its not true you use Toggle behavior. It will break if the user holds the grip button while pressing trigger so its not a viable solution sadly.

We need a mechanism for defining true and false bindings for a bool action. But we also need a way to define that true should be true UNTIL the false binding triggers.

**Comment by AndersMalmgren** [comment]
I found the undocumented ActivateSecondary and ActivatePrimary yesterday. Need to test those more. I noticed if I create a action set I need to call one of these to activate the set. Maybe its means that Primary will outwin Secondary if they use the same devices for actions. Will try some more tonight, but it I cant express enough how important it is with good docs.

**Comment by zite** [comment]
Grip and GripToggle make sense as optional modes that the user can bind if they choose. 

I'll pass on the feedback about a function to get conflicts.

I'm currently reworking how the actionset activation works since, as you say, it was a bit confusing. I'm going with a single Activate method. For now though: ActivatePrimary is the one you want to use. ActivateSecondary activates the set for the "secondary" input device. So the hand not specified by activate primary.

**Comment by AndersMalmgren** [comment]
Thanks for reply @keithbradner 

About conflict, 

You have it almost in place already. You have functions for Setting a action set to primary and secondary.

If the secondary conflicts with primary then deactive that secondary action. Then we can poll GetActive to test if a command conflicts. Would be very elegant

A real world example: The player has set weapon functions to the D Pad on the Vive. He now tries to use the touchpad to walk with he same hand holding the weapon.  The action for walking will be deactivated because it conflicts with D pad

**Comment by AndersMalmgren** [comment]
Alright so while I wait for you guys to look into the conflict stuff I started to look into how to make our Tutorial work with the new API,  after looking into #167 i fixed so the `GetDeviceComponentName` method returned what it should. I guess **scroll_wheel** is just a bug and it Should return **touchpad**. 

Lets say **Release magazine** is bound to D Pad North. Then a text saying Touchpad wont do. Maybe you guys can add a method, `GetUserFriendlyDescription` which will return something like 'D Pad North' but maybe thats not enough, maybe it even needs to return "Touch D Pad North" or "Click D Pad North",

**Comment by AndersMalmgren** [comment]
Let me know if you want me to create individual issues for each thing I find, otherwise I do it all here.

Ok so we have a Sprint feature in the game. You are moving and press the Sprint action and start to sprint. With our old mechanics the user could choose to toggle this or hold the button to sprint.

You have a Toggle button binding which is nice, it would work for this since we do not want to bind that feature to two buttons like we want interact above. Problem is with our old implementation if the player bumped into something or raised his firearm we aborted the sprint and he needed to press the button again to start sprint. This does not work with the Toggle button binding. We need some way to force a reset to the toggle.

**Comment by kisak-valve** [comment]
Hello @AndersMalmgren, multi-issue issue reports aren't good for any issue tracker and separate issue reports, one issue per issue report is the better option.

**Comment by AndersMalmgren** [comment]
@kisak-valve Alright, I created 3 new issues
