### ISSUE TITLE
GetStateDown one true for a single frame

### ISSUE THREAD

**Issue by TheMadmanofChaos** [ValveSoftware/steamvr_unity_plugin#171]
Unity Version: 2018.2.11f1
Steam VR version: 1540419160

Currently trying to wrap my head around Steam VR as a whole, and the recent 2.0 version has made that difficult due to lack of documentation. I'm trying something simple that "Should" be working, but isn't.

`public void Planter()
        {
            
            if (SteamVR_Input._default.inActions.Plant.GetStateDown(hand.handType))
            {
                Plant();
            }
        }
        void Update()
        {
            if (SteamVR_Input._default.inActions.Plant.GetStateDown(hand.handType))
                Debug.Log(SteamVR_Input._default.inActions.Plant.GetStateDown(hand.handType));
            Planter();
        }
    }
}`

The goal is, every frame to plant a flower so long as the button is held down. However, I can't seem to find a way to read it as held down as it only returns true once, then false every frame after that. I have tried the button bound as "Held" in controller config UI, but that hasn't seemed to work.

If I am doing something silly and missed a simple answer, feel free to let me know.

**Comment by zite** [comment]
Hi, can I ask where you'd be expecting documentation? Personally, I look in the code, for intellisense's summaries of methods, so that's where I put docs. Are you expecting a website, wiki, or folder of documentation with per function docs?

As to your question: GetStateDown triggers when the state changes from false to true. GetStateUp triggers when the state changes from true to false. GetState gives you the plain state.

**Comment by TheMadmanofChaos** [comment]
Personally, I'd prefer "Any of the above". Right now, all I can do is dig through the provided examples and try to reverse-engineer why anything is working, digging through a dozen class files trying to find anything.  I'm trying to learn this, and any tutorial I can find is so painfully out of date as to be near useless. So, it has been a bit of a "Trial by fire" for someone who only recently picked up C#. It is almost like Voodoo magic: You can see something it is working, but trying to copy it throws so many errors because of everything you can't see happening. 

A matter of "You can't find it, because you aren't sure what to be looking for."

As for your solution, it works(Even if I could have sworn I tried that earlier and it wasn't working...). What is so vexing is the simple tutorial for this version of steam VR is frustratingly inaccurate because of name changes. https://steamcommunity.com/sharedfiles/filedetails/?id=1416820276

**Comment by zite** [comment]
Thanks for the feedback. I'll work on updating, and adding to the documentation.
