### ISSUE TITLE
2.01 with new input system doesn't work

### ISSUE THREAD

**Issue by bartburkhardt** [ValveSoftware/steamvr_unity_plugin#175]
I just updated to latest version with new input system, but it doesn't work and its also unclear how to generate the template files.

Is there documentation how to generate a Vive with the two wand controllers?

**Comment by superjayman** [comment]
Have the same issue??

**Comment by bartburkhardt** [comment]
I don't know what happened but now I don't get the errors. 
I remember generated the SteamVR Input file and opened the UI binder page

**Comment by bartburkhardt** [comment]
it works now
