### ISSUE TITLE
Need system to find conflicting actions

### ISSUE THREAD

**Issue by AndersMalmgren** [ValveSoftware/steamvr_unity_plugin#179]
This is a fork from #165 

Pasted from that issue:

I think somehow flagging a action set as more important than another and if any buttons inside the less important action set conflicts then disable the conflicted actions in the less important group would be the most elegant way togo. Maybe also a method for testing two actions if they conflict could be nice, though it might be redundant if we can use the actions sets like described above.

Edit: it would also be really elegant if the conflict code was very smart. For example using D Pad north would not conflict with a action using D pad east, but a action using touchpad touch or click would. Also using the vector2 output from the touchpad also conflicts with any d pad bound action. I understand this would be some work, but it would be really elegant and alot of games with touchpad movement and snap turn would gain from this, basicly any shooter like our own.

**Comment by AndersMalmgren** [comment]
I wrote this just to have something until this is supported natively. Downside is it will detect conflict between **D Pad North** and **D Pad South** for example all though there is no conflict.  Also I cache the output because `GetDeviceComponentName` uses some string handling etc. We would need a feature in SteamVR input that let us subscribe to when bindings change so we can update caches like these. Also it would be nifty if we can bring up the Bindings UI from within the game for better user experience from our settings menu in game.

```csharp
    public static class ActionExtensions 
    {
        //TODO: reset this when bindings update Issue #179
        private static readonly Dictionary<SteamVR_Action_In, Dictionary<SteamVR_ActionSet, bool>> conflicts = new Dictionary<SteamVR_Action_In, Dictionary<SteamVR_ActionSet, bool>>();


        public static bool Conflicts(this SteamVR_Action_In action, SteamVR_ActionSet set, SteamVR_Input_Sources source)
        {
            if(!conflicts.ContainsKey(action)) conflicts[action]  = new Dictionary<SteamVR_ActionSet, bool>();
            var c = conflicts[action];
            if (!c.ContainsKey(set))
            {
                c[set] = false;

                foreach (var suspect in set.nonVisualInActions)
                {
                    if (suspect.GetDeviceComponentName(source) == action.GetDeviceComponentName(source))
                    {
                        c[set] = true;
                        break;
                    }
                }
            }

            return c[set];
        }
    }
```

**Comment by AndersMalmgren** [comment]
I have given this some more thought, what about each binding returns a data structure (internally in OpenVR). For example for a **D Pad North** Click binding it would look something like
```csharp
{
   device: "Touchpad", //String or maybe a enum id
   part: "D Pad North", //String or maybe a enum id
   reactsTo: Click, //Enum Click, Touch
}
```

This structure could be used both for conflict determination in the SDK, but it could also be used to get a good text representation of the binding we devopers can use from Tutorial/UI etc.

Lets say you have a action that binds to Touchpad click

```csharp
{
   device: "Touchpad", 
   part: null, 
   reactsTo: Click
}
```

Since it has no part id it will conflict with above **D Pad North** binding, but if it would had reacted to Touch instead

```csharp
{
   device: "Touchpad", 
   part: null, 
   reactsTo: Touch
}
```

It would be a one way conflict, because a Touch binding can coexist with a Click binding, but a click binding can not coexist with a Touch binding.

**Comment by AndersMalmgren** [comment]
Above data is not enough for all use cases. For example if this is implemented #183 (Which would be a awsome feature and required if our game should not loose some functionally when moving to SteamVR 2)

D Pad is position sensitive (Its affected by were you hold the finger on the pad) with Dynamic center explained in #183 that binding will not be position sensitive.  A none position sensitive binding does not conflict with a position sensitive one.

**Comment by zite** [comment]
We've got some more advanced action set management coming in a beta version of the plugin I'll be releasing here soon. I'll update here when I've released it so you can check it out and see if it's sufficient.

**Comment by AndersMalmgren** [comment]
@keithbradner super cool, can't wait :) thanks for the effort :)

**Comment by zite** [comment]
Here's the link to a beta version of the plugin with the action set priority management: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.1b2

If you have two actions bound to the same input (button) the higher priority set will override the lower priority. If they are the same priority both will execute.

**Comment by AndersMalmgren** [comment]
@keithbradner  Cool will check it out tonight, can you also determine if there is a conflict for example by testing GetActive?

**Comment by AndersMalmgren** [comment]
Hi @keithbradner, downloaded it. But I get alot of errors (After I fixed the ones I got like Actions now are generic etc).

![image](https://user-images.githubusercontent.com/817577/48157276-7858e700-e2cf-11e8-8ba7-76814b4045f8.png)

**Comment by AndersMalmgren** [comment]
ah there are two folders, I didnt saw that the errors was in the autogenerated folder. Deleted that folder but now my game can compile because is misses teh actions. And since it does not compile the menu item to generate the actions again is not present. 

I see some potential problems migrating with this approach sadly :D

**Comment by AndersMalmgren** [comment]
Allright so I commented out the stuf in the autogenerated files that didnt compile so that the game compiled and the SteamVR input menu was present again. I then generated the action. Here is the output of that

![image](https://user-images.githubusercontent.com/817577/48165290-6a15c580-e2e5-11e8-8e01-1241f99eb582.png)


But  the the ```inActions``` member is null of my action sets in runtime

```SteamVR_Input._default.inActions.InteractUI)```

**Comment by zite** [comment]
I just uploaded a new beta, you might try again with that. Make sure you fully delete the generated SteamVR_Input folder before re-generating. I've removed inActions and just put the actions inside the action set.

**Comment by AndersMalmgren** [comment]
Will try it tonight. Last time I got problems because you had changed to generic versions of the actions. So my domain did not build and the SteamVR input menu was gone. Let me see if it works better this time.

**Comment by AndersMalmgren** [comment]
@keithbradner Alright. I have tested it, keep in mind, I need to test it ALOT more before I can give a final verdict. But first impression is promising.

I set the items associated set to a high prio

```
         public void ActiveItemActionSet()
        {
            CurrentlyInteracting.ActionSet.Activate(SteamInputSource, 2);
        }
```

This works fine, movement is now disabled for this hand because Movement set has prio 0. Perfect. When I drop the item I call

```
        public void DeactiveItemActionSet()
        {
            if(CurrentlyInteracting.ActionSet != null)
                CurrentlyInteracting.ActionSet.Deactivate(SteamInputSource);
        }
```

And now I can move again with the hand. Just like I want it. 

One problem though. With my old solution I didnt count is as a conflict if I was already moving with the hand when I pick up the item. Old code
```
        private bool CanMove(NVRHand hand)
        {
            return !hand.Conflicts(SteamVR_Input.Movement.DirectionTouched, SteamVR_Input.SnapTurning) && !hand.Conflicts(SteamVR_Input.Movement.DirectionTouched) || lastMovementHand == hand;
        }
```

The code checks for conflict **OR** if we are moving with the hand from last frame. I guess I could translate that into

```
SteamVR_Input.Movement.Activate(SteamInputSource, lastMovementHand == hand ? 2 : 0);
```

Or do you have any more elegant way?

I will keep testing

**edit:**

The conflict code does not take into account for example that I bind D Pad North to a low prio and D Pad South to a high prio. They dont conflict, but it still does not let me execute action bound D Pad North

**Comment by AndersMalmgren** [comment]
Ok @keithbradner So i continuned to explore my idea in last post.

```
        public bool UpdateCanMove(NVRHand lastMovementHand)
        {
            var isLastMovementHand = lastMovementHand == this;
            SteamVR_Input.Movement.Activate(SteamInputSource, isLastMovementHand ? 2 : 0);
            return isLastMovementHand || SteamVR_Input.Movement.DirectionTouched.GetActive(SteamInputSource);
        }
```

So what I do here is if we are the movementhand already I increase Movement set prio to 2 other reset it to 0. Problem is neither GetActive or Vector2 action will be enabled after this so the code that uses this method

```
        private NVRHand GetMovementHand()
        {
            NVRHand movementHand = null;
            float travelled = 0;

            foreach (var hand in Hands)
            {
                if(!hand.UpdateCanMove(lastMovementHand)) continue;

                var sqr = hand.GetTouchpad().sqrMagnitude;
                if (sqr > travelled)
                {
                    travelled = sqr;
                    movementHand = hand;
                }
            }

            return movementHand;
        }
```

Will get a zero sqrmagnitude and the hand will not be considered as movement hand

**Comment by AndersMalmgren** [comment]
@keithbradner I Just created a little video for you to show some context of what Im trying to achieve 

https://www.youtube.com/watch?v=MjgYKEJR5SA

**Comment by AndersMalmgren** [comment]
@keithbradner Hey man, had any time looking at my latest feedback about this?

**Comment by AndersMalmgren** [comment]
@keithbradner I have tested all cases now I think, if I havent missed anything. Everything seems to work. Besides the problem mentioned above with actions not being active straight after prio is increased. Also it would be really cool I think if the conflict determination code would be smarter so it for example can distinct between D Pad right and D Pad left for example and that these two does not conflict.

**Comment by zite** [comment]
Thanks for testing this so thoroughly, this issue has gotten a bit confusing. Do you mind creating a new one for the action not being active after priority increase?

**Comment by AndersMalmgren** [comment]
I will upgrade to latest version of the sdk and try again. After that file new issue if its not working

**Comment by zite** [comment]
This initial issue has been fixed in the latest release. The others are unfortunately still open. But I'll close this one.
