### ISSUE TITLE
Use GUI to bind controllers for HMDs that you don't have.

### ISSUE THREAD

**Issue by TesseractCat** [ValveSoftware/steamvr_unity_plugin#181]
Is it possible to bind the controllers of HMD's that you don't have via the binding GUI? For example: if I have a Vive, but want to bind actions for Oculus controllers via the GUI, is this possible?

I know it is possible to do through the JSON default files, however I would prefer to do it through the GUI (as I haven't seen any documentation for editing the JSON files directly).

**Comment by glock00** [comment]
I would be interested in that as well. Today I edited the JSON file for the Touch controllers and someone else with a Rift has to test it so this is more like a shot in the dark.
