### ISSUE TITLE
Some objects were not cleaned up when closing the scene.

### ISSUE THREAD

**Issue by AndersMalmgren** [ValveSoftware/steamvr_unity_plugin#182]
I get this message when we load a new scene in our game.

> Some objects were not cleaned up when closing the scene. (Did you spawn new GameObjects from OnDestroy?)

I have a basic camera rig, two controllers hooked up using the `SteamVR_Behaviour_Pose` behavior to left and right hands. And a head gameobject connected using the old `SteamVR_TrackedObject` behavior  set to HMD.

Other than that its same logic as before SteamVR 2.0 Have only ported our own abstraction to use the new action SDK

**Comment by AndersMalmgren** [comment]
Found the problem. SteamVR_Camera behaviour causes this. Removed it since it's not needed in SteamVR 2?

**Comment by zite** [comment]
I believe this has been fixed in recent betas (by not using the camera as you suggest): https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.2b1

**Comment by zite** [comment]
Fixed in latest release
