### ISSUE TITLE
Steam 2.0.1 + Vive Trackers + Unity

### ISSUE THREAD

**Issue by javinair** [ValveSoftware/steamvr_unity_plugin#184]
Hello,

I am trying to create a new project with the latest SteamVR SDK (2.0.1) for Unity (2018.2.0f2).

Importing the package from the AssetStore works perfectly with one or two Vive controllers. The problem appears if I try to use 2 Vive trackers instead of 2 Vive controllers. I can not make they appear in scene (they are paired and working properly in the mini SteamVR app).

I have been working previously without any problem with SteamVR 1.2.3 and Vive trackers, but there are some classes that are not currently in this version, such as `SteamVR_Controller_Manager.cs`. So I would like to know if I have to perform some changes or this version is not ready to use with Vive trackers yet.

Thanks in advance.

**Comment by zite** [comment]
Here's the link to a beta version of the plugin with this feature: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.1b2
You should now be able to set actions to check a more specific "devices". For example you can set a tracker to be on the "right foot" then set an action to check the "right foot" for a value. Let me know if this works for you.

**Comment by zite** [comment]
This is now in 2.2b1: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.2b1

**Comment by zite** [comment]
Added in latest release
