### ISSUE TITLE
Trigger as a button not working as it should

### ISSUE THREAD

**Issue by AndersMalmgren** [ValveSoftware/steamvr_unity_plugin#185]
I did a video showing the bug
https://youtu.be/EnWhfKbDVQA

Basicly Click and Pull modes does not work like they should.

In click mode the activation threshhold works it engages at 100% (which means after the clicker in the knuckles controller). But it resets just after the clicker is released even if I have chosen a reset threshold at 40%

In pull mode its reversed. Now The reset works at 40% put it enganges before the clicker even after I chose 100% threshhold.

I will try with Vive and see if same behaviour.
edit: same bug with Vive

**Comment by AndersMalmgren** [comment]
Have you guys looked into this bug? 
Thanks

**Comment by zite** [comment]
Can you show a video of this behaviour with the SteamVR Input Live View (Window menu in Unity) open so we can see the action engaging and disengaging? Or open the Input Debugger in the binding ui to show the same thing?

**Comment by AndersMalmgren** [comment]
@keithbradner will do, I'll record with both modes

**Comment by AndersMalmgren** [comment]
Alright @keithbradner Here is a new vid

https://youtu.be/VxLLNd4wBEM

**Comment by AndersMalmgren** [comment]
@keithbradner Interesting, I said above that same bug with Vive, thats not true anymore, maybe a fix in StreamVR beta? anyway. Here is the difference. Both Knuckles and Vive binding are set to Pull.

Here is knuckles
![image](https://user-images.githubusercontent.com/817577/48096259-091fbc00-e217-11e8-9c46-cfd13e1a6518.png)

As you can see both Trigger pressed is true and trigger is att 1.0 which means fully clicked. But thats not true. I have not pressed the clicker on above screenshot

Here is Vive instead which now behaves correctly,

![image](https://user-images.githubusercontent.com/817577/48096347-3bc9b480-e217-11e8-87fa-9f552e51f0a1.png)

Trigger pressed is false and trigger is at 0.8 becasue the last 20 procent or so is kept for the clicker

**Comment by AndersMalmgren** [comment]
@keithbradner Those are the default vendor bindings, I always make sure that I revert to  vendor bindings. That part is a bit weird, I mentioned it in video above :D

edit: hmm, just realized thats not what you meant. You want me to post the a screenshot of my default action set? or the json?

**Comment by zite** [comment]
Ideally the actual binding_knuckles.json and binding_vive_controller.json. Not sure where it's popular to paste code these days, maybe paste.org still

**Comment by kisak-valve** [comment]
Hello @keithbradner, in general, it's recommended to use https://gist.github.com with github issue reports.

**Comment by AndersMalmgren** [comment]
Interesting I have deleted the actions that was in the demo but they are still in the json

Here is knuckles
https://gist.github.com/AndersMalmgren/657c79b2a0fce50e2a336cc7df40ee3f

And Vive
https://gist.github.com/AndersMalmgren/05644ce1252361a0c7262d8c20b0ef03

**Comment by AndersMalmgren** [comment]
Hi,
Well, not really since Vive and Knuckles work different . In pull mode Vive works as I think it should, which means reset at 0.4 and engage at 1 which is at clicker click. On knuckles pull instead means reset at 0.4 but engage just before clicker click, plus axis value 1 just before clicker click. Doesn't make much sense that two hardware work different here regardless of what I think about pull mode.

If you choose to use Knuckles version of pull mode we need click mode changed to reset at 0.4 or a new mode that honors both reset and engage values fully. Most games probably want it to work like we want atleast games which tries to mimic how triggers work. In real life triggers do engage a bit before it reaches bottom, but you have physical feedback when this happens. In VR you only have the clicker as physical feedback before the bang.

This feature is paramount for the feel of our shooter. Thanks for all the help

**Comment by AndersMalmgren** [comment]
@keithbradner Need any more info for this issue? I think Vive and Knuckles (And Touch) must function the same. And if neither pull or click will work like i suggest fix a third mode that does since this is standard for any shooting game.

**Comment by AndersMalmgren** [comment]
@keithbradner This is also interesting but takes me further down the rabbit hole, the render model gets the correct axis data. But the vector action does not. Observe the value of the "trigger" action. Its 1.0 before the clicker. But the render model correctly renders the last little movement to the clicker engange.

https://www.youtube.com/watch?v=9FUNgniIy4U

**Comment by AndersMalmgren** [comment]
Its been almost two weeks since I heard anything about this. I would like to complete porting to SteamVR 2,0 so that I can merge this feature branch with master because we will have alot of conflicts if I let the branches retain. Any news on this @keithbradner?

**Comment by AndersMalmgren** [comment]
@keithbradner I tried 22b4 and latest SteamVR beta and the problems remain. The trigger raw data > bindings > actions needs to have a through review from you guys, it cant hit stable in this state.

**Comment by AndersMalmgren** [comment]
@keithbradner Thanks man, I just want a perfect user experience for my users (Basicly the same we got on 1.x or better :D) and a nice API for my fellow developers out there. :D

You know what. Vive seems to works like I suspect it to work so its a discrepancy between Vive and Knuckles DV. With vive the axis value goes from 0 - 1 and 1 is when clicker is engaged. The Button binding set to Click works like I suspect it to work, 

![image](https://user-images.githubusercontent.com/817577/51208341-b137bc80-190d-11e9-95b3-775424f9a274.png)

With above config it engages at clicker engage and resets at 40% 

With Knuckles DV the axis values goes from 0 - 1 just before clicker engages. And trigger as a button set to Click engages right before the clicker.

My fellow developer located off site is the one in charge with Rift/Touch so I can not test Rift at this time. but like you say it does not have a clicker. Though I think 100% should be at bottom and the developer/user can choose what to use.

edit: Reset is a firearms term. It means when the trigger resets and you can pull again for a semi automatic firearm to fire again when it reaches its engage point. Vive Button binding set to Click now does this correct, at 100% it engages at physical click and resets at 40% or whatever the user have set.

**Comment by zite** [comment]
So it sounds like the solution for your scenario right now is to create two bindings for the same action on knuckles. One Trigger Mode binding that binds the "click" and one Button Mode binding with the activation at 100 and the deactivation at 40. The combination of the two bindings for the one action will OR them together so it will be true whenever either of the actions is true.

**Comment by AndersMalmgren** [comment]
Why not make Knuckles work just like Vive. There is no reason for the discrepancy and the Vive way makes much more sense. 

Plus there is no work around for axis value being 1.0 before the clicker engage on Knuckles.

**Comment by AndersMalmgren** [comment]
@keithbradner I have a feeling we are not completly understranding eachother, because to me its so obvious how this should work :D I created a new video to show the discrepancies between vive and knuckles dv

I start with Knuckles and then the correctly working Vive so please see it to the end :D
https://www.youtube.com/watch?v=godilc_yd3Y

**Comment by zite** [comment]
Well it's not just me making this decision, I'm relaying other people's opinions about it as well. There's some disagreement about how the trigger pull should act. Some people think trigger pull should go 0-100 before the click because it's a separate component from the click (knuckles/vive pro). Some people think trigger pull should go 0-95 before the click and 100 after the click (vive original).

Here's an example scenario where people want a 0-100 pull before the click. Think about a racing game where trigger pull is the throttle and then click is a boost. You want throttle to go all the way up to 100 from the pull and click does a separate action entirely. 

I understand your frustration but we don't have a clean fix for you right now. After re-reading my response from before I think that's not quite right. You'll want to create two bindings for the same action:

Fire Action Binding1: Chord: Trigger mode click + Button mode 100% trigger pull activation / 40% deactivation.
Fire Action Binding 2: Trigger mode click

Maybe pseudo code will make more sense:
(binding1.click && (binding1.pull <= 100 && binding1.pull >= 40)) || (binding2.click)
