### ISSUE TITLE
Determin which controllers are connected

### ISSUE THREAD

**Issue by AndersMalmgren** [ValveSoftware/steamvr_unity_plugin#187]
In a perfect world we shouldn't need to know which controllers are used. But sadly we need to rig each item to the physical layout of controllers for optimum feel. Realoading guns etc can make controllers collide and we need to position magazines and firearms carefully for each hardware we support. How can I determin if Knuckles or Vive controllers are plugged in? Thansk

**Comment by AndersMalmgren** [comment]
From SetIndex yuo can call ```SteamVR.instance.GetStringProperty(ETrackedDeviceProperty.Prop_ControllerType_String, (uint)index))``` to get the type. Best way maybe?

**Comment by zite** [comment]
For the future, we're working on a better solution so you don't need to know the model of controller and can position items in relation to the controller some other way. Possibly in the binding layer.

For now, you can check the UpdateModel function of SteamVR_RenderModel for an example. There's a function called GetStringTrackedDeviceProperty. You can get the devoiceIndex it wants 
from SteamVR_Action_In.GetDeviceIndex, that's an instance method on each in action (everything except haptics). 

https://github.com/ValveSoftware/steamvr_unity_plugin/blob/a97cface7d1a2a09b1758840abac5a23d8b111d1/Assets/SteamVR/Scripts/SteamVR_RenderModel.cs#L147

**Comment by AndersMalmgren** [comment]
@keithbradner in our case each item is rigged different depending on were the magazine well is or how you operate the weapon so we minimize controller conflict by rigging the item different for different controllers. For example with Vive the big puck is in the way when reloading Pistols since the mag well is inside the grip were you hold the pistol with the other hand. So we probably always need to rig our items different per controller type. Though we also position the hand models when not interacting and this could be abstracted to SteamVR
