### ISSUE TITLE
Deadband for Trackpad and Joystick bindings

### ISSUE THREAD

**Issue by AndersMalmgren** [ValveSoftware/steamvr_unity_plugin#188]
We need the option to define deadband for Trackpad and Joystick bindings

Would fit perfect to the existing settings

![image](https://user-images.githubusercontent.com/817577/48096755-5bada800-e218-11e8-808a-6bb7719de60d.png)

Today we define Deadband in our own abstraction layer, it works. But more flexible if the player can define it from binding. Here is our deadband for Vive 

```
        private const float MaxTouchpadAxis = 0.8f;
        private const float DeadBand = 0.05f;

        public Vector2 MapTouchPadValue(float x, float y)
        {
            var mappedX = MathHelpers.Deadband(MathHelpers.MapRange(x, -MaxTouchpadAxis, MaxTouchpadAxis, -1, 1), DeadBand, -1, 1);
            var mappedY = MathHelpers.Deadband(MathHelpers.MapRange(y, -MaxTouchpadAxis, MaxTouchpadAxis, -1, 1), DeadBand, -1, 1);

            return new Vector2(mappedX, mappedY);
        }
```

It remaps the Touchpad so Axis goes from 0-1 from 0.05 to 0.8 instead. 0.8 is because Vive trackpad is unreliable in the outer sections and 0.05 so that you stop walking at center.

**Comment by zite** [comment]
This issue was moved to ValveSoftware/openvr#928
