### ISSUE TITLE
1.2.1 Crashes in Unity 5.6 when trying to add CameraRig prefab to scene (Linux/Ubuntu)

### ISSUE THREAD

**Issue by jessedubord** [ValveSoftware/steamvr_unity_plugin#19]
In Unity 5.6.0b8 on Ubuntu 16.10, Adding the CameraRig Prefab to my scene causes unity to Crash. Unity developer Tak said it was something related to the OpenVR file openvr_api.cs. 

See my original post in the Unity forums for Tak's work-around code: [https://forum.unity3d.com/threads/5-6-0b8-crashes-while-trying-to-add-steamvr-plugin-camerarig-prefab-video-included.457907/](url)

Expected behavior would be to add the CameraRig prefab into scene on Linux without it crashing the Unity 3D editor.

**Comment by johnv-valve** [comment]
You are actually hitting this issue https://github.com/ValveSoftware/openvr/issues/59 which will be fixed in the next openvr release.

**Comment by johnv-valve** [comment]
Another workaround is to run the Unity editor inside the Steam Runtime (which will allow SteamVR to initialize successfully)

**Comment by jessedubord** [comment]
Awesome, glad to know it'll be fixed in the next OpenVR release! As far as the work-around, how do I run Unity inside the Steam Runtime?

**Comment by kisak-valve** [comment]
Hello @jessedubord, there is a convenience script at `~/.steam/bin/steam-runtime/run.sh` which you can use followed by the application you want run in the steam runtime.

**Comment by jessedubord** [comment]
Nice, thanks @kisak-valve! I'll give it a try and report back.

**Comment by JamesHagerman** [comment]
@jessedubord Have you gotten any farther with this?
