### ISSUE TITLE
Haptics getting stuck on

### ISSUE THREAD

**Issue by pauberson** [ValveSoftware/steamvr_unity_plugin#190]
I'm having issues where my Vive controller haptics are getting stuck on. Is this a known issue? 

I've been trying to reproduce, but can't seem to find a pattern that triggers it, but it happens fairly often.

I'm using v2.0.1.

**Comment by pauberson** [comment]
I've worked around this by preventing any haptic calls until current haptics should be finished and also removing the haptics from the binding UI for buttons.

**Comment by AndersMalmgren** [comment]
+1 here. Also getting it

**Comment by zite** [comment]
Is this still an issue? I believe this has been fixed in recent versions.

**Comment by AndersMalmgren** [comment]
Havent gotten this for a while, but havent worked that much on our 2.0 branch for a while. Will get back to you if it happens again.

**Comment by zite** [comment]
Closing issue for now
