### ISSUE TITLE
action json files don't copy correctly in SteamVR_Input_PostProcessBuild

### ISSUE THREAD

**Issue by cdytoby** [ValveSoftware/steamvr_unity_plugin#191]
If the `actionsFilePath` in `SteamVR_Settings` is not in the root folder of project, for example `"Assets/ExternalLibrary/SteamVRExtra/actions.json"`, the file will still be copied to root folder of built binary. And this will cause error in game.

This happens in SteamVR plugin 2.0.1

My fix suggestion:

```
[PostProcessBuildAttribute(1)]
		public static void OnPostprocessBuild(BuildTarget target, string pathToBuiltProject)
		{
			SteamVR_Input.InitializeFile();

			FileInfo fileInfo = new FileInfo(pathToBuiltProject);
			string buildPath = fileInfo.Directory.FullName;

			string[] files = SteamVR_Input.actionFile.GetFilesToCopy();

			bool overwrite = EditorPrefs.GetBool(SteamVR_Input_Generator.steamVRInputOverwriteBuildKey);

			foreach (string file in files)
			{
				FileInfo bindingInfo = new FileInfo(file);
				//string newFilePath = Path.Combine(buildPath, bindingInfo.Name);
				//remove the "Assets", so -6
				string newFilePath = Path.Combine(buildPath, bindingInfo.FullName.Remove(0, Application.dataPath.Length - 6));

				bool exists = false;
				if (File.Exists(newFilePath))
					exists = true;

				if (exists)
				{
					if (overwrite)
					{
						FileInfo existingFile = new FileInfo(newFilePath);
						existingFile.IsReadOnly = false;
						existingFile.Delete();

						File.Copy(file, newFilePath);

						//UpdateAppKey(newFilePath, fileInfo.Name);
						RemoveAppKey(newFilePath, fileInfo.Name);

						Debug.Log("[SteamVR] Copied (overwrote) SteamVR Input file at build path: " + newFilePath);
					}
					else
					{
						Debug.Log("[SteamVR] Skipped writing existing file at build path: " + newFilePath);
					}
				}
				else
				{
					//File.Copy(file, newFilePath);
					FileInfo newFileInfo = new FileInfo(newFilePath);
					if (!newFileInfo.Directory.Exists)
						newFileInfo.Directory.Create();
					File.Copy(file, newFilePath);

					//UpdateAppKey(newFilePath, fileInfo.Name);
					RemoveAppKey(newFilePath, fileInfo.Name);

					Debug.Log("[SteamVR] Copied SteamVR Input file to build folder: " + newFilePath);
				}

			}
		}
```

**Comment by cdytoby** [comment]
I think reading from StreamingAssets is a better place. But in that case, the other part of the code need to be changed. Either way will do.

Currently, when the program read the json files, it will search the folder the same way, for both Editor and Player. So in current situation, when I set a correct folder in Editor and not copied to the correct folder in Player, the player will have error.

I hope the json files stay in a structured folder, not in root. Extra files in the root looks not good when I'm looking at my repository (my personal feeling).

**Comment by dubois** [comment]
We ran into a similar issue, except our `actionsFilePath` is `Support/OpenVRInput/actions.json` (ie, *not* under Assets, just a loose file in the standalone build).

I created #443 which successfully gets them copied into the correct place, but now `SteamVR_Input_ActionManifest_Manager.CleanBindings()` is emptying out `default_bindings` after a save, because all its file-exists checks are looking in the wrong place. Probably an easy thing for me to fix in that PR, but there seem to be enough hidden issues here that I think it would be helpful if the plugin didn't give developers the false impression that it supported having the json files anywhere but the root.

IOW, something like this in SteamVR_Settings.cs:
```
#if UNITY_EDITOR
  public void OnValidate() {
    if (actionsFilePath.Contains("/")) { Debug.LogError("Not supported yet; see #191 etc etc"); }
  }
#endif
```

**Comment by dubois** [comment]
Looking at uses of `SteamVR_Input_ActionFile_DefaultBinding.binding_url`, this isn't a trivial fix; there are lots of uses of `binding_url` that need to change, and the location of the owning `actions.json` file is not threaded through everywhere. So we'll just move our files back to the root... @keithbradner please do consider that warning so other developers don't shoot themselves in the foot like we did ;-)

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
