### ISSUE TITLE
Unity 2018.3b9: Errors when running "Interactions_Example"

### ISSUE THREAD

**Issue by ciwolsey** [ValveSoftware/steamvr_unity_plugin#193]
After hitting play I receive the following errors in the console:
```
SteamVR]</b> No pose action set for this component
UnityEngine.Debug:LogError(Object)
Valve.VR.SteamVR_Behaviour_Pose:Start() (at Assets/SteamVR/Input/SteamVR_Behaviour_Pose.cs:52)
```
and also:
```
Assertion failed on expression: 'task.rasterData.vertexBuffer == NULL'
```
The former appears twice and the latter is spammed constantly.
[Console Screenshot](https://i.imgur.com/FiOuKhN.png)
[Editor Log](https://gist.github.com/ciwolsey/09988ca18fc96c6bf82defc6c649773f)

**Comment by zite** [comment]
What headset are you using? Did you generate actions in the SteamVR Input window?

**Comment by ciwolsey** [comment]
If there's anything else I can do to help out with this problem let me know.

**Comment by zite** [comment]
I've updated the beta with a new version, can you give it a try?

https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.1b2

**Comment by ciwolsey** [comment]
Of course.

**Comment by ciwolsey** [comment]
Unity Beta 10 is out, would you prefer if I use that to test?

**Comment by zite** [comment]
Sure, I tested with 9, but hopefully they haven't changed anything significant in serialization since then.

**Comment by ciwolsey** [comment]
Still having issues with b10 but I noticed I'm on SteamVR beta so switched to stable branch and will try again. It seemed to get stuck when generating default actions. I could click "cancel" to get past that but still get a bunch of errors when hitting play.

**Comment by zite** [comment]
you're using the beta package that I just put up? It shouldn't show any generation progress bar. That part should be instant now.

**Comment by ciwolsey** [comment]
Tested with 2018.3b10. The issue with generating actions appears to be fixed but only black is being rendered to the HMD. Pressing the system button takes you to the SteamVR menu and the rendering and tracking works as expected, but when you switch back to the Unity app it continues to render as black. Perhaps that's a new issue with b10 and I'll log that separately after trying with b9 first.

**Comment by ciwolsey** [comment]
So I've tested on both b9 and b10 and with both SteamVR stable and SteamVR beta and here are the notes I took:

# 2018.3b9 with SteamVR stable
Action generation works fine, only get SteamVR overlay though, Unity app remains unresponsive with only SteamVR overlay rendered and console error:
```
Assertion failed on expression: 'task.rasterData.vertexBuffer == NULL'
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)"
```
# 2018.3b9 with SteamVR beta
 Works fine despite the following being spammed to the console:
```
Assertion failed on expression: 'task.rasterData.vertexBuffer == NULL'
```
# 2018.3b10 with SteamVR stable
Action generation works fine, black is rendered in Unity app, but SteamVR menu works as expected, chaperone is still rendered but everything else is black when in Unity app

# 2018.3b10 with SteamVR beta
Works fine despite the following being spammed to the console:
```
Assertion failed on expression: 'task.rasterData.vertexBuffer == NULL'
```

**Comment by ciwolsey** [comment]
I've tested on 2018.3.0b10 along with SteamVR beta branch (because it's not designed to work with the stable branch right?). The interaction example works fine and there are no issues with the json generation but I am still getting an error when running that doesn't seem to affect anything:
https://i.imgur.com/TbkilI1.png

**Comment by ciwolsey** [comment]
I discovered I can reproduce this error without SteamVR by doing the following:

1. Create a new project in Unity 2018.3b10
2. Install the OpenXR package using package manager
3. Enable VR support in player settings
4. Add a particle system to the scene and hit play
5. Errors appear in console

So I'm guessing this is a Unity problem and I should report it to them?

**Comment by zite** [comment]
Thanks for your help sorting this out! Hopefully Unity can get that fixed up asap.

**Comment by tatoforever** [comment]
Im also having this same error: Assertion failed on expression: 'task.rasterData.vertexBuffer == NULL'  and im not using Steam VR.

**Comment by kisak-valve** [comment]
Hello @tatoforever, you'll want to keep an eye on https://issuetracker.unity3d.com/issues/vr-particle-systems-cause-task-dot-rasterdata-dot-indexbuffer-equals-equals-null-error-and-lead-to-graphical-glitches. The investigation on this side has concluded.
