### ISSUE TITLE
SteamVR_TrackedController not exists, how to know if trigger clicked or other VR controller button? 

### ISSUE THREAD

**Issue by castana1962** [ValveSoftware/steamvr_unity_plugin#194]
Hi
I was using the SteamVR_TrackedController to set the Triggers and other VR Controller Buttons but the SteamVR_TrackedController script is not more in the SDK 2.0.1, for it, Could you said me how to remplace this features?
Thanks and sorry for my little English
Thanks for your time
Alejandro Castan

**Comment by AndersMalmgren** [comment]
Its been replaced by the new Input system

https://github.com/ValveSoftware/steamvr_unity_plugin/raw/master/Assets/SteamVR/SteamVR%20Unity%20Plugin%20-%20Input%20System.pdf

**Comment by zite** [comment]
Yeah, sorry, there is no longer direct access to buttons. You'll need to reference "Actions" that map to buttons. Check out this post: https://steamcommunity.com/sharedfiles/filedetails/?id=1416820276
