### ISSUE TITLE
2.1b3 Knuckles model issue

### ISSUE THREAD

**Issue by AndersMalmgren** [ValveSoftware/steamvr_unity_plugin#196]
I'm testing 2.1b3 to help @zite with the new action conflict API (#179). I noticed the right controller have a missing material problem.

![image](https://user-images.githubusercontent.com/817577/48372910-580a9d00-e6c0-11e8-85d5-3d5d2c035cbc.png)

This was not the case in the regular plugin from asset store.

This is not a huge issue for us, only haveing the models visible while debugging item positions etc

**Comment by zite** [comment]
I believe this is a knuckles driver issue, we're working on it, thanks.

**Comment by zite** [comment]
Going to assume from the thumbs up that this was fixed :)

**Comment by AndersMalmgren** [comment]
@keithbradner the thumbs up was more "glad you are working on it". But I just tested it and it works.
