### ISSUE TITLE
Binding UI Not loading (vive_controller EDIT)

### ISSUE THREAD

**Issue by Intersebbtor** [ValveSoftware/steamvr_unity_plugin#197]
So, I'm revisiting SteamVR in Unity after a long time with little to no former experience in developing with VR. 
I was Saving and Generating a new Action. Afterwards I followed "Open binding UI", it opened in my browser, but I could not EDIT the vive_controller binding. I even followed instructions from #154 like getting rid of capital letters. 
The procedure is as follows:
-Pressing EDIT
-Screen darkens down a bit
-nothing for a while
-console shows Loading
-back to default screen with controller and vive_controller

Plain Unity Project in 2018.2.10f1 
SteamVR Plugin 2.0.1
Opened in Chrome and IE

**Comment by elliotstaker** [comment]
Definitely get the SteamVR beta if you aren't running it. Fixed all my issues.

**Comment by Intersebbtor** [comment]
Yes I am running the beta. Since I'm kind of on a schedule I switched back to 1.2.3 and will be finishing my project that way now. Do you have any idea though as to why this happened? Would be great for future work

**Comment by big-r81** [comment]
Hi,

using "SteamVR Unity Plugin v2.1.5b2" i'm facing the same problem. Nothing happens if I am clicking on the edit button.

**Comment by zite** [comment]
Is anybody still seeing this issue on SteamVR 1.2.3?

**Comment by zite** [comment]
Sounds like this is fixed in the latest release

**Comment by Intersebbtor** [comment]
That's nice to hear.
I have my project finished by now, though :)
thanks for the help anyways!
