### ISSUE TITLE
More Information/Documentation on Bindings required

### ISSUE THREAD

**Issue by ani-rudh** [ValveSoftware/steamvr_unity_plugin#199]
Hi Team,

I am struggling to find what the bindings actually mean and what return type they return. For example, I am trying to use the RadialSwipe and Scroll on the Trackpad of the Vive Wands, but, I do not know what return type have to be defined in the Input UI in Unity. 

I had to try each return type before figuring out that Trackpad -> "Use as Scroll Wheel" action returns a Vector3. Also, What the Vector 3 really means is hard to understand (the scroll direction, speed and so on).

The "Use as radial Menu" action has no assignable return type and when called in the code, it has a direction() field that always remains on "In" and the GetAxis() is always returning 0. How is the usage of this action? 

It will be a great help and easier to adapt to the major change in the SDK, which is now more powerful but lacks comprehensive documentation.

Any pointers/examples on using the actions will be a great quick-start guide for the users.

Thank you in advance!
AN

**Comment by superjayman** [comment]
Yes, clarify the new binding procedures. SteamVr beta or not?

**Comment by superjayman** [comment]
If it's beta, MAKE IT CLEAR!!!.. So what does that mean? can you explain? Why not the official version? This new version is so buggy, taken me weeks to get simple things to get working. Very frustrating and time wasting. (should get things working before publishing)

**Comment by zite** [comment]
I think superjayman is confused. @ani-rudh, the direction field designates what type of action it is (in, or out). I do agree a bit more explanation on some of the types would be helpful but I'm not totally sure how the radial menu mode works. As the binding ui is more part of openvr you might have better luck asking in the openvr repo here: https://github.com/ValveSoftware/openvr/issues
