### ISSUE TITLE
Visual Studio Warnings and SteamVR Unity Plugin (Unused fields)

### ISSUE THREAD

**Issue by AmericanKulak** [ValveSoftware/steamvr_unity_plugin#2]
The field 'AfterTimer_Component.go' is never used   [...]SteamVR\InteractionSystem\Core\Scripts\Util.cs
The field 'AfterTimer_Component.timer' is never used    [...]SteamVR\InteractionSystem\Core\Scripts\Util.cs
The field 'ArrowHand.arrowRigidbody' is never used    [...]SteamVR\InteractionSystem\Longbow\Scripts\ArrowHand.cs
The field 'BalloonColliders.ColliderData.localPosition' is never used   [...]SteamVR\InteractionSystem\Longbow\Scripts\BalloonColliders.cs
The field 'BalloonColliders.ColliderData.localRotation' is never used   [...]SteamVR\InteractionSystem\Longbow\Scripts\BalloonColliders.cs
The field 'ItemPackageSpawner.prevItemPackage' is never used    [...]SteamVR\InteractionSystem\Core\Scripts\ItemPackageSpawner.cs
The field 'Longbow.prevArrowHandItemPackage' is never used    [...]SteamVR\InteractionSystem\Longbow\Scripts\Longbow.cs
The field 'SeeThru.hand' is never used    [...]SteamVR\InteractionSystem\Core\Scripts\SeeThru.cs
The field 'SteamVR_Settings.toggleState' is never used  .Editor [...]SteamVR\Editor\SteamVR_Settings.cs

**Comment by aleiby** [comment]
Fixed in next update.
