### ISSUE TITLE
Not Able to Set The Properties from OpenVR.Settings.Setbool();

### ISSUE THREAD

**Issue by lakshjain** [ValveSoftware/steamvr_unity_plugin#20]
In Unity 5.5.0 and SteamVR plugin v1.2.1 i tried to set the camera section property via OpenVR.Settings.SetBool (OpenVR.k_pch_Camera_Section, OpenVR.k_pch_Camera_EnableCameraForRoomView_Bool, true, ref error); 
and i checked OpenVR.Settings.GetBool() 
it changes the value but in the steamvr application ie compositor it doesnt change and also GetBool works correctly and in realtime with doing changes within steamvr application(compositor).

**Comment by aleiby** [comment]
That bool is a user setting which should not be set by applications.  You can access the camera stream and display it yourself.  There is an example here: 
https://github.com/ValveSoftware/steamvr_unity_plugin/blob/master/Assets/SteamVR/Extras/SteamVR_TestTrackedCamera.unity
https://github.com/ValveSoftware/steamvr_unity_plugin/blob/master/Assets/SteamVR/Extras/SteamVR_TestTrackedCamera.cs
Which uses the OpenVR interface wrapped up here:
https://github.com/ValveSoftware/steamvr_unity_plugin/blob/master/Assets/SteamVR/Scripts/SteamVR_TrackedCamera.cs
