### ISSUE TITLE
Can't open Binding UI - SteamVR beta

### ISSUE THREAD

**Issue by EntroPiGames** [ValveSoftware/steamvr_unity_plugin#200]
When running the latest version of the SteamVR beta, I can't open the binding UI. 
I've tried opening it in different web browsers and through the VR dashboard, but both display a blank page.

In the development console I get the following 2 errors:
Loading failed for the <script> with source “http://localhost:8998/dashboard/vrwebui_core.818f3c921b0d9a62ae60.js”. controllerbinding.html:14:1
Loading failed for the <script> with source “http://localhost:8998/dashboard/controllerbindingui.ad75be5a7ad9c6c96dd6.js”.

Everything works fine with the stable version of SteamVR, but I need the beta to develop for the Knuckles controllers. I've tried doing a clean reinstall of the SteamVR beta, but that didn't fix the issue.

In general, I like the concept behind the new action system, but so far converting my application to use the new input system has been rather frustrating, due to lack of documentation #199 and numerous bugs that I encountered and the workarounds required. Everything feels very clunky, and the UI of the Unity editor panels and the controller bindings are not very user-friendly.

With the current state of the plug-in, I feel less than confident about releasing a version of my project with the new input system.

**Comment by shashank-bss** [comment]
Hi,

Even I am experiencing the same issue! Would there be fix for this soon? If not is there a way for us to roll back to previous version of beta for development and testing purpose?

Thank you!

**Comment by zite** [comment]
This should be fixed today or early tomorrow. Sorry about the inconvenience.

**Comment by superjayman** [comment]
Is this fixed?

**Comment by EntroPiGames** [comment]
> 
> 
> Is this fixed?

Yes, this was fixed in the latest SteamVR beta (1.1.1), released yesterday.
