### ISSUE TITLE
Action.GetStateDown set to true after deactivating its actionset

### ISSUE THREAD

**Issue by wadams201** [ValveSoftware/steamvr_unity_plugin#204]
Hey @zite,

I'm trying to use actionsets to dictate whether or not you're actually able to grab an interactable. I have an actionset with grab pinch and grab grip actions. Prior to activating that actionset, if I hover an interactable, I  am unable to grab it. If I activate the grabbing actionset, I'm now able to grab it. If I deactivate the actionset, now if I hover the interactable, I grab it. It looks like the grabPinchAction.GetStateDown on line 1220 of the Hand script is firing when it shouldn't.

**Comment by zite** [comment]
Are you sure your action set is disabled in that scenario? In the new beta on the releases page there's a section in the live window that shows you what action sets are currently active. Can you verify this issue with that?

**Comment by wadams201** [comment]
Yep, you're right, it wasn't, I just had something tangled up in my action sets. Sorry about that!
