### ISSUE TITLE
GPU Performance Drops

### ISSUE THREAD

**Issue by Eskazar** [ValveSoftware/steamvr_unity_plugin#207]
Hello,

My setup:
GTX 980ti
I7-6700

And I found a weird problem while developing with Unity. Sometimes my GPU timings drop down to 50-70ms, without any perticular reason. It stays constant at that rate for the whole time the application is running. Neither restarting unity nor SteamVR fixes the low timing while in application. In the dashboard everything is fine. After ~30 game start and stops it resolves itself again, going down to 5ms and staying there constantly. Very strange.
Using Unity 2018.3.0b9 and the newest SteamVR release here on github.

Thanks in advance.

**Comment by zite** [comment]
Do you have maximize on play set? Having the scene window open seems to cause signicifant perf impacts.

**Comment by zite** [comment]
It's been a month with no reply, going to assume this was fixed.
