### ISSUE TITLE
"Could not find action set for: /actions/" when an action named "Pose" isn't in actionset

### ISSUE THREAD

**Issue by jcrapsey** [ValveSoftware/steamvr_unity_plugin#208]
plugin version 2.1.5b2

You should be able to reproduce this issue by opening a new project, installing the plugin and deleting all the default actions.

I just renamed my pose action back to "Pose" to stop the error from showing.

The error seems to be here, where it's setting up a default action pose "Pose".
in SteamVR_Behaviour_Pose.cs line 17
`public SteamVR_Action_Pose poseAction = SteamVR_Input.GetAction<SteamVR_Action_Pose>("Pose");`

**Comment by zite** [comment]
I believe this should be fixed in the latest 2.2b1 beta on the releases page: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.2b1

**Comment by zite** [comment]
Fixed in latest release
