### ISSUE TITLE
VR Course by SteamVR SDK for Unity 2.1

### ISSUE THREAD

**Issue by castana1962** [ValveSoftware/steamvr_unity_plugin#211]
Hi All
I am sorry for this because I know that it is not the place to ask this question but I could not find anything about it, for it and since the biggest changes in the SteamVR SDK for Unity V2.1 . Do you know any VR Course by SteamVR SDK 2.1 now?
Thanks for your time and understanding
Alejandro

**Comment by zite** [comment]
We've started adding some documentation here: https://valvesoftware.github.io/steamvr_unity_plugin/tutorials/SteamVR-Input.html

Unfortunately a full course is a bit outside the scope of this github. You may have better luck on the steamvr developer forums here: https://steamcommunity.com/app/250820/discussions/7/
