### ISSUE TITLE
VelocityEstimator FinishEstimatingVelocity is not always called on release

### ISSUE THREAD

**Issue by P3TE** [ValveSoftware/steamvr_unity_plugin#212]
Within the class: Throwable.cs
Within the function: OnAttachedToHand
The following is called: velocityEstimator.BeginEstimatingVelocity();

Within the same class,
Within the function: OnDetachedFromHand
The following function is called: GetReleaseVelocities
Within: GetReleaseVelocities
velocityEstimator.FinishEstimatingVelocity();
is called, but ONLY if:
releaseVelocityStyle == ReleaseStyle.ShortEstimation:
is true.

Therefore, for all other types of releaseVelocityStyle, velocityEstimator.FinishEstimatingVelocity(); is not called and the Co-Routine is left running forever.

**Comment by zite** [comment]
I believe this has been fixed in the current release
