### ISSUE TITLE
Time.deltaTime called in FixedUpdate

### ISSUE THREAD

**Issue by P3TE** [ValveSoftware/steamvr_unity_plugin#213]
Using version: steamvr_2_1_5b2
In the class: Hand.cs
In the method: FixedUpdate
UpdateAttachedVelocity(attachedInfo) is called,
which calls:
bool success = GetUpdatedAttachedVelocities(attachedObjectInfo, out velocityTarget, out angularTarget);
Which has the following line:
velocityTarget = (positionDelta * velocityMagic * Time.deltaTime);
As it's called from FixedUpdate, shouldn't it be using Time.fixedDeltaTime
I will note that this isn't the only place GetUpdatedAttachedVelocities is called from, but other cases are one-off occasions such as releasing a Throwable

Additionally, further down in that function, there exists the line:
realNumbers &= true;
Where realNumbers is defined above as a bool
This line does absolutely nothing, and I wonder whether it's a mistake.

**Comment by ckorris** [comment]
If Time.deltaTime is called from inside FixedUpdate, it'll automatically return the fixed frame time instead: https://docs.unity3d.com/ScriptReference/Time-deltaTime.html

That &= line does look like a mistake, though.

**Comment by zite** [comment]
Yeah looks like that realnumbers stuff was a quick fix. I'll try and get that fixed.
