### ISSUE TITLE
Grabbing constrained objects 

### ISSUE THREAD

**Issue by wadams201** [ValveSoftware/steamvr_unity_plugin#215]
I'm using the velocity method to grab a table, which I have given rididbody constraints to: positionally frozen in the y axis, and rotationally frozen in the x and z axis. If I grab the table near its pivot point (in this case, the top and center of the table) the object moves and rotates as I'd expect. However, if I grab the table near an edge or bottom, farther away from its pivot, it's rotational motion is exaggerated. 

I've created a solution for this by instantiating a parent gameobject at the hand position prior to attaching to a hand in handhoverupdate, childing the object I actually want to grab to the parent, and passing the parent as the gameobject in hand.AttachObject (this method requires the attachObject method in the hand script to getComponentsInChildren<interactable> instead of getComponent<interactable>). 

This might not be very elegant, but seems to work pretty well, and may be worth improving upon.

**Comment by zite** [comment]
Thanks for the suggestion. There's indeed quite a few scenarios where the velocity method of pickup isn't sufficient as is. This interaction system is meant more as an example of the input system and something you can build on top of. If you'd like to fork the project and add your solution that'd be great :)
