### ISSUE TITLE
Cannot assign Actions in Bindings UI

### ISSUE THREAD

**Issue by IbakonFerba** [ValveSoftware/steamvr_unity_plugin#218]
In SteamVR 2.1.5b2 I cannot assing actions in the bindings UI. In the Javascript Console I am getting this error:

```
SetActionForPose: Invalid action set specified
```

When I try to assign an action, I can click on the Button that says "Unused" and I get the list with all the actions I created, but when I click on one I get the error and the action is not set.

**Comment by zite** [comment]
Is this with the default actions or have you modified them? Added new action sets maybe? Can you include your actions.json file from the root of your project directory?

**Comment by onelivesleft** [comment]
> On a side note, I think it would be great if the Bindings UI would work even if I am not logged into steam and my Vive is not connected. Sometimes I just need to access it without having to test immediately.

Would be even better if you could assign bindings to any VR device without it being plugged in; shouldn't have to buy every VR on the market just to be able to support them (without resorting to hacking in json).

**Comment by zite** [comment]
This issue has been fixed, @onelivesleft you can create a separate issue for that feature request in the openvr repo here: https://github.com/ValveSoftware/openvr/issues
