### ISSUE TITLE
Teleporting to New Scene causes Teleport to break

### ISSUE THREAD

**Issue by keiranlovett** [ValveSoftware/steamvr_unity_plugin#22]
When teleporting to a new scene through 'TeleportPoint.cs TeleportToScene()' using basic unity scene switch code, the below error is thrown when trying to teleport once more.

`MissingReferenceException: The object of type 'TeleportPoint' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
Valve.VR.InteractionSystem.TeleportPoint.ShouldActivate (Vector3 playerPosition) (at Assets/SteamVR/InteractionSystem/Teleport/Scripts/TeleportPoint.cs:107)
Valve.VR.InteractionSystem.Teleport.ShowPointer (Valve.VR.InteractionSystem.Hand newPointerHand, Valve.VR.InteractionSystem.Hand oldPointerHand) (at Assets/SteamVR/InteractionSystem/Teleport/Scripts/Teleport.cs:689)
Valve.VR.InteractionSystem.Teleport.Update () (at Assets/SteamVR/InteractionSystem/Teleport/Scripts/Teleport.cs:266)
`

In this case, the scene is loaded and switched to, however the player, the teleport points, and everything VR related is in a gameobject which won't destroy with scene switch.

**Comment by xXH4tchXx** [comment]
Look in the interaction example scene for a "Teleport" game object. If you add that to any scenes you are looking to teleport in this error should be resolved. Alternatively you can mark as "[DontDestroyOnLoad](https://docs.unity3d.com/ScriptReference/Object.DontDestroyOnLoad.html)".
