### ISSUE TITLE
Issue with Simulator

### ISSUE THREAD

**Issue by TechnoOscuro** [ValveSoftware/steamvr_unity_plugin#220]
Im using the simulator to test my game because i cant develop with a vr device conected.
The problem is that my "hand" gets stucks in the floor and cant interact with anything.
any idea?

**Comment by TechnoOscuro** [comment]
I manage to move the indicator, manually activating the hand script, but now cant interact with anything

**Comment by zite** [comment]
I believe we fixed this in the beta of the unity plugin. Can you try that here? https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.1.5

**Comment by TechnoOscuro** [comment]
Thanks, will try it tomorrow.

**Comment by TechnoOscuro** [comment]
I tested that and can grab objects but i cant "exit" from that interaction

**Comment by zite** [comment]
Which object are you seeing this behavior on? I'm able to throw the cubes near the target.
