### ISSUE TITLE
Why New Input System only available for hand held device?

### ISSUE THREAD

**Issue by lawwong** [ValveSoftware/steamvr_unity_plugin#227]
I get that most "games" use only two hands to play.
But why banning all other possibilities?
Why can't we get inputs from more then 2 devices at the same time?

**Comment by lawwong** [comment]
The biggest problem is that event using SteamVR plugin v1.2.3, now inputs only available for up to 2 tracking device (user/left and user/right)

**Comment by kisak-valve** [comment]
Closing in favor of the existing issue report at #205.
