### ISSUE TITLE
Custom Actions in Teleport and Hand scripts are overridden

### ISSUE THREAD

**Issue by hendrik-schulte** [ValveSoftware/steamvr_unity_plugin#228]
Hey folks,

I just encountered a bug with custom Actions in the Teleport and Hand scripts. You can define a custom Action in the inspector but it is automatically overridden by the default action when entering play mode. This is strange as the inspector still shows the custom action but when debugging *Teleport.WasTeleportButtonPressed* revealed that the default action /actions/default/in/Teleport is used. It can be resolved by changing line 16:
```
public SteamVR_Action_Boolean teleportAction = SteamVR_Input.GetAction<SteamVR_Action_Boolean>("Teleport");
```
To:
```
public SteamVR_Action_Boolean teleportAction;
```

The same applies to the actions in the Hand script.

Were using 2.1.5 and Unity 2018.2.7f1

**Comment by zite** [comment]
Thanks for the report, and for testing the beta! We'll get this fixed before the next release.

**Comment by zite** [comment]
This should be fixed in the 2.2b1 beta on the releases page: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.2b1

**Comment by timetosmile** [comment]
> This should be fixed in the 2.2b3 beta on the releases page: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.2b3

Hello,

I'm using v2.2b3 and create for my handtools an individual actionset with the same names like in default (GrapGrip, GrapPinch and Teleport). When I test my application in playmode out of the editor everything works well. 

But when I create a build, the below error always appears and the actions can not be executed anymore.

![argumentexception](https://user-images.githubusercontent.com/12845370/50684796-1ab6f180-1017-11e9-8656-eeb6cbe2585c.PNG)

Changing the actions names doesn't help. Only to use the default actions. I assigned them to my players hands in the inspector. 

The error occurs in ControllerButtonHint.cs on line 292 when the actionHintInfos dictonary get filled. 

I've done the same like @hendrik-schulte and this solves my problems.

**Comment by zite** [comment]
Sorry about that, looks like there was an issue with deserialization in b3. I believe I've fixed it in b4 here: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.2b4

**Comment by timetosmile** [comment]
> Sorry about that, looks like there was an issue with deserialization in b3. I believe I've fixed it in b4 here: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.2b4

Yes, with the new beta the problem doesn't apear anymore. 
Thanks
