### ISSUE TITLE
Mixed Reality controller models override all other models

### ISSUE THREAD

**Issue by TheBricktop** [ValveSoftware/steamvr_unity_plugin#229]
Just like in the title, while in Interaction Example Scene, when one tries to change the controller model nothing is happening, cant display new hand glove model, no obvious way to change the model to any other. 

Please clarify, how to change the model controller, how to force one particular model prefab.

**Comment by zite** [comment]
Unfortunately the interaction system is designed around using either hands, real controllers, or both. You can override the hand to be a different hand (that supports the skeleton system) but overriding the controller model is sort of a different concept. I'd recommend you use a different interaction system (vrtk) or create your own based on the camera rig prefab.
