### ISSUE TITLE
Cannot build working example scene [Linux/Ubuntu]

### ISSUE THREAD

**Issue by JamesHagerman** [ValveSoftware/steamvr_unity_plugin#23]
After making the change mentioned in issue #19, I was able to finally load the example scene.

However, even after setting up the Vulken Graphics API in the Player Settings, I still cannot seem to get the compiled version to load up in SteamVR.

SteamVR is running on this machine, I can put the headset on and see the default grid world.

I'm using the NVidia Beta Vulken drivers version 375.27.14 because the version from the PPA mentioned here:

https://github.com/ValveSoftware/SteamVR-for-Linux/blob/master/README.md

Didn't seem to support direct mode for some weird reason.

Is there a trick to getting this thing to actually start up in the headset?
Is there a bug with the plugin that I've missed?

Thanks

**Comment by Plagman** [comment]
The current Unity builds don't yet support SteamVR for Linux targets, you'll have to wait for 2017.2 based builds for the time being. If you're seeing an image in headset, direct mode is most likely working despite the UI not reflecting that it does.
