### ISSUE TITLE
Spawn multiple glove models after opened SteamVR menu and also randomly on startup (HandCancer)

### ISSUE THREAD

**Issue by timetosmile** [ValveSoftware/steamvr_unity_plugin#236]
It has now happened to us often that a hand model is constantly being spawned. This Issue can be reproduced by going into the SteamVR menu and then the hands have a slight mica and the scene has a strong framedrop.
The following error will be displayed:

`
NullReferenceException: Object reference not set to an instance of an object
Valve.VR.SteamVR_Input_EditorWindow.HasBeenModified () (at Assets/3rd Party Assets/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:527)
Valve.VR.SteamVR_Input_EditorWindow.OnDestroy () (at Assets/3rd Party Assets/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:533)
UnityEditor.GenericMenu:CatchMenu(Object, String[], Int32)
`

I once added a few pictures, how it all looks in the end. In part, this error also happens at startup. I hope you can do something there.

The error apears and grows like a cancer, because of this we call it HandCancer.

![handcancer3](https://user-images.githubusercontent.com/12845370/50284157-6cc51800-0458-11e9-8227-39ec1d5e2c4f.png)
![handcancer](https://user-images.githubusercontent.com/12845370/50284158-6cc51800-0458-11e9-849e-1b4b32accd71.png)
![handcancer2](https://user-images.githubusercontent.com/12845370/50284159-6cc51800-0458-11e9-8d7d-7d190ec0964f.png)

**Comment by TLobes** [comment]
Happens in our project, too, exact same situation yet finding that this occurs when either the game starts without finding a hand and later discovering it, and/or loses tracking of the hand during play and finds it again. The frame rate skyrockets linearly until it maxes out around 65-70 ms per frame.

The workaround right now is to disable hands from being drawn completely in the Left and Right Render model prefabs assigned to each hand and attaching your own.

**Comment by zite** [comment]
Thanks for the report. I've fixed this in the next release. I'll update here when that goes live.

**Comment by zite** [comment]
I believe this has been fixed in the 2.2b1 beta that I've just put up on the releases page. Can you verify that? https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.2b1

**Comment by zite** [comment]
Fixed in latest release
