### ISSUE TITLE
About SteamVR native Integration with Cybershoes..

### ISSUE THREAD

**Issue by castana1962** [ValveSoftware/steamvr_unity_plugin#241]
Hi
Sorry for my ignorance but since I backed a new VR device named Cybershoes and it is SteamVR native Integration now.
more info here
https://www.kickstarter.com/projects/cybershoes/cybershoes-step-into-vr
For it and I will get it soon. Do you know where I could get any info to build my own VR projects with SteamVR plugin for Unity and Cybershoes? Would it be possible?
Thanks for your time
Alejandro
Ps. Merry Christmas and Happy new Year for all !!!

**Comment by zite** [comment]
Sounds like something you should ask the developers of the shoes. They can probably tell you how the integration works.
