### ISSUE TITLE
When a user testes our beta with SteamVR 2 and going back to stable with SteamVR 1  controls break

### ISSUE THREAD

**Issue by AndersMalmgren** [ValveSoftware/steamvr_unity_plugin#242]
We have gotten reports from our customers that when they are going from beta to stable the controls break. I just tested it and can reproduce. 

I just need to first play the game on beta then switch to stable (From the Steam UI) and the game breaks. I cant click the control bindings button from within SteamVR.

**Comment by kisak-valve** [comment]
Hello @AndersMalmgren, this issue is already being tracked at #240. Closing as a duplicate.
