### ISSUE TITLE
SteamVR 2.1.5b2 is not compatible with PhysX upgrade in 2018.3.0f2

### ISSUE THREAD

**Issue by LucidDreamsVR** [ValveSoftware/steamvr_unity_plugin#244]
Two items used by the Interactions Example are not compatible with the upgrade to PhysX in Unity 2018.3 and result in the following Debug.LogError():

> RigidBody::setRigidBodyFlag: kinematic bodies with CCD enabled are not supported! CCD will be ignored.

I was able to fix this for the TargetHitEffect prefab by going to the Arrowhead collider's Rigidbody and changing the Collision Detection setting to Continuous Speculative (the suggested mode for fast moving Kinetic rigidbodies per Unity's docs).

This also has to be done for the Arrow prefab for both the top level Arrow gameobject and the "ArrowHead collider" grand-child gameobject.

![steamvr 2 1 5b2 physx bug unity 2018 3 0f2](https://user-images.githubusercontent.com/28881505/50489204-55e07180-09d4-11e9-850d-1198cd45c828.png)

**Comment by zite** [comment]
Thanks, I've believe I've fixed this in the next beta.

**Comment by zite** [comment]
2.2b1 beta has been released and I believe it fixes this issue.

**Comment by timetosmile** [comment]
> 2.2b1 beta has been released and I believe it fixes this issue.

Not for me. I'm using now v2.2b3 and still got this error.

**Comment by zite** [comment]
I'm not getting this error when shooting arrows. Is that hwne you're getting it?

**Comment by LucidDreamsVR** [comment]
Works for me with the latest on master (2.2).

**Comment by zite** [comment]
Fixed on the current release.

**Comment by Yuyang01** [comment]
I do not understand why as a commercial software, unity3d has so many bugs and not compatible with lower version.
