### ISSUE TITLE
SteamVR_PlayArea calculates vertices at different corners depending on Calibrated or specific size

### ISSUE THREAD

**Issue by thestonefox** [ValveSoftware/steamvr_unity_plugin#25]
If the `SteamVR_PlayAre` is set to `Size = Calibrated` then the vertices in the public `vertices` variable are reported as follows:

```
vertices[0] = Bottom Right Inner point
vertices[1] = Bottom Left Inner point
vertices[2] = Top Left Inner point
vertices[3] = Top Right Inner point

vertices[4] = Bottom Right Outer point
vertices[5] = Bottom Left Outer point
vertices[6] = Top Left Outer point
vertices[7] = Top Right Outer point
```

If the `Size` is set to any other specific size (e.g. `200x150`) then the `vertices` Vector3 array reports the corners in different locations:

```
vertices[0] = Top Right Inner point
vertices[1] = Bottom Right Inner point
vertices[2] = Bottom Left Inner point
vertices[3] = Top Left Inner point

vertices[4] = Top Right Outer point
vertices[5] = Bottom Right Outer point
vertices[6] = Bottom Left Outer point
vertices[7] = Top Left Outer point
```

This causes issues if these vertices are being used to draw a Play area representation as the figures are not consistent.

The piece of code that dictates the manual Quad for the play area is located here:
https://github.com/ValveSoftware/steamvr_unity_plugin/blob/master/Assets/SteamVR/Scripts/SteamVR_PlayArea.cs#L66-L80

However, to have it consistent with how the Calibrated play area is set up it should be:

```
pRect.vCorners0.v0 =  x;
pRect.vCorners0.v1 =  0;
pRect.vCorners0.v2 =  -z;

pRect.vCorners1.v0 =  -x;
pRect.vCorners1.v1 =  0;
pRect.vCorners1.v2 = -z;

pRect.vCorners2.v0 = -x;
pRect.vCorners2.v1 =  0;
pRect.vCorners2.v2 = z;

pRect.vCorners3.v0 = x;
pRect.vCorners3.v1 =  0;
pRect.vCorners3.v2 =  z;
```

Example of the discrepancy in an image: 
![image](https://cloud.githubusercontent.com/assets/1029673/24351390/6965259c-12dd-11e7-9384-8cb03ac422cb.png)

I'll also raise a PR to go with this ticket.

**Comment by thestonefox** [comment]
PR with fix https://github.com/ValveSoftware/steamvr_unity_plugin/pull/26

**Comment by aleiby** [comment]
Thanks, I'll integrate this for the next update.
