### ISSUE TITLE
Hand Models Disappear when Disable All Other Action Sets Checked

### ISSUE THREAD

**Issue by jaran** [ValveSoftware/steamvr_unity_plugin#251]
Not sure if this is a bug or I am missing something, but when I use the component SteamVR_ActivateActionSetOnLoad and check Disable All other Action sets then my hand models disappear.  If I don't check that then the hand models stay visible.

Unity 2018.3
SteamVR Plugin from asset store

**Comment by zite** [comment]
Are you talking about the SteamVR hands? If so then this may be intended
behavior. The hands work by skeleton actions that are (by default) in the
default action set. If you disable that set then the hands can’t get data
anymore and disappear.

**Comment by jaran** [comment]
Yes the steamVR hands.  OK Ill have to move my actions to default then to keep the hands.  Thanks for help.

**Comment by zite** [comment]
Alternatively you can not disable other actions on start
