### ISSUE TITLE
SteamVR_Controller.Input No longer exists?

### ISSUE THREAD

**Issue by zezba9000** [ValveSoftware/steamvr_unity_plugin#253]
How do I get input from a controller WITHOUT using the action system. I already have an "action" system.

What is the API used to get raw input values. Using Unity3D 2018.3.0
I don't see any example code for this in the sample scene.

This SDK is doing to much and ends up making it harder to use in existing systems.

**Comment by zite** [comment]
Getting raw values is no longer supported by the SteamVR Unity Plugin going forward. If you don't want to use the new Input and Action system you can either stick with the old version of the plugin (1.2.3 here: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/1.2.3) or manually access the functions in openvr_api.cs

We're strongly recommending developers switch to our standard action system for a variety of reasons. https://steamcommunity.com/games/250820/announcements/detail/1696059027982397407 https://steamcommunity.com/games/250820/announcements/detail/3809361199426010680

**Comment by zezba9000** [comment]
1.2.3 plugin doesn't work with Unity 2018.3.

The SteamVR system should just remap input on the SteamVR end so the game need not know the difference if button A is swapped with button B for example. This new system is just verbose for very basic stuff and for pods this addition will never be used.

**Comment by zezba9000** [comment]
Also people are just going to bypass this by using Unity's input systems. Now if the OpenVR input driver handled what input remaps were it would work in both situations instead of putting this work on the game dev.

**Comment by zite** [comment]
I closed this issue because it's not a problem with a plugin, it's more feedback on SteamVR Input. We're working with Unity to get their future input system working cleanly with ours. If you have more SteamVR Input feedback we'd welcome it on the forum here: https://steamcommunity.com/app/250820/discussions/7/

**Comment by zezba9000** [comment]
Are there input docs for this? All I can find are the C++ ones and the example project doesn't actually show how to get button presses etc.

**Comment by zezba9000** [comment]
I guess the correct answer here is to import the "ViveInputUtility-Unity": https://github.com/ViveSoftware/ViveInputUtility-Unity/releases

Then use stuff like: ViveInput.GetPressDown(HandRole.LeftHand, ControllerButton.Grip);

**Comment by bddckr** [comment]
>1.2.3 plugin doesn't work with Unity 2018.3.

This isn't true - it's working fine for VRTK users. Make sure to allow Unity to run the API Updater and ensure your project actually uses the OpenVR package through the Unity Package Manager.

**Comment by guiglass** [comment]
I feel that restricting access to low level hardware state is overly assertive on Steam's behalf, first off, Vive trackers are VERY broken at the moment, and bindings are not a good solution.

I must find a way around their screwy SteamVR bindings limitation. I have exhausted using the bindings system after hours of trial and complete error, it just keeps breaking and is no good for trackers.

I am sure there are 1000s of other examples why allowing direct access a device's: "/input/trigger/click" is a truly wonderful idea.

**Comment by guiglass** [comment]
I feel that restricting access to low level hardware state is overly assertive on Steam's behalf, first off, Vive trackers are VERY broken at the moment, and bindings are not a good solution.

I must find a way around their screwy SteamVR bindings limitation. I have exhausted using the bindings system after hours of trial and complete error, it just keeps breaking and is no good for trackers.

I am sure there are 1000s of other examples why allowing direct access is a good idea. I need access to each trackers pogo pins, such as path: "/input/trigger/click".

How can I access pogo pin state?

**Comment by zezba9000** [comment]
Here is the solution for others running into this: https://github.com/VRStudios/Unity3D-XRInput
