### ISSUE TITLE
v2.2b3 InvalidHandle Errors when enabling SteamVR at runtime

### ISSUE THREAD

**Issue by ZnelArts** [ValveSoftware/steamvr_unity_plugin#256]
WIndows 10
Unity 2017.3.1f1
SteamVR v2.2b3

If you start a without SteamVR and then load SteamVR and a Camera Rig, SteamVR will throw the InvalidHandle errors. You can repro this with the SteamVR_ForceSteamVRMode Scene

```
]</b> GetPoseActionData error (/actions/default/in/Pose): InvalidHandle Handle: 1152997645787070915. Input source: LeftHand
0x00000001412F21A6 (Unity) StackWalker::GetCurrentCallstack
0x00000001412F2D1F (Unity) StackWalker::ShowCallstack
0x00000001411B0910 (Unity) GetStacktrace
0x00000001406DAF53 (Unity) DebugStringToFile
0x00000001406DB731 (Unity) DebugStringToFile
0x000000014142BB62 (Unity) DebugLogHandler_CUSTOM_Internal_Log
```

**Repro Steps:**

1. Open the **SteamVR_ForceSteamVRMode** Scene
2. Play The Scene
3. Wait 1 second for SteamVR to be loaded

**Expected Behavior:**
VR shoudl start normally without errors

**Observed Behavior**
SteamVR throws a bunch of errors to the console

**Comment by ZnelArts** [comment]
A workaround is to add a small delay when starting to execute LateUpdate on SteamVR_Behavious.cs

**Comment by ZnelArts** [comment]
It even seems that you are aware of this issue:
`
            EVRInputError err = OpenVR.Input.GetPoseActionData(handle, universeOrigin, predictedSecondsFromNow, ref poseActionData, poseActionData_size, inputSourceHandle);
            if (err != EVRInputError.None)
            {
                if (err == EVRInputError.InvalidHandle && Time.realtimeSinceStartup < 5)
                {
                    //ignore. This is probably just steamvr input starting up.
                    //todo: get this fixed
                }
                else
                {
                    Debug.LogError("<b>[SteamVR]</b> GetPoseActionData error (" + fullPath + "): " + err.ToString() + " Handle: " + handle.ToString() + ". Input source: " + inputSource.ToString());
                }
            }
`

Is it really just SteamVR input starting up???

**Comment by zite** [comment]
Yeah. For now you can just remove the right half of that if statement and
it should be fine

**Comment by zite** [comment]
I believe I've got a better fix for this in b4. I'm suppressing the automatic update calls that are made the same frame that steamvr input starts. https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.2b4

**Comment by ZnelArts** [comment]
Im still getting this errors on v2.2RC1

[SteamVR]</b> GetSkeletalActionData error (/actions/default/in/SkeletonLeftHand): InvalidHandle handle: 1152996237037797839
0x00000001412F21A6 (Unity) StackWalker::GetCurrentCallstack
0x00000001412F2D1F (Unity) StackWalker::ShowCallstack

**Comment by ZnelArts** [comment]
Confirmed that this issue is still seen in v2.2RC1

The code that logs this error on frame zero and some other code that runs on a LateUpdate in frame zero is still present in v2.2RC1.

**Comment by zite** [comment]
I'm doing it based on the frame that steamvr input was initialized now, which fixed the issue for me. Let me know if it fixes your scenario. https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.2RC2

**Comment by zite** [comment]
Is this fixed in the current release?

**Comment by ZnelArts** [comment]
Yes, this has been fixed in the current published v2.2.0

**Comment by kisak-valve** [comment]
Thanks for retesting, closing per the last comment.

**Comment by JashanChittesh** [comment]
I'm seeing the same, or a similar issue in our project with SteamVR Unity Plugin 2.3.2 and Unity 2019.1 (and SteamVR 1.6.10):

The first time of a session that I start "Play" in Unity, I get the log spammed with:

[SteamVR] GetDigitalActionData error (/actions/default/in/InteractUI): InvalidHandle handle: 1155126746975044000
and similar messages

This log spam does not stop, and SteamVR Input is broken in this state.

Stopping play mode and restarting "fixes" the issue.

**Comment by OuterObsessionSoftware** [comment]
For anyone having this issue ensure that you have the [CameraRig] with both controllers present and enabled.

When I disabled the controllers my input stopped functioning. If you don't want the controllers visible disable the Model child instead.

**Comment by bongistka** [comment]
> 
> 
> For anyone having this issue ensure that you have the [CameraRig] with both controllers present and enabled.
> 
> When I disabled the controllers my input stopped functioning. If you don't want the controllers visible disable the Model child instead.

This didn't work for me. What did work instead was regenerating the "StreamingAssets/SteamVR" folder. Good luck!
