### ISSUE TITLE
Controller position set to (0,0,0) when entering VR

### ISSUE THREAD

**Issue by KirbX** [ValveSoftware/steamvr_unity_plugin#257]
Hi!

I've seen a tutorial in order to create my own controllers sets, and the script that goes with it.
In this tutorial, I saw that I must add a `public SteamVR_ActionSet actionSetEnable;` and then a call to `actionSetEnable.ActivateSecondary(true);`, in order to be able to map controllers triggers and button with what I want.

It worked well yesterday, but this morning, when I start my project, my hands position are set to (0,0,0) and I can't move them. By removing the line ` actionSetEnable.ActivateSecondary(true);` in the Start function, I can see my hand again. But when I make a call to it, they disappear, even if I have nothing more in my code that this line. 

Someone know the problem?
Thanks a lot!

**Comment by zite** [comment]
Probably what you want is ActivatePrimary. ActivateSecondary is mainly for
“offhand” things. You can activate multiple “primary” sets. This wording
has been changed in the beta versions.

**Comment by KirbX** [comment]
There is no difference if I call ActivatePrimary instead of ActivateSecondary. I lose my hands.
But still I can use the function of my controller. For example, I can move by using the pad, and even if my controllers are not visible in my scene, I can use this functionnality :(

**Comment by zite** [comment]
Yeah, sorry again for the confusing function calls. The explanation was in the intellisense summary but it wasn't very clear. So I've changed future versions to just have a single Activate() method (with a priority if you want).

But here's the documentation for the function:
https://github.com/ValveSoftware/steamvr_unity_plugin/blob/master/Assets/SteamVR/Input/SteamVR_ActionSet.cs#L91
