### ISSUE TITLE
Missing compiler directive causes build error on MacOS

### ISSUE THREAD

**Issue by chilton** [ValveSoftware/steamvr_unity_plugin#259]
Assets/SteamVR/WindowsHelper/SteamVR_Windows_Editor_Helper.cs(19,42): error CS0161: 'SteamVR_Windows_Editor_Helper.GetDefaultBrowser()': not all code paths return a value

Possible Solution: Add an additional set of directives prior to the ifdef.

    #else
            return BrowserApplication.Firefox;
    #endif

**Comment by DeadFenix** [comment]
Im having the same issue on the Linux Editor

**Comment by zite** [comment]
I believe this issue is fixed in rc2. But there are other osx / linux compatibility issues.
https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.2RC2

**Comment by zite** [comment]
This particular issue was fixed in the current release. Still issues with linux support though.
