### ISSUE TITLE
Vive Controllers not showing up in build

### ISSUE THREAD

**Issue by julienkay** [ValveSoftware/steamvr_unity_plugin#266]
I have an issue, where the Controllers are not visible in the scene. I'm using Unity 2018.3.0f2 and the newest beta version v2.2b4 of the plugin. (I upgraded from 2.0.1 trying to fix this issue).
This doesn't happen on all machines however. On my development machine the Controllers show up fine in Unity and in a build. On another machine (that I unfortunately don't have access to) the Controllers are not visible in the same build which is working fine for me.

The output_log.txt of that machine contains the following lines:
```
[SteamVR] Loading actions file: C:/Test/actions.json
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

System.NullReferenceException: Object reference not set to an instance of an object
  at Valve.VR.SteamVR_Input.IdentifyActionsFile () [0x00000] in <filename unknown>:0 
  at Valve.VR.SteamVR.CreateInstance () [0x00000] in <filename unknown>:0 

[SteamVR] Loading actions file: C:/Test/actions.json

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

System.NullReferenceException: Object reference not set to an instance of an object
  at Valve.VR.SteamVR_Input.IdentifyActionsFile () [0x00000] in <filename unknown>:0 
  at Valve.VR.SteamVR.CreateInstance () [0x00000] in <filename unknown>:0 
```

The only thing I can imagine throwing a NullReferenceException in `SteamVR_Input.IdentifyActionsFile()` would be the call to `SteamVR_Settings.instance`
It uses Resources.Load(), so that could potentially be the cause of different result on different machines, but I don't know what the exact issue is.

**Comment by zite** [comment]
Sorry you're having issues with the plugin, is there anything strange about the machine you can think of? Different version of SteamVR maybe? Are there any other errors before this? Can you include the full log up to this point?

**Comment by JamesCitu** [comment]
I've found that closing both Unity and SteamVR. Then launching SteamVR via Steam rather than letting Unity do it tends to fix the issue.

**Comment by julienkay** [comment]
> 
> 
> Sorry you're having issues with the plugin, is there anything strange about the machine you can think of? Different version of SteamVR maybe? Are there any other errors before this? Can you include the full log up to this point?

Here's the full output_log, but there doesn't seem to be any preceeding error. [output_log.txt](https://github.com/ValveSoftware/steamvr_unity_plugin/files/2759062/output_log.txt)

Some specifics I can think of: In the project I have the Oculus SDK active as well. I use a "regular" HTC Vive while the machine where the problem occurs uses an HTC Vive Pro. There's not much more I can think of right now, sorry.

@JamesCitu Thanks for the suggestion, but the issue only appears in a build. No Unity installed on that machine, so starting would always happen through Steam.

**Comment by HansenBerlin** [comment]
Hi,
same here. Running same versions of stem VR on 2 machines. On the machine where unity is installed the build works fine. On the other machine (fresh windows, all drivers up to date) the same build doesnt load the controllers. I am using Unity 2018.3 and Steam SDK 2.2 beta (because in earlier versions the input bindings generation gets stuck in my case).

**Comment by julienkay** [comment]
If you have access to the machine, could you do what @keithbradner suggested and create a development build, so we're able to pinpoint where the issue is with the output_log from that build?
That would be awesome.

**Comment by HansenBerlin** [comment]
Will do tommorow. Something that might have to do with this issue: on the machine that is not showing the controllers, the .exe is not shown in the controller binding window of steam vr. On the machine that shows the controllers it is possible to select the app and change bindings. Both Steam VR installs are up to date and have the same (default) settings.

**Comment by HansenBerlin** [comment]
Allright, solved this. I simply didnt add the actions.json etc. in the archive from the build. Sorry for bothering you with this. :-)

**Comment by julienkay** [comment]
This is not solved for me yet.
I'll try to somehow reproduce the issue. I can also try to use the newest release and report back if that changes anything.

**Comment by kosma822** [comment]
Same problem here, on build, both controllers not showing up... i've tried to launch steamvr from steam client, then launch the build, but this not solve the issue. all binding json file are on build folder

Any news?

**Comment by julienkay** [comment]
@kosma822Does your ouput_log.tx contain the same error message?

**Comment by HansenBerlin** [comment]
Hi,

in my case it was a very stupid mistake on my side. I packed the .dll, .exe and data Folder as usual when developing for Oculus or non VR. But when using the steam sdk there are a couple more files like the bindings.json that Need to be within the same directory.
So check that first, other than that I have no idea, it is working like a charm now for me.



________________________________
Von: Julien Kipp <notifications@github.com>
Gesendet: Wednesday, February 20, 2019 10:03:56 AM
An: ValveSoftware/steamvr_unity_plugin
Cc: HansenBerlin; Comment
Betreff: Re: [ValveSoftware/steamvr_unity_plugin] Vive Controllers not showing up in build (#266)


@kosma822Does your ouput_log.tx contain the same error message?

**Comment by kosma822** [comment]
> @kosma822
> Does your output_log.txt contain the same error message as above?
> (NullReferenceException in IdentifyActionsFile())

Yes, i have already generated require action files, but nothing happens... here is my log:

`UnloadTime: 1.684900 ms
<b>[SteamVR]</b> No actions found, but the action manifest was loaded. This usually means you haven't generated actions. Window -> SteamVR Input -> Save and Generate.
UnityEngine.DebugLogHandler:Internal_Log()
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
Valve.VR.SteamVR_Input:IdentifyActionsFile(Boolean)
Valve.VR.SteamVR:CreateInstance()
Valve.VR.SteamVR:Initialize(Boolean)
Valve.VR.SteamVR_Behaviour_Pose:OnEnable()`

**Comment by JustinAtSama** [comment]
Issue is definitely not solved please reopen this -- SteamVR2.2 Unity 2018.1.1f1.
Making a standalone build shows no Vive controllers.

**Comment by balamsoto** [comment]
Same issue here, I had try few workarounds ( copy controllers .jason files from sample to root of project and still not working. Works fine with Unreal engine. Running on MacOS

**Comment by ValentinaScarfi** [comment]
I'm experiencing the same issue, has anyone found a fix to this problem?

**Comment by HansenBerlin** [comment]
I dont experience it anymore, but I have „Cancer Hands“ sometimes.

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Valentina Scarfi <notifications@github.com>
Gesendet: Monday, May 20, 2019 2:34:36 PM
An: ValveSoftware/steamvr_unity_plugin
Cc: HansenBerlin; Comment
Betreff: Re: [ValveSoftware/steamvr_unity_plugin] Vive Controllers not showing up in build (#266)


I'm experiencing the same issue, has anyone found a fix to this problem?

**Comment by JustinAtSama** [comment]
Not sure why this issue keeps closing as this issue is not fixed. This will probably remain an issue until an actual update provided by Steam is released. Otherwise, if there is a fix, there should be some straight-forward documentation of how to set up the profile. Everyone is experiencing the same issue and these half solutions to them don't always work.

**Comment by kisak-valve** [comment]
Hello @JustinAtSama, there's multiple issue reports open for this symptom like #323, #364, #412. It's likely one of those issue reports covers your issue.
