### ISSUE TITLE
Haptic problem in Vive controllers with SteamVR 2.0.1

### ISSUE THREAD

**Issue by castana1962** [ValveSoftware/steamvr_unity_plugin#267]
Hi
I am trying the haptics feature in Unity and SteamVR 2.0.1 and I have the following problem,
It is working well, but for example, when I click one time the Right controller trackpad, the haptic works fine but I have click twice the Left controller trackpad to works fine. I spoke with some people and they have the same problem and I found also one youtube video with similar problem( in this case click the trigger)
https://youtu.be/wq4OJUFghNI
Could you help me to fix this problem?
Thanks
Alejandro
Note. I tried the same Unity project with the Knuckles EV3 controllers and it is working very well. It seems that the problem is with the old vive controllers

**Comment by zite** [comment]
Pretty sure this has been fixed or is a hardware issue. If not please create a new issue with repro steps and ideally an example project. Thanks!
