### ISSUE TITLE
Can't feel haptics in the Interactions example scene with Touch controllers

### ISSUE THREAD

**Issue by MichaelSchenck** [ValveSoftware/steamvr_unity_plugin#269]
I am trying out the interaction examples with Unity 2018.3.0f2, Steam VR beta 1.2.6, and SteamVR Unity Plugin v2.2b4.  

I am having issues with feeling the haptics with the Touch controllers when using the Rift.  I don't feel anything except the interface hints (when the buttons flash).   When I switch over the the Vive the haptics feel good.  

I dug into the setup and the code and the events and so on are working and I turned on the debug statement in the SteamVR_Action_Vibration.cs class in the Execute method.  I found that the interface hits had very different values than the ones coming from TriggerHapticPulse in Hand.cs.  I ended up just modifying a line in there to get values in a range i could feel:

```
//hapticAction.Execute(0, seconds, 1f / seconds, 1, handType);
hapticAction.Execute(0, seconds * 10.0f, seconds * 10.0f, 1, handType);
``` 

Obviously this isn't a proper solution but wondering if this should be working or maybe there is something wrong elsewhere where these values go to the touch controller.  I have not messed with my bindings at all and I am just using the defaults the unity plugin makes.

**Comment by ZnelArts** [comment]
May be related to https://github.com/ValveSoftware/steamvr_unity_plugin/issues/267

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
