### ISSUE TITLE
VR not working. New install of unity and steamVR... htc vive. 

### ISSUE THREAD

**Issue by dalco78** [ValveSoftware/steamvr_unity_plugin#270]
Hi I've installed completely new install of SteamVr and unity 2018.3.0f2 both the latest versions direct from the websites and asset store on brand new PC that is HTC vive ready.. after install on completely new file adding a plane and a cube into the scene. Then adding the steam VR camera rig from the Prefab folder. then pressing Save.

Going main menu>Steam VR input>open binding UI (button)    <- non responsive nothing happens --- firefox is my default browser.

Not able to enter into VR by pressing play.

i was able to make this work once the very first time on the first day yesterday but i have since not been able to make it work

reinstalled unity many times no change

If I find an old unity file. like a tutorial file i can follow this process the open UI binding works and i can enter into VR mode. but no newly created files are working.

**Comment by zite** [comment]
Sorry you're having issues with the plugin. What version of SteamVR are you on? When you say the button is non-responsive, are you saying no browser window opens? Are there any errors in the console?

**Comment by dalco78** [comment]
G'day. I use the latest SteamVR. I use the Store tab in Unity to get it direct from there and import it.. The UI button when you click it does nothing at all doesn't open a browser. I know the steam VR works because I can open an existing file like a tutorial or something and install steamVR the UI button works. it just not working on a brand new scene/ project. Also on the first day it worked correctly every now and then, now it's not working at all. i was able to retain a new file that i had created for my new project where it worked and use that but i can't create any new projects where it works. i might try making my 1 working file my starting template as i know it works.

**Comment by zite** [comment]
Can you let me know what your Editor App Key is? You can find this by selecting SteamVR_Settings in Assets/SteamVR/Resources/SteamVR_Settings.

**Comment by zite** [comment]
Are there errors in the unity console window when you hit the open binding ui button?
