### ISSUE TITLE
Can't access SteamVR_Actions._default from other classes

### ISSUE THREAD

**Issue by khalv** [ValveSoftware/steamvr_unity_plugin#273]
Seriously tearing my hair over this new update... I used the UI to generate an action set, and it successfully creates the action classes in Assets/SteamVR_Input, and reports success in the console. However, i can't access the generated classes from any other scripts, despite including the Valve.VR namespace. How do i use my actions?? Judging by my generated code, it should be in SteamVR_Actions._default, but that is not recognized as a class by IntelliSense. I have tried restarting Visual Studio but no dice. 

I have an old project which is built upon a modified version of NewtonVR, and i am trying to rewrite the input wrapper to work with the newest SteamVR plugin version.

**Comment by DrummerB** [comment]
Which version are you using? I think in 2.2 they moved the SteamVR_Actions class into a separate assembly, which is (probably by mistake?) not referenced by the main project assembly. Try checking the "Auto Reference" checkbox in the assemby definition file's inspector:

![image](https://user-images.githubusercontent.com/2104474/51185533-a82bf880-18d7-11e9-9514-cfce1feeedd6.png)

**Comment by zite** [comment]
Whoops, yeah, still getting a hang of these assembly definitions. I’ll make
sure that box gets checked by default in the next beta.

**Comment by DrummerB** [comment]
Great, thanks!
