### ISSUE TITLE
The naming of SteamVR_Actions._default is misleading

### ISSUE THREAD

**Issue by DrummerB** [ValveSoftware/steamvr_unity_plugin#275]
I think that the name of the default action set getter is misleading, because it starts with an underscore. Most people associate that with private variables. Seeing something like `SteamVR_Actions._default` immediately looks like a temporary hack for something.

This is only done for the "default" action set, but not for any others like "plaform" and "mixedreality". I assume this is because `default` is a reserved keyword in C#. I suggest using an `@` prefix for variables that collide with C# keywords, [as recommended by Microsoft](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/verbatim). 

Even better would be to use capitalized action sets, and just use `SteamVR_Actions.Default`, since public properties [should be PascalCase anyway](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions).

**Comment by ZnelArts** [comment]
I would be in favor on the capitalized approach since @ may be actually more confusing, specially since @ is used by some other languages and has a vast variety of uses.

**Comment by zite** [comment]
I appreciate the feedback but I've opted to leave the casing to the developer. If you create an ActionSet named Default it will be generated as such, if you create an ActionSet named default it'll prepend an underscore to make it valid. I think the @ sign will just confuse inexperienced developers.
