### ISSUE TITLE
Can't Hide trackers

### ISSUE THREAD

**Issue by robrab2000** [ValveSoftware/steamvr_unity_plugin#276]
Hi,

I'm trying to hide the controllers and trackers (I have 2 controllers and 3 trackers in my scene). The controllers are easy, I just go to Controller Left/Right under the [Camera-Rig], and disable the 'model' gameobject under them.

For the trackers however I don't any 'model' game objects? I just have an empty gameobject with a SteamVR_TrackedObject script attached to it and it tracks. In the headset, I can see the model of the tracker, however I can't see how to turn off the model for it.. If I could even just affect it's material then I could make it invisible, I just need to not be able to see it.

Thanks

**Comment by robrab2000** [comment]
er... okay I solved it... but I don't understand how... basically if I disable the models under the left and right controllers, the trackers turn off too... i... dont... understand...  ...but it works... can anyone explain? or tell me if there is a better way to do this? (I don't want it to suddenly stop working at some point or something)

**Comment by zite** [comment]
You can disable the SteamVR_RenderModel component to turn off dynamically created models.
