### ISSUE TITLE
how to get  HTC VIVE pro (SRWorks) ar effect in HTC VIVE using extrenal USB Camera

### ISSUE THREAD

**Issue by junglee372018** [ValveSoftware/steamvr_unity_plugin#277]
Hi,
I want to get the AR effect into HTC VIVE using external USB logitec CAM.

Is there any way possible to replicate the ar effect in HTC vive in unity same as the effect we get when using the HTC VIVE PRO SRWORKS

https://www.youtube.com/watch?time_continue=108&v=xkw133wvPYM

Presently i am getting the input from logitec usb camera and projecting it onto a quad and using shader to get a full screen effect. But the image scale 3 times the usual one on the desktop output.

Is there any way to get the same AR effect we get in SRWorks in HTC VIVE version.

Project link:

**Comment by junglee372018** [comment]
Hi,
Sorry for the not giving the proper info about my issue and what i am trying to do.

I want to get the AR effect into HTC VIVE using external USB logitec CAM.

Is there any way possible to replicate the ar effect in HTC vive in unity same as the effect we get when using the HTC VIVE PRO SRWORKS

https://www.youtube.com/watch?time_continue=108&v=xkw133wvPYM

Presently i am getting the input from logitec usb camera and projecting it onto a quad and using shader to get a full screen effect. But the image scale 3 times the usual one on the desktop output.

Is there any way to get the same AR effect we get in SRWorks in HTC VIVE version.

Project link:

**Comment by zite** [comment]
Sorry this github Issues forum is for bugs with the SteamVR Unity Plugin. You might be better served by the SteamVR Developer forum on steam here: https://steamcommunity.com/app/250820/discussions/7/
