### ISSUE TITLE
SteamVR_Action event handler doesn't receive correct input source

### ISSUE THREAD

**Issue by DrummerB** [ValveSoftware/steamvr_unity_plugin#279]
In a simple example I want to handle menu button clicks with an event handler (instead of adding an unnecessary Update method). The event handler I define has an SteamVR_Input_Sources parameter, but it is always Any, instead of the correct source, such as RightHand.

```csharp
using UnityEngine;
using Valve.VR;

public class ApplicationMenu : MonoBehaviour
{
    public SteamVR_Action_Boolean toggleAction;

    void OnEnable()
    {
        toggleAction.onStateDown += OnToggleMenu;
    }
    
    void OnDisable()
    {
        toggleAction.onStateDown -= OnToggleMenu;
    }

    void OnToggleMenu(SteamVR_Action_Boolean fromAction, SteamVR_Input_Sources fromSource)
    {
        Debug.Log($"fromSource: {fromSource} activeDevice: {fromAction.activeDevice}");
    }
}
```

Output when I press the menu button on the right controller:

`fromSource: Any activeDevice: RightHand`

Expected output:

`fromSource: RightHand activeDevice: RightHand`

**Comment by zite** [comment]
It's somewhat confusing but those onStateDown events are shortcuts for the Any input. To get a specific input device you can specify that as an indexer on the toggle action. So: `toggleAction[SteamVR_Input_Sources.Right].onStateDown += OnToggleMenu;`

Let me know if that works out.

**Comment by DrummerB** [comment]
Thanks for the clarification. 

Yes, your suggestion works, however it's not quite what I'm trying to do. I am interested in *any* device triggering that action, but at the same time I need to know which device ended up triggering the action and display the menu in front of that device. Whether that's one of the right/left controllers, a third controller or tracking device doesn't really matter. 

I could of course hard code some of this stuff (which I did now), but I want to take advantage of the new abstractions of the input system as much as possible.

Can you confirm that `SteamVR_Action_In.trackedDeviceIndex` (which I can access from the callback) is a reliable way to determine which device triggered the event? Of course at that point I would still have to map the device index to a Transform somehow. Maybe I'm overthinking this.

**Comment by zite** [comment]
Depending on your situation you'd probably be better served subscribing to the event for each source.

`
        protected void AddHandlers()
        {
            booleanAction[SteamVR_Input_Sources.LeftHand].onStateUp += SteamVR_Behaviour_Boolean_OnStateDown;
            booleanAction[SteamVR_Input_Sources.RightHand].onStateUp += SteamVR_Behaviour_Boolean_OnStateDown;
        }

        private void SteamVR_Behaviour_Boolean_OnStateUp(SteamVR_Action_Boolean fromAction, SteamVR_Input_Sources fromSource)
        {
            //fromSource will never be Any, it will be left or right.
        }

        protected void RemoveHandlers()
        {
            booleanAction[SteamVR_Input_Sources.LeftHand].onStateUp -= SteamVR_Behaviour_Boolean_OnStateDown;
            booleanAction[SteamVR_Input_Sources.RightHand].onStateUp -= SteamVR_Behaviour_Boolean_OnStateDown;
        }
`

The trouble with subscribing to Any is that it may not give you good results for stateDown AND stateUp. Any means unrestricted. So all the input sources are OR'd together to produce the result. Here's a scenario: 
User presses right trigger down:
* System throws stateDown.Any
User presses left trigger down:
* System throws no events
User releases left trigger
* System throws no events
User releases right trigger
* System throws stateUp.Any

However, if that doesn't sound like it's going to be a problem for you, you can check the .activeDevice on any In action:

`
        protected void AddHandlers()
        {
            booleanAction[SteamVR_Input_Sources.Any].onStateUp += SteamVR_Behaviour_Boolean_OnStateUp;
        }

        private void SteamVR_Behaviour_Boolean_OnStateUp(SteamVR_Action_Boolean fromAction, SteamVR_Input_Sources fromSource)
        {
            Debug.Log(fromAction[fromSource].activeDevice); //should be RightHand or LeftHand
        }

        protected void RemoveHandlers()
        {
            booleanAction[SteamVR_Input_Sources.Any].onStateUp -= SteamVR_Behaviour_Boolean_OnStateUp;
        }
`
