### ISSUE TITLE
example scene cannot detect controller in Unity 5.6

### ISSUE THREAD

**Issue by if1live** [ValveSoftware/steamvr_unity_plugin#28]
1. Open unity 5.6.0f3
2. Create new project
3. Import steamVR plugin from asset store
4. Open example scene
5. Play game
6. Game cannot detect controller

I test in unity 5.5.0f3, it works. Maybe this is not my hardware problem.

## Environment
* unity version : unity 5.6.0f3
* steamvr plugin : 1.2.1 (from unity asset store)

**Comment by if1live** [comment]
I found solution. I think that this is steam vr plugin's bug.
http://answers.unity3d.com/questions/1299567/vive-controllers-not-tracking-in-unity-560b3.html

**Comment by bddckr** [comment]
https://github.com/ValveSoftware/steamvr_unity_plugin/issues/11#issuecomment-281595933
