### ISSUE TITLE
Controllers not registering when SteamVR initialised manually

### ISSUE THREAD

**Issue by jirimotejlek** [ValveSoftware/steamvr_unity_plugin#282]
Using _Unity 2018.3.2f1_ and _SteamVR Unity Plugin v2.2b5_ I would like to create a hybrid application that runs both, in VR as well as just in desktop mode. Unfortunately, major problem I have now is that the controllers are not showing up.

This is how I set things up:

First, in Player Settings->XR Settings I put "None" on the first place in the list, then "OpenVR" on the second and check "Virtual Reality Supported".

Then I initialise VR with this simple script once the user makes the choice to use VR. (When user clicks the button it starts procedure StartVR().)
```csharp
using UnityEngine.XR;

private Valve.VR.EVRInitError VRError;

    void StartVR() {
        XRSettings.LoadDeviceByName(new string[] { "OpenVR", "None" });
        XRSettings.enabled = true;
        Valve.VR.OpenVR.Init(ref VRError);
        Valve.VR.SteamVR.enabled = true;
        TeleportVR.SetActive(true);
        StartCoroutine(LoadDevice("OpenVR"));
    }

    IEnumerator LoadDevice(string newDevice) {
        if (String.Compare(XRSettings.loadedDeviceName, newDevice, true) != 0) {
            PlayerVR.SetActive(true);
            XRSettings.LoadDeviceByName(newDevice);
            
            yield return null;

            XRSettings.enabled = true;
            Valve.VR.SteamVR.Initialize(true);
            ActivateVRRig();
        }
    }

    void ActivateVRRig() {
        Valve.VR.InteractionSystem.Player.instance.rig2DFallback.SetActive(false);
        Valve.VR.InteractionSystem.Player.instance.rigSteamVR.SetActive(true);

        if (Valve.VR.InteractionSystem.Player.instance.audioListener) {
            Valve.VR.InteractionSystem.Player.instance.audioListener.transform.parent = Valve.VR.InteractionSystem.Player.instance.hmdTransform;
            Valve.VR.InteractionSystem.Player.instance.audioListener.transform.localPosition = Vector3.zero;
            Valve.VR.InteractionSystem.Player.instance.audioListener.transform.localRotation = Quaternion.identity;
        }
    }
```

This then initialises the VR and the scene appears in the headset. Disadvantage of this is though, that the controllers don't register. I was wondering if it's possible to initialise those controllers somehow. Also, if possible, is there a simpler way of initialising VR somehow?

**Comment by zite** [comment]
In the Assets/SteamVR/Extras folder you'll find a scene named SteamVR_ForceSteamVRMode and a script by the same name that should provide a good example of how to do this.

https://github.com/ValveSoftware/steamvr_unity_plugin/blob/beta/Assets/SteamVR/Extras/SteamVR_ForceSteamVRMode.cs

**Comment by zite** [comment]
Fixed in current release.
