### ISSUE TITLE
Calling SteamVR_Action_Vibration.Execute with amplitude of 1.0 causes no vibration

### ISSUE THREAD

**Issue by lachlansleight** [ValveSoftware/steamvr_unity_plugin#284]
Basically as the description says - passing in a value of 0.99 for amplitude works fine, but 1.0 will result in no vibration. Took me ages to figure out why my haptics weren't working for a particular interaction...

Note that I'm using the original HTC Vive Controllers - this might be different with other SteamVR controllers...

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
