### ISSUE TITLE
TeleportArea throwing Errors in Editor when no Teleport object is in scene

### ISSUE THREAD

**Issue by ZnelArts** [ValveSoftware/steamvr_unity_plugin#286]
Seen in v2.2RC1

Steps to reproduce
Create a new Scene

1. Add a collider and add the TeleportArea Script
2. When selecting this object in the editor errors will be printed in the console

This is happening because there is no Teleport instance in the scene and the TeleportArea uses an instance of Teleport to get the material to be applied to the collider. 

It is a common case to not have a Teleport object on the scene, sometimes SteamVR and VR objects are loaded at runtime, e.g. the SteamVR_ForceSteamVRMode Scene

**Comment by zite** [comment]
I just added a return if the teleport instance is null to that function. Should be fixed in the next RC

**Comment by zite** [comment]
Here's RC2 where this should be fixed: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.2RC2

**Comment by zite** [comment]
Fixed in the current version.

**Comment by jirimotejlek** [comment]
I'm not sure how it's possible, but this issue is actually not fixed in the current final release 2.2.0. TeleportArea.cs is getting the materials in Start() and that function is not checking whether the instance exists or not.
