### ISSUE TITLE
camera not avialable issue on steam vr

### ISSUE THREAD

**Issue by junglee372018** [ValveSoftware/steamvr_unity_plugin#287]
The system says the camera is "not recogonized on the current USB port". I've tried 3 different ports on my PC all USB 3 & USB 2 ports i get  the same error. Windows actually sees the camera in device manger as HTC Cam but on the SteamVR settings still getting camera not available error.
![camera1](https://user-images.githubusercontent.com/44200667/51466566-85df2280-1d90-11e9-97df-7ba538c26cee.JPG)
![camera2](https://user-images.githubusercontent.com/44200667/51466567-8677b900-1d90-11e9-983e-a23688c4b7c0.JPG)
![camera3](https://user-images.githubusercontent.com/44200667/51466568-8677b900-1d90-11e9-8db9-98798dcf0cdf.JPG)
![camera](https://user-images.githubusercontent.com/44200667/51466569-8677b900-1d90-11e9-8912-6eee6de553fd.JPG)

**Comment by kisak-valve** [comment]
Hello @junglee372018, per https://github.com/ValveSoftware/VR-Community-Bugs/issues/93, should be fixed with the SteamVR 1.2.8 beta.
