### ISSUE TITLE
SteamVR.settings is NULL in SteamVR.RenderLoop()

### ISSUE THREAD

**Issue by Salzian** [ValveSoftware/steamvr_unity_plugin#288]
When importing SteamVR v2 into an Unity project and running the project, Unity throws a NullPointerException at SteamVR_Renderer.cs:139:

```
var compositor = OpenVR.Compositor;
                if (compositor != null)
                {
                    if (!compositor.CanRenderScene())
                        continue;

NULL>>>             compositor.SetTrackingSpace(SteamVR.settings.trackingSpace);
                }
```

`SteamVR.settings` is null at this point.

Temporary fix for me was to change _SteamVR.cs:103_ to
`public static SteamVR_Settings settings { get; private set; } = SteamVR_Settings.instance;`

As it seems, the `SteamVR_Renderer.RenderLoop()` (_SteamVR_Render.cs:124_) throwing the NullPointer is called before `SteamVR.CreateInstance()` containing the important variable initialization `settings = SteamVR_Settings.instance;` (_SteamVR.cs:144_).

**Comment by zite** [comment]
Is this on version 2.0.1 or 2.2 of the unity plugin? And what version of Unity are you running?

**Comment by Salzian** [comment]
Oops, sorry. Totally forgot.

Unity 2018.3.0
SteamVR 2.0.1 (Asset Store)

**Comment by zite** [comment]
Can you try to upgrade to the 2.2RC1 on the github repo here and let me know if the issue still exists? https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.2RC1

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by GrahamGSG** [comment]
This error can still occur in SteamVR 2.8.0
Unity version 2022.3.48f1
