### ISSUE TITLE
Interaction system player prefab hands stutter/flicker

### ISSUE THREAD

**Issue by gschomburg** [ValveSoftware/steamvr_unity_plugin#29]
I am seeing stuttering/flickering of the controllers when using the Interaction System Player prefab.
In a empty Unity project and a scene that just contains the Player prefab. Making large horizontal movements (with the controllers) back and forth you will see the stuttering, it's also pretty clear to see with large arcs. The stutter looks like the controller is rendering at the previous frame position. 
I do not see similar stuttering/flickers using the CameraRig prefab and I've also had another test this so I don't think it is a hardware issue.
Using: Unity 5.5 & GTX970

**Comment by zite** [comment]
Thanks for the report, I believe this issue has been fixed in recent versions. Let me know if it's still an issue and I'll reopen.
