### ISSUE TITLE
Expose VRIOBuffer to Unity Plugin

### ISSUE THREAD

**Issue by hyaticua** [ValveSoftware/steamvr_unity_plugin#290]
I am trying to access the VRIOBuffer to read IMU data using the functionality added in [OpenVR release v1.0.15](https://github.com/ValveSoftware/openvr/releases/tag/v1.0.15). I am able to implement this behavior correctly in C++ by following the example as laid out in [the openVR wiki documentation](https://github.com/ValveSoftware/openvr/wiki/IVRIOBuffer). I am failing to access the same data in Unity. 

There are definitions for the [ImuSample_t](https://github.com/ValveSoftware/steamvr_unity_plugin/blob/master/Assets/SteamVR/Plugins/openvr_api.cs#L5120) struct and a wrapper class for [VRIOBuffer](https://github.com/ValveSoftware/steamvr_unity_plugin/blob/master/Assets/SteamVR/Plugins/openvr_api.cs#L1636) itself, so it seems like this is intended to be exposed, but not completed. 

There is no public accessor for VRIOBuffer under COpenVRContext in the current public iteration of OpenVR_api.cs and adding an accessor fails on the GetGenericInterface call. The GetGenericInterface call itself returns null if you follow the pattern of using the FnTable prefix + Module Version String ([example](https://github.com/ValveSoftware/steamvr_unity_plugin/blob/master/Assets/SteamVR/Plugins/openvr_api.cs#L5974)). If you try to access the interface without the FnTable prefix, using the exact same parameters as the C++ examples, you fail on invoking any function on the CVRIOBuffer object you are returned. 

Access to this data in C#/Unity would be immensely helpful.

**Comment by zite** [comment]
Can you try upgrading to the latest version of the plugin and trying this again? I believe this has been fixed.

**Comment by hyaticua** [comment]
VRIOBuffer functionality seems to work as intended across the FFI with latest version of OpenVR with one exception. There is a minor typo in the new version of openvr_api.cs causing an error. I have submitted a pull request addressing it: https://github.com/ValveSoftware/openvr/pull/1034

Thanks.

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by YongD0ng** [comment]
hello,how to use c# to read IMU data?
