### ISSUE TITLE
Left Controller has strange UI functionality

### ISSUE THREAD

**Issue by PittMichelmann** [ValveSoftware/steamvr_unity_plugin#291]
Hey Guys,
I'm using the HTC Vive and I've coded a custom UI Navigation, that navigates on Touchpad-Clicks. I'm using my custom input module, that subscribes to the button events fired by the SteamVR_Tracked Controller Script.
This works all fine so far on both controllers, except that when both controllers are enabled, only the Controller (left) has functionality I didn't code . There seems to be a second navigation that works with Touchpad touches also. So in my menu it will scroll through the items, even when just touched. I've debugged as far as I could and found out, that this functionality uses neither my navigation script nor my input script.
Soo is this a inherent functionality from Steam VR? How do I turn this off?
My Controllers both have the Tracked Object and Tracked Controller Script attached.
What seems to work is, when running, disabling the Tracked Controller script by hand and enabling it again. I tried to do this from code with a Coroutine, but that doesn't work.

Thanks in advance for any help! I'm really lost here

**Comment by zite** [comment]
Unfortunately it sounds like you're using version 1.2.3 of the plugin which is no longer officially supported. You may have some luck posting in the SteamVR Developer forums here: https://steamcommunity.com/app/250820/discussions/7/
