### ISSUE TITLE
Rendering bug objects popping in/out peripheral vision

### ISSUE THREAD

**Issue by horst789github** [ValveSoftware/steamvr_unity_plugin#293]
Almost nobody seems to mention this but I find this currently one of the biggest issues, the problem where objects pop into/out of your peripheral vision. The main environment is good but some (I don’t even think all) objects pop in/out in your peripheral vision, while this actually should happen outside the FoV, so that objects just naturally ‘move’ into your peripheral vision. I find this highly distracting since stuff just ‘flashes’ in your peripheral vision. Not in all games, maybe only in unitygames or games with "Occlusion Culling"

HMD: Pimax 5k+
Example Games: Onward, SteamVR Home

please give steamvr a native support for Pimax 5k+/8k with Field of View ~170 - 200°

**Comment by zite** [comment]
Sorry this is a pimax or possibly unity issue. You will need to contact them for support.

**Comment by horst789github** [comment]
its not unity issue because the lab (roboter repair is in source 2): 
i make video on youtube with the problem: https://www.youtube.com/watch?v=JAQqmb2qyhk
