### ISSUE TITLE
【Assets/SteamVR/Interaction System/Samples】why can't you see the controller?

### ISSUE THREAD

**Issue by kwooshung** [ValveSoftware/steamvr_unity_plugin#294]
Running the Assets/SteamVR/Interaction System/Samples case, why can't you see the controller? With this Assets/Steam VR/Prefabs/[CameraRig]. prefab is also invisible. Only VR helmet can be used.

**Comment by zite** [comment]
What headset / version of SteamVR / version of the SteamVR Unity Plugin are you running?

**Comment by kwooshung** [comment]
SteamVR Unity Plugin v2.2RC4
Unity 2018.3.2
HTC VIVE LAST VERSION

**Comment by zite** [comment]
Did you save and generate actions from the SteamVR Input window?

**Comment by kwooshung** [comment]
I develop it in Mac, build it to generate Windows programs, and run it in Windows. I've done this before, but I don't know why it doesn't work.

**Comment by kwooshung** [comment]
Then I copy the generated file to HTC Vive and run it with the latest version of Stame installed. The helmet can see things, but when the controller opens, it can't see the controller.

Windows 10

Stame VR Last Version

Creation Process Video：https://youtu.be/4FLgRS_DzfI

**Comment by kwooshung** [comment]
> Did you save and generate actions from the SteamVR Input window?

It's not really generated. It's not done. I'll try it.

**Comment by david-jares** [comment]
Any News on this one ? I go the Same Problem, Unity 2018.3.2F1. 
![image](https://user-images.githubusercontent.com/24854306/52431159-f6fc3500-2b07-11e9-915b-9f3255af99a3.png). In the SimpleSample-Scene I have two warnings during Playmode and One Error after Exiting Playmode.. AAAh

**Comment by david-jares** [comment]
Ok, So I got my problems solved by updating my steamvr-application. I realized the one I used was 3 ,5 Months old. After updating to the newest everything forks well so far. :)
