### ISSUE TITLE
Hands localPosition don't change sometimes in Unity with SteamVR version 2.0.1 and HTC ViVE

### ISSUE THREAD

**Issue by dpggit** [ValveSoftware/steamvr_unity_plugin#295]
I am using Unity 2018.2.17f1 and hands localPosition don't change , stays at 0,0,0, this just happens few times, usually works, it is random. I opened Hands.cs but i don't see where the localPosition is changed. I can see the trackers work well, it is just that the localPosition is not updated in the gameobject with the Hands.cs script
If i restart SteamVR application it works again

**Comment by zite** [comment]
You may need to start Steam to access a binding if you have it saved on a different computer. Otherwise did you save and generate bindings. Are there any errors in the Unity Console?

You might also try upgrading to the new version of the SteamVR Unity Plugin v2.2.0 that was released today.

**Comment by kisak-valve** [comment]
Closing pending feedback.
