### ISSUE TITLE
Controller poses only update while Steam client is running

### ISSUE THREAD

**Issue by EntroPiGames** [ValveSoftware/steamvr_unity_plugin#298]
When I start my project from inside the Unity Editor the controller poses / positions won't update unless the Steam client is running. 

I think this issue was introduced with an update to SteamVR a couple of versions ago.

No errors or warnings are logged in the console.

Versions:
- Unity 2017.4.18f1
- SteamVR Unity Plugin v2.0.1
- Latest SteamVR beta

**Comment by zite** [comment]
Have you made changes to the bindings? If so did you then hit the Replace
Default Bindings button to copy them to your project directory?

**Comment by EntroPiGames** [comment]
Thanks for the help, I didn't make changes to the bindings, but fixed this by following these steps:

1. Starting the app in play mode in the Unity Editor
2. Opening the Controller Input Binding Menu (SteamVR > Devices > Controller Input Binding)
3. Selecting the [Testing] version of my app
4. Selecting the default binding for the Vive controller
5. Clicking "Use this binding"
