### ISSUE TITLE
Cubes passing through static objects vs cubes that don't

### ISSUE THREAD

**Issue by HansenBerlin** [ValveSoftware/steamvr_unity_plugin#299]
In the interaction demo scene it works fine, also when i copy paste a cube in a new scene (I mean the cubes that dont pass through static objects on the left table and the ones that do on the right table). But I can't figure out what is the difference between them. I checked all elements in the inspector but they seem to be the same. I also don't find anything in the documentation. 
And theres another issue: After copying the cubes to a new scene the throwing gets mesed up. Estimation seems not to work, they drop to the ground right after I release them (works fine in the demo scene). Gravitation settings are not changed.

**Comment by zite** [comment]
Ah I'll make sure to add that to the documentation. The difference is in the Attachment Flags in Throwable. The table on the left has VelocityMovement set.

**Comment by HansenBerlin** [comment]
Cool, great. I wouldnt have found that by myself. I'll try to isolate the weird throwing behaviour on my other scene and update this post. Thanks!
