### ISSUE TITLE
SteamVR_Status accesses SteamVR_Utils.Event, which does not exist

### ISSUE THREAD

**Issue by floAr** [ValveSoftware/steamvr_unity_plugin#3]

**Comment by bddckr** [comment]
The Status script was removed. The Unity Asset Store doesn't remove files on upgrade when an asset removes it. You'll have to delete the SteamVR plugin from your project and then reimport.
There were some reports that people also needed to clear their Asset Store cache and download the plugin again from the store.

**Comment by floAr** [comment]
You are right. I was using the repo but somehow git must have mixed some folder.
