### ISSUE TITLE
Motion not detected in Unity 5.6

### ISSUE THREAD

**Issue by michidk** [ValveSoftware/steamvr_unity_plugin#30]
Hi,

tested with Oculus Rift + Touch and HTC Vive.
In both cases controllers on the SteamVR camera rig are always disabled.  Controllers are still shown in the SteamVR window.

**Comment by michidk** [comment]
Okay. Just found this in the readme:

> * The current beta version of Unity 5.6 breaks the normal operation of the SteamVR_UpdatePoses component (required for tracked controllers).
To work around this in the meantime, you will need to manually add the SteamVR_UpdatePoses component to your main camera.

Latter fixed it

**Comment by bddckr** [comment]
You can also use #14.
