### ISSUE TITLE
Unity build is not running on VIVE HMD 

### ISSUE THREAD

**Issue by pramodnp** [ValveSoftware/steamvr_unity_plugin#300]
SteamVR plugin version ver. 2.0.1
Unity 2018.3.3.1f
Windows 10 
Graphics card Nvidia 1060,

Build an application(.exe) for Intractions_Example am able to the run application on Desktop but the same application is not running on VIVE HMD. I have set up the Player and selected the XR settings and selected the openVR SDK. Please let me know if am missing something so that I can resolve this issue.

Thank you.

**Comment by zite** [comment]
A new version of the SteamVR Unity Plugin was released today (2.2.0) can you upgrade to that and try your build again?

**Comment by kisak-valve** [comment]
Closing pending feedback.
