### ISSUE TITLE
Unity Canvas UI and event system via "point and click" not "reach and touch"?

### ISSUE THREAD

**Issue by sterlingcrispin** [ValveSoftware/steamvr_unity_plugin#301]
Hey I was just noticing this 2.2 release doesn't seem to mention anything about interacting with UI in a laser-pointer style, is this supported or not? What does the laserpointer scene actually do? Can that be easily modified to interact with canvas UI elements? It's a little unclear , https://valvesoftware.github.io/steamvr_unity_plugin/articles/Interaction-System.html#uielement mentions interactivity but is that only with a "reach and touch it" modality? 

thanks!

**Comment by zite** [comment]
The interaction system does currently only support the "reach and touch" style. I'll mark laser pointer UI as a feature request to be considered for a future release.

**Comment by sterlingcrispin** [comment]
@keithbradner thanks! What does the laser pointer do then? Can it process click-like events on colliders its pointed at? Seems like if it could, a solution may be to add box colliders to UI and add another script that handled those laser pointer events and invoked the unity UI events to whatever game object it was attached to

**Comment by DrummerB** [comment]
I'd also like to see a standard first-party implementation of a laser pointer style input module that matched the behavior of the input in SteamVR Home and the SteamVR Dashboard.

There is an MIT licensed VR Input Module [here](https://github.com/wacki/Unity-VRInputModule). [This fork](https://github.com/S1r0hub/Unity-VRPointerVive) seems to be the most up-to-date, with SteamVR 2.0 support. One of these might be a good starting point. 

My only problem with these is that they don't support the same kind of scrolling input like in SteamVR Dashboard (dragging the scroll view with the laser pointer or just pointing at it and scrolling on the touchpad). Currently you have to drag the scroll bar.

**Comment by dariol** [comment]
You can also take a look at VIU (Vive Input Utility) examples (it's cross
platform)
