### ISSUE TITLE
Skeleton Poser drifts out of alignment

### ISSUE THREAD

**Issue by PhantomBadger** [ValveSoftware/steamvr_unity_plugin#305]
The Skeleton Poser when set up with an object doesn't seem to respect the offset to that object, either changing after a few seconds of run time, or being wrong from the start.

You can see an example of the issue, wherein it changes after a few seconds of run-time here (Please ignore the white hands, that is as intended):
https://media.giphy.com/media/5pYoYOIeyRnQeljuF9/giphy.gif

The Poser preview looks like this:
![image](https://user-images.githubusercontent.com/9095972/52067292-3065fb00-2572-11e9-93b6-73a87cdb45b1.png)

Then at runtime, when grabbed with the user's actual hand, it looks like this:
![image](https://user-images.githubusercontent.com/9095972/52067304-39ef6300-2572-11e9-8ef4-67b26d136293.png)

The settings on the screw are as follows:
![image](https://user-images.githubusercontent.com/9095972/52067331-483d7f00-2572-11e9-8da1-5b025fbd75fd.png)

I have tried to following to attempt to isolate the problem;
- Trying a different object (Bog standard 3D Cube)
- Trying default values for all components
- Trying any of the pre-built objects in the provided sample scene
- Trying an empty new scene with only the provided Player prefab and a 3D cube with the above settings.
- Trying a new project with a freshly imported SteamVR and trying out the 'Happy' ball

All of which exhibit the issue, I can assume that the issue is something to do with the hand tracking or pose behaviour class, but I'm unable to find out what triggers that offset to occur.

**Unity Version:** 2018.3.0f2
**SteamVR Plugin Version:** v2.2.0
**SteamVR Version:** 1.2.7

EDIT: Updating to:
**Unity Version:** 2018.3.3f1
**SteamVR Version:** 1.2.10

Still shows the same issues in the following test project (most visible when picking up the Throwable Cubes, you can see that the Index Finger does not align with the edge of the Cube as it does in the Poser):
https://www.dropbox.com/s/t0p09hp8ty7rea7/SVRTest.zip?dl=0

**Comment by 3DMagicVR** [comment]
Hi, I got the same problem here, but in my case it's more notorious, when the interaction occurs, the object has a big offset, positioning over the hand pose, I follow the tutorial from youtube, but no resolve my problem, any chance to know what produce this kind of "bug"?, cheers.

![2019-04-16_2123](https://user-images.githubusercontent.com/34051446/56256372-09f22f00-608e-11e9-9e89-5fb18a116434.png)

**Comment by 3DMagicVR** [comment]
How to solve this problem...
----
@PhantomBadger, In fact it's just related on which transforms your have to move/rotate, this are:

- The main hand root (vr_glove...(clone)).
- The fingers only.

As I can see, if you move the wrist and the fingers without re-positioning the main hand root, just the fingers are posed as you did it, the wrist ignores the new position.

**Comment by tplager** [comment]
@3DMagicVR are you sure that's actually the solution? I am having the same problem and even after multiple tests and changes that solution has not solved the problem. Could you please elaborate? Or @PhantomBadger have you found another solution?

**Comment by MSQStaff** [comment]
I am currently on version v2.3.2 (sdk 1.4.18)  and facing similar problems.
I created a blank Unity project (2019.1.10f1) imported the package and ran the "Interactions_Example" scene. 

When grabbing the grande or one of the balls on the "Interesting Interactables" tables using a regular Vive Controller you can see that there is an offset on the object.

When swiping around with the thump on the touch pad of the controller the whole hand begins to move around in a strange way rather than just the thump itself.

This also happens on poses where all fingers are set to static, where nothing is supposed to happen at all.

**Comment by kimberlysiva** [comment]
We were struggling with this issue as well and finally found fix. In the pose assets that are generated there are checkboxes for "Ignore Root Pose Data" and "Ignore Wrist Pose Data" under each hand. Uncheck these boxes and the root/wrist pose of your cloned hand model will be respected.

**Comment by 3DMagicVR** [comment]
> We were struggling with this issue as well and finally found fix. In the pose assets that are generated there are checkboxes for "Ignore Root Pose Data" and "Ignore Wrist Pose Data" under each hand. Uncheck these boxes and the root/wrist pose of your cloned hand model will be respected.

Thanks, I will check it out when I have a chance, actually I don't have a HTC Vive to see that,, greetings.

**Comment by zite** [comment]
We've had difficulty replicating this issue. If the Ignore root/wrist workaround fixes the issue let us know that may give us a better clue as to the underlying issue.

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by IARI** [comment]
I've had the same issue using
* Unity 2019.3.3f1
* SteamVR 2.5.0 (sdk 1.8.19)
Unchecking Ignore root/wrist as suggested by @kimberlysiva fixed it for me.

**Comment by nrebei2** [comment]
I've also had the same issue, with a temporary fix using @kimberlysiva 's method.
