### ISSUE TITLE
Storefront Flexibility

### ISSUE THREAD

**Issue by jschlechte** [ValveSoftware/steamvr_unity_plugin#306]
Hi! I really enjoy working with this plugin, and I am especially fond of the Interaction System, you have done great work! Thank you!

I would really love to continue using this plugin to its fullest potential, however from a business standpoint it is concerning because there is no clear path for releasing an app on other storefronts (such as Oculus Home). I do realize that there is little business justification for Valve to make this an easy process within this plugin, as it would encourage sales on storefronts/platforms in competition with Steam and SteamVR. **However, lacking a clear migration path to other storefronts makes it harder to justify dedication to this plugin on new projects as the range of available VR devices continues to grow.**

**If the dev team has any thoughts or suggestions on this, please let me know. And once again, great work on this plugin!** 🍻

**Comment by zite** [comment]
Thanks! Glad you're enjoying the plugin.

Valve actually doesn't restrict developers distributing on other platforms and encourages OpenVR use with all headsets. Oculus policies restrict releasing OpenVR based applications on their store. As another example: Viveport is a store separate from Steam that sells OpenVR based applications. So the plugin itself is storefront agnostic, however the policies of stores may be more restrictive.

**Comment by jschlechte** [comment]
Thanks for the quick response and for correcting my incorrect assumptions. I will dig into the policies further!
