### ISSUE TITLE
Tracking Issues only in Unity 5.6

### ISSUE THREAD

**Issue by michidk** [ValveSoftware/steamvr_unity_plugin#31]
The motion controllers/the whole view are jumping up and down. Tested using Oculus Rift + Touch using SteamVR in Unity 5.6 on Windows. 

It has to do with the SteamVR plugin, because if you enable the VR Steam overlay of SteamVR, you can see that the tracking is fine, but in the background you can see the Unity application still bugging.

**Comment by aleiby** [comment]
Are you still seeing this issue?  Do you have any repro steps or simple example scene the demonstrates it?
