### ISSUE TITLE
The Unity package manager failed to automatically install the Open VR package.(only in v2018)

### ISSUE THREAD

**Issue by VivekKalkur** [ValveSoftware/steamvr_unity_plugin#310]
Whenever I try to open the package from GitHub or asset store I get the following message : 

"**The Unity package manager failed to automatically install the Open VR package. Please open the Package manager window and try to install it manually in 2018**". 

I am trying to pull this into a empty project. No other assets. Also, this package works fine with the 5.6 version which I have. What could be causing this issue and what could be the solution?

**Comment by zite** [comment]
This is a Unity Package Manager issue. It's likely due to firewall settings on your computer or somewhere upstream on your network. Can you open the package manager window from the Window Menu?

**Comment by VivekKalkur** [comment]
I go this fixed. It was basically a firewall issue as you told. Now, I have another issue,whenver I try to run my scene with the SSteam VR I am getting this error which was working fine before!!!

"[SteamVR] Error loading action manifest into SteamVR: MismatchedActionManifest
UnityEngine.Debug:LogError(Object)
Valve.VR.SteamVR_Input:IdentifyActionsFile() (at C:/Users/Z00234M/Documents/Unity projects/Test/Assets/SteamVR/Input/SteamVR_Input.cs:121)
Valve.VR.SteamVR:CreateInstance() (at C:/Users/Z00234M/Documents/Unity projects/Test/Assets/SteamVR/Scripts/SteamVR.cs:151)
Valve.VR.SteamVR:Initialize(Boolean) (at C:/Users/Z00234M/Documents/Unity projects/Test/Assets/SteamVR/Scripts/SteamVR.cs:88)
Valve.VR.SteamVR_Behaviour_Pose:OnEnable() (at C:/Users/Z00234M/Documents/Unity projects/Test/Assets/SteamVR/Input/SteamVR_Behaviour_Pose.cs:102)
"

How do I fix this?

**Comment by JustinAtSama** [comment]
![OPENVR](https://user-images.githubusercontent.com/47543833/55035508-643f2900-4fd5-11e9-8e30-77672475bc58.JPG)

1) I get this every time I open the project and play in editor. I dont see any specific Firewall exception to add.
2) I cant seem to use the namespace Valve.VR in any of my scripts I make. I'm pretty much stuck here.
3) Demo scenes can run in with no problems. I can even make a buid and play them as standalone.

**Comment by zite** [comment]
Have you tried opening the package manager UI manually from the window menu?

**Comment by JustinAtSama** [comment]
When I open the package manager manually, OpenVR is not listed in the installed nor not installed. I also can't seem to find any standalone package for OpenVR. Isnt Unity suppose to come with it pre-installed? Btw I only get this prompt with SteamVR2. I downgraded and I nor longer get this window.

**Comment by Hunter-Bobeck** [comment]
@JustinAtSama Did you ever resolve this?

**Comment by upeksha1996** [comment]
I have the same issue :3

**Comment by Matt2468rv** [comment]
I also have the same issue in Unity 2019.3.0f3 and SteamVR 2.5.0

**Comment by cuhde** [comment]
i have the same issue with unity 2020.1.0b5.3485 and SteamVR 2.5.0

**Comment by zite** [comment]
Unity 2020.1+ will need the beta version of the SteamVR Unity Plugin found here: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.6.0b1

They also removed the old VR api, so you may need to read up on XR API: https://docs.unity3d.com/Manual/XR.html
