### ISSUE TITLE
Tracked controllers go to origin on system button press

### ISSUE THREAD

**Issue by jordanvr** [ValveSoftware/steamvr_unity_plugin#313]
I think this is a bug with OpenVR actions but it should probably have a consideration in the SteamVR plugin.

In the newer versions of the SteamVR plugin which use the OpenVR action system, if the system button is pressed on a controller the TrackedDevicePose_t for both controllers from the api will send a blank transform matrix and bDeviceIsConnected and bDeviceIsConnected will both be false. 

I have loaded up the old SteamVR plugin 1.2.3 and the controllers continue to be tracked normally on a system button press. 

A hacky fix I have in place is in the UpdateValue method of SteamVR_Action_Pose to check for either of the above bools before SetCacheVariables() and to make sure changed is then set to false. Something like:

```c#
//(line 580 SteamVR_Action_Pose.cs)
if(poseActionData.pose.bPoseIsValid){
    SetCacheVariables();
    changed = GetChanged();
}else{
    changed = false;
}
```

Of course there needs to be a fix in OpenVR, but this could potentially be useful for controller disconnections sending in-game objects flying around.

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
