### ISSUE TITLE
No trigger action  assigned

### ISSUE THREAD

**Issue by MomoVCHH** [ValveSoftware/steamvr_unity_plugin#314]
Hi, i always get this message. The Unity progam can not work.  How can i fix this propblem? please help
I didn't get this problem with steamvr 2.1 version. 

Please see below error message. 
----------------------------------------------------------
No trigger action assigned
UnityEngine.Debug:LogError(Object)
VRUiKits.Utils.LaserInputModule:NewMethod() (at Assets/UIKits/Demo/Laser/Scripts/LaserInputModule.cs:123)
VRUiKits.Utils.LaserInputModule:Start() (at Assets/UIKits/Demo/Laser/Scripts/LaserInputModule.cs:115)

**Comment by zite** [comment]
You'll need to assign an action to the laser input module component. You may need to regenerate actions. For general steamvr input documentation see our documentation page here: https://valvesoftware.github.io/steamvr_unity_plugin/articles/SteamVR-Input.html

**Comment by MomoVCHH** [comment]
Thank!

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
