### ISSUE TITLE
I can't make variable in SteamVR Plugin script

### ISSUE THREAD

**Issue by byelove** [ValveSoftware/steamvr_unity_plugin#316]
Hello 

I'm using Unity 2017,4,2 (LTS) version.

I dowloaded SteamVR Plugin 2.2.0

I wnat to custom class type variable in Hand script ( Hand.cs exist in the SteamVR > InteractionSystem > Core > Scripts)

But It ocurred error CS0246 : The type or namespace name 'CustomHandController' could not be found ( are you missing a using directive or an assembly reference?)

And I tried to make new script which copy Hand.cs.

I copied Hand.cs script and pasted it to the NewHand.cs

And then I tried to make CustomHandController type variable in the NewHand class.

It worked fine. 

I found that I could not create a class-type variable for scripts created outside of SteamVR folder in the scripts within the SteamVR folder.

How can I solve this problem?

Please help

**Comment by zite** [comment]
Unfortunately this is one of the effects of using unity's new assembly definition files. They increase compile speed but have sort of weird effects. If you want you can search your project for them and delete them, but if you're going to modify the interaction system I'd recommend moving it out of the SteamVR folder into it's own folder so when you upgrade the plugin your changes don't get overwritten.

For reference the assembly definition files are located here:
/Assets/SteamVR/SteamVR.asmdef
/Assets/SteamVR/Editor/SteamVR_Editor.asmdef
/Assets/SteamVR/Input/Editor/SteamVR_Input_Editor.asmdef
/Assets/SteamVR/WindowsHelper/SteamVR_Windows_EditorHelper.asmdef
