### ISSUE TITLE
SteamVR_Behaviour_Pose.GetVelocity() always outputs in world axis

### ISSUE THREAD

**Issue by db-mew** [ValveSoftware/steamvr_unity_plugin#317]
If you rotate the [CameraRig] which has the playspace, everything else seems to work normally in terms of position and orientation of controllers and the HMD. But the GetVelocity() you get from SteamVR_Behaviour_Pose will still output values in the original (0, 0, 0) axis.

Using Transform.TransformDirection will align it again.

If this is intended, nevermind!

**Comment by zite** [comment]
Hm this does seem like an issue, we'll look into it.
