### ISSUE TITLE
Knuckles DV Joystick input is wonky 

### ISSUE THREAD

**Issue by AndersMalmgren** [ValveSoftware/steamvr_unity_plugin#320]
I noticed something new yesterday. The Knuckles DV joystick Vector2 input is wonky. It does not always report the correct Vector2 state to the game. Works fine for Vive Wands.

**Comment by zite** [comment]
I'm not really clear on what you mean. What kind of wrong information is it reporting? Zeros, opposite directions, etc?

**Comment by AndersMalmgren** [comment]
Its like it's have a deadzone but it's completely random. There are no reports on the Knuckles DV have a hardware problem or similar? Though it feels more like a software problem. I will check the input debugger tonight.
