### ISSUE TITLE
GetStateUp not working

### ISSUE THREAD

**Issue by ai281918** [ValveSoftware/steamvr_unity_plugin#321]
Hello, 

The return value of GetStateUp is always as same as GetStateDown. Should the function call in 1033 line in SteamVR_input.cs must be modified into GetStateUp?

![image](https://user-images.githubusercontent.com/9144769/52761056-dcb4e080-304c-11e9-8d7b-c2cc01728174.png)

**Comment by zite** [comment]
Ack, good catch! Sorry about that, we'll get that fixed in the next version.

**Comment by zite** [comment]
Thanks again. Released version 2.3.2 with this fix.
