### ISSUE TITLE
Hand using Handheld Vive trackers

### ISSUE THREAD

**Issue by CarlosMeloStuff** [ValveSoftware/steamvr_unity_plugin#322]
Hi @zite 

I was wondering if you could explain to me how I could use the SteamVR player prefab and have the hands working but using trackers instead of the controllers. I have my trackers set to handheld right hand and handheld left hand, so they do get linked to the LefHand and RightHand game objects but, the Hand script doesn't instantiate the hand models with the poses.

What I am trying to do is to be able to see the hands and then make them blend poses when hovering over objects. I have a custom made controller that also uses trackers but I want players to be able to see their hands as they need to be able to see where to hold the objects with both hands. I would set it up with two holding positions.

I imagine that if it was possible to use trackers as hands and we could blend the grab position on some objects it can be useful on virtual objects that could be moved but don't need to be picked up, like twisting doorknobs to open a door, pushing buttons or pulling levers. The hand would blend to a grab pose and the object would snap to the hand while the hand is inside a trigger, and then when you move the hand out of the trigger the hand would let go of the object and blend back to an idle pose.﻿

Thanks

**Comment by zite** [comment]
The Interaction System is really meant to work with the underlying SteamVR Skeleton system which estimates finger positions based on button presses. So this isn't really a supported scenario. 

But if you like you could go into Assets/SteamVR/InteractionSystem/Core/Scripts/RenderModel.cs and delete line 68. After that you may need to remove some active and activeBinding checks elsewhere to get the hand to display without the underlying data. Good luck!

**Comment by CarlosMeloStuff** [comment]
No worries, thanks for the clarification :)
