### ISSUE TITLE
I saw the Unity scene Inverted in my HTC Vive Headset 

### ISSUE THREAD

**Issue by castana1962** [ValveSoftware/steamvr_unity_plugin#327]
Hi All
I am confusing myself because I am trying the SteamVR plugin 2.2.0 and Unity 2019.1 alpha version with this Lightweight Render Pipeline Boat Demo more info here https://www.youtube.com/watch?v=8ancNOmt4pA.
My problem is that that when I added the Player or Camera Rig Prefab to it, I saw the Unity Scene Ok in the Editor Game tab but I saw this scene inverted in my HTC Vive Headset.
I did a new scene of this and added only the their Environment and the Steam VR plugin to it again and I have the same problem, to be honest I do not know what is the problem but I guess that the problem can be with Unity 2019 alpha version or Steam VR plugin 2.2.0 version, for it, Could anybody advice me to fix it?
Thanks for your time

**Comment by zite** [comment]
I don't think this is a steamvr plugin issue since we're using the standard unity camera in our prefabs. Sounds like a unity xr issue to me.

**Comment by castana1962** [comment]
Hi, 
So I will post the topic in Unity forum, 
Thanks
Best Regards
Alejandro

**Comment by castana1962** [comment]
Hi All
This problem was fixed with the 2019.1.0b10 version. I added the CameraRig prefab and I can the scene successfully( Thanks to Bugs Unity people.....)
Hope this help !!!
Regards
Alejandro
