### ISSUE TITLE
Cant seem to change Speed of VelocityBased movement of items held in hand.

### ISSUE THREAD

**Issue by SteenPetersen** [ValveSoftware/steamvr_unity_plugin#330]
I have been dealing with this issue for a few days now and cannot seem to find a solution:

I illustrate the problem here in [this](http://www.pixlrelm.com/twitter_Stuff/lagSwing.gif) gif

I am making no assumptions here and am looking for anyone familar with thisd problem that can assist me with trying to speed up the rate at which the sword in that gif would swing to catch up with the hand. I have previously asked this question on unityAnswers and made the assumption that one of the methods in Hand.cs was the culprit but im beginning to doubt that assessment.

I was under the impression that I could simply change or accelarate the values here (Hand.cs line 1212):

```
        protected const float MaxVelocityChange = 10f;
        protected const float VelocityMagic = 6000f;
        protected const float AngularVelocityMagic = 50f;
        protected const float MaxAngularVelocityChange = 20f;

        protected void UpdateAttachedVelocity(AttachedObject attachedObjectInfo)
        {
            Vector3 velocityTarget, angularTarget;
            bool success = GetUpdatedAttachedVelocities(attachedObjectInfo, out velocityTarget, out angularTarget);
            if (success)
            {
                float scale = SteamVR_Utils.GetLossyScale(currentAttachedObjectInfo.Value.handAttachmentPointTransform);
                float maxAngularVelocityChange = MaxAngularVelocityChange * scale;
                float maxVelocityChange = MaxVelocityChange * scale;

                attachedObjectInfo.attachedRigidbody.velocity = Vector3.MoveTowards(attachedObjectInfo.attachedRigidbody.velocity, velocityTarget, maxVelocityChange);
                attachedObjectInfo.attachedRigidbody.angularVelocity = Vector3.MoveTowards(attachedObjectInfo.attachedRigidbody.angularVelocity, angularTarget, maxAngularVelocityChange);

            }
        }
```

but that does seem to be the case. If this is the wrong place to ask these things please let me know where I should go to find the experts on SteamVR development.

**Comment by zite** [comment]
You may need to unlock the rigidbody's speed limits. Increasing maxAngularVelocity or maxVelocity. Throwable does this a bit. If you're using that script you can increase that number or if you're not then you may need to do that in your own script.
 https://github.com/ValveSoftware/steamvr_unity_plugin/blob/master/Assets/SteamVR/InteractionSystem/Core/Scripts/Throwable.cs#L70

**Comment by SteenPetersen** [comment]
Perfect this was it, was very confused by the fact that there was all those variables to change velocities yet the upper limits are hidden by the actual rigidbodies constraints. Personally I put in a comment to remind me of this, I suggest the same be done in the next build.

`/// Variables affecting the rigidbody, upper limits may be limited `
`/// by the rigidbody.maxAngularVelocity`

Thank you so much for looking into this.

**Comment by zite** [comment]
Sounds like a good thing to add. Will do.
