### ISSUE TITLE
Skeleton pose blending defaults not working properly with Vive wands

### ISSUE THREAD

**Issue by Wyattari** [ValveSoftware/steamvr_unity_plugin#333]
In a fresh project out of the box in the interaction example scene with Vive wands the pose animations are broken when going to/from the controller to grab poses. [here's a video.](https://giant.gfycat.com/AntiqueCloseDore.webm)

**Comment by KellanHiggins** [comment]
I have this problem as well. I've noticed the left hand is giving the biggest problems. The right hand is fine most of the time.

It has also stopped me from being able to pose custom hands. I've tried but I get super warped messd up hands when I set it to anything but static.

**Comment by zite** [comment]
I believe this should be fixed in the recent beta: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.3b1

**Comment by kisak-valve** [comment]
Closing per the last comment.
