### ISSUE TITLE
SteamVR conflicts with UnityEngine.AnimationCurve:Evaluate

### ISSUE THREAD

**Issue by AndersMalmgren** [ValveSoftware/steamvr_unity_plugin#334]
> Assertion failed: Assertion failed on expression: 'curveT >= GetRange().first && curveT <= GetRange().second'
> UnityEngine.AnimationCurve:Evaluate(Single)

I get this error when ever I bring up the SteamVR overlay

**Comment by AndersMalmgren** [comment]
More examples of the same

> Assertion failed: Assertion failed on expression: 'CompareApproximately(det, 1.0F, .005f)'
> UnityEngine.Quaternion:LookRotation(Vector3, Vector3)

**Comment by AndersMalmgren** [comment]
haha, this one was hard to find. Its actually that this method is removed, forgot about it

SteamVR_Render.instance.pauseGameWhenDashboardIsVisible = false;

So the game is paused when you bring up the dashboard. Which set deltaTime to 0 which gives devided by  zero problem.  :D So. How Can I get pauseGameWhenDashboardIsVisible in SteamVR 2?

**Comment by AndersMalmgren** [comment]
`SteamVR.settings.pauseGameWhenDashboardVisible = false;`

**Comment by zite** [comment]
Sounds like you found the setting. Let me know if I closed this in error.
