### ISSUE TITLE
SteamVR_Actions gone in 2018.3.6

### ISSUE THREAD

**Issue by AndersMalmgren** [ValveSoftware/steamvr_unity_plugin#335]
We have started the work to migrate from 2017.4.21 to 2018.3.6. 
We are now on  .NET 4.x runtime and 4.x API compatible level

Even after save and generate actions I get

![image](https://user-images.githubusercontent.com/817577/53299351-f3bbb580-3838-11e9-9fa9-680b86bd09b9.png)

**Comment by bddckr** [comment]
I didn't test 2018.3.6 myself yet but I wonder if this is a regression. Unity did try to fix some stuff in .3.5 regarding assembly definition files and the compilation process.

Do you have any other compilation errors? If so fix them, if not try reimporting one of the SteamVR plugin files manually (in the project panel right-click > reimport).

If this doesn't help I suggest re-importing all of SteamVR and ultimately trying to delete the `Library` folder in the root of your project - this will reimport everything, though, so beware of a long wait time there!!!

---

_I'm assuming you're using the latest SteamVR plugin version._

**Comment by AndersMalmgren** [comment]
I only have SteamVR errors at this time, but I think its because those errors blocks the rest from compiling. Will probably have more errors once its done. 

This is a clean UNity project with a new library for 2018.3.6 (We use git so I forked our master branch and cloned a fresh folder)

**Comment by AndersMalmgren** [comment]
I deleted SteamVR_Input folder, reimport SteamVR folder and then save and generate actions. That did the trick!

**Comment by wadams201** [comment]
I'm having the same issue (with multiple versions of Unity - 2018.3.5 and 2018.3.6) and the fix Anders used hasn't worked for me

**Comment by zite** [comment]
@wadams201 can you post your own issue for this? It sounds like Anders issue has been resolved and yours is different.
