### ISSUE TITLE
Allow changing render model at runtime

### ISSUE THREAD

**Issue by DrummerB** [ValveSoftware/steamvr_unity_plugin#339]
Currently, changing `SteamVR_RenderModel.modelOverride` at runtime is not allowed. Sometimes it would be useful to be able to load a render model without a direct association with a tracked device.

For instance, in a tutorial, it would be nice to be able to easily load a second copy of the controller, put it in front of the player and play some animation that demonstrates some kind of interaction.

This would also make it easier to sync the controllers in a multiplayer game. You would just need to sync the name of the controller model of each player and have the render model component automatically load the meshes.

**Comment by zite** [comment]
This is outside the scope of that component, I'd recommend creating your own based on the code from SteamVR_RenderModel
