### ISSUE TITLE
The plugin can't be built for the Windows Universal target

### ISSUE THREAD

**Issue by demonixis** [ValveSoftware/steamvr_unity_plugin#34]
Hi,

The plugin can't be built for the Windows Universal target. I know that this plugin will not work on that target, but a game can be built for SteamVR on Linux, for Oculus home and for Windows Mixed Reality. The Windows Universal API doesn't support some methods. We can fix that by two methods

- Using defines `#if !UNITY_METRO` to block the code that doesn't compile
- Refactor the code to be compatible

If you want SteamVR on Windows Universal, it's a good idea to start a refactor, however the first point is better and faster if don't. I can submit a pull request with these changes. However there are some changes to do in Steamvr_api.cs and I don't have the hands on it.

This is all errors returned by Unity when trying to build for Windows Store

![image](https://cloud.githubusercontent.com/assets/1017126/26052171/dac2676a-3964-11e7-868a-3c6df239ec33.png)

I fixed all of these with simple `#if !UNITY_METRO`

**Comment by aleiby** [comment]
Can you provide more specifics for how to reproduce these errors?  I installed the Windows Store target in Unity 2017.1.0b9, but it seems to compile and run fine in editor.  The Build and Build & Run options are greyed out for me - maybe because I'm testing on Win7?

**Comment by demonixis** [comment]
Hi,

You have to install Windows 8.1 or 10 to be able to deploy to Windows Store. The plugin is fine in the editor but fails to compile in builds.
Windows Stores apps uses the native .Net runtime, so some APIs are not present. By example, you can't use DLLImport, which is the main cause of error when compiling the OpenVR.
I can send you a patched version of the API, if you want to see what has changed.

**Comment by aleiby** [comment]
I did a pass on this for the next release.  The changes to openvr_api.cs likely won't make it into this version however.
