### ISSUE TITLE
Render model meshes are mirrored along the Z axis

### ISSUE THREAD

**Issue by DrummerB** [ValveSoftware/steamvr_unity_plugin#341]
What is the reason for mirroring the render models along the Z axis when loading their mesh?
The mirroring happens at [SteamVR_RenderModel.cs:372](https://github.com/ValveSoftware/steamvr_unity_plugin/blob/7e957350fe84e2ab663b77382b9912c33353815e/Assets/SteamVR/Scripts/SteamVR_RenderModel.cs#L372).

If you load the same mesh normally, by importing the render model obj files into the project, the model will appear mirrored along the Z axis, compared to how it is loaded by SteamVR. This makes it more convoluted to manually load a render model and try to sync it's position and rotation in a multiplayer game.

If the reason for the mirroring is, that the forward vector of the mesh doesn't match the forward vector of Unity, wouldn't this better be solved by rotating or parenting the mesh and not modifying it?

This is related to #339. Since loading render models without an associated tracked device doesn't seem to be allowed (apart from reimplementing half of SteamVR_RenderModel), I need to manually import and load a controller model to display the controllers of other connected players.

**Comment by zite** [comment]
It's a matter of different engines having different coordinate systems. Somebody's got to flip the coordinates, in this case it's Unity unfortunately.
