### ISSUE TITLE
Bindings not included in build

### ISSUE THREAD

**Issue by wadams201** [ValveSoftware/steamvr_unity_plugin#343]
I'm using the v2.2.0 version of the plugin (the git one, not the unity asset store one which seems to be different,) and I'm using unity 18.3.6. When I run out of the editor, my bindings are fine, but when I build, the steam window pops up and tells me that bindings aren't set.

**Comment by kosma822** [comment]
Same problem here

**Comment by finnusmagic** [comment]
Usually you have to open the binding UI and set your bindings as default. 
In Unity open:
->Window
-> SteamVR Input
-> Open binding UI
-> Select the Binding you made
-> Replace default binding
-> Save and generate

However, this used to work for me. But right now my issue is, that it is not working anymore. It's either a bug, or I'm missing something else.

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
