### ISSUE TITLE
Adding a forward-slash (/) in an action name causes issues

### ISSUE THREAD

**Issue by PeturDarriPeturs** [ValveSoftware/steamvr_unity_plugin#345]
Tested on v2.2.0.

If you type a forward-slash in an action's name in the SteamVR Input window, the console gets filled with errors, the SteamVR Input window becomes unresponsive and Unity has to be restarted to fix it.

I didn't need a forward-slash in the action name, just wanted to see what would happen. If the fix is automatically removing slashes from the name, that's fine by me.

**Comment by zite** [comment]
That's probably the fix we'll do. Thanks for the report.

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
