### ISSUE TITLE
Can I set origin of the SteamVR CameraRig to an absolute position via scirpt?

### ISSUE THREAD

**Issue by schwarzmalerei** [ValveSoftware/steamvr_unity_plugin#346]
I'm creating a multiplayer game for the HTC Vive using the SteamVR Plugin and Unity. Since the game is supposed to be played local I obviously came to have some troubles with the positions. As far as I came to understand the recent position of the headset represents the origin of the scene when played. So since I have two headsets in one play area I also have two different origins for each of the game instances, which means that the player position you can see on your own device is different from where the other person is actually standing. Any ideas on how to deal with that?

**Comment by zite** [comment]
This sounds like more of a conceptual VR development problem rather than a bug with the steamvr unity plugin. I'd recommend this forum here: https://steamcommunity.com/app/250820/discussions/7/
