### ISSUE TITLE
SteamVR_Actions gone

### ISSUE THREAD

**Issue by wadams201** [ValveSoftware/steamvr_unity_plugin#348]
I was having an issue with a steamVR_Actions class after using the unity store to download the steamVR asset, however I was able to fix the issue by using the one available here on github instead.

**Comment by zite** [comment]
Do you know what the difference was? Does the one you're using now have assembly definition files?

**Comment by wadams201** [comment]
I'm not sure what the difference was, but the one I'm using now does have assembly definition files
