### ISSUE TITLE
SteamVR_UpdatePoses script still required in Unity's 5.6 Release

### ISSUE THREAD

**Issue by LordNed** [ValveSoftware/steamvr_unity_plugin#35]
Unity has officially released Unity 5.6 (and 5.6.1!) and it is no longer in beta. However, it still requires you to add the SteamVR_UpdatePoses script to the main camera. 

This has officially been classified as [Won't Fix by the Unity Team](https://issuetracker.unity3d.com/issues/vr-slash-regression-vive-controllers-are-not-activated-and-do-not-function-in-scenes-with-steamvr-camera-rig) so it is probably time to merge Pull Request #14 so that people do not need to continue to use a workaround to have this work out of the box with the latest version of Unity.

Thanks!

**Comment by kisak-valve** [comment]
Hello @LordNed, discussion of #14 should be made on the pull request, not in a separate issue report. I've gone ahead and copied you post. Closing.
