### ISSUE TITLE
Controls don't show up for new input system 

### ISSUE THREAD

**Issue by chilton** [ValveSoftware/steamvr_unity_plugin#350]
I've done some pretty exhaustive testing on this issue, as I've had it off and on for almost a month. It boils down to this: occasionally, the hand controllers don't work in the app, but work just fine in the settings screen, home screen, etc.

Furthermore, they work just fine in older builds of my app, which used Unity 2018.2 and the old SteamVR plugin. It's only on builds based in 2018.3 with the current plugin that it fails.

Attached are screenshots and log files. I was able to confirm that this happens for all builds back to roughly the beginning of December when I updated the Steam VR plugin for Unity, for my builds. 

The bug, however, only started sometime roughly in the last 1.5 months. Also, I have knuckles, and it happens on those as well. And it happens on Windows and MacOS (though not at the same time, which I think rules out any hardware issues with the HMD). 

These screenshots show the errors that are thrown in the editor. This is with a new copy of the plugin and the latest non-beta version of Unity, and absolutely nothing else. I rebuilt the inputs, as per the instructions, then ran the sample code. 

![screen shot 2019-03-07 at 10 41 32 pm](https://user-images.githubusercontent.com/4139553/54008726-8c9ddb00-412d-11e9-95cb-ac6793e24a7a.png)
![screen shot 2019-03-07 at 10 47 01 pm](https://user-images.githubusercontent.com/4139553/54008727-8c9ddb00-412d-11e9-9eb2-e077228cab3c.png)
![screen shot 2019-03-07 at 10 47 20 pm](https://user-images.githubusercontent.com/4139553/54008728-8d367180-412d-11e9-8110-f0b9a85c314f.png)

It's probably important to note that this is sporadic, and occasionally works. I don't know why. But when it fails, it fails for all apps built with the new plugin. So I assume this is something happening at the SteamVR level. 

I'll update this as I do more testing. Suggestions welcome and encouraged--this has been holding up a new release of Glycon for almost a month now.

**Comment by chilton** [comment]
I tried uninstalling the game via the Uninstall command in Steam, and reinstalling it. That did nothing. But I also noticed that the underlying files did not disappear after Steam said it had uninstalled them. It did not say the room was incorrect. I thought that was odd. 

So I went to the downloads section, I think, and dug down to the actual tool, then uninstalled it from there. Then I reinstalled it, and it told me my room setup was invalid. So I re-ran the room setup, and now the hand controllers work properly. 

The issue appears to be in SteamVR, and not in the Unity plugin itself. And this does happen on my Windows 10 system as well as my Mac, so until it's solved, I'm going to just tell people to completely uninstall and reinstall SteamVR. That appears to be the only working solution at this time.

If I figure out more about what is causing this, I'll append this note.

**Comment by zite** [comment]
The unity plugin hasn't been tested on mac in a while. Are you getting the same errors on windows?

**Comment by chilton** [comment]
Yes. It started on Windows.

**Comment by chilton** [comment]
And the frustrating thing is that it *sometimes* does work. I have no idea why or how that's even possible.
