### ISSUE TITLE
Interactable : OnDestroy() generating Null Reference Exception

### ISSUE THREAD

**Issue by Raphael-Os** [ValveSoftware/steamvr_unity_plugin#351]
In Unity 2017.4.21f, with SteamVR 2.2.0.

When I try do destroy the Component "Interactable" on a gameObject inside a running Script, it show in the console :

```
NullReferenceException: Object reference not set to an instance of an object
Valve.VR.InteractionSystem.Interactable.OnDestroy () (at Assets/SteamVR/InteractionSystem/Core/Scripts/Interactable.cs:326)
```

[The code](https://github.com/ValveSoftware/steamvr_unity_plugin/blob/c3db99b1e28e2eecbd92ca0e952706b6a3fa2b1c/Assets/SteamVR/InteractionSystem/Core/Scripts/Interactable.cs#L325-L326) generating the error is 

```
attachedToHand.DetachObject(this.gameObject, false);
attachedToHand.skeleton.BlendToSkeleton(0.1f);
```

One solution could be to reverse the lines
```
attachedToHand.skeleton.BlendToSkeleton(0.1f);
attachedToHand.DetachObject(this.gameObject, false);
```

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
