### ISSUE TITLE
Best approach with asset bundles

### ISSUE THREAD

**Issue by roelkok** [ValveSoftware/steamvr_unity_plugin#353]
I have a Unity component that has a SteamVR action as property. This script works fine in the normal situation. However I'm having problems when placing the object with this script in a scene that is loaded through an Unity asset bundle.

I have a basic scene with the SteamVR player prefab. In this scene I load another scene as '_additive'_. This other scene is loaded through an asset bundle and has the object with my script.
The problem is that the actions get duplicated between the first scene with the player and the second one with the script because of Unity's dependency management for asset bundles. Ie. Unity sees the actions as a dependency of the second and includes a copy in the asset bundle. The actions in the first scene get initialized, but since script in the second scene actually refers to a duplicate of the action, that script doesn't work anymore because it doesn't refer to an initialized action.

I tried adding the actions to an asset bundle (that way the first scene and the second one should refer to the same actions), but then I have problems with instantiating the player prefab.
I also tried adding the player prefab to the asset bundle instead and then load a scene from that asset bundle with the player, but that also didn't work for me.

So I'm a bit lost on how to work with SteamVR actions in combination with asset bundles. Are there any guides on this?

**Comment by zite** [comment]
Unfortunately this isn't an issue we've tested, you seem to be the first! As an immediate solution you could try loading the actions through code to get around unity recognizing them as dependencies. You can do this through a number of static functions in the SteamVR_Input class. GetAction to get by name, or GetActionFromPath to get by the full path.

**Comment by roelkok** [comment]
Thanks for pointing me in the direction of GetActionFromPath. That will do as a work around for now.
