### ISSUE TITLE
Tracking and Input completely broken in released Steam app. Reverting to older version in Steamworks does not fix the problem!

### ISSUE THREAD

**Issue by EntroPiGames** [ValveSoftware/steamvr_unity_plugin#354]
I released a new version of my SteamVR app (642770) today, but when launching this new version from Steam, the SteamVR controller binding panel shows the message “The action manifest for XXX was not found” and as a result all tracking and input is broken. I’ve checked and all the json files are in the install directory. 

The output log is spammed with the following messages (for all actions):

[SteamVR] GetDigitalActionData error (/actions/default/in/GrabPinch): NoData handle: 1152969591060693192

and

[SteamVR] GetPoseActionData error (/actions/default/in/SkeletonRightHand): NoData Handle: 1152969591060693196. Input source: Any

Other users have also reported the exact same problem. 

Most worryingly **this problem persists when I revert the SteamPipe branch to an older version** which was working fine before, so this tends me to believe this is an issue with Steam or the SteamVR app. When I launch the same build from outside of the Steam client, everything works as expected.

Any help in resolving this issue would be greatly appreciated, since my application is now broken and there’s no way I can fix it!

Versions:
- SteamVR Unity Plugin v 2.2.0
- Unity 2014.1.18f1

**Comment by EntroPiGames** [comment]
Maybe also import to mention, I tested this new version on a beta branch before moving it to the default one. 

Everything was working fine when I tested it on the beta branch, so it seems like moving it to the default branch is what caused the issues.

I remember reading about a similar issue in the SteamVR release notes a couple of months ago, so I figured it might be related.

**Comment by EntroPiGames** [comment]
I remember I also published some changes to the App Data in Steamworks, so I had a look at what was changed.

Looks like this string was added to the common section:
`"openvr_action_manifest_path"	""`

There's no way to set this path, but my guess is that this is what is causing the issue.

**Comment by zulubo** [comment]
You can change that string (I think it's the same one) in Application/Virtual Reality in your steamworks app admin settings. Have you tried that? It's set to actions.json by default

**Comment by EntroPiGames** [comment]
> 
> 
> You can change that string (I think it's the same one) in Application/Virtual Reality in your steamworks app admin settings. Have you tried that? It's set to actions.json by default

I don't have this option in either Application/Virtual Reality, or Store/Basic Info/Virtual Reality.

Maybe it's because my project is configured as an application and not a game?

**Comment by EntroPiGames** [comment]
I've searched through every setting on both the Steamworks App and Store admin pages, and can't find anywhere to set it.

**Comment by zite** [comment]
![image](https://user-images.githubusercontent.com/198704/54169222-0afcc480-442f-11e9-871e-e33cdaa286c8.png)

Do you see this checkbox at the bottom of your Application/Virtual Reality settings? When you check it you should see the textbox to change the value.

**Comment by EntroPiGames** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/198704/54169222-0afcc480-442f-11e9-871e-e33cdaa286c8.png)
> 
> Do you see this checkbox at the bottom of your Application/Virtual Reality settings? When you check it you should see the textbox to change the value.

No, it is missing. 

Here's a screenshot of what my VR settings page looks like in Steamworks:

![SteamworksVRSettings](https://user-images.githubusercontent.com/45169553/54169892-f17e6b80-4474-11e9-9e77-e2250c884e64.png)

**Comment by EntroPiGames** [comment]
I noticed the description in the image you posted says 

> **Games** using the SteamVR input system...

Could the SteamVR Input section be missing from my Steamworks VR settings, because **my app is configured as an application**, and not a game, in Steam?

**Comment by mkultra333** [comment]
I got the same issue, my app is a game and I'm not using Unity.  Game should be using legacy VR controls but because of the bad "openvr_action_manifest_path" key that is missing any option to fix, the game is trying to load an action manifest that has no name.

**Comment by zite** [comment]
Thanks, and I apologize. What I showed was an internal setting. I'll investigate and get back to you both.

**Comment by EntroPiGames** [comment]
A user on the [Steamworks Development forums](https://steamcommunity.com/groups/steamworks/discussions/0/1836811737991032581/?tscn=1552410087#c1836811737993480682) came up with a way to set the value using an Ajax Request (in the web console) from the VR settings page:

> var appId = 1234;
> AppsAjaxRequest(
> 				g_szBaseURL + '/apps/setvrdata/' + appId,
> 				{
> 					'openvr' : $('vr_sdk_openvr').checked ? 1 : 0,
> 					'othervr' : $('vr_sdk_othervr').checked ? 1 : 0,
> 					'othervr_rift_13' : $('vr_sdk_othervr_rift13').checked ? 1 : 0,
> 										'cont_steamvr' : $('vr_controller_steamvr').checked ? 1 : 0,
> 					'action_manifest_path' : 'actions.json',
> 					'cont_oculus' : $('vr_controller_oculus').checked ? 1 : 0,
> 					'cont_xinput' : $('vr_controller_xinput').checked ? 1 : 0,
> 					'cont_kbm' :  $('vr_controller_kbm').checked ? 1 : 0,
> 					'playarea_seated' : $('vr_playarea_seated').checked ? 1 : 0,
> 					'playarea_standing' : $('vr_playarea_standing').checked ? 1 : 0,
> 					'playarea_roomscale_width' : $('vr_playarea_roomscale_width').value,
> 					'playarea_roomscale_depth' : $('vr_playarea_roomscale_depth').value,
> 					'playarea_360_required' : $('vr_playarea_360_required').checked ? 1 : 0,
> 					'vrheadset_streaming' : ( $J('input[name=vrheadset_streaming]:checked').attr('id') == 'vrheadset_streaming_hmdview' ) ? 1 : 0,
> 									},
> 				function ( results )
> 				{
> 					if ( results[ 'success' ] )
> 					{
> 						// no error, reload page
> 						$('AjaxOutput').innerHTML = 'Reloading...';
> 						RefreshCallback( results );
> 					}
> 					else
> 					{
> 						$('AjaxOutput').innerHTML = "<span style='color:red'>" + results.message + "</span>";
> 					}
> 				}
> 			);


This has fixed the issue for now, but a proper fix would still be highly appreciated.

**Comment by jonpile** [comment]
The Steamworks site has been updated with a fix for this issue, and I've gone through and updated all games that were inadvertently affected. Thanks for the report!

**Comment by flightCrazed** [comment]
I am having this same exact problem, do you guys have any other info on this?

I did enter this into "This game uses the SteamVR Input system and an action manifest file. Enter the path to your action manifest file, relative to your game install directory"
GameNameVR_Data\StreamingAssets\SteamVR

Also tried using GameNameVR_Data\StreamingAssets\SteamVR\Actions.json

nothing worked.
