### ISSUE TITLE
unity 2018.x SteamVR 2.2.0 Input Action Set crashes if more than one set added

### ISSUE THREAD

**Issue by HawkenKing** [ValveSoftware/steamvr_unity_plugin#355]
When I added a new action set "newset", and a test action "testaction", everything was OK. If I add another new action set "newset2", and a testaction "testaction" or "testaction2" (in addition to default, buggy, platformer, mixedreality & newset), I get a lot of errors like this:

```
ArgumentException: An element with the same key already exists in the dictionary.
System.Collections.Generic.Dictionary`2[System.String,Valve.VR.SteamVR_Action].Add (System.String key, Valve.VR.SteamVR_Action value) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:404)
Valve.VR.SteamVR_Input.PreinitializeActionDictionaries () (at Assets/SteamVR/Input/SteamVR_Input.cs:226)
Valve.VR.SteamVR_Actions.PreInitialize () (at Assets/SteamVR_Input/SteamVR_Input_Initialization.cs:26)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
Valve.VR.SteamVR_Input.FindPreinitializeMethod () (at Assets/SteamVR/Input/SteamVR_Input.cs:134)
Valve.VR.SteamVR_Input..cctor () (at Assets/SteamVR/Input/SteamVR_Input.cs:114)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for Valve.VR.SteamVR_Input
Valve.VR.InteractionSystem.Sample.SquishyToy..ctor () (at Assets/SteamVR/InteractionSystem/Samples/Squishy/SquishyToy.cs:16)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:295)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:288)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:255)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

SteamVR Input window no longer renders.

I've tried a few variations on this and sometimes it creates duplicate actions, then I get an error saying the action exists, if I remove the duplicate action and hit save and generate, the above error happens with item instead of element.

` An item with the same key has already been added.`

After either error the console fills with errors and the scene can't be run.

the issue is apparent in 2018.2 and 2018.3

2017 LTS was ok.

using SteamVR 2.2.0

In SteamVR 2.0.1 it seems to fail more gracefully if two actions share the same name in actionsets, the actionset with the initial duplicate action name will get two actions of the same name.

Attempting to call the offending action in the other actionset "testaction2" (numeral) will only rename the new duplicate in the previous actionset.

Can we have actionsets with action names that are used in other actionsets? I'd like to use this system in the same way as driving the buggy uses a different actionset, but with same action names.

For example; "motorbike" and "car" actionsets can't have actions in both sets called "Throttle" & "Brake" as this causes errors like above. (in Unity 2018.x)

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
