### ISSUE TITLE
Access to Room view (tron mode)

### ISSUE THREAD

**Issue by jbaessens** [ValveSoftware/steamvr_unity_plugin#357]
Hi,

I have read and try code of this article on unity's blog 
https://blogs.unity3d.com/2017/06/16/codesnippets-toggle-vives-front-facing-camera-and-tron-mode-at-run-time/

And I want to do exactly the same thing but it seems to don't work in Unity 2017.3.1.  with SteamVR 2.2. This code does absolutely nothing. And I really want to avoid to double click on the vive controller to activate this mode. Is there any other way? Anyone with some experience on that? :-)

```
EVRSettingsError SetTronMode(bool enable)
{
    EVRSettingsError e = EVRSettingsError.None;
    OpenVR.Settings.SetBool(OpenVR.k_pch_Camera_Section,
                            OpenVR.k_pch_Camera_EnableCameraForCollisionBounds_Bool,
                            enable,
                            ref e);
    OpenVR.Settings.Sync(true, ref e);
    return e;
}
```

![maxresdefault](https://user-images.githubusercontent.com/4145024/54283996-75cd0d80-459f-11e9-8f02-03f3724affef.jpg)

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
