### ISSUE TITLE
Missing initialization in SteamVR_Behaviour_SkeletonCustom

### ISSUE THREAD

**Issue by louspawn** [ValveSoftware/steamvr_unity_plugin#359]
Hi all,

I came across a "NullReferenceException: Object reference not set to an instance of an object" error while trying to use a custom hand model with the SteamVR_Behaviour_SkeletonCustom.cs script. After inspecting the code I believe the problem is that the bones array doesn't get initialized when the  SteamVR_Behaviour_SkeletonCustom class extends SteamVR_Behaviour_Skeleton class before the overriden function AssignBonesArray gets called.

So what I have done is that I have placed:
`bones = new Transform[31];`
at the start of the AssignBonesArray function and that solves the problem but I am not entirely sure that the array length of 31 is the correct one, I just looked at the highest number of the SteamVR_Skeleton_JointIndexes on the SteamVR_Action_Skeleton.cs script.

Hope that helps.

**Comment by zite** [comment]
This should be fixed in the 2.3.2 asset store / github release. https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.3.2
