### ISSUE TITLE
Tracker Index Issue

### ISSUE THREAD

**Issue by larryjohncarter** [ValveSoftware/steamvr_unity_plugin#361]
Hello,
Im using two trackers on my unity project which i have set the device index to 3 and 4. However whenever I unpair one tracker and then pair a controller and unpair that controller to pair tracker, the tracker device index isnt 3 or 4. Is there anyway I can override SteamVr Indexing for the tracked objects or at least get the index of the paired controller and assign it? I have also tried the SetDeviceIndex(int index) it doesnt work like that neither

**Comment by larryjohncarter** [comment]
I have fixed this problem, if anyone else has this problem, don't hesitate to ask me :)

**Comment by Gotcab** [comment]
What was the cause fo the problem?
