### ISSUE TITLE
SteamVR2+ Haptic Pulse is using default values instead of parameters that is being passed 

### ISSUE THREAD

**Issue by zkkzkk32312** [ValveSoftware/steamvr_unity_plugin#362]
for a call like the following,

VRTK_ControllerHaptics.TriggerHapticPulse(VRTK_DeviceFinder.GetControllerReferenceLeftHand(), 0.15f, .1f, .1f);

only the strength value is correctly being passed into the new SteamVR2 execute,
all the other values gets lost in between and execute end up using the default values.

Not related to IL2CPP.

**Comment by zite** [comment]
Are you certain this is not a VRTK issue?

**Comment by zkkzkk32312** [comment]
if you trace that call, at the end only the 0.15f strength value get passed through the stack.
In previous versions of VRTK (3.2) and SteamVR (1.X) it worked as intended.

**Comment by zite** [comment]
I think this must be a vrtk issue. I don't see any places that defaults are defined in the steamvr plugin itself.
