### ISSUE TITLE
Teleporting using a Vive Tracker

### ISSUE THREAD

**Issue by pbeks** [ValveSoftware/steamvr_unity_plugin#363]
I would like to use the teleporting prefab with the HTC Vive trackers.
I use a homemade device with two HTC Vive Trackers and two buttons connected to the pogo pins for teleporting.
This worked in the old version of steamVR plugin, however in 2.2 I can't get it to work.
I am able to use the steamVR tracked object script, however that again does not allow you to usse the lefthand, righthand instead of the index.

Are there plans to update the plugin to support the vive tracker to teleport?

**Comment by zite** [comment]
If you switch the tracker role to Held In Hand it should work like a vive wand. https://steamcommunity.com/games/250820/announcements/detail/1697186829260359619
