### ISSUE TITLE
Vive Controllers not showing up in build

### ISSUE THREAD

**Issue by Crycks** [ValveSoftware/steamvr_unity_plugin#364]
In Unity Editor everything works perfectly well, no issue. But when building impossible to get my controllers to move and appear... I'm on windows not mac so no issues with that part.
Using : Unity 2018.3.0f2 and SteamVr 2.2.0 from the asset store.

So in editor i have no error, and no warnings:
![image](https://user-images.githubusercontent.com/48651104/54493374-9a8ef100-48cf-11e9-8c93-fd980fbc1998.png)

As for the build: 
[output_log.txt](https://github.com/ValveSoftware/steamvr_unity_plugin/files/2975322/output_log.txt)

If more information needed, please ask...

**Comment by PichonDev** [comment]
Thanks for asking, I'm stuck with the same issue :S

**Comment by zite** [comment]
Make sure you've copied your bindings to the default bindings in the root of your assets directory. In the binding UI if it says there are local changes you need to hit "Replace Default" in the details of that binding to replace the jsons files. Those should then be copied to your build directory.

**Comment by PichonDev** [comment]
On my side, i did put it on the root of my project but should it be there or on the Asset folder ? 
![image](https://user-images.githubusercontent.com/48758796/55251052-eaff3a80-524f-11e9-8b36-928f2a0a99da.png)

(I'm not on my work computer and this is not the good file, but its just to say that the actions.json was here and i did use the ReplaceDefaultButton. Also in the good project i have quite some other json file here too).

This is what i have in my "Asset/" folder :

![image](https://user-images.githubusercontent.com/48758796/55251302-87294180-5250-11e9-9697-3fadd718b172.png)

And this is what is in my "Assets/SteamVR_Input/"

![image](https://user-images.githubusercontent.com/48758796/55251340-9d370200-5250-11e9-8696-e4fdfdd0cc58.png)

**Comment by Crycks** [comment]
Thanks, problem solved for me, json werent in Assets/

**Comment by chilton** [comment]
So these go in /Assets/ ?

When an app is built, what folder should they be in, relative to the executable?

**Comment by zite** [comment]
binding files should go in the root of your project directory and if you didn't create them in the binding ui you may need to manually editor you actions.json to include them (look for the controller type section near the button). If they're in the root of your project they will get copied to builds automatically.
