### ISSUE TITLE
Mixed Reality Controllers throwing objects fly downward instead of outward

### ISSUE THREAD

**Issue by WarlockEnki** [ValveSoftware/steamvr_unity_plugin#365]
Issue:
Throwing objects in the Interactions_Example using a Mixed Reality (Windows) controller is difficult as they fly immediately downward when released.

Repro:
1. Open Interactions_Example unity scene
2. Teleport over to the tables with the balls and spheres.
3. Pick up any object and throw it along the local z-y plane.

Expected:
Object's trajectory flies outward in relation to your velocity and relase point as expected.

Actual:
Object's trajectory seems to be using a velocity that is pointing downward. Note that MR Controllers have two different points. One for the origin of the pointer, and one for the controller. Make sure you are using the proper point. If you are using the pointer point, that may explain why we are seeing this behavior.

**Comment by davidfufu** [comment]
I've also experienced this error. I have a simple grab and throw example that works on SteamVR v2.0.1, but on 2.3.2, on release of the currently held object, anything thrown left goes back, thrown right goes forward, thrown forward goes left, and thrown back goes right.

**Comment by zite** [comment]
I believe this has been fixed since this post was made. If not, please create a new issue with the repro steps and ideally an example project to replicate the issue. Thanks!
