### ISSUE TITLE
Teleport uses wrong vector for Mixed Reality Controllers

### ISSUE THREAD

**Issue by WarlockEnki** [ValveSoftware/steamvr_unity_plugin#366]
Issue:
When using Mixed Reality controllers the teleport line is using the wrong vector.
Mixed Reality controllers have two points and associated vectors. One is for the handle, the other is for when you use the pointer. It seems the wrong vector is being used.

Repro:
1. Open the Interactions_Example scene in Unity.
2. Teleport to any location.

Expected:
The teleport line should use the pointer vector..

Actual:
The teleport line comes out of the handle vector.

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
