### ISSUE TITLE
Interactable : Hide Highlight is Null when AddComponent<Throwable>() inside script

### ISSUE THREAD

**Issue by Raphael-Os** [ValveSoftware/steamvr_unity_plugin#367]
When I add a Throwable component on a gameobject inside a running script, and then in game my hand is hovering this object, there is no highlight and it show in the console : 

`NullReferenceException: Object reference not set to an instance of an object
Valve.VR.InteractionSystem.Interactable.ShouldIgnore (UnityEngine.GameObject check) (at Assets/SteamVR/InteractionSystem/Core/Scripts/Interactable.cs:113)`

**Comment by crawelsky** [comment]
Please does anyone found a solution ? am facing the same issue.

**Comment by crawelsky** [comment]
Hello @Raphael-Os, I took some time today to see where is the issue. It seems that you just have to add : 
`if(hideHighlight == null)
                return false;`
at the beginning of "ShouldIgnore" function to resolve the issue. 
Hope this will help.

**Comment by blevesque** [comment]
Thanks @crawelsky it works for me :)

**Comment by zite** [comment]
I believe this has been fixed since this post was made. If not, please create a new issue with the repro steps and ideally an example project to replicate the issue. Thanks!
