### ISSUE TITLE
How add SteamVR pligin in Megacity demo done with ECS?

### ISSUE THREAD

**Issue by castana1962** [ValveSoftware/steamvr_unity_plugin#368]
Hi 
Sorry for my ignorance but I am trying the new Megacity project done with ECS and I am interested in adding the SteamVR plugin to it, for it, What is the best to do it? Is SteamVR plugin for Unity  ECS compatible?
Does anybody try it?
Thanks for your time
Alejandro
PS. I added the Camera Rig prefab from Steam VR plugin in Megacity project and I see all Black in the game and I got the following warning
Cannot set field of view on camera with name PlayerCam while VR
Does anybody know how to fix it?
Thanks again

**Comment by DavideRiccitiello** [comment]
Hi Castana,

If you wanna try MegaCity in VR, just install in package manager >OpenVR and in XR settings tick Virtual Reality Supported. 
I haven't try to add SteamVR plug-in.

**Comment by KellanHiggins** [comment]
MegaCity should work with any type of Unity Project. You can still run GameObjects along side any Entities you have created.

I don't think this is an issue with this github repo and should probably be closed.

**Comment by zite** [comment]
This isn't really related to the steamvr plugin. I'd recommend asking on the unity forums.
