### ISSUE TITLE
SteamVR_LevelLoad loadingScreenTransform being overridden

### ISSUE THREAD

**Issue by roskelld** [ValveSoftware/steamvr_unity_plugin#37]
I think I've found an issue in the code where a transform override to the loading screen is being set.

		if (loadingScreen != null && loadingScreenDistance > 0.0f)
		{
			// Wait until we have tracking.
			var hmd = SteamVR_Controller.Input((int)OpenVR.k_unTrackedDeviceIndex_Hmd);
			while (!hmd.hasTracking)
				yield return null;

			var tloading = hmd.transform;
			tloading.rot = Quaternion.Euler(0.0f, tloading.rot.eulerAngles.y, 0.0f);
			tloading.pos += tloading.rot * new Vector3(0.0f, 0.0f, loadingScreenDistance);

			var t = loadingScreenTransform != null ? loadingScreenTransform : transform;
			t.position = tloading.pos;
			t.rotation = tloading.rot;
		}

The above code seems to be setting the `loadingScreenTransform` to t then on the following line overwriting it with the generated `tloading.pos` and `tloading.rot`.

I tested the following fix in my code and the results for both having a transform override or not seem to function as expected.

		if (loadingScreen != null && loadingScreenDistance > 0.0f)
		{
			// Wait until we have tracking.
			var hmd = SteamVR_Controller.Input((int)OpenVR.k_unTrackedDeviceIndex_Hmd);
			while (!hmd.hasTracking)
				yield return null;

			var tloading = hmd.transform;
			tloading.rot = Quaternion.Euler(0.0f, tloading.rot.eulerAngles.y, 0.0f);
			tloading.pos += tloading.rot * new Vector3(0.0f, 0.0f, loadingScreenDistance);

            	var t = transform;

	            	if (loadingScreenTransform != null)
        	    	{
                		t = loadingScreenTransform;
	            	}
        	    	else
            	{
                		t.position = tloading.pos;
	                	t.rotation = tloading.rot;
        	    	}
        	}

**Comment by aleiby** [comment]
The original code is choosing between whether to set the position and rotation of the component's GameObject's transform, or some other transform specified by setting loadingScreenTransform, to the pos and rot of tloading calculated above.  I'm not sure what bug you are trying to fix here - simply assigning the local variable t to loadingScreenTransform has no effect.
