### ISSUE TITLE
Continuous "Binding not Set" when using 3rd party controller / not using Admin mode

### ISSUE THREAD

**Issue by L-Steiner** [ValveSoftware/steamvr_unity_plugin#371]
I'm using SteamVR 1.2.10 and Unity 2018.3.9f1. I have a joystick which is set up as an X Box One Controller in Steam.
If the joystick is connected and I'm not using Unity in admin mode, the controller is selected as default and i get the "binding not set" message whenever i activate play mode. I can make changes in the binding UI but they are gone when I restart play mode. It seems that I can either disconnect the joystick or switch to admin mode to avoid the message/make changes permanent.
[This guy](https://forum.unity.com/threads/steamvr-update-no-controllers-in-unity-games-error-bindings-for-unity-exe-was-not-set.534336/#post-3881812) here apparently had the same issue

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
