### ISSUE TITLE
Teleporting not working when SteamVR initialised manually

### ISSUE THREAD

**Issue by jirimotejlek** [ValveSoftware/steamvr_unity_plugin#372]
I'm trying to instantiate SteamVR plugin on runtime, using the final version 2.2.0 and the SteamVR_ForceSteamVRMode example, but there's an issue with the Teleporting, which is not working. It doesn't work either if I instantiate the Teleporting prefab from code or create it manually in the scene. This worked in the 2.0.1 version.

(If I don't initialize SteamVR in code and just put Player prefab and Teleporting prefab in the scene teleporting works fine as expected)

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
