### ISSUE TITLE
Haptic feedback on scroll action?

### ISSUE THREAD

**Issue by kosipovic** [ValveSoftware/steamvr_unity_plugin#376]
My controller is vibrating on every scroll action, I have tried everything to disable it, is it a bug? hardware issue?  Action binding in steam actions only has haptic configurations to trigger, but not scroll / trackpad, which is weird by itself.

Unity 2018.3 , SteamVR 1.2.10, newest unity plugin, simple Vive setup, with older controllers

**Comment by ThomasMountainborn** [comment]
I just stumbled across this same issue when using the scroll action for the first time. There are a few haptics related settings in the scroll action control binding properties, but even with all of them disabled, the haptics are still being triggered.

**Comment by zite** [comment]
I believe this has been fixed and the setting to disable the haptic (if its there by default) should work now.
