### ISSUE TITLE
[Question] Compability between the plugin and the steam vr platform

### ISSUE THREAD

**Issue by YasHB10** [ValveSoftware/steamvr_unity_plugin#377]
Hello, I hope someone can answer my question.

I'm using steam vr plugin with the VRTK plugin in unity. VRTK only works with steam vr version1.2.3.
Can the steam vr platform support apps which have been developed in the older version of the VR plugin? When I say vr platform I mean the one which recognizes controllers and sensors.
for how long the 1.2.3 version of the plugin will be supported on the newest steam Vr platform?

Thank you for your time.

**Comment by zite** [comment]
We have no plans to deprecate runtime calls through the legacy input system (1.2.3 calls). The plugin itself is no longer supported but calls to those interfaces should continue to work.
