### ISSUE TITLE
SteamVR_Skybox.SetOverride() makes VRAM leak!

### ISSUE THREAD

**Issue by hanklord** [ValveSoftware/steamvr_unity_plugin#378]
Because I have to change to SteamVR Skybox according to my game logic when scene loaing, 
but I found there is VRAM leaking when I call SteamVR_Skybox.SetOverride(). 
My SteamVR version is 1533664367

Here is the simple project to reproduce the problem
https://drive.google.com/file/d/1EUbL6LPvxGVxilwQwi0Bf74i_uOXxlRB/view?usp=sharing
Reproduce
1. Open project
2. Open Assets/Scenes/SteamVR_SkyboxTest
3. Press key "A" to call SteamVR_Skybox.SetOverride
4. See Dedicated GPU memory of vrcompositor.exe in [Task Manager] -> [Details]
5. Press key "A" again
6. Dedicated GPU memory of vrcompositor.exe is increasing
PS. Press key "C" to call SteamVR_Skybox.ClearOverride() dose not help to decrease the GPU memory.
    If Press "A" again the VRAM will reach a new high!

If I have any wrong, feel free to let me know, Thanks.

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
