### ISSUE TITLE
Custom ActionSet only returning false Get values

### ISSUE THREAD

**Issue by JustinAtSama** [ValveSoftware/steamvr_unity_plugin#379]
![SteamVRCode](https://user-images.githubusercontent.com/47543833/55048341-117d6580-5005-11e9-9e9f-971260eddcab.JPG)
![SteamVRBindings](https://user-images.githubusercontent.com/47543833/55048348-180bdd00-5005-11e9-9ada-34f1d4a63672.JPG)
Version 2.2

As shown, custom ActionSets are created but when I try to access my custom ActionSet named "sama", the GetBooleanAction is always returning false. It does return true when when I access "default" at "GrabPinch".

In the Vive Controller Dashboard link, I tried "Replace Default Binding" but it does nothing. I hear beta versions of 2.2+ fixes some of these issues, but I didn't find anyone specifically having issues getting values from a custom ActionSet.

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
