### ISSUE TITLE
Accessing pogo pin state for a tracker?

### ISSUE THREAD

**Issue by guiglass** [ValveSoftware/steamvr_unity_plugin#381]
I am finding that using bindings is not working very well for trackers, and I need a way to access each of my tracker's pogo pins.

I see the device "/devices/htc/vive_trackerLHR-1ADEAAA3 -vive_tracker"

How can I access pogo pin values such as: "/input/trigger/click".

Please help, I am desperate to get trackers working properly!!!

**Comment by MahmoudAshraf-CIS** [comment]
am facing the same problem, even downgrading to an older steam vr plugin version it didn't work

**Comment by nocanwin** [comment]
see issue #152

**Comment by zite** [comment]
Closing as a duplicate of #152
