### ISSUE TITLE
Trackers not using bindings?

### ISSUE THREAD

**Issue by guiglass** [ValveSoftware/steamvr_unity_plugin#383]
I have set my trackers to role "Disabled"

Then I create bindings for the trackers using that role.

Using Unity editor I try printing the values from actions I had set earlier, but they never change. 

Is "disabled" the wrong role?

I have tried setting all trackers to "camera" role but only one tracker changes.

How do I set up all of my trackers so Unity can properly read each tracker's action values (pogo pins)?

**Comment by Gotcab** [comment]
How are the trackers used? Are they held in hand or juste positioning an object in space?

**Comment by zite** [comment]
Disabled is not a valid role, it means the trackers are essentially off for input system purposes. I'd recommend using a different role.
