### ISSUE TITLE
I just downloaded from the asset store and am getting an error in Sample Scene

### ISSUE THREAD

**Issue by drivestudios** [ValveSoftware/steamvr_unity_plugin#386]
Hello, 

I keep getting this error when trying to run the sample scene and am not sure how to resolve it. 

NullReferenceException: Object reference not set to an instance of an object
Valve.VR.SteamVR_Input.IdentifyActionsFile (Boolean showLogs) (at Assets/steamvr_unity_plugin-master/Assets/SteamVR/Input/SteamVR_Input.cs:1259)
Valve.VR.SteamVR.InitializeTemporarySession (Boolean initInput) (at Assets/steamvr_unity_plugin-master/Assets/SteamVR/Scripts/SteamVR.cs:312)
Valve.VR.SteamVR_RenderModel+RenderModelInterfaceHolder.get_instance () (at Assets/steamvr_unity_plugin-master/Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:90)
Valve.VR.SteamVR_RenderModel.SetModel (System.String renderModelName) (at Assets/steamvr_unity_plugin-master/Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:303)
Valve.VR.SteamVR_RenderModel.Update () (at Assets/steamvr_unity_plugin-master/Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:721)

Thanks!

**Comment by zite** [comment]
Hi, is this the only error you got? Did you save and generate actions from the SteamVR Input window?

**Comment by zite** [comment]
Closing from inactivity.
