### ISSUE TITLE
SteamVR_Fade.Start does not work in LWRP

### ISSUE THREAD

**Issue by krzys-h** [ValveSoftware/steamvr_unity_plugin#388]
The SteamVR_Fade script does not work in LWRP since the OnPostRender callback no longer works there.

Also see a similar issue in VRTK which has an almost identical script and my patch that works in LWRP here: ExtendRealityLtd/VRTK#1959

**Comment by d1xt1r** [comment]
Hi, is there any progress on this issue? @krzys-h can you suggest a workaround (for SteamVR, not for VRTK) which works in the Scriptable Render Pipeline? Thank you!

**Comment by ataylor09** [comment]
Came across this issue also. I've found that `SteamVR_Fade.Start(...)` does nothing, however `SteamVR_Fade.View(...)` seems to work fine.

**Comment by d1xt1r** [comment]
Wow! This is working! Thank you very much!

**Comment by RikSagara1990** [comment]
It working for me too (i am using URP), thanks
