### ISSUE TITLE
Cannot set Layer and Tag for Created Assets

### ISSUE THREAD

**Issue by OptrixAU** [ValveSoftware/steamvr_unity_plugin#39]
I need to keep my Steam-VR controllers and several other ui-related elements on particular layers, so they aren't caught in some computations.

The trouble is that there isn't anywhere to specify what layer or tag you'd like your SteamVR-created GameObjects to appear on.

Currently, I'm adding '<object>.tag = gameObject.tag' and '<object>.layer = gameobject.layer' in every place that you instantiate a control. This way, I can place the objects on other layers - and I have the flexibility to split the left and right hands, if I feel it's needed. 

It would be good to see this integrated into the code-base.

**Comment by OptrixAU** [comment]
Updates can be found here - https://github.com/OptrixAU/steamvr_unity_plugin

**Comment by aleiby** [comment]
Integrated for next update.  Thanks!
