### ISSUE TITLE
Actions not triggers when low battery message apperas

### ISSUE THREAD

**Issue by arhcy** [ValveSoftware/steamvr_unity_plugin#390]
Usually this case reproduces well.
- Connect controllers with drained battery (tested on Oculus and WMR controllers)
- Actions will not work
- SteamVR_Action::active and SteamVR_Action:;activeBinding properties are true for all actions

The biggest problem is that I can't handle if they are really active or disabled.

**Comment by zite** [comment]
Do the controllers work in the SteamVR dashboard under this scenario?

**Comment by arhcy** [comment]
We utilized our drained batteries. We will check this case next time they will drained.

**Comment by zite** [comment]
Hasn't been updated in a month. Closing for now.
