### ISSUE TITLE
Solution for hand controllers not working on Mac and Windows builds in Unity 2018/2019 with current version of SteamVR plugin

### ISSUE THREAD

**Issue by chilton** [ValveSoftware/steamvr_unity_plugin#391]
This is a general note for everyone struggling with the bug where a build will not result in a working product, because the hand controllers won't show up. This has been an ongoing struggle for some of us for months, and the solution is really simple, but I have to stress it's also a stopgap, at best. 

The first step is to make the build a development build so you can read the error messages. This will show that in most cases, it's because the build post process script is not properly moving the various json files into place. 

**1. After you make a build, look for these files:**
bindings_oculus_touch.json
bindings_knuckles.json
bindings_vive_controller.json
bindings_holographic_controller.json
actions.json
binding_holographic_hmd.json
binding_vive_pro.json
binding_rift.json
binding_vive.json
binding_vive_tracker_camera.json

**2. Find these files in your Unity project and move them to the right folder.** 

Windows: These go at the root level of the folder next to your exe. I know this clutters up the folder and is generally considered bad form, but it's a requirement. 

Mac: These go inside the application package, at the first level. I know this location is traditional off limits, and that no files should EVER be placed here, according to Apple's rules, but again, this is where it's looking. In the old days, placing files here would prevent an app from being sellable through the App Store. I don't know if that's still the case, but I'm going to know in a few days. 

These changes will get your app to at least work, until a correct multi-platform solution is in place.

**Comment by chilton** [comment]
With a very minor change to the build process, this can be automated. Here's how to do that:
https://github.com/ValveSoftware/steamvr_unity_plugin/issues/394

**Comment by PlayingKarrde** [comment]
My build copies these files across, and even if I do it manually, I still get no Vive controllers in my build. Are there any other workarounds? This is really important and time sensitive for me. I can't afford to drop the Vive plugin for another solution at this point but this is obviously a dealbreaker.
