### ISSUE TITLE
Please namespace your classes. Causes compilation problems

### ISSUE THREAD

**Issue by jerotas2005** [ValveSoftware/steamvr_unity_plugin#392]
I'm Brian Hunsaker at Dark Tonic, and we make the popular Unity plugin Master Audio. One of our 6,000+ users informed me that installing both Master Audio and SteamVR results in being unable to compile. And that is because SteamVR has a class with the same name as a class in Master Audio. I have fixed Master Audio in the next update so that it uses the correct one by specifying the full namespace and class name of it (AmbientSound). This happened SteamVR did not use namespaces for their classes. There are probably other plugins out there that cause similar compilation issues, so I hope you guys can add namespaces to all your classes in the plugins so that nothing like this happens in the future. Thank you!

**Comment by zite** [comment]
As of version 2.0 all SteamVR classes should be namespaced into Valve.VR.
Is there a specific class you're having an issue with?

**Comment by jerotas2005** [comment]
I don't actually use the product (SteamVR). A user of Master Audio told me there was a conflict and I verified. The conflict was a class named AmbientSound. We verified with the latest version on the Unity Asset Store at the time ( a few weeks ago).
https://assetstore.unity.com/packages/tools/integration/steamvr-plugin-32647
The asset store release notes page says that you haven't published a new version there since January this year, so it should still be broken as per my test.When I went to the AmbientSound class in your SDK I saw it had no namespace...
Thanks,-Brian
    On Monday, 15 April 2019, 02:22:54 pm GMT-7, Keith Bradner <notifications@github.com> wrote:  
 
 
As of version 2.0 all SteamVR classes should be namespaced into Valve.VR.
Is there a specific class you're having an issue with?

**Comment by bddckr** [comment]
That's an example scene/project/asset class found here:
https://github.com/ValveSoftware/steamvr_unity_plugin/blob/7e957350fe84e2ab663b77382b9912c33353815e/Assets/SteamVR/InteractionSystem/Samples/BuggyBuddy/Audio/AmbientSound.cs#L1-L5

It looks like the example stuff isn't namespaced properly.

**Comment by zite** [comment]
This should be fixed in 2.3.2. Let me know if it's still an issue. https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.3.2

**Comment by jerotas2005** [comment]
Thank You!
    On Thursday, 13 June 2019, 5:22:32 pm GMT-7, Keith Bradner <notifications@github.com> wrote:  
 
 
This should be fixed in 2.3.2. Let me know if it's still an issue. https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.3.2
