### ISSUE TITLE
LeftRenderModel prefab has problem once every two instanciation

### ISSUE THREAD

**Issue by gizmhail** [ValveSoftware/steamvr_unity_plugin#397]
When I instanciate any InteractionSystem/Core/LeftRenderModel prefab, the first instanciation is ok, while the second is always distorted (not mirrored, and with a buggy mesh).

The right prefabs do not have this bug.

To reproduce, simply put an InteractionSystem/Core/Player in your scene, and launch it. Your actual left hand (the one instanciated by the Player prefab) is properly displayed. 
Them, at runtime, directly instanciate a LeftRenderModel prefab in the scene, it will be incorrect. If you instanciate another one, it will be correct, the next one incorrect and so on.

See below what happens with 4 manual instanciations:
![4instanciations](https://user-images.githubusercontent.com/566198/55832509-07d02380-5b16-11e9-945b-2e189fe00505.PNG)

_To give context, I wanted to have a second hand to be able to block my main hand when colliding an object, while still displaying to the user where its real-life hand is: on a collsion, I wanted to disable my Player hand SteamVR_behavior_Pose to freeze it on the collision position, and enable my second ghost hand, having an enabled SteamVR_behavior_Pose to show where my actual real life hand was (and then, I would handle my VR hand with physics while there're not unite again to adapt seemlessly)._

**Comment by zite** [comment]
This should be fixed in the new beta release: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.3b1

**Comment by gizmhail** [comment]
Thank you :)

**Comment by zite** [comment]
Fixed in the recent 2.3.2 asset store release https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.3.2
