### ISSUE TITLE
Custom rig problem.

### ISSUE THREAD

**Issue by Sachonski** [ValveSoftware/steamvr_unity_plugin#398]
Recently I've been working on a custom pair of hands rigged exactly like the original SteamVR. Based on that rig for the number of bones. Everything works like a charm until I try the new poser system. It seems like the auxiliary bones are messing up the rig. 
Is there a template on Maya or Blender somewhere, where we can get a reference rig so this won't happen anymore?

**Comment by zite** [comment]
Do the models included not work well as a reference?

**Comment by Sachonski** [comment]
@keithbradner Yeah they do, but the 5 auxiliary bones are invisible, and you don't get where those points are after importing the reference FBX, into a modelling program.
A professional modeler could probably handle that stuff pretty easily I guess. But not my case, that's why I've asked if there was any referenced .blend or .maya, to investigate further...

**Comment by joevdh** [comment]
Can you give us more detail on how the aux bones are messing things up?

One thing to look out for when importing your custom model back into Unity is that Unity likes to re-order the bones, but the SteamVR plugin requires that the order matches the order defined in SteamVR.  You need to manually make sure that the imported prefab has the bones in the right order in the hierarchy.

**Comment by Sachonski** [comment]
It has to do with the way the new Poser System. The root hierarchy seems to be fine (Exactly as the original one), hands bones and skeletal input do work and track correctly, once you setup a custom pose with the new poser system tho, everything goes offboard. The aux finger joints seem to be out of place and stretch the hand in funny ways. Despite that, the rest of the SteamVR hand tracking plugin seems to works fine with my custom made hand. That's why I'm thinking the new addition from Zulubo is messing things up.

**Comment by zite** [comment]
I think we're having trouble imagining your scenario. If you have a lightweight project you could send us that would be helpful. Or videos of the project view when this happens.

**Comment by Sachonski** [comment]
I'll see if I can find the source or upload the video, the project got cancelled tho.
