### ISSUE TITLE
Interactions_Example: Selecting BowPickup within hierarchy crashes Unity editor

### ISSUE THREAD

**Issue by JimW** [ValveSoftware/steamvr_unity_plugin#4]
At the bottom of ItemPackageSpawner.cs, ItemPackageSpawnerEditor has this line within it's OnInspectorGUI:

script.itemPackage = script._itemPackage;

But because itemPackage has a setter which calls CreatePreviewObject(), When in the editor, a bunch of LongbowPreviews keep getting added (There is already one in the scene's hierarchy by default).   

I just removed the whole ItemPackageSpawnerEditor and it fixes the issue. ItemPackageSpawnerEditor adds no editor functionality anyway.. I'm still confused why CreatePreviewObject() is called within the setter like that, but at least I can continue my digging around.  Thanks for sharing all this by the way.

**Comment by VampireLestat** [comment]
@JimW Seeing the exact same issue here as well, thanks for the workaround.

**Comment by aleiby** [comment]
Fixed in next update.
