### ISSUE TITLE
SteamVR External Camera, Screen Position out of View Frustum

### ISSUE THREAD

**Issue by varian97** [ValveSoftware/steamvr_unity_plugin#40]
I use third controller to enable mix reality in the Unity, but this error keeps appear when I selecting the camera in the child of third controller : 

![error](https://user-images.githubusercontent.com/15712645/27316062-8b630e04-55a7-11e7-9567-63a0728b8bc0.PNG)

And the quadratic view becomes : 
![tanya](https://user-images.githubusercontent.com/15712645/27316093-a8b7ef6a-55a7-11e7-9512-372f48e9bb89.PNG)

**Comment by aleiby** [comment]
Which version of Unity?

**Comment by varian97** [comment]
Sorry I didn't mention it.
Unity version : v5.6.1f1
SteamVR version : 1.2.1

**Comment by aleiby** [comment]
I am unable to reproduce this.  Maybe you have some other changes in your project that is causing this?

**Comment by varian97** [comment]
I deleted the SteamVR gameobjects and now it works, maybe that's the cause ?
