### ISSUE TITLE
controllers not working

### ISSUE THREAD

**Issue by LiableDuke** [ValveSoftware/steamvr_unity_plugin#400]
I am using Unity 2018.3.10f1 with SteamVR latest version from Unity Asset Store when i start the game i the controllers don't show up or respond to input. I do get an error but i don't know why.

[SteamVR] No pose action set for this component
UnityEngine.Debug:LogError(Object)
Valve.VR.SteamVR_Behaviour_Pose:Start() (at Assets/SteamVR/Input/SteamVR_Behaviour_Pose.cs:76)

**Comment by zite** [comment]
Is that the only error you get? Did you delete the Pose action from your list of actions?

**Comment by LiableDuke** [comment]
yes this is the only error i get, i did not delete it but it is not there not even when i reinstall the plugin

**Comment by zite** [comment]
That's strange, you may want to delete the actions.json in the root of your project directory. The plugin should then prompt you to copy over a new one when you open the SteamVR Input window.

**Comment by LiableDuke** [comment]
oke that worked but i still get the error

**Comment by LiableDuke** [comment]
oke never mind that did fix it i was just being an idiot
