### ISSUE TITLE
After using Lightweight RenderPipeline, start the VIVE black screen!

### ISSUE THREAD

**Issue by kwooshung** [ValveSoftware/steamvr_unity_plugin#401]
![1555071208127](https://user-images.githubusercontent.com/3413930/56036568-bf0bab00-5d5f-11e9-9af7-15baebd8ebb5.jpg)

**Comment by dantman** [comment]
Go to Player > XR Settings > Stereo Rendering Mode and change it to "Single Pass". Also double check that your camera instances do not override it to a different setting.
