### ISSUE TITLE
SteamVR 2.0 license

### ISSUE THREAD

**Issue by MichaelAmat** [ValveSoftware/steamvr_unity_plugin#402]
Hello, I'm sorry this might be an old question, but I can't find it anywhere. 

What is the license agreement for steamVR 2.0? Is it open source, can I use any of the scripts in it in any game?
What is the proper way to give attribution?

Thank you very much, sorry if this question has been answered before.

**Comment by bddckr** [comment]
It's... right there in the root. https://github.com/ValveSoftware/steamvr_unity_plugin/blob/master/LICENSE

**Comment by kisak-valve** [comment]
Closing per the last comment.
