### ISSUE TITLE
LaserPointer "getStateUp" in update no more triggered after scene changement

### ISSUE THREAD

**Issue by DevVirtualCreation** [ValveSoftware/steamvr_unity_plugin#405]
After loading a second scene with same Player as the first scene the condition with getStateUp or getStateDown in update function on LaserPointer script is no more true even the GetSate return the correct current state of the controller trigger.

**Comment by zite** [comment]
Are there any errors in the scene when this happens? Is the pose set correctly still? The interaction action?

**Comment by DevVirtualCreation** [comment]
Ok i found why, i just didn't saw that is my second Player object initially present in the new scene who is in conflict with the old DontDestroyOnLoad Player by bloquing events of him. Lack of testing... So i assuming that we can have only one Player at the time even it's a singelton, or it can cause event conflict with this new version ?
