### ISSUE TITLE
DisplayResolutionDialog warnings

### ISSUE THREAD

**Issue by dantman** [ValveSoftware/steamvr_unity_plugin#406]
Unity has deprecated `ResolutionDialogSetting`/`PlayerSettings.displayResolutionDialog` in 2019.1 so Unity is now emitting 8 warnings for its usage in [SteamVR_UnitySettingsWindow.cs](https://github.com/ValveSoftware/steamvr_unity_plugin/blob/master/Assets/SteamVR/Editor/SteamVR_UnitySettingsWindow.cs).

Those usages should probably be disabled in `UNITY_2019_1_OR_NEWER`.

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
