### ISSUE TITLE
Strange behavior when getting data from proximity sensor

### ISSUE THREAD

**Issue by arhcy** [ValveSoftware/steamvr_unity_plugin#408]
Oculus Rift + SteamVR 1.3.23. + Unity 2018.3.12f1

Created proximity event
![Screenshot_1](https://user-images.githubusercontent.com/5066332/56577468-c50d5180-65d3-11e9-9b99-26b4723855a7.png)

Geting data in Update.
```C#
public SteamVR_Action_Boolean ProximityProjectile;

...

ProximityProjectile.GetState(SteamVR_Input_Sources.Head);
```

Found such behavior:

Case1:
- If app starts with headset on head - it returns true
- If user removes headset - it returns false
- If user wears headset back - it still returns false
- Always returns false, whenever headset on head or not

Case2:
- If app starts without headset on head - it returns false
- Always returns false, whenever headset on head or not

Proximity data in the SteamVR Input Live View shows the same results as described above.
Proximity data in the Input Debugger works correctly.

Looks like users with WMR headests has the same issue

**Comment by oxvr-tec** [comment]
Experiencing the same thing with Unity 2018.3.7 and Steam VR plugin 2.2.
Though I can clearly see /user/head/proximity turning true, the HeadsetOnHead action NEVER does, no matter if I start with HMD on or off.

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
