### ISSUE TITLE
Free Locomotion with SteamVR plugin

### ISSUE THREAD

**Issue by castana1962** [ValveSoftware/steamvr_unity_plugin#409]
Hi All
Sorry but maybe this place is not the best to post it but I do not know where find some info about it. 
I have in Unity a 3D Environment and I need to do a free locomotion to it with SteamVR plugin because I would need to walking by Oculus thumb stick button. Is it possible? Could you help me to do it? or let me get any tutorial about it
Thanks for your time
Alejandro

**Comment by zite** [comment]
There's lots of resources for this. Here's one I found: http://moonmotionproject.com/
