### ISSUE TITLE
Can I change the SteamVR Input Action Set grammatically from a c# script? 

### ISSUE THREAD

**Issue by alco6** [ValveSoftware/steamvr_unity_plugin#410]
Hello, 

I am using the last version of SteamVR Plugin for Unity. 
I would like  to change my SteamVR Input/ Actions set programatically from C# script.

Is there a way to do so? In all the resources I have found it is done manually from Unity interface. 

Please, let me know, 

Regards

**Comment by derosa** [comment]
You can change the ActionSet via code. Check Interactable.cs. There's the following code:

```
[Tooltip("Activates an action set on attach and deactivates on detach")]
        public SteamVR_ActionSet activateActionSetOnAttach;
```
And then:

```
protected virtual void OnAttachedToHand(Hand hand)
{
    if (activateActionSetOnAttach != null)
        activateActionSetOnAttach.Activate(hand.handType);
...
```

Hope that helps!
