### ISSUE TITLE
SteamVR Asset as compiled library

### ISSUE THREAD

**Issue by MikeLimaSierra** [ValveSoftware/steamvr_unity_plugin#411]
Hi guys,

We are using SteamVR for Unity and have some issues with the way it is delivered as an asset.

Our own assets are written entirely in Visual Studio and are built against Unity's UnityEngine.dll that ships with the Unity Editor. This is so that we have all our code in one place instead of multiple copies across multiple Unity projects. Assets are compiled into dlls and are then imported into Unity.
To reference constructs from within SteamVR unity plugin, we have to precompile your plugin into a library that is then referenced from within Visual Studio.
This process is somewhat problematic, since the resulting dlls also contain CustomEditor classes depending on how we compiled SteamVR.

The current way of using your asset could be improved considerably by offering another asset that does not contain code files. This would also make the whole process of referencing SteamVR a lot cleaner.
Here is my suggestion to solve the issue:

- extract nested custom editors from their current classes (e.g. HandEditor in Hand.cs) and put those into SteamVR_Editor project.
- compile your projects into dlls (referencing UnityEngine.dll, without UNITY_EDITOR defined)
- create another SteamVR Asset consisting of only dlls and resources (textures, prefabs, etc.)

I've already requested this on the community boards a few months back. However it was probably in the wrong spot so it got no attention: https://steamcommunity.com/app/358720/discussions/0/1743354432806077350/

This may not seem like a big issue for most asset users within the unity realm. However it is a huge problem if you want to keep your projects and code clean.

Many thanks in advance,
mike

**Comment by zite** [comment]
Hi Mike, sorry it's taken a long time to get back to you about this. We generally prefer to distribute the source by default so users can modify it if they would like to. 

We can however split up editor scripts into their own files if that will help. Looks like handeditor didn't do anything anymore so I just removed it. If you see other places that happens we can fix that.
