### ISSUE TITLE
Unity +  vive controllers not showing  

### ISSUE THREAD

**Issue by balamsoto** [ValveSoftware/steamvr_unity_plugin#412]
Unity does not show controllers I had try few work around and nothing works 
Not even projects templates from SteamVR plugging.

Any advice is really welcome, i been reading online from months ago about this problem 
It seems like the plugging new version needs some love to get it back to be awesome

**Comment by gedig** [comment]
I have been having this issue more and more often as well. Three things that have helped me:

1. Regenerate your actions files in Unity. Window->SteamVR Input -> Save and generate
2. If that hasn't worked, try restarting Unity.
3. Ensure that Steam is running in the background, go back to the Steam VR Input Window and Open the binding UI.

**Comment by DrummerB** [comment]
May be related to this: https://steamcommunity.com/app/250820/discussions/3/1647665620943527379/

**Comment by tshead** [comment]
Or #447 

Cheers,
Tim

**Comment by zite** [comment]
Going to assume this has been fixed. If people are still having issues please comment in the appropriate existing thread or open a new one. Thanks.
