### ISSUE TITLE
Skeleton Poser issue on Oculus

### ISSUE THREAD

**Issue by Sachonski** [ValveSoftware/steamvr_unity_plugin#415]
Hello there,
We've been implementing the poser system for our game without a problem for both Vive controllers and Knuckles. Recently when trying it out on Oculus, we've discovered that the pose system drift the grabbed object out of alligment by a hand aproximately.
No error reports have been warned to indicate what could be causing the error.

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
