### ISSUE TITLE
SteamVR_Action activeBinding is always false on the first frame

### ISSUE THREAD

**Issue by hlink** [ValveSoftware/steamvr_unity_plugin#418]
`SteamVR_Actions.example_Squeeze.activeBinding` is always showing false on the first frame. This is messing up some of my initialization calls when the project starts - are there any workarounds to get this value without having to wait a frame?

**Comment by zite** [comment]
My guess is steamvr hasn't fully been initialized yet. You could try also checking for SteamVR_Input.initialized as well.

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
