### ISSUE TITLE
SteamVR_Actions get copied every time they are called directly, generating garbage

### ISSUE THREAD

**Issue by hlink** [ValveSoftware/steamvr_unity_plugin#419]
![image](https://user-images.githubusercontent.com/3581594/57244758-fa5f6980-6fed-11e9-9cd8-675c768277e8.png)

![image](https://user-images.githubusercontent.com/3581594/57244781-05b29500-6fee-11e9-8974-73cefd35d3ed.png)

The auto-generated versions of the SteamVR_Input_Actions file returns copies instead of returning references to static instances of each action. This generates garbage every time they are called. I was able to work around it by manually caching the actions in my game code (essentially making a wrapper for the SteamVR_Input_Actions file) but that ends up being a maintenance problem whenever action sets change.

**Comment by zite** [comment]
Thanks, this turned out to be a much larger issue than anticipated because of how this version of mono deals with generic instantiation. It should be fixed in the beta released yesterday: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.3b1

**Comment by zite** [comment]
This is fixed in the recent asset store release 2.3.2 (https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.3.2)
