### ISSUE TITLE
Default Unity CameraRig/Camera no longer contains an Audio Listener

### ISSUE THREAD

**Issue by peroht** [ValveSoftware/steamvr_unity_plugin#420]
No AudioListener by default on the CameraRig/Camera. How so?

If adding an audiolistener to the Camera, then pressing play and then removing the audio listener i will still hear sound. 

Without having to go through the code - where is the audio listener created? Should it not be visible in the editor?

**Comment by peroht** [comment]
There has been a bug in Unity where disabling the AudioListener did not fire an error. This has been fixed in 2019.1.1. Maybe this is why you've removed the AudioListener in the first place?

https://issuetracker.unity3d.com/issues/audio-is-playing-even-when-there-is-no-audio-listener-in-the-scene

**Comment by zite** [comment]
Yeah looks like it got accidentally removed. Thanks for the report.

**Comment by zite** [comment]
This should be fixed in 2.3.2 just released on the asset store and github: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.3.2
