### ISSUE TITLE
SteamVR Render Model component does not use Universal Render Pipeline shader.

### ISSUE THREAD

**Issue by jgwinner** [ValveSoftware/steamvr_unity_plugin#421]
The HTC Vive controllers appear pink with a fresh project created with the LWRP, version 2019.1.1f1 and SteamVR. I have not installed the Oculus VR runtime.

All project materials were converted with Edit->Render Pipeline->Update project materials to Lightweight RP Materials. No other materials in the scene look odd.

It is the Vive controller, not the 'hand' that's part of the SteamVR Sample Interactions (Prefab is at SteamVR->InteractionSystem->Core->Prefabs as "Player".

Steps to reproduce: 
1. Generate a new Unity project using the Lightweight RP.
2. Install the SteamVR package from the Unity asset store
3. Delete the camera in the scene
4. Drag the "SteamVR->InteractionSystem->Core->Prefabs->Player into the scene.
5. Update the materials by Edit->Render Pipeline->Update project materials to Lightweight RP Materials
6. Click "Play" in the editor.

The Vive controller will show up pink.

**Comment by jgwinner** [comment]
note that this isn't related to the controllers not showing up; they do, they just show up as pink. I found a work around, at: https://answers.unity.com/questions/1615702/htc-vive-controllers-are-pink-in-unity.html which leads to https://forum.unity.com/threads/changing-the-htc-vive-controller-model-with-a-custom-hand-model.395107/ but I figure if I do this, other models may not show up as well.

I tried it with Windows Mixed Reality, and NOTHING showed up. Oddly, when I first ran the program, the controllers showed up as gray transparent outlines and 'teleport' callout signs, but once I teleported the first time, the controllers disappeared, along with my hands.

That's a bigger bug, WMR should work I'd assume. 

        == John ==

**Comment by andybak** [comment]
LWRP is out of preview now. It would be fantastic to get an ETA on this being fixed.

**Comment by Manchaiser** [comment]
Problem of this issue is here:
https://github.com/ValveSoftware/steamvr_unity_plugin/blob/c3db99b1e28e2eecbd92ca0e952706b6a3fa2b1c/Assets/SteamVR/Scripts/SteamVR_RenderModel.cs#L455
Workaround - replace it with default lit shader:
```C#
material = new Material(shader != null ? shader : Shader.Find("Lightweight Render Pipeline/Lit"));
```
Or create your own shader which must be compatible with default one

**Comment by Nufflee** [comment]
any updates on this?

**Comment by PierreLouisPAUGAM** [comment]
LWRP will soon become the Universal Render Pipeline (2019.3), thereby it will be the default Unity Render Pipeline. Are there any news about the "pink controller" issue ?

**Comment by Hexodus** [comment]
The same goes to HDRP - pink is everywhere. Should be fixed urgently. URP(formaly known as LWRP) is essential.

**Comment by flightCrazed** [comment]
Hi guys, any word on this? or a work around? thanks!

**Comment by jgwinner** [comment]
I switched renderers for a project last year, but honestly I've abandoned Unity to use Unreal lately. So, I don't have an update. It's somewhat absurd that Unity hasn't fixed this. 

        == John ==

**Comment by flightCrazed** [comment]
![shader set on steam controller](https://user-images.githubusercontent.com/48101354/79259200-295a9e00-7e41-11ea-9287-45c7545c3e01.PNG)

I figured it out See the screenshot. You canto set the shader here.

**Comment by flightCrazed** [comment]
> 
> 
> I switched renderers for a project last year, but honestly I've abandoned Unity to use Unreal lately. So, I don't have an update. It's somewhat absurd that Unity hasn't fixed this.
> 
> ```
>     == John ==
> ```

Thanks. Yeah, Unity is moving fast, its probably difficult for other parties (such as Valve) to keep up with their assets, but I think in the end it will all come together. I just switched to URP and I was really surprised to see the performance boost I got despite much better lighting/graphics in VR.

**Comment by airdorf** [comment]
> ![shader set on steam controller](https://user-images.githubusercontent.com/48101354/79259200-295a9e00-7e41-11ea-9287-45c7545c3e01.PNG)
> 
> I figured it out See the screenshot. You canto set the shader here.

This worked for me! Thanks for the tip!

**Comment by andybak** [comment]
@jgwinner 

>  It's somewhat absurd that Unity hasn't fixed this.

It's not something for Unity to fix. URP uses different shader to the legacy pipeline. Valve should supply a material that's compatible with URP. However @airdorf has proposed a fix that's very simple to apply - and Valve are working on an entirely new XR plugin that will replace this within the next few weeks (hopefully)

**Comment by Jack-Eatock** [comment]
> Problem of this issue is here:
> https://github.com/ValveSoftware/steamvr_unity_plugin/blob/c3db99b1e28e2eecbd92ca0e952706b6a3fa2b1c/Assets/SteamVR/Scripts/SteamVR_RenderModel.cs#L455
> 
> 
> Workaround - replace it with default lit shader:
> ```cs
> material = new Material(shader != null ? shader : Shader.Find("Lightweight Render Pipeline/Lit"));
> ```
> 
> Or create your own shader which must be compatible with default one

This worked perfectly for me! Thank you so much!!!! But one thing is as the Light Weight Render has now become the standard Universal renderer. You need to do this instead:

" material = new Material(shader != null ? shader : Shader.Find("Universal Render Pipeline/Lit")); "

**Comment by jgwinner** [comment]
@andybak 

> It's not something for Unity to fix. URP uses different shader to the legacy pipeline. Valve should supply a material that's compatible with URP.

Whoops, my bad. You're right. Restated, it's absurd that Valve hasn't fixed it **in nearly a year**, and it was a problem before I opened this bug last year.

Unity could have helped; the newer rendering pipeline was their baby, and you'd want your baby to succeed in the world. But you're right, it was really up to Valve to fix.

Don't get me wrong, Valve has done more to advance XR than any other company - even making their flagship content compatible with other headsets, unlike their competitors. Still, a bad bug is a bad bug.

Looking forward to the new plugin. Hopefully Unreal will get some love :)

**Comment by flightCrazed** [comment]
material = new Material(shader != null ? shader : Shader.Find("Lightweight Render Pipeline/Lit"));

One more point: note that shader is checking to see if this is null, and it is likely not null as seen on my screenshot and this will fail to set the new one. Either remove the null check or set it to null in the inspector.

**Comment by morganavr** [comment]
After changing to HDRP/Lit shader controllers (HTC Vive, Oculus Touch) are displayed as white:
![image](https://user-images.githubusercontent.com/51041813/81670968-12fc2e00-9451-11ea-8572-04bcf63aa916.png)
Anybody have the same issue?

**Comment by ziomio** [comment]
After I changed shader to HDRP/Lit controllers appeared white:
![image](https://user-images.githubusercontent.com/2357073/81674234-86a03a00-9455-11ea-8439-61088cb0e76e.png)
Anyone experience the same issue? How to fix it?

**Comment by RFlintstone** [comment]
> After I changed shader to HDRP/Lit controllers appeared white:
> ![image](https://user-images.githubusercontent.com/2357073/81674234-86a03a00-9455-11ea-8439-61088cb0e76e.png)
> Anyone experience the same issue? How to fix it?

Same issue here (although mine are pink / missing textures) - I use the Valve Index.

**Comment by zite** [comment]
As a temporary workaround you should be able to set the shader to a hdrp shader on the controller render model component. For the interaction system that's at Assets/SteamVR/Prefabs/controller. For the CameraRig that's in Assets/SteamVR/Prefabs/[CameraRig] and in the hierarchy under [CameraRig]/Controller (left/right)/Model.
![image](https://user-images.githubusercontent.com/198704/83831317-022f8880-a69c-11ea-9de8-f69c49e39734.png)

**Comment by yellowneck** [comment]
The workaround does not work to render the controller correctly. I achieved the 'best resutls' with the HDRP/Lit shader resulting in a white controller model like @ziomio mentioned above.

![grafik](https://user-images.githubusercontent.com/54441660/83873276-d19b2d80-a733-11ea-8ca1-697f6a05a1ed.png)

**Comment by adampeled** [comment]
I was able to fix the white controllers by changing this line right below the other one:
https://github.com/ValveSoftware/steamvr_unity_plugin/blob/c3db99b1e28e2eecbd92ca0e952706b6a3fa2b1c/Assets/SteamVR/Scripts/SteamVR_RenderModel.cs#L456

to:

`material.SetTexture("_BaseColorMap", texture);`

The default HDRP Lit shader doesn't have a `_MainTex` field, so setting the `mainTexture` property on a material using it won't do anything.

**Comment by zite** [comment]
The latest beta should also fix this problem. See the release here: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.6.0b3

**Comment by chris-redbeed** [comment]
Im using 2020.1 with 2.6.1 and everything in the "Sample" Scene ist Pink.

**Comment by zite** [comment]
For URP or HDRP?

**Comment by zite** [comment]
This has been fixed
