### ISSUE TITLE
Teleport overlay not visible with LWRP

### ISSUE THREAD

**Issue by jgwinner** [ValveSoftware/steamvr_unity_plugin#422]
When I use the Lightweight rendering pipeline, I get some weird display artifacts with the Teleport prefab.

Current SteamVR downloaded from the Unity Asset store, and Unity 2019.1.1f1

I've tried every combination of Render Queue, SeeThru, and Darken, but get essentially the same issue. The teleport destination UI and the hoop/arrows don't show up unless they are rendering 'behind' something.

Check out this screenshot for an example of the problem: 

![image](https://user-images.githubusercontent.com/10425170/57269702-4d144200-703d-11e9-8c51-08ae1bba3989.png)

You can see the teleport ring and arrow only where they are 'on top' of the 2x4 from the demo assets. Oddly, it doesn't display on the floor or the floor plane in the distance, just where it goes through another polygon. Odd.

        == John ==

**Comment by jonathan-bryant** [comment]
Chiming in with the same issue, arguably related to #210 

![image](https://user-images.githubusercontent.com/16954813/59476022-14fcec00-8e92-11e9-863c-705e72f75c91.png)

**Comment by Manchaiser** [comment]
Hey
I made a sort of remake of highlight shader on shader graph. Im not sayin it 100% same as default one but it works like default and might be useful for someone so:
![image](https://user-images.githubusercontent.com/51863280/59555407-07974d00-8fcb-11e9-9130-8432e1797d9f.png)
Just make sure u updated shader in materials (/Assets/SteamVR/InteractionSystem/Teleport/Materials/) where old highlight shader is used.

**Comment by jonathan-bryant** [comment]
@Manchaiser Thank you, absolute legend. 
![image](https://user-images.githubusercontent.com/16954813/59571645-4bcd3f00-90ea-11e9-95fd-c324c3a34bdd.png)

**Comment by Manchaiser** [comment]
In case if someone can't reproduce shadergraph as it described on screenshot above here is packed file of shadergraph. Unpack it inside assets folder and remap every material in steamvr where old highlight shader is used. Should work just as expected
[Highlight.zip](https://github.com/ValveSoftware/steamvr_unity_plugin/files/3294889/Highlight.zip)

**Comment by ataylor09** [comment]
Brilliant... exactly what I was looking for!

**Comment by jgwinner** [comment]
It's a cool workaround. I haven't checked in a while, but the bottom line is, the project generator needs to produce a stock project that *works* or a particular rendering pipeline needs to be documented as being a minimum requirement.

        == John ==

**Comment by ataylor09** [comment]
@Manchaiser you don't happen to have a shader-graph equivalent of the Valve/VR/Silhouette  shader do you?

**Comment by Giantbean** [comment]
The shadergraph makes the highlights appear but the teleportation still wont work in Unity 2019.2.12f1.
The teleport floor is also gray instead of highlighting?

**Comment by omrib** [comment]
Same problem with 2019.3f universal render pipeline.

**Comment by paulerikf** [comment]
@ataylor09 Did you ever find anything for the silhouette shader?

**Comment by ataylor09** [comment]
> @ataylor09 Did you ever find anything for the silhouette shader?

No I didn’t unfortunately. I ended up implementing a different visual method for highlighting objects

**Comment by armanhamzehlou** [comment]
This solution works!

**Comment by zite** [comment]
Beta 3 of the SteamVR Unity Plugin has URP shaders, I'm not positive if those will work for LWRP though. https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.6.0b3

**Comment by doktorbanana** [comment]
> Hey
> I made a kinda remake of highlight shader on shader graph. Im not sayin it 100% same as default one but it works like default and might be useful for someone so:
> ![image](https://user-images.githubusercontent.com/51863280/59555407-07974d00-8fcb-11e9-9130-8432e1797d9f.png)
> Just make sure u updated shader in materials (/Assets/SteamVR/InteractionSystem/Teleport/Materials/) where old highlight shader is used.

This is awesome. Thank you so much.

**Comment by elliottower** [comment]
The Valve/VR/SeeThru and Valve/VR/Silhouette shaders are also missing even with the most recent 2.6.1 release. Shouldn't be too hard to recreate using shader graphs, maybe someone could upload a .zip similar to the highlights one above

**Comment by jgwinner** [comment]
This is really absurd. This needs to be fixed. Yes, the community has come up with a lot of fixes for the base problem, but when you buy a car you expect it to have tires!

@keithbradner Keith - you added the "Will Fix" tag - can this be fixed? Can the Valve shader be uploaded, or maybe accept one of the community contributions? (I've been working with Unreal and WebXR lately, sorry, or I'd suggest something).

Thank you! 

        == John ==

**Comment by jgwinner** [comment]
Two years, and a basic scene still doesn't work out of the box?

**Comment by zite** [comment]
The example scene does in fact work out of the box. LWRP as far as I know is no longer supported by unity. This was marked will fix but not fixed because we were suspicious that unity would be dropping LWRP from the default options. The shader is open source so the community is welcome to change it at will.

**Comment by jgwinner** [comment]
The example scene does NOT work with **_URP_** out of the box, which is what LWRP became.

https://github.com/ValveSoftware/steamvr_unity_plugin/issues/875 This is still an issue.

This is like pulling teeth. It was never fixed and was a huge problem, for years, then you drop it even though it's still an issue.

**Comment by paulerikf** [comment]
URP still seems to be the most recommended pipeline for Unity VR, can only speak for myself but it definitely felt pretty janky having my first SteamVR experience be having to remake the highlight shader 'cause I couldn't see where I was teleporting.

**Comment by zite** [comment]
Fixing URP support is valid, there is code in the plugin to make that work. So if it isn't working then we'll need specific bugs around that, and new issues for them should be created.

Some people have been petitioning for LWRP from previous Unity versions to be supported. I'm trying to clarify that we will not be doing that.

**Comment by jgwinner** [comment]
@keithbradner I appreciate that. Thank you.

> Fixing URP support is valid, there is code in the plugin to make that work. So if it isn't working then we'll need specific bugs around that, and new issues for them should be created.

I posted that already: https://github.com/ValveSoftware/steamvr_unity_plugin/issues/875

> Some people have been petitioning for LWRP from previous Unity versions to be supported. I'm trying to clarify that we will not be doing that.

Ok, that's understandable because ... I mean, nothing was done for 2 years. Why fix it now? Sorry, that was snarky - but I completely agree (seriously) backporting to LWRP isn't really needed. People with newer Unity should move forward with URP.

You understand the quality problem? URP sample scenes with no added content don't work? It's like the test drive of a new car that has an engine explode starting the car. How many sales will you make?

**Comment by Chu-XiaoYao** [comment]
So, how to solve it？

**Comment by tanjunior** [comment]
> @Manchaiser you don't happen to have a shader-graph equivalent of the Valve/VR/Silhouette shader do you?



> @ataylor09 Did you ever find anything for the silhouette shader?



> The Valve/VR/SeeThru and Valve/VR/Silhouette shaders are also missing even with the most recent 2.6.1 release. Shouldn't be too hard to recreate using shader graphs, maybe someone could upload a .zip similar to the highlights one above

I converted the shader here https://github.com/ValveSoftware/steamvr_unity_plugin/issues/902#issuecomment-1431050872
