### ISSUE TITLE
Throwable.onHeldUpdate is not visible in Inspector

### ISSUE THREAD

**Issue by VincentFTS** [ValveSoftware/steamvr_unity_plugin#424]
In the Throwable class, the onHeldUpdate UnityEvent is not usable whereas it is public.
No way to add a callback in the inspector, and using it with code leads to an error.
According to [https://docs.unity3d.com/ScriptReference/Events.UnityEvent_1.html](https://docs.unity3d.com/ScriptReference/Events.UnityEvent_1.html), a specific event class must be created, for exemple :
```
[System.Serializable]
public class HandEvent : UnityEvent<Hand>
{
}
...
public HandEvent onHeldUpdate;

**Comment by zite** [comment]
Thanks for the report. Fixed in 2.3.2 on the asset store.

here's the github link
https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.3.2
