### ISSUE TITLE
Is there any default 2 handed interaction solution for v2.2 + ?

### ISSUE THREAD

**Issue by Oyshoboy** [ValveSoftware/steamvr_unity_plugin#425]
Is there any 2 handed interaction with objects solution by default, for rifles, crowbars and so on?
If no, can somebody share it, or maybe let's do it from scratch?

![image](https://user-images.githubusercontent.com/23486183/57465394-33663b00-7287-11e9-819e-63a9debacfc2.png)

P.S. I know about VRTK , but I need something light and for 2.2 version, also which will work with **VelocityMovement** interaction option

**Comment by zite** [comment]
There is not currently a built in solution for this. You may be better off asking in the developer forums here: https://steamcommunity.com/app/250820/discussions/7/
