### ISSUE TITLE
"Binding for _____ was not set. Please select bind options" issue

### ISSUE THREAD

**Issue by HoweZhu** [ValveSoftware/steamvr_unity_plugin#426]
I am currently doing some work with creating a full body avatar using FinalIK with three Vive Tracker (two trackers are 2017 model and one is 2018 model) and two vive pro controllers and one vive pro headset. I am currently using base stations 1.0. 

My unity version is 2018.2.19f1 64 bit, STEAMVR 1.3.23 and Unity Plugin 2.2.0. 

My camera and controllers are using the prefab, my trackers are using the SteamVR_TrackedObject script with the correct indexing (object is tracking fine). My scene functions fine. However this pop up (see image below) keeps coming up whenever my scene plays/builds. 

I've searched around different solutions, I've tried:
- Using the Beta and opting out of the beta
- Going into Window>SteamVR Input and tried a few settings, clicked save and generate everytime. Also tried the dashboards UI binding interface options to no avail. 
- Regenerating the SteamVR asset in the asset store and tried using the github version.
- Tried on different Project folders, same issue on every attempt.

Does anyone have any suggestion on how to fix this issue?

![image](https://user-images.githubusercontent.com/37510610/57594640-71fc3e00-7584-11e9-926a-d7a0b4a912d9.png)

**Comment by zite** [comment]
Generally this means you don't have a binding file for the specific type of tracker you have connected. I'm betting FinalIK is still using the legacy input system so that makes sense. You could try and create bindings for your trackers by selecting them in the current controller area.

**Comment by HoweZhu** [comment]
Thanks for the response, got around to testing it. Creating a binding for trackers on hand seems to have fixed the problem. Thanks for the help!!

**Comment by fengkan** [comment]
> Generally this means you don't have a binding file for the specific type of tracker you have connected. I'm betting FinalIK is still using the legacy input system so that makes sense. You could try and create bindings for your trackers by selecting them in the current controller area.

I created a binding for my trackers, and the popup doesn't appear on my computer any more, but when I run my program on other computers, the popup comes up again. Is that normal? How can I solve this problem from FinalIK side?
