### ISSUE TITLE
Plugin brakes color channels reading in displacement vertex shader

### ISSUE THREAD

**Issue by olehgavrilyuk** [ValveSoftware/steamvr_unity_plugin#428]
Bug: after import of asset reading of Color RGB channels is broken in vertex shader.
It becomes interpolated somehow in a strange wrong way with a values scaled nonlinear.
Ways to reproduce:
- Create blank Project in 2018.3.13f1 (happens in other too).
- Create Unlit shader from menu (right click -> Create -> Shader -> Unlit).
- Add Color (0.5,1,1,1) to properties, variable and to vertex vert part.
- Add update world position of vertex to vert method:
`float4 worldPos = mul(unity_ObjectToWorld, v.vertex);
worldPos.y = _MyColor.r * 10;
v.vertex = mul(unity_WorldToObject, worldPos);`
(full shader below)
- Make material with shader, put default plane on scene to (0,0,0) coords, assign material to plane
- See the plane surface moves up to y=5
- Import SteamVR asset and Agree to all default settings
- See surface drops down to y=2.13 immediately
Whats happening?

Full shader code:
```
Shader "Unlit/Test"
{
    Properties
    {
		_MyColor("Color", Color) = (0.5,1,1,1)
    }
    SubShader
    {
        Tags { "RenderType"="Opaque" }
        LOD 100

        Pass
        {
            CGPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #include "UnityCG.cginc"

            struct appdata
            {
                float4 vertex : POSITION;
            };

            struct v2f
            {
                float4 vertex : SV_POSITION;
				float4 color : COLOR;
            };

			float4 _MyColor;

            v2f vert (appdata v)
            {
                v2f o;
				float4 worldPos = mul(unity_ObjectToWorld, v.vertex);
				worldPos.y = _MyColor.r * 10;
				v.vertex = mul(unity_WorldToObject, worldPos);
                o.vertex = UnityObjectToClipPos(v.vertex);
				o.color = _MyColor;
                return o;
            }

            fixed4 frag (v2f i) : SV_Target
            {
				
                return i.color;
            }
            ENDCG
        }
    }
}
```

**Comment by zite** [comment]
Is this because you switched from linear color space to gamma? or the reverse? Try importing the plugin and not agreeing to all the settings changes.

**Comment by Ogavr** [comment]
And You are right.
It is color space issue.
Issue can be closed.
More info on mechanics behind this is in my thread on unity forums
(just for anyone being googled here)
[Link](https://forum.unity.com/threads/strange-bug-behaviour-in-color-channels-value-access-in-fragment-shader-nonlinear-channel-value.678619/)
