### ISSUE TITLE
How to adjust the camera moving scale to the real world in Unity?

### ISSUE THREAD

**Issue by elvindp** [ValveSoftware/steamvr_unity_plugin#43]
Hi, I try to make the feedback of the camera movement larger in Unity because my movement space is quite small and I hope that with a little movement in real world, I can have a larger movement in Unity than the default scale. but I did not find any way to get the camera position offset parameter in Unity.
I read the source codes and find that it seems that the script "steamVR_trackedObject" in camera is redundant, while the "steamVR_camera" will add the camera into "steamVR_render" and disable the "steamVR_trackedObject". And the steamVR_render will directly render the frame of the camera so that it is unable to adjust the camera movement. Maybe am I wrong?
Anyway, my problem is that how I can adjust the steamVR_camera's move scale to the real world. I would be very appreciate if you can help me out. Thanks!

**Comment by aleiby** [comment]
You should be able to change Tranform.scale on the camera.  This will scale both the camera movement *and* the IPD (distance between eyes) which will affect how big things appear.  If you don't scale these both similarly, then you will make people sick.

**Comment by elvindp** [comment]
Do you mean that change the transform.localscale of the camera? I try to change it but the movement still the same as before.

**Comment by elvindp** [comment]
And if I change the transform.localscale on the parent of the camera, the view will be very strange. It seems that the vertical axis y will change much even if I set the y localscale as 1f.
