### ISSUE TITLE
How to start/stop at runtime?

### ISSUE THREAD

**Issue by cpetry** [ValveSoftware/steamvr_unity_plugin#430]
Currently it somehow works quite well using SteamVR plugin when starting my standalone application build.  
SteamVR gets automatically started and is started successfully.  

Problem though: Once my headset gets to sleep, I can't re-enable it. I have to restart the standalone application build.

Is there a way to initialize SteamVR while running the unity application?  Ideal would be checking if a headset exists and then initializing. When gone, it should disable it again.
If there is a solution, a Wiki entry would also be nice :)

**Comment by zite** [comment]
Which headset is this with?

**Comment by cpetry** [comment]
Does it matter? I would like to be able to do this with all headsets available out there.
Currently I have a WMR Headset from Lenovo and the HTC Vive available.

**Comment by zite** [comment]
I'm trying to replicate what you're describing. The headset going to sleep should not disrupt steamvr. Or are you talking about disconnecting your headset?

**Comment by cpetry** [comment]
It's not steamvr that gets closed. It's the unity application build that gets shutdown along. Even when I try stopping it by application.wantsToQuit event handling.

**Comment by zite** [comment]
When the plugin receives a quit event it tries to exit the application. But headsets going to sleep should not cause this.

Unity reinitializing SteamVR after a quit event isn't a super supported scenario. You could try SteamVR.Initialize(true);
You may also want to uncomment the line that causes the application to quit: https://github.com/ValveSoftware/steamvr_unity_plugin/blob/master/Assets/SteamVR/Scripts/SteamVR_Behaviour.cs#L232

But again, SteamVR (or the application) should not exit when a headset goes to sleep. If you want to open a separate issue for that we can troubleshoot that.
