### ISSUE TITLE
Hand GetTrackedObjectVelocity(), GetEstimatedPeakVelocities() etc use 'TransformVector' instead of 'TransformDirection'

### ISSUE THREAD

**Issue by RodGreen** [ValveSoftware/steamvr_unity_plugin#437]
Hand GetTrackedObjectVelocity, GetEstimatedPeakVelocities use 'TransformVector' instead of 'TransformDirection'
Which means any final world relative scale values will be applied to the velocities. Resulting in inaccurate values if any scale exists in the hierarchy

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
