### ISSUE TITLE
SteamVR Plugin breaks Unity's built-in XR input system

### ISSUE THREAD

**Issue by DrummerB** [ValveSoftware/steamvr_unity_plugin#441]
#### Summary

Adding components from the SteamVR Unity Plugin to a scene seems to cause Unity's built-in XR input system to break.

It would be nice if one could use the built-in XR module together with the external plugins for platform-specific features (e.g. render models and avatars).

#### Steps to reproduce

1. Create a new project (tried with Unity 2019.1.0, 2019.1.4 and 2019.2.0b3)
2. Import the SteamVR Unity Plugin (tried Asset Store version 2.2)
3. In a new scene, add a simple script to read out controller button states using the UnityEngine.XR.InputDevice class (example below).
4. Play the scene, press the button. This should still work
5. Drop a [CameraRig] prefab into the scene, then immediately delete it. 
6. Play the scene again, press the button. Now it doesn't register input anymore.

#### Notes

No SteamVR Plugin scripts need to actually be present in the scene at runtime for the Unity XR input system to break. Simply adding one of the scripts to the scene, then removing it again already triggers the broken behavior. Doesn't have to be the [CameraRig] specifically, but some of the scripts that trigger some kind of internal initialization of the plugin.

I noticed that removing the [ExecuteInEditMode] in SteamVR_RenderModel delays the issue until the scene is actually started with the [CameraRig] still being present. Simply adding and immediately removing it is not enough.

#### Example 

```
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.XR;

public class ControllerInput : MonoBehaviour
{
    List<InputDevice> devices = new List<InputDevice>();
    void Update()
    {
        InputDevices.GetDevicesWithRole(InputDeviceRole.RightHanded, devices);
        foreach (var device in devices)
        {
            if (device.TryGetFeatureValue(CommonUsages.triggerButton, 
                    out var triggerState) && triggerState)
            {
                Debug.Log($"Pressing {device.name} - {CommonUsages.triggerButton.name}");
            }
        }
    }
}
```

**Comment by zite** [comment]
Unfortunately this is not possible with the current design of unity's XR system. We are working with them for the new Input System that is based on actions and is more inline with the OpenXR spec.

You should still be able to use the old version of the unity plugin to accomplish some of these goals though: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/1.2.3
