### ISSUE TITLE
cs 1.6 fps stuck

### ISSUE THREAD

**Issue by keeeennnji** [ValveSoftware/steamvr_unity_plugin#442]
i've played cs 1.6 for a few days and then after Windows update i stuck at 4/5fps (in main menu) and 20 fps (in game/map/server) 

my device is acer aspire V5-122p
Windows 10 64bit
6gb ddr3 memory
amd a6 1450
amd radeon hd 8250

**Comment by zite** [comment]
Sorry this is not the counterstrike support forum.

**Comment by keeeennnji** [comment]
sorry
