### ISSUE TITLE
Update to 2019.3.0a4 breaks SteamVR

### ISSUE THREAD

**Issue by gkapellmann** [ValveSoftware/steamvr_unity_plugin#444]
I have tried to update to Unity 2019.3.0a4 and it broke all the project, mainly because it says that the "GUI Layer" or something similar has been removed, and all the "UnityEngine.UI" libs have changed.

This has produced a good amount of errors, some of them in the SteamVR plugin.

Is this just me? Or this will need to re-adapt some libs?

**Comment by gigiwotou** [comment]
I have the same problem. How did you solve it?

**Comment by gkapellmann** [comment]
Haven't solved it, i had no time to get stuck with it, so I just went back to the previous version, for now.

**Comment by AristokratOne** [comment]
It has been observed that as of 2019.2.0b1, UnityEngine.UI is no longer included as a DLL and rather as source in BuiltInPackages, which may be related. 
To fix it look for the file SteamVR.Asmdef , open it with a text editor and in references add add:
"references": [
        "SteamVR_Windows_EditorHelper",
        "Unity.ugui"

**Comment by zite** [comment]
Thanks @AristokratOne. I included this version of the asm in the version of the plugin that just shipped to the asset store.

**Comment by gkapellmann** [comment]
Is it really solved?

Just downloaded the fixed version from the asset store and I installed Unity 2019.3.0a5, but I still get multiple errors (not as many as before though), mainly saying:

The namespace UnityEngine.UI cant be found, which if I delete then its solved, but...
The namespace Text, and other related components are not been found.

Also, Image, BasiInputModule, EventSystem...

Or am I missing something?

**Comment by gkapellmann** [comment]
Forget my project, if you open a totally new project and the first thing you do is import the SteamVR asset from the store in 2019.3xxxx the same errors appear (16 errors).

**Comment by zite** [comment]
You’ll need to delete the SteamVR.asmdef and rename SteamVR.asmdef.20192 to
SteamVR.asmdef. Unity 2019.1 has problems importing the asmdef if it has
the new ui line in it since it doesn’t exist for that version.

**Comment by gkapellmann** [comment]
I see!

Yes, that solved the problem of the simple project, but with the one I've been working, it got a set of new errors, I've never seen them:

UnassignedReferenceException: The variable trackingOriginTransform of Player has not been assigned.
You probably need to assign the trackingOriginTransform variable of the Player script in the inspector.
UnityEngine.Transform.get_position () <0x13138112270 + 0x0006a> in <39b3f9801916460c91c1f5e3a3e521e5>:0
Valve.VR.InteractionSystem.Player.get_feetPositionGuess () (at Assets/SteamVR/InteractionSystem/Core/Scripts/Player.cs:222)
Valve.VR.InteractionSystem.Player.OnDrawGizmos () (at Assets/SteamVR/InteractionSystem/Core/Scripts/Player.cs:313)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

When the project is opened, it starts with 55 errors, all the same like this, and as time passes by I get a new one every time the mouse travels through the editor or the editor gains focus.

Is it something in my configuration?
