### ISSUE TITLE
How to represent hand prefab with SteamVR using Photon (unity)?

### ISSUE THREAD

**Issue by Davidkatom** [ValveSoftware/steamvr_unity_plugin#445]
I'm working on a multiplayer project in unity, and I have set up the Player prefab with final IK. I'm using SteamVr and it has its own way to represent hand and finger position. I am wondering if there is a way to synchronize it with Photon.

**Comment by zite** [comment]
Sorry, this would probably be best asked on the photon forums or the steamvr developer forums: https://steamcommunity.com/app/250820/discussions/7/
