### ISSUE TITLE
AUX Bones issues on custom rig.

### ISSUE THREAD

**Issue by BrunoRenirie** [ValveSoftware/steamvr_unity_plugin#446]
Hi there, we are currently making a game and we want a pair of custom hands. We got the rig working other than the AUX bones. They always have a weight on them and deform the mesh. We cant figure out how to ignore the aux bones, the rest of the rig works fine. Thank you for your time.

**Comment by kisak-valve** [comment]
Hello @BrunoRenirie, this issue is already being discussed on #398. Feel free to join the discussion there.

Closing as a in favor of the existing issue report.
