### ISSUE TITLE
 OpenVR.Input.SetActionManifestPath(fullPath) fails on network drives

### ISSUE THREAD

**Issue by selfishReplicator** [ValveSoftware/steamvr_unity_plugin#447]
OpenVR.Input.SetActionManifestPath(fullPath) fails if a Unity build is started from a network drive with a UNC path name like: //computername/path/...

It works alright with a fullpath like C:/path/...

A took me quite a while to realize that the location where my builds were started from was relevant!

The result was that controllers where not found when starting from a network drive, but everything works fine when starting from a local disk.

**Comment by tshead** [comment]
I’ve run into this too, using Windows 10, Unity 2019.1, and SteamVR plugin 2.2.

Glad it isn’t just me.
Tim

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
