### ISSUE TITLE
Bindings UI allows creating bindings that are ignored at runtime (bool source -> vector1 action)

### ISSUE THREAD

**Issue by dubois** [ValveSoftware/steamvr_unity_plugin#448]
Context: Tilt Brush has a vector1 action that controls whether the user is painting; the float value indicates the "pressure" of the stroke. For accessibility reasons I was curious whether boolean input sources (eg, trigger touch or trackpad touch) could be mapped to vector1 actions; and if so, what the bool -> float conversion would be.

1. Create a Vector1 action called "Test float".
2. Open the knuckles bindings UI and add an action to `Trackpad -> Button -> Touch`.
3. Note that the dialog lists both "Boolean Actions" and "Vector1 Actions"
4. Bind to the vector1 action called "Test float" and save bindings
5. Open the SteamVR Input Live View and hit play in editor

Expected results: The live view's value for "Test float" is yellow, indicating that a binding exists.
Actual results: The live view's value for "Test float" is colored red, indicating that no binding exists.

Alternative expected results: in step 3, the dialog lists only "Boolean Actions".

**Comment by zite** [comment]
Thanks for the report! We've got a fix for this that should come in the SteamVR Beta in the next few days.

**Comment by zite** [comment]
This SteamVR Beta update just shipped.

**Comment by zite** [comment]
This should be fixed in the SteamVR version that just shipped. Closing this issue.
