### ISSUE TITLE
Change defaut hands from Steam VR

### ISSUE THREAD

**Issue by Sam024033** [ValveSoftware/steamvr_unity_plugin#449]
Hi everyone,

I would have liked to know if it was possible to change the default hands offered in the Steam VR package. I rigged a hand in 3Ds max, using the same hierarchy of bones as the vr_glove_slim, namely 31 bones, including a Root, wrist and 5 auxiliary bones attached to each finger.
The bones are named exactly the same way as the model used for the prefab.
When I replace the prefab to use by that of my hands, the animations react but the skin is completely destroyed ...
Would there be documentation somewhere that explains in detail the procedure to follow?

**Comment by BrunoRenirie** [comment]
We currently have the same issue, what i am suspecting is that the aux bones have effect on the rig which breaks everything. The documentation on this is awfull and really has to be more clear.

**Comment by Sam024033** [comment]
Sure :(

I leave here a method that I found and that works well, it will just drag your prefab of hands in the Render Model Prefab. I recommend using Blend Shapes rather than Animation States in order to have intermediate states between two hand positions.

https://wirewhiz.com/vr-hands/

**Comment by BrunoRenirie** [comment]
I got a little further, it turns out that unity creates its own blending weights for the imported mesh and you have to turn those all off, if you got to the model thats imported you have to copy their import settings: https://gyazo.com/e721e326c1d1453f53fe4899aa9521c0
