### ISSUE TITLE
SteamVR controller function loss after scene change

### ISSUE THREAD

**Issue by Dr-Function** [ValveSoftware/steamvr_unity_plugin#450]
Hello! Our question relates to developing a game using SteamVR. We've reach out over the community boards but unfortunately haven't found a solution yet.

Our team is developing a game in Unity using the SteamVR plug-in for the gesture support and teleportation mechanics. Everything has been working well until we ran into the following problem. We could use a little help troubleshooting. 

Problem: When switching scenes (in Unity play mode or in the built game), the left controller hand becomes deformed and teleportation mechanics are lost on both hands. In the linked video at the start, the hands look fine and teleportation via thumbstick depression works on both hands. Then after the player changes scenes partway through the video, the left hand become deformed and the teleportation mechanics are lost. 
Video link:
https://www.youtube.com/watch?v=vYyg_btLhpE&list=WL&index=3&t=0s

Thing we've tried and other important details:
-The problem does not occur in each of the two scenes individually. I only come across the error after loading to a different scene during Unity play mode or in the built game.
-SteamVR assets exist as needed in both scenes including the player assets and teleportation assets for each scene to be fully functional individually.
-The are two yellow flag Unity errors (can be seen in lower left of Unity screen on video) but I don't think these are causing this problem as they are also present when the problem is not occurring.
-Versions: Unity 2018.3.9f1. SteamVR 2.2.0
-Hardware: Gigabyte P57 laptop with GTX 1070. Oculus Rift with touch controllers and 2 outside-in IR sensors.

Is it a bug or maybe it is an error on our part?

Thanks!

**Comment by zite** [comment]
Looks like you've got Don't Destroy On Load set on your SteamVR_Behaviour in your player prefab (the default). You probably want to uncheck this. Or move the [SteamVR] object outside your player prefab.

![image](https://user-images.githubusercontent.com/198704/59122768-6f390280-8910-11e9-9e5c-2f15dd825f17.png)

**Comment by Dr-Function** [comment]
Keith you're a genius!!  Problem fixed thank you SO much it works perfect now!
