### ISSUE TITLE
Steam VR input window disappeared

### ISSUE THREAD

**Issue by Rollerpaw** [ValveSoftware/steamvr_unity_plugin#452]
Hi, I am experiencing something really weird right now. Today when I opened Unity, the "Steam VR Input" and "SteamVR Input Live View" windows under the "Window" tab are gone. And even if I delete and reimport the asset it doesn't help. Also the whole asset folder looks bizarre. The "Steam VR Unity Plugin.PDF" and "Steam VR Unity Plugin - Input System.PDF" files are all gone. Instead there is one "quickstart.PDF". And sample scenes are slightly different too. Was there an update recently? If there was and this is normal, how can I do the action set binding things if I can't find the SteamVR Input window?
Thanks a lot.
![image](https://user-images.githubusercontent.com/51768599/59397171-fda8fa80-8dce-11e9-813e-f48536a8d494.png)
![image](https://user-images.githubusercontent.com/51768599/59397176-00a3eb00-8dcf-11e9-9797-ed355759a4f7.png)

**Comment by zite** [comment]
Seems like you loaded an old version of the plugin. It's just been updated on the asset store a few hours ago. I'd try reimporting again, making sure you have version 2.3.2.

**Comment by Rollerpaw** [comment]
> Seems like you loaded an old version of the plugin. It's just been updated on the asset store a few hours ago. I'd try reimporting again, making sure you have version 2.3.2.

Yeah I think that was the problem. Do different versions of Unity import different versions of StreamVR automatically? Because the problem was solved when I import the plugin from another computer and copy it to the computer connected to VR. On the VR computer for some reason we can't update Unity, so every time I import SteamVR it's still the old version. But it doesn't make sense if I can use the new SteamVR on the old Unity but just can't import it.
Thanks.

**Comment by zite** [comment]
Unity down to 5.4.6 should import the plugin version 2.3.2. If you have an older version downloaded and aren't connected to the internet (or unity is having problems connecting) it won't update the version of the plugin you import.
