### ISSUE TITLE
Having trouble with using two hands to interact with Objects in SteamVR plugin

### ISSUE THREAD

**Issue by Wojtex28** [ValveSoftware/steamvr_unity_plugin#453]
Hello, 
I am making a small VR app and I came across a problem with using objects that require two hands simultaneously. 

So, every time I grab my object with two hands things seems to work fine, but when I release one hand and at the same time I hold an object with only second prop slowly falls to the ground,

My guess is that there is something wrong with Interactable script, but so far I couldn't solve it by myself. Is there any example or method to solve this problem?

**Comment by zite** [comment]
Currently the interaction system doesn't support this. This is more a section for bugs than suggestions on implementing features. I'd recommend the steamvr developer forum here: https://steamcommunity.com/app/250820/discussions/7/
