### ISSUE TITLE
New 2.3.2 Not working with MacOs and unity 2019.1.6 

### ISSUE THREAD

**Issue by balamsoto** [ValveSoftware/steamvr_unity_plugin#456]
vive headset is completly black with this new version.
using the previous version example file loads fine.

**Comment by balamsoto** [comment]
[SteamVR] Interface Not Found (105)
UnityEngine.Debug:LogWarning(Object)
Valve.VR.SteamVR:ReportError(EVRInitError) (at Assets/SteamVR/Scripts/SteamVR.cs:229)
Valve.VR.SteamVR:CreateInstance() (at Assets/SteamVR/Scripts/SteamVR.cs:178)
Valve.VR.SteamVR:Initialize(Boolean) (at Assets/SteamVR/Scripts/SteamVR.cs:98)
Valve.VR.SteamVR_Behaviour_Pose:OnEnable() (at Assets/SteamVR/Input/SteamVR_Behaviour_Pose.cs:88)

[SteamVR] Interface Not Found (105)
UnityEngine.Debug:LogWarning(Object)
Valve.VR.SteamVR:ReportError(EVRInitError) (at Assets/SteamVR/Scripts/SteamVR.cs:229)
Valve.VR.SteamVR:CreateInstance() (at Assets/SteamVR/Scripts/SteamVR.cs:178)
Valve.VR.SteamVR:Initialize(Boolean) (at Assets/SteamVR/Scripts/SteamVR.cs:98)
Valve.VR.SteamVR_Behaviour_Pose:OnEnable() (at Assets/SteamVR/Input/SteamVR_Behaviour_Pose.cs:88)




OpenVR Shutdown



[SteamVR] Could not instantiate OpenVR Input interface.
UnityEngine.Debug:LogError(Object)
Valve.VR.SteamVR_Input:IdentifyActionsFile(Boolean) (at Assets/SteamVR/Input/SteamVR_Input.cs:1269)
Valve.VR.SteamVR:InitializeTemporarySession(Boolean) (at Assets/SteamVR/Scripts/SteamVR.cs:321)
Valve.VR.RenderModelInterfaceHolder:get_instance() (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:90)
Valve.VR.SteamVR_RenderModel:SetModel(String) (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:303)
Valve.VR.SteamVR_RenderModel:Update() (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:721)

**Comment by zite** [comment]
Looks like we haven't updated the mac sdk. I'd recommend sticking with the version that worked for now if you're dependent on mac support.

**Comment by balamsoto** [comment]
thanks.  any ETA for the Mac Update?

**Comment by n1n3b1t** [comment]
Also interested if steamvr runtime would be updated for Mojave or upcoming Catalina? Metal seems to have all needed parts for VR. If valve developers isn't interested in supporting macOS, maybe they can open source a code for platform integration?

**Comment by indus** [comment]
#466 & #474 make me think this is not only a problem on mac but also on windows

**Comment by lukasmaxim** [comment]
Exact same issue here on Catalina. Any ETA on an update?

**Comment by zite** [comment]
https://store.steampowered.com/news/app/250820/view/2216278054495230717
