### ISSUE TITLE
Custom hands model

### ISSUE THREAD

**Issue by maciejgorskiwenklystudio** [ValveSoftware/steamvr_unity_plugin#457]
How to prepare hands custom hands model fo knuckles?
Most importan is to know if I have to use exacly same rig structure with same names?
Is there any guide hwo to prepare models?
Thanks in advance!

**Comment by xVinicius** [comment]
In theory you just need to follow the bone structure for the custom hand model as it is described in [OpenVR Wiki](https://github.com/ValveSoftware/openvr/wiki/Hand-Skeleton). 

The skeletons with an example mesh are located here:
`Steam\steamapps\common\SteamVR\resources\skeletons\vr_glove_right_skeleton.glb`

You have to follow the same nomenclature, order, hierarchy, units and coordinate system.

*BUT*

When exported from Blender I'm not able to get it to work in Unity, the hands get all distorted. I even tried mapping it to the `SteamVR_Behaviour_SkeletonCustom` script without success.

I hope for a better guide on creating (from scratch) and exporting (settings and units) custom hand models, for now I use animations to drive the hands and fingers :(

**Comment by maciejgorskiwenklystudio** [comment]
Thanks. Your answer helped me a lot. And maybe I will help with your issue.
I had no problems with exporting rigged hand. I have imported to blender default hand added to pack for unity: vr_glove_left_model_slim. In blender I've just added my model to imported bones with automatic weights and corrected it manualy when needed. 
I hope it will hepl you!
![customHandExportAndImport_blender](https://user-images.githubusercontent.com/28386222/59755790-d64ba500-9288-11e9-9ef2-f68c852bd7fd.jpg)

**Comment by attharmirza** [comment]
This thread helped me out SO MUCH, thank you. @xVinicius the part that helped me was making sure Apply Scalings was set to "FBX All" and also making sure I didn't change a single thing when importing Valve's default skeleton. Originally, I was forcing the child bones to align to their parents so that I could model the hand more easily. But that messes up the output.
