### ISSUE TITLE
No controllers using the latest SteamVR with 2017.1 

### ISSUE THREAD

**Issue by pateras** [ValveSoftware/steamvr_unity_plugin#46]
I did the following:

1. Installed the latest Unity 2017.1 release candidate.
2. Imported the latest version of SteamVR (v1.2.2) via the asset store.
3. Per the SteamVR Quickstart PDF, I clicked on MainCamera, added a "Steam VR_Camera" script, and then clicked Expand.
4. This didn't work at all (moving the headset did nothing), so I went to Player Settings > Other Settings, checked "Virtual Reality Supported" and added the OpenVR SDK.

That got the headset working, but now the controllers don't show up.

**Comment by pateras** [comment]
Tried Unity 5.6.2. Same results.

**Comment by pkarjala** [comment]
Related to #49; solution is to remove MainCamera from the scene, and instead drag the Assets>SteamVR>Prefabs>[Camera Rig] object into the scene.

This should fix the issue.

**Comment by stuartdalrymple** [comment]
Hi all - I'm following a Hello World tutorial (which is going well!) however I can't see my controllers in the scene. They are working, as when I open up the SteamVR menu or sit in the pre-loading room, they are there. All lights on the SteamVR are green. I have removed the default camera and added the SteamVR camera rig as detailed above.

Can anyone link or detail beginner-friendly steps to getting the controllers to appear in scene? Thanks in advance :)
![no-controllers-shown-in-scene](https://user-images.githubusercontent.com/11348612/34967904-fc072f8e-fab9-11e7-99b3-07f6571707ab.jpg)

**Comment by zite** [comment]
Thanks for the reports. I believe these issues have been fixed with the latest version of the plugin released today. If this is still an issue let me know and I'll reopen.
