### ISSUE TITLE
SteamVR_RenderModel Custom Shader is null in Interactions_Example scene

### ISSUE THREAD

**Issue by MaZyGer** [ValveSoftware/steamvr_unity_plugin#460]
If I use the Lightweight Render Pipeline and update materials everything works fine. I also used the LWRP Shader with SteamVR_RenderModel Prefab. So CameraRig works fine and shader is applied to the controller. But if I am using the Interactions_Example Scene where the Player prefab spawns the controller it doesn't work. Shader variable is NULL. I even can see in the Inspector the shader variable is there and assigned.. but still the (WMR) controller are pink and in the inspector I can see they use default shader and not the assigned shader (because shader is null).
I wanted to figure out why the variable is NULL even it is assigned in the inspector but I couldn't figure out.

My hardcore solution was to edit SteamVR_RenderModel and make from default to `Shader.Find("Lightweight Render Pipeline/Lit")`
https://github.com/ValveSoftware/steamvr_unity_plugin/blob/master/Assets/SteamVR/Scripts/SteamVR_RenderModel.cs#L455 #

**Comment by zite** [comment]
We're not planning to support LWRP as its being deprecated for URP. If not please create a new issue with repro steps and ideally an example project. Thanks!
