### ISSUE TITLE
SteamVR_TestIK scene not setup properly

### ISSUE THREAD

**Issue by benblo** [ValveSoftware/steamvr_unity_plugin#463]
Hi, I'm using the latest version of the plugin from the Asset Store, with Unity 2019.1.8f1, and tried running the SteamVR_TestIK scene: it spams errors due to both hands' target and poleVector transforms being unassigned:
```
UnassignedReferenceException: The variable target of SteamVR_IK has not been assigned.
You probably need to assign the target variable of the SteamVR_IK script in the inspector.
UnityEngine.Transform.get_position () <0x1b597d6c3f0 + 0x0006a> in <c0ef81e1639b423ab35ce0e4c08b5b7a>:0
Valve.VR.SteamVR_IK.LateUpdate () (at Assets/SteamVR/Scripts/SteamVR_IK.cs:30)
```
Maybe the IK script was updated with new fields and the scene wasn't modified?

I tried assigning whatever transforms in there, it removed the error but obviously the IK doesn't work as expected :) ! What's the proper setup?

**Comment by DesperateHouseDev** [comment]
Up. 
Same issue here, with the same questions...

**Comment by zite** [comment]
This scene is deprecated

**Comment by Bengt** [comment]
Since the scene is deprecated and throws errors, please delete it to avoid any user confusion.
