### ISSUE TITLE
RemoveOnStateDownListener does not remove

### ISSUE THREAD

**Issue by MaZyGer** [ValveSoftware/steamvr_unity_plugin#464]
```
public void OnGetHand(Hand hand)
{
	usedHand = hand;
	fireAction.AddOnStateDownListener(FireAction_onStateDown, hand.pose.inputSource);
}

public void OnLeaveHand(Hand hand)
{
	usedHand = null;
	fireAction.RemoveOnStateDownListener(FireAction_onStateDown, hand.pose.inputSource);
}


private void FireAction_onStateDown(SteamVR_Action_Boolean fromAction, SteamVR_Input_Sources fromSource)
{
	Fire();
}
```
Hello if I use AddOnStateDownListener everything works fine. If I use RemoveOnStateDownListener it does not work. So The button on my controller still triggers the FireAction Function. I see it also in the Input Live View
I am not sure if this is a bug or I do it wrong.

**Comment by timetosmile** [comment]
Why are you using the 'hand.pose.inputSource' ?

I'm using 'hand.handtype' and it working fine so far.

**Comment by zite** [comment]
I believe this has been fixed since this post was made. If not, please create a new issue with the repro steps and ideally an example project to replicate the issue. Thanks!
