### ISSUE TITLE
Teleport area does not draw outline like in The Lab (#87 reopened)

### ISSUE THREAD

**Issue by Gotcab** [ValveSoftware/steamvr_unity_plugin#465]
I am implementing a teleport area in a shape that is not square and I would like to display the outline like in The Lab. It is a thick outline following the mesh's border.

Like this: 
![2019-06-28_13-01-16](https://user-images.githubusercontent.com/18290502/60358704-df352880-99a4-11e9-9bff-73e081e79dcd.png)

As you can see in the red circle. There is an outline following the teleport area mesh border.

My question is: How do we achieve this in Unity?

Do I need a special shader not provided by SteamVR Plugin?

**Comment by zite** [comment]
This is outside the scope of this github. Please see the developer forums here: https://steamcommunity.com/app/250820/discussions/7/
