### ISSUE TITLE
OpenVR Input Interface not found (105). Offline machine, SteamVR without Steam

### ISSUE THREAD

**Issue by tyrellturley** [ValveSoftware/steamvr_unity_plugin#466]
My vive controllers aren't showing up in the scene, and I'm getting the following warnings and errors when running the Simple Sample scene in Play Mode:
```
[Steam VR] Interface Not Found (105)
Valve.VR.SteamVR:ReportError(EVRInitError) (at Assets/SteamVR/Scripts/SteamVR.cs:229)
Valve.VR.SteamVR:CreateInstance() (at Assets/SteamVR/Scripts/SteamVR.cs:178)
Valve.VR.SteamVR:Initialize(Boolean) (at Assets/SteamVR/Scripts/SteamVR.cs:98)
Valve.VR.SteamVR_Behaviour_Pose:OnEnable() (at Assets/SteamVR/Input/SteamVR_Behaviour_Pose.cs:88)

[SteamVR] Could not instantiate OpenVR Input interface.
Valve.VR.SteamVR_Input:IdentifyActionsFile(Boolean) (at Assets/SteamVR/Input/SteamVR_Input.cs:1269)
```
My environment is unique in that I am on an offline machine, and I have SteamVR installed without Steam (This was done by installing Steam and SteamVR on an online machine, and then moving over just the SteamVR folder from the Steam install to my offline machine). I also had to download the SteamVR plugin on my online machine and copy over the SteamVR plugin .unitypackage file to my offline machine. 

My guess is that my problem stems from not having Steam installed. Is there a way around this?

I'm using SteamVR 1.3.23, SteamVR Unity plugin v2.3.2, and Unity 2017.4.10 on a Windows 10 machine.

I have generated an actions.json file using the example files, but that didn't fix it.

**Comment by autofish** [comment]
I have same problem!

**Comment by indus** [comment]
It looks like this is related to #474

**Comment by waikikamoukow** [comment]
Updating to SteamVR 1.5.16 solved this issue for me.

**Comment by zite** [comment]
I believe this has been fixed since this post was made. Generally try to use the latest version of SteamVR. If not, please create a new issue with the repro steps and ideally an example project to replicate the issue. Thanks!
