### ISSUE TITLE
Binding UI does not report an error when trying to save a binding with required inputs missing

### ISSUE THREAD

**Issue by Fewes** [ValveSoftware/steamvr_unity_plugin#467]
I received my Index controllers today and wanted to start implementing bindings for them. However, I can no longer save any bindings using the UI. Pressing "Save" in either the "Save Personal Binding" or "Replace Default Binding" dialogue just results in nothing happening. Nothing saved, no errors, nothing. Happens in both stable and beta version of SteamVR.

**Comment by Fewes** [comment]
After fiddling around with it a bit I noticed the browser console reported that the save failed because some required bindings were not set. The UI itself did not report this, however.

**Comment by sebjf** [comment]
I've nothing to add other than to say thank you for reporting this issue. I was having the same symptoms and only found the cause after finding this. There is nothing in the docs to indicate that we should be looking at the browser console for error information.

**Comment by zite** [comment]
I believe this has been fixed since this post was made. If not, please create a new issue with the repro steps and ideally an example project to replicate the issue. Thanks!
