### ISSUE TITLE
Tracking issue on Oculus.

### ISSUE THREAD

**Issue by Neuxz** [ValveSoftware/steamvr_unity_plugin#468]
Hello,
im trying get the SteamVR Sample Scene to run.

Problem is that the HMD(Rift S) get detected and tracked, but the controllers not.

What i tryed so far:

- I've removed the Oculus SDK and use only the OpenVR one.
- I tested the default controll cheme and an custom one.
- I tested the Player and VRCamera Prefab.

It seems that the HMD get its index but the controllers not.

There was once an [issue](https://github.com/ValveSoftware/steamvr_unity_plugin/issues/51) with the same problem but it has been closed without solution.

**Comment by zite** [comment]
I believe this has been fixed since this post was made. If not, please create a new issue with the repro steps and ideally an example project to replicate the issue. Thanks!
