### ISSUE TITLE
SteamVR_Behaviour_Skeleton not working correctly in build.

### ISSUE THREAD

**Issue by cocapasteque** [ValveSoftware/steamvr_unity_plugin#469]
Hello,

I have an avatar that is driven by the VRIK from FinalIK and I control the hands with the Skeleton_Behaviour from SteamVR.
My avatar is composed of two skinned mesh for the hands and one skinned mesh for the body.

Here's my bone hierarchy : 
![Hierarchy](https://user-images.githubusercontent.com/10882518/60529658-5ba66f00-9cf7-11e9-93a0-3c2956c58201.png)

And the setup of the Skeleton_Behaviour here : 
![Skeleton Behaviour](https://user-images.githubusercontent.com/10882518/60529756-96100c00-9cf7-11e9-88a9-11ecd41b4ff7.png)

The position of the hand is set by VRIK and the rotation by SteamVR.
It is working super good in the Editor but whem I build, the rotations of the hands are not working at all.

Here's what I tried so far :
- Playing with the Quality of the Skinned mesh renderer (1,2,4 bones), same in Graphics settings, put the bone count to unlimited.
- Setting the origin of the Behaviour_Skeleton to the Forearm and some different bones.
- Adding an animator (?) to the Hand objects.
- A lot of other different things, that are maybe not related with this issue at all but we never know...

So the thing is that it's working good and realiably in the editor but not in the build. Are there any Build depedent settings that I may have skipped somewhere or I am doing something wrong.

Thanks !

**Comment by Gotcab** [comment]
Are you using Vive trackers for the skeleton? If so, make sure that you have a json binding file for the trackers and add it to actions.json. For me, it did not add itself either to the build.

Your project bindings should look something like this:
![bindings files](https://user-images.githubusercontent.com/18290502/60534385-af04c700-9ccf-11e9-824b-9d556f4a940c.png)
 
My trackers binding file is **vive_tracker_handed.json**

Look at the end of your binding file, it should look something like this:
![bindings file end](https://user-images.githubusercontent.com/18290502/60534467-e5424680-9ccf-11e9-945e-6b71b13b64ef.png)

For my case, I need the trackers to act as hands. So my **controller_type** is set to **vive_tracker_handed**.
Copy this line, you need to add it to **actions.json** if it is not already there.

![default bindings](https://user-images.githubusercontent.com/18290502/60534575-23d80100-9cd0-11e9-806b-10b61ee6bc17.png)

The part in the rectangle was not set automatically for me. Just add your controller type and the name of your binding file there. Don't forget to add the curly braces and stuff...

**Comment by cocapasteque** [comment]
@Gotcab no, I'm using the Vive Controllers, the trackers are attached to the feet.
My actions.json and controller bindings are correct : 

actions.json
```
  "default_bindings": [
    {
      "controller_type": "vive_controller",
      "binding_url": "bindings_vive_controller.json"
    }
```

bindings_vive_controller.json
```
  "controller_type": "vive_controller",
  "description": "Controller Bindings for Speech Trainer",
  "name": "vive_controller_speechTrainer"
```

I know they work because just before enabling and callibrating the avatar with VRIK, I have a set of detached hands that work correctly with the vive controller. 
It's just when I try to use the hands on the avatar that I have the problem, but it works in the editor.
Any other ideas ?
Thanks !

**Comment by cocapasteque** [comment]
Here's a copy of the question I asked on the FinalIK forum, since I'm not sure where the problem is, I'll share it here to have more insight on the question, you have gifs and pictures attached to get a better understanding of the problem : 

> Hey @Partel-Lang,
> I'm using VRIK in combination with SteamVR new input system. VRIK is amazing and doing a great job.
> I have one small problem though but I'm not sure it is related to VRIK and wanted your pov on this issue.
> 
> So I use VRIK and SteamVR_Behaviour_Skeleton to get the hand poses from the vive controller and rotate the hand bones. We had to do some research to get a nice working avatar with this system. The rig and the SteamVR look like this :
> 
> https://ibb.co/N3wWyBQ
> 
> I've set SteamVR script to only set the rotation because the pose is controlled by VRIK, and the hands are not floating like other "VR Hands" but they are attached to the body skinned mesh.
> 
> Everything is working super good in the editor, but it's a whole different story in a build.
> When I want to activate the VRIK Avatar with SteamVR Hands, it looks like the rotation of the wrist is wrong and not affected at all :
> 
> This is in the editor :
> https://media.giphy.com/media/Idaoi4Q6oktwEQ3Q7K/giphy.gif
> 
> And this is in the build :
> https://media.giphy.com/media/Vd340bLD2MQGIxUoJM/giphy.gif
> 
> Do you have any ideas why this could happen ? I already asked on SteamVR github issues but no answer so far. And I don't really know where to look or where the problem comes from :/
> 
> Thank you for your amazing work and support !
> Antoine.

**Comment by cocapasteque** [comment]
I've fixed it, the issue was SteamVR and VRIK trying to modify the transform of the wrists at the same time, I gently asked SteamVR to ignore the wrist bone in the UpdateSkeletonTransforms() methode from SteamVR_Behaviour_Skeleton and it fixed it for me :) 
Closing.
