### ISSUE TITLE
Unity Video Component

### ISSUE THREAD

**Issue by dmikw** [ValveSoftware/steamvr_unity_plugin#47]
I am using the steamVR plugin for a vr app witch plays a video. Therefore I am using the unity Video player (video component). In the Unity editor everything runs fine. But when I am making an executeable (build) the video does not start ...you only see the first frame of the video.
My system is Windows 7 - and I am using Unity 5.6.2f1 (64bit)

**Comment by bddckr** [comment]
I noticed using the `VideoPlayer` API in Unity to play ogg videos doesn't work in builds, only in the Editor. This was on Windows 10, standalone build. mp4s etc. work just fine. I fall back to the old `MovieTexture` to play oggs.

Therefore I don't think this has anything to do with SteamVR.

**Comment by dmikw** [comment]
I have also tried the same application with oculus and it works fine in the exe. I have also tried the application with the vive moving the player via the arrows on the keyboard and it works fine in the exe. But when I am including the teleport function of the SteamVR plugin the video does not start in the exe. Also when it trie to start it via a keyboard command. ( in the editor it will work fine)

**Comment by dmikw** [comment]
... so i think it has something to do with the teleport-function of the SteamVR plugin

**Comment by dmikw** [comment]
... yes and i want to play an mp4 in this application

**Comment by zite** [comment]
Hi, thanks for the report. Can you try with modern versions of things and let me know if this is still an issue? Thanks.
