### ISSUE TITLE
Vive Trackers bindings not added to build automatically

### ISSUE THREAD

**Issue by Gotcab** [ValveSoftware/steamvr_unity_plugin#470]
I had a problem where my **vive_tracker_handed** bindings would work in the editor but not in the build. The problem was that my bindings were not added to the **actions.json** bindings automatically. Why it worked in editor anyway? I don't know. My fix was to simply add the bindings to the **default_bindings** list and it worked.

![default bindings](https://user-images.githubusercontent.com/18290502/60535455-2cc9d200-9cd2-11e9-89b1-b8d5f66e32e5.png)

Is it supposed get added automatically?

**Comment by zite** [comment]
I believe this has been fixed since this post was made. If not, please create a new issue with the repro steps and ideally an example project to replicate the issue. Thanks!
