### ISSUE TITLE
SteamVR Input workflow unclear

### ISSUE THREAD

**Issue by Gotcab** [ValveSoftware/steamvr_unity_plugin#471]
I can't find a place explaining how to properly use the SteamVR Input UI and what are the different parts of it. This thing is frustratingly hard to learn and understand because of the lack of documentation. Here are my questions:

1. How do action set works? Is it a set of actions for a specific device? Can I have multiple action set active at the same time to support different devices? When should I click Save and Generate and what does it do? What is the hidden option doing?

2. How do configurations works? Is a configuration valid only for a specific device? What is the difference between Personal, Default and Current configurations? When should I use which?

3. What is the difference between a configuration and a binding?

4. What happens when I click Replace default configuration? Is it replacing the configuration of other devices I made earlier? Am I loosing something?

5. Should I Save a personal configuration before replacing the default configuration?

6. Why is my Vive tracker bindings not added to actions.json automatically?

**Comment by zite** [comment]
I'll try to address these issues in the updated documentation, sorry for the delay
