### ISSUE TITLE
Missing Input Source for Treadmills

### ISSUE THREAD

**Issue by kaplat** [ValveSoftware/steamvr_unity_plugin#472]
Hello, 

I am currently working on a custom driver for a treadmill device and wrote a Unity test application to test whether a character moves when i walk in my treadmill. 
In the test application i am unable to specify that the movement event should only be triggered for a treadmill device. A device registered with the treadmill role in OpenVR seems to send SteamVR_Input_Sources.Any when i move in the Treadmill. One drawback of using SteamVR_Input_Sources.Any is that the event is also triggered for all controller events then. 

Furthermore this is a problem when applications only trigger the movement event for SteamVR_Input_Sources.LeftHand or RightHand sources (as i think many games do??), as it would never trigger for a treadmill. This is a major drawback for all treadmills implemented with treadmill role in OpenVR as they can't handle free locomotion used in many games (using the new SteamVR Input System e.g. Arizona Sunshine) anymore!

Has anyone had similar observations? Am I not implementing something correct?

Thanks in advance for all answers. I would really appreciate the help.

**Comment by andreaskern** [comment]
@kaplat you are totally correct.
for arizona sunshine for example they really do filter for `LeftHand`.
There is an older version 1_5 available in the store where they used `Any`.
something like `SteamVR_Input_Sources.Treadmill` would be great.

**Comment by kaplat** [comment]
This issue is handled in ValveSoftware/openvr#1153
