### ISSUE TITLE
OpenVR.IVRInput_Version -> Init_InterfaceNotFound

### ISSUE THREAD

**Issue by indus** [ValveSoftware/steamvr_unity_plugin#474]
With version 2.3 I'm getting an error (```Init_InterfaceNotFound```) here: https://github.com/ValveSoftware/steamvr_unity_plugin/blob/master/Assets/SteamVR/Scripts/SteamVR.cs#L175

In the end the Player script switches to the 2d debug fallback.

Everything worked fine with the 2.2 version; but I wanted to update the library.

I'm working on Windows 7 with Unity 2018.4 and SteamVR 1.3.23

Do you know what the problem could be?

**Comment by zite** [comment]
I believe this has been fixed since this post was made. If not, please create a new issue with the repro steps and ideally an example project to replicate the issue. Thanks!
