### ISSUE TITLE
No Input from WMR controllers

### ISSUE THREAD

**Issue by Ladrik** [ValveSoftware/steamvr_unity_plugin#475]
My users are reporting that WMR controllers are not working. I don't have one fore testing so I'm not sure where to look for problems.

Does anyone have experience or suggestions for getting WMR working with the new input system? Thanks!

**Comment by zite** [comment]
WMR does not currently support skeletal input. If your application relies
on this you may need to work around it. Version 2.3 of the plugin has an
example of this in the interaction system sample scene.

**Comment by Salzian** [comment]
Can confirm. My Dell Visor doesn't recognize my controllers anymore. So basically v2.3 deprecated the whole WMR family.

**Comment by clint205** [comment]
Is there a way to simply have the open palm glove (without controller setting) and still have the hand animate with button presses for WMR?  I just want the user to be able to point by pressing the grip button.  It is the solution we did for the wand controllers.

**Comment by A20T3M4** [comment]
My users are reporting the same issue, even if they try to set up their own binding their input doesn't work for them. I am not using skeletal pose. When I go to the window where I can set up SteamVR Input bindings I do not see WMR as an option, only Oculus, Vive, and Index. Why wouldn't I be able to see WMR as an option for setting up control bindings? How can I add this as an option?
![Screenshot 2020-11-04 233059](https://user-images.githubusercontent.com/22603847/98197943-d6882700-1ef5-11eb-958e-b36ac3c2d96b.png)

**Comment by zite** [comment]
This has been fixed
