### ISSUE TITLE
Scripts like LinearDrive are not Polymorphable

### ISSUE THREAD

**Issue by Ahrdie** [ValveSoftware/steamvr_unity_plugin#48]
I would like to create a custom `LinearDrive,` that moves the repositioned `GameObject` on a free axes, but when released clicks in Place at discrete Points.

That means I only have to create some new variables and change a function from `LinearDrive.` To archive this while maintaining an upgradable SteamVR Plugin, I want to Inherit the new Script from `LinearDrive` and use Polymorphism to adjust the functions I need.

Sadly, I cannot access the private variables in `LinearDrive,` because they have no Set/Get Function.

Would it make sense, if I made a pull request with these added Set/Get functions?

**Comment by Gotcab** [comment]
You should maybe make a Propriety in this case

**Comment by zite** [comment]
Hey thanks for the request. We've done a fair amount of work recently to make things more friendly to polymorphism. Let me know if this is still an issue and I'll reopen.
