### ISSUE TITLE
Deserialization Error for SteamVR_Action

### ISSUE THREAD

**Issue by hendrik-schulte** [ValveSoftware/steamvr_unity_plugin#482]
Hey,

I have lately encountered an issue concerning the deserialization of an SteamVR_Action_Boolean quite similar to an [issue](https://github.com/ValveSoftware/steamvr_unity_plugin/issues/228) i have submitted before. I have an action set *handtool* with a boolean *teleport* that is defined in the inspector. When starting the application, SteamVR seems to seek the default teleport action *default/in/teleport* (which I deleted as we don't use it), fails and sets the *teleportAction* field to null. Obviously this results in errors spamming the console.

Teleport Inspector during Edit mode:

![image](https://user-images.githubusercontent.com/22526345/61358543-cff61c00-a87a-11e9-9912-b6c0e50a21e1.png)

After entering play mode:

![image](https://user-images.githubusercontent.com/22526345/61358507-bb198880-a87a-11e9-8eed-6272ee88c2b4.png)

As a workaround, you can delete the auto assignment in Teleport.cs, line 16:

```
public SteamVR_Action_Boolean teleportAction = SteamVR_Input.GetAction<SteamVR_Action_Boolean>("Teleport");
```
to
```
public SteamVR_Action_Boolean teleportAction;
```

Strangely, this doesn't seem to happen all the time.

**Comment by JashanChittesh** [comment]
I have also seen this a lot. I have two components, one for the left hand, one for the right hand. And half my actions (all of the actions that belong to a non-default Action Set) frequently get removed from the second controller. The first always keeps them all.

In my case, there is actually little use of even having those in the Inspector, so I simply declared them all private which fixes all my problems with this issue.

The initialization code that I'm using is this:

`private SteamVR_Action_Boolean actionPlayingSkip = SteamVR_Actions.playing.Skip;`

... and this eventually calls this:

`        public CreateType GetCopy<CreateType>() where CreateType : SteamVR_Action, new()
        {
            if (SteamVR_Input.ShouldMakeCopy()) //no need to make copies at runtime
            {
                CreateType action = new CreateType();
                action.InitializeCopy(this.actionPath, this.GetSourceMap());
                return action;
            }
            else
            {
                return (CreateType)this;
            }
        }
`

(that's in SteamVR_Action.cs) ... maybe something's going wrong with this when used together with serialization? I haven't checked the code path for GetAction<SteamVR_Action_Boolean>(string) but if it's the same, that might be what's going wrong there.

**Comment by zite** [comment]
I believe this has been fixed since this post was made. If not, please create a new issue with the repro steps and ideally an example project to replicate the issue. Thanks!
