### ISSUE TITLE
NullReferenceException in SteamVR_Action_Vibration

### ISSUE THREAD

**Issue by Gotcab** [ValveSoftware/steamvr_unity_plugin#483]
I tried disabling haptics when there is a button hint on the controller by settings Haptic Flash on ControllerButtonHints.cs to **None** instead of **\actions\default\out\Haptic** but it triggers a NullReferenceException in the Execute method of SteamVR_Action_Vibration.cs at line 49. It is the SourceMap that becomes null if I set Haptic Flash to None. Is it normal and/or is it the correct way of disabling haptics on button hints?

**Comment by mertkura** [comment]
Got same error when i tried to teleport in simulation mode.
I ain't got any solution during bug trace. Null error sent from lower level API.
SteamVR_Action_Vibration.cs : 202
   OpenVR.Input.TriggerHapticVibrationAction(...

Workaround : Disabling Hand.cs -> TriggerHapticPulse functions or SteamVR_Action_Vibration.cs -> Execute function makes Teleport.cs work again. (Don't use this workaround if you need haptic feedback)
Or check for simulation-VR mode. I just modified hand.cs for handType. [Fallback camera is in any mode, hands are in Left-Right hand mode].
This error apeared after latest update of steamVR.

**Comment by zite** [comment]
This is not the correct way to disable the haptics. Unfortunately we don't have a built in way of ignoring attempts at triggering null actions. You'll need to remove the call to trigger haptic as described above.
