### ISSUE TITLE
PoGo Pins clicks not detected 

### ISSUE THREAD

**Issue by MahmoudAshraf-CIS** [ValveSoftware/steamvr_unity_plugin#484]
**is it supported to use the Vive Trackers PoGo pins ? and if so how to get the PoGo pins clicks ?**

![image](https://user-images.githubusercontent.com/20478561/61406004-4dea0f80-a8db-11e9-89fd-c7ecf21c2bb5.png)
the developers guide for the trackers [link](https://dl.vive.com/Tracker/Guideline/HTC_Vive_Tracker(2018)_Developer+Guidelines_v1.0.pdf?_ga=2.218515419.318210528.1562814897-879948222.1562814897&fbclid=IwAR063_vpReb_1R_h9P565hNulUVcUPU2vSQVlK-lVn57JjjnmJPgpP0Yc4Q)

i tried a new project in unity 2018.3.8f1 and got imported the [SteamVR Plugin](https://assetstore.unity.com/packages/tools/integration/steamvr-plugin-32647) and [ViveInputUtility ](https://assetstore.unity.com/packages/tools/integration/vive-input-utility-64219)

notice the trackers are detected and tracked in the Game play, but the clicks of the tracker pins are not detected 

here is my hierarchy that rely on ViveInputUtility  
and the `TrackerClickHandler` is just a script with functions to log messages 

when i used ViveInputUtility  simulator the logs are called but using the physical devices does not 

------------------------------

i also tried downgrading to an older version of [steamVR plugin (dupricated)](https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/1.2.3) see this [Tutorial](https://www.youtube.com/watch?v=MCiGpOSZM8A) and used the following script to get the inputs 

```c#
    using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Valve.VR;

public class Tracker : MonoBehaviour
{
    SteamVR_TrackedObject trackedObject;

    public bool trigger, trackpad, grip, menu;

    // Start is called before the first frame update
    void Start()
    {
        trackedObject = GetComponent<SteamVR_TrackedObject>();        
    }
    private void Update()
    {
        var device = SteamVR_Controller.Input((int)trackedObject.index);

        trigger = device.GetPress(Valve.VR.EVRButtonId.k_EButton_SteamVR_Trigger);
        if (trigger)
            Debug.Log("trigger");
        trackpad = device.GetPress(Valve.VR.EVRButtonId.k_EButton_SteamVR_Touchpad);
        if (trackpad)
            Debug.Log("trackpad");
        grip = device.GetPress(Valve.VR.EVRButtonId.k_EButton_Grip);
        if (grip)
            Debug.Log("grip");
        menu = device.GetPress(Valve.VR.EVRButtonId.k_EButton_ApplicationMenu);
        if (menu)
            Debug.Log("menu");
    }
}

```

and also got the 4 bools always false 

Thanks in advance 
-----------------

**Comment by bc** [comment]
I'm also interested in using POGO pins w SteamVR 2.2+

**Comment by nocanwin** [comment]
see issue #152

**Comment by zite** [comment]
Closing as duplicate
