### ISSUE TITLE
Round trip VR/no-VR works only one time

### ISSUE THREAD

**Issue by blevesque** [ValveSoftware/steamvr_unity_plugin#485]
Hi everyone,

In my house design project, you can at the end activate a VR mode (and take HTC Vive Headset and one controller) to visit the house you designed. 
It works, np.
Then, you can leave this VR mode with a button and go back to computer to change something (for example a door). It works too.
But when you re-activate VR mode to visit again, I don't know why but there is not any controller. Headset works, you can see the game world, rotate on yourself, etc. But the controller is fixed in its world position, it doesn't move or take any touch events.

I use SteamVR and OpenVR (HTC Vive). My transition is done just by deactivating the main camera and enabling Player and Teleporting SteamVR prefabs.
Unity 2019.1.10f1
Steam VR 1.5.16

The strangest thing is : It works in editor play mode, but doesn't when it's build (Controllers work only "one time")

To activate VR :

```
MainCamera.SetActive(false);
yield return new WaitForEndOfFrame();
XRSettings.LoadDeviceByName("OpenVR");
yield return new WaitForEndOfFrame();
XRSettings.enabled = true;
PlayerVR.SetActive(true);
TeleportVR.SetActive(true);
```

To deactivate VR :

```
PlayerVR.SetActive(false);
TeleportVR.SetActive(false);
XRSettings.LoadDeviceByName("None");
yield return null;
XRSettings.enabled = false;
MainCamera.SetActive(true);
```

Did someone develop a program where you could go to VR and back to no-VR as many times as you want ?

Thanks

**Comment by martamartino86** [comment]
Hi,
I had the same issue, as you can read here: https://github.com/ValveSoftware/steamvr_unity_plugin/issues/307

**Comment by zite** [comment]
I believe this has been fixed since this post was made. If not, please create a new issue with the repro steps and ideally an example project to replicate the issue. Thanks!
