### ISSUE TITLE
IgnoreHovering variant at Interactable level.

### ISSUE THREAD

**Issue by VincentFTS** [ValveSoftware/steamvr_unity_plugin#488]
It would be useful to duplicate the IgnoreHovering mechanism at Interactable level.
I mean, it can be difficult to add an IgnoreHovering component (and manage it by script) for each sub collider of each sub GameObject.

In the Hand component, we could test the existence of an IgnoreHovering component on the Interactable component (as it is done on the colliders), or we could do this with a dedicated new component (that could be named "IgnoreInteractableHovering").

**Comment by zite** [comment]
The Interaction System is meant more as an example rather than a catch-all. You're welcome to fork it and add on top though!
