### ISSUE TITLE
adjustment of east and west touchpad positions

### ISSUE THREAD

**Issue by LexQzim** [ValveSoftware/steamvr_unity_plugin#489]
We're using the D-Pad east and west keybinding for some controls. The problem is that the detection area for east and west is so small, that it is not uncommon to activate the north or south input and thus trigger a wrong action.

Is it therefore possible to rearrange these areas? I don't know exactly how the distribution is, but I would have assumed that every area of the touchpad has 45° available.

**Comment by zite** [comment]
This is indeed an option in the configuration section of the dpad binding. Click the little gear and you should see more options.
