### ISSUE TITLE
Fix Unity crash on "Open binding UI" when using as package

### ISSUE THREAD

**Issue by JashanChittesh** [ValveSoftware/steamvr_unity_plugin#492]
When using SteamVR Unity Plugin as a package (by adding a package manifest / package.json to the SteamVR folder and then adding it via Packages/manifest.json), SteamVR_Settings.asset cannot be created and Unity crashes when you click the button "Open binding UI" in the Window "SteamVR Input".

I have already created a Pull Request that fixes this issue: https://github.com/ValveSoftware/steamvr_unity_plugin/pull/491

**Comment by kisak-valve** [comment]
Hello @JashanChittesh, there's no value in tracking this in both a pull request and an issue report because Github handles them together and discussion can be done on the pull request. Closing in favor of #491.
