### ISSUE TITLE
OpenVR.System null reference using SteamVR 1.2.2 and Unity 5.6.0.3.p

### ISSUE THREAD

**Issue by TimNeck** [ValveSoftware/steamvr_unity_plugin#50]
When I try  to run a VR application in the Unity editor with the latest version of steamVR (1.2.2) I always get the following null reference: NullReferenceException: Object reference not set to an instance of an object
SteamVR.GetStringProperty (ETrackedDeviceProperty prop, UInt32 deviceId) (at Assets/SteamVR/Scripts/SteamVR.cs:167). The problem here is this line: hmd = OpenVR.System; OpenVR;System returns null for some reason. This happens in an empty scene in a new project, in the sample scenes and also in a scene from an existing project. The headset is tracking correctly and the application runs in editor, but the controllers are not showing up in the scene.

**Comment by pkarjala** [comment]
Please see issue #46 and #49.

**Comment by julianstopher** [comment]
For those that got nowhere with @pkarjala's solution, this is what fixed it for me:

https://imgur.com/a/HISpy

In XR Settings (under Player Settings), make sure you have the correct SDK loaded. For me, I had Oculus loaded instead of OpenVR, which caused the null references.
