### ISSUE TITLE
SteamVR_ActivateActionSetOnLoad

### ISSUE THREAD

**Issue by ajippolito** [ValveSoftware/steamvr_unity_plugin#500]
I have the standard player prefab loaded in my scene, with the script "SteamVR_ActivateActionSetOnLoad" added to the SteamVRObjects>[SteamVR] child gameobject.

The settings for this script component are set to default.  To troubleshoot, I have tried to uncheck "Deactivate on Destroy", and to comment out the onDestroy() method based on another discussion thread.  Neither of these fixed the issue I am having.

I have another gameobject Thing1, which contains an empty child gameobject Thing2 with a light component added.  The light component is by default disabled.

I have two actionsets in SteamVR; default and anotherSet.

The default actionset is the Action Set loaded on the player prefab component.  Again, this is the standard, default setting.

The anotherSet is the Action Set loaded on Thing1's **SteamVR_ActivateActionSetOnLoad** component.

The idea is - you pick Thing1 up, and only when using Thing1, you have anotherSet actions to use.  I have it working great.

The problem is this:  I have a gameobject with a 'reset' script attached to it (it's a button I created).  It's not associated with any of the above objects.  The reset script simply reloads the current scene.

ISSUE:  When the scene reloads, the Steam controllers are frozen.  When the player>SteamVRObjects>[SteamVR] component is inspected, the action set "default" has been removed, and the component reports it cannot before.  anotherSet is still present on the Thing1 object's component.

This breaks the scene.  

To repair, I have to go to the SteamVR input window, Advanced Settings, "Delete generated input folder", then rebuild the bindings.

Things I have tried:

1.  Disabling the SteamVR_ActivateActionSetOnLoad script on the Thing1 object.  This does not fix it; simply having the script added as a component, despite being disabled, is enough to break it.

2.  hiding the Thing1 object itself during play.  Still breaks it.

The only way to not having it break is to actually remove the SteamVR_ActivateActionSetOnLoad component from Thing1.

Please help!

**Comment by ajippolito** [comment]
As a follow-up, I have also attempted using interactable.cs, which has a method for activating an action set on pickup.  This also does not work.  I am at wit's end.

**Comment by zite** [comment]
I believe this has been fixed since this post was made. If not, please create a new issue with the repro steps and ideally an example project to replicate the issue. Thanks!
