### ISSUE TITLE
SteamVR WMR hand pose

### ISSUE THREAD

**Issue by AleVerDes** [ValveSoftware/steamvr_unity_plugin#501]
Hi all,
I use the SteamVR Plugin and Unity 2018.4.1f1. This plugin provides 3D models of all the controllers I use (Oculus Rift, HTC Vive, WMR), and all of them are successfully animated (finger movements, button interactions) - except WMR. For WMR, only two options of hands animation are present: idle and grip. Is it possible to somehow set up animated button interactions for WMR? Or will I have to animate manually?

Idle animation screenshot: https://forum.unity.com/attachments/wmr_anim_idle-png.462491/
Grip animation screenshot: https://forum.unity.com/attachments/wmr_anim_grab-png.462494/

**Comment by zite** [comment]
I believe this has been fixed since this post was made. If not, please create a new issue with the repro steps and ideally an example project to replicate the issue. Thanks!
