### ISSUE TITLE
Move problem with Oculus S Controllers SteamVR 2.2

### ISSUE THREAD

**Issue by inbaltal** [ValveSoftware/steamvr_unity_plugin#502]
I am working on Unity 2019.2 and Steam VR 2.2 I use Oculus S Headset and Controllers

When I working with the Player Prefabs, It's working with the Default action-set, and I can Teleport from one point to another.

But - I want also to move and rotate(On Dpad) and also teleport (Click) and I can't manage to move with the controller in the scene, just to teleport

It's possible the Oculus S controller can't do that?

Need Your Help Please

Inbal

**Comment by zite** [comment]
I believe this has been fixed since this post was made. If not, please create a new issue with the repro steps and ideally an example project to replicate the issue. Thanks!
