### ISSUE TITLE
LWRP Editor Double Vision

### ISSUE THREAD

**Issue by nscarfo** [ValveSoftware/steamvr_unity_plugin#504]
I opened up a new Lightweight RP Template in 2019.2.0f1 and then imported the latest SteamVR from the asset store (v2.3.2 ,sdk 1.4.18)and have done nothing else to the project. Repeating this process leads to the same issue in 2019.1.9f1.

When I enter Play mode, every tab is duplicated and the entire Unity window gets "crunched up," as shown. Game mode is blank, Scene mode is as shown below, and the headset view is just as messy.

![before](https://user-images.githubusercontent.com/29439166/62804274-cbf49d00-baba-11e9-9532-e2c762367f95.JPG)
![scene](https://user-images.githubusercontent.com/29439166/62804275-cbf49d00-baba-11e9-87fd-267f126b3711.JPG)
![after](https://user-images.githubusercontent.com/29439166/62804276-cbf49d00-baba-11e9-9204-2fc4e731db0a.JPG)

**Comment by beardedlinuxgeek** [comment]
I did exactly the same thing and this happens to me in 2019.2.13f1

**Comment by zite** [comment]
This sounds like a unity issue
