### ISSUE TITLE
SteamVR_Skeleton_PoseSnapshot returns inverted position/rotation

### ISSUE THREAD

**Issue by LordHorusNL** [ValveSoftware/steamvr_unity_plugin#506]
I'm trying to set the position and rotation of the standard valve vr_glove in local space using PoseSnapshot and GetBlendedPose(), however the position and rotation of the hand in game seems to be inverted.

Moving the poser HandPreviews in the editor in any specific axis direction, results in the in game hand being positioned in the opposite direction along the axis, same for rotations. Editor rotation of -45 results in an in game rotation of 45.

The rotations are easily fixed by using Quternion.Inverse, however the fix for position eludes me.

**Comment by zite** [comment]
I believe this has been fixed since this post was made. If not, please create a new issue with the repro steps and ideally an example project to replicate the issue. Thanks!
