### ISSUE TITLE
Completely Disable Haptic Feedback

### ISSUE THREAD

**Issue by epezent** [ValveSoftware/steamvr_unity_plugin#507]
Is there a way to completely disable haptic feedback? Despite not having any haptic actions or calling TriggerHapticPulse, my Oculus Touch controllers still provide subtle vibration when the triggers are pressed about half way. Where is the code responsible for this?

**Comment by epezent** [comment]
Discovered this was an option (Haptic Amplitude) within the Binding UI.

**Comment by SonitoShori** [comment]
Is this in normal steamVR software or do I have to install the github software (Sorry i'm new)

**Comment by epezent** [comment]
It was in the SteamVR bindings menu accessible via Steam.
