### ISSUE TITLE
Citation for SteamVR Unity plugin

### ISSUE THREAD

**Issue by Rhybo** [ValveSoftware/steamvr_unity_plugin#508]
How should I cite SteamVR for academic work?  I am using SteamVR to develop an application for a thesis and I want to ensure appropriate citation is given (IEEE format specifically -- a BibTeX citation would be sensational).

**Comment by zite** [comment]
I figure this is no longer relevant. I'm not sure how you'd cite us, if you figured it out please post here. Thanks!
