### ISSUE TITLE
 SteamVR_skeleton_Poser XRSettings disabled

### ISSUE THREAD

**Issue by JesusNexus** [ValveSoftware/steamvr_unity_plugin#509]
Hello,
I am creating a multiplayer game in Unity.
I would like to know if it is possible to use the SteamVR_skeleton_Poser pose system and the Blending Editor when the XR Settings are disabled.

The pose system works well for me on the PC that has the HMD and supports VR, but I can't get it to work on the PC that acts as a spectator and does not have HMD and automatically deactivates the XRSettings.

I want to modify the pose of the hands with the SteamVR pose system (not with animations) of the hands that are in multiplayer to different poses, but I can't do it with the XRSettings disabled.

Thank you.

**Comment by zite** [comment]
This is unfortunately outside the scope of this github. The Interaction System is meant more as an example rather than a catch-all. Please see the developer forums here: https://steamcommunity.com/app/250820/discussions/7/
