### ISSUE TITLE
Is anyone else having major problems if you don't use the built in Interaction system

### ISSUE THREAD

**Issue by KellanHiggins** [ValveSoftware/steamvr_unity_plugin#510]
So if I strip away whatever is provided by the plugin, I immediately get a host of errors. I've tried to get left and right hand actions by just activating the corresponding left and right hand actions but I just can't get them to link up.

I am finding it impossible to quickly grab the inputs from the left hand and use them. The system seems to be rigged to fail with null errors popping up everywhere.

Is anyone else having these problems?

**Comment by KellanHiggins** [comment]
For example,

In order to just get the action working, I had to call code that the plugin tells me not to call.

```
GrabAction.ForceAddSourceToUpdateList(HandType);
```

It now works, but clearly I am not supposed to do that. It took me nearly half a day to find the way to activate this Grab Action.

**Comment by KellanHiggins** [comment]
And this function ` GrabAction.active ` returns a null error instead of false if I haven't assigned the binding in the editor. Which means null errors will explode all over the place if I forget to set something.

**Comment by KellanHiggins** [comment]
It seems there is no way to know if your Action has been assigned in the editor. I have checked half the functions and they throw null errors.

**Comment by KellanHiggins** [comment]
And nowhere in the code that I can see have I added `GrabAction` to be registered with `Any` input type, yet it still registers itself with it. I've been programming in Unity for 5 years, 3 of those using SteamVR and I am completely lost about how this thing works.

**Comment by martamartino86** [comment]
Hi,
under Window/SteamVR Input Live View you should be able to see the current state of your actions. Maybe you have to activate the action set that you want to use by script:
`sampleActionSet.Activate(activateForSource, priority, disableAllOtherActionSets);`

**Comment by KellanHiggins** [comment]
I got the grab actions working but the problem with the SDK is it is not clear if I want to use my own actions how the action grab is being activated. I barely have any of the SDK's code activated. I just want to assign a grab action to be activated at awake per hand. I am confused as to why "Grab" is being activated on any. I never activated that. Nowhere I am looking at enabling the action.

Also can you point me to the documentation that explains how action sets work? I haven't found it yet.

**Comment by KellanHiggins** [comment]
I've also never seen that function call. Where is it?

**Comment by martamartino86** [comment]
It could be the `SteamVR_ActivateActionSetOnLoad` script. The default action set (which contains the Grab action, if I remember correctly) is activated on start.

**Comment by KellanHiggins** [comment]
Is there documentation on this? I don't understand what the purpose of it is? I've also deleted almost all the standard actions as I don't need them.

**Comment by martamartino86** [comment]
I believe the purpose of the default action set is to set up a working environment for demos, hence to show what you can do with it and how to handle them properly.
The only documentation I know is the one included in the source code directory.

**Comment by martamartino86** [comment]
Yeah no problem, I totally get it.
Regarding actions docs, I found [this](https://youtu.be/a9EBILq2ep8) and [this](https://www.youtube.com/watch?v=bn8eMxBcI70) video very interesting, I hope they will help.

**Comment by KellanHiggins** [comment]
I had seen the first video, hadn't seen the second. Thanks!
