### ISSUE TITLE
ItemPackageSpawner "requireTriggerPressToReturn" does not work 

### ISSUE THREAD

**Issue by funylion** [ValveSoftware/steamvr_unity_plugin#511]
Maybe some logic problems, I can only do this to get what I want.

**Comment by funylion** [comment]
if (hand.isActive)
				{
                 
                    ItemPackage currentAttachedItemPackage = GetAttachedItemPackage( hand );

                    if (currentAttachedItemPackage == itemPackage &&(hand.grabGripAction.GetStateDown(hand.handType) || hand.grabPinchAction.GetStateDown(hand.handType)))
					{
                      
						TakeBackItem( hand );
						return; // So that we don't pick up an ItemPackage the same frame that we return it
					}
				}

**Comment by kisak-valve** [comment]
Hello @funylion, please check if #246 helps.

**Comment by zite** [comment]
I believe this has been fixed since this post was made. If not, please create a new issue with the repro steps and ideally an example project to replicate the issue. Thanks!
