### ISSUE TITLE
Unity Controller not showing up 

### ISSUE THREAD

**Issue by sunchunhei** [ValveSoftware/steamvr_unity_plugin#513]
I am using unity 2018.3.6, making a game using just controller and tracker, with out Htc HMD , but every time i test my game the controller in game is no tracking my controller, but my tracker can move.

without Htc HMD: https://vvvv.org/blog/using-htc-vive-trackers-without-headset

**Comment by sunchunhei** [comment]
i restart the steamVR and Play in unity editor it work once after that i play again it not work again

**Comment by zite** [comment]
I believe this has been fixed since this post was made. If not, please create a new issue with the repro steps and ideally an example project to replicate the issue. Thanks!
