### ISSUE TITLE
Changing pose back and forth via Script

### ISSUE THREAD

**Issue by KellanHiggins** [ValveSoftware/steamvr_unity_plugin#514]
I've got a pose. When I pick up something, I blend the post with

```
SteamVR_Skeleton_PoseSnapshot pose = itemPoser.GetBlendedPose(skelly);
skelly.BlendToPoser(itemPoser);
````

and then when I try and blend back, I use

```
skelly.BlendToSkeleton(1f);
```

But instead of it just blending the other way, I get the hand doing a 180 for some reason.

https://www.youtube.com/watch?v=jSYoLNjp98c

Not sure what I am doing wrong. I've looked at all the documentation and it says nothing about why this would be happening.

**Comment by martamartino86** [comment]
Hi,
have you tried the SteamVR scene demo? Do you experience the same behaviour?

**Comment by KellanHiggins** [comment]
Nope I do not. I've looked through the code for the hand interaction and tried to faithfully recreate it. I can't use the standard stuff because I am using Entity's ECS system and need something more lightweight.

Do I need to set the blend from pose first manually before I execute that function? It looks like it is lerping from the default pose.

**Comment by martamartino86** [comment]
I see. I would suggest you to inspect some game objects inside the Interaction_Example scene (inside SteamVR/InteractionSystem/Samples) as it's the best way to understand how things are supposed to work.

**Comment by KellanHiggins** [comment]
I've looked through them extensively. I've watched the setup video. I am at a loss as to why this is happening. I am calling the exact same code as in the examples yet the rotate happens.

**Comment by KellanHiggins** [comment]
Figured it out, I had modified the root / wrist on the pose that I had created. You CAN NOT touch these or else the pose will get very funky when you transition out of it. The hand will snap and slide.

I think something needs to be done about this. It wasn't clear that I wasn't supposed to change the Root or Wrist transform or bad things would happen.

**Comment by zite** [comment]
I believe this has been fixed since this post was made. If not, please create a new issue with the repro steps and ideally an example project to replicate the issue. Thanks!
