### ISSUE TITLE
Behavior Skeleton Custom Error

### ISSUE THREAD

**Issue by VRArt1** [ValveSoftware/steamvr_unity_plugin#515]
I've seen to come over a few errors when trying to use the custom behavior skeleton script on a full body character as opposed to floating hands.

I've set up all the bones and I click on the "Only Set Rotations" button however upon playback the entire character gets picked up and carried on top of the hand.

Another issue, for some reason the middle finger is rotated at an angle instead of staying in line with the other fingers.

The final issue, for some reason no matter what combination of skeleton action/input source/mirroring I set up the right hand will rotate backwards the finger curls.

**Comment by zite** [comment]
I believe this has been fixed since this post was made. If not, please create a new issue with the repro steps and ideally an example project to replicate the issue. Thanks!
