### ISSUE TITLE
Need more null checks throughout the code

### ISSUE THREAD

**Issue by KellanHiggins** [ValveSoftware/steamvr_unity_plugin#516]
I am trying to get this working with my own solution (instead of using the interaction system) and I've found I get a lot of  null errors.

```
SteamVR_Behaviour_Skeleton : Line 441

        public void BlendToSkeleton(float overTime = 0.1f)
        {
            blendSnapshot = blendPoser.GetBlendedPose(this);
            blendPoser = null;
            BlendTo(1, overTime);
        }
```

If you call this without a blendposer being set, you get a null error.

Similarly if you are not trying to find if the source is present in the hand here,

```
        public bool GetLastStateDown(SteamVR_Input_Sources inputSource)
        {
            return sourceMap[inputSource].lastStateDown;
        }
```
The program assumes that it is valid, but it is pretty easy to get a case where this is not true. 

I don't want to modify the SDK plugin because then I'll never be able to update it. Just wanted to let you guys know :).

**Comment by zite** [comment]
Thanks for the feedback, and sorry for the delay in responding. I believe we've added a variety of null checks, but sometimes I find them useful rather than getting bad data back.

**Comment by KellanHiggins** [comment]
@keithbradner Thanks for the response. From what I recall, the issue was getting an error when asking the SDK to give me some information because an internal array wasn't initialized. If I look at this again, I'll see if the null checks are good. You won't get bad data, you'll crash the system.

In general I'd like to see a system that allows a super easy way to grab whatever action you want. If I wanna grab the trigger float it is as easy as saying VRHand.GrabTriggerAction(hand) and boom trigger is there. The interaction system is powerful, but it would still be good to be able to just grab whatever you need without setting things up.

**Comment by KellanHiggins** [comment]
The same issues I had when I tried to use this are happening again. I am finding it very difficult to just start using this SDK. I changed the default actions that shipped with the SDK and it broke everything and the only errors I am getting are 30 stack deep null references.

If Valve wants us to use the SDK it needs to be easy to use or else people are just going to go with XR or the Quest.
