### ISSUE TITLE
OnAttachedToHand not called, but OnHandHoverBegin is?

### ISSUE THREAD

**Issue by ckcollab** [ValveSoftware/steamvr_unity_plugin#517]
Heyo! Thanks so much for all of the work on this, having a blast trying to get little prototypes working!

One problem we're having, is when hovering we can trigger events, but when clicking `Interactables` they never trigger `OnAttachedToHand`. It's probably something simple we're missing, but if you can click the `Interactable` and use it (i.e. we can turn it with `CircularDrive`) shouldn't attach events fire before `CircularDrive` kicks in?

```c#
    // fires
    private void OnHandHoverBegin(Hand hand)
    {
        print("Hovered!");
    }
```

```c#
    // doesn't fire
    private void OnAttachedToHand(Hand hand)
    {
        print("Attached!");
    }
```

Appreciate any help, thanks again for releasing this :)

**Comment by tcwatson** [comment]
Hi! Did you ever figure this out? I have run into this same issue.

**Comment by Steedalion** [comment]
Make sure the object has the `Interactable.cs` script attached. It worked for me.
