### ISSUE TITLE
Launch VR .exe in background without losing headset

### ISSUE THREAD

**Issue by martamartino86** [ValveSoftware/steamvr_unity_plugin#518]
Hello everyone!
My objective is to launch a VR .exe from an already running VR .exe. I would like to do it without losing the "priority" on the headset, meaning, the user wearing the headset doesn't have to notice it.
Basically, is it possible to "block" SteamVR from requesting the headset when starting the app, and ask for it later?

Thanks in advance!

**Comment by martamartino86** [comment]
Anyone on this?

**Comment by zite** [comment]
You can tell unity to not startup VR until you ask it to. There should be a checkbox in the VR/XR UI to do it.
