### ISSUE TITLE
Valve Index Headset not returning HeadsetOnHead 

### ISSUE THREAD

**Issue by Mahallon** [ValveSoftware/steamvr_unity_plugin#519]
`isPresent = SteamVR_Actions.default_HeadsetOnHead.GetState(SteamVR_Input_Sources.Head);` The function call above returns false for the valve index headset but works properly for all the other headsets. 

the save and generate button in the steamVR Input window does not produce a binding_indexhmd.json file and the open binding UI does not have the option to change the bindings for the Valve Index headset like it did for the Vive headset where I was able to say that the proximity sensor maps to default_HeadsetOnHead so how do I do that for the Valve Index headset. 

I looked through the actions,json of a build of our program and it includes 
`    {
      "controller_type": "knuckles",
      "binding_url": "bindings_knuckles.json"
    },` 
but it did not include
`	{
      "controller_type": "indexhmd",
      "binding_url": "bindings_indexhmd.json"
    },`
so I added that into the actions.json and I also created a bindings_indexhmd.json which is as follows but that didn't fix it in the build or in the editor so maybe i'm adding it wrong? or is the "indexhmd" not the right string to use? I have tried everything I can think of to get this working and it is not so i'm hoping that someone can shed some light on this so we can get a fix out soon for our users.
``` {
   "alias_info" : {},
   
   "bindings" : {
      "/actions/default" : {
         "chords" : [],
         "haptics" : [],
         "poses" : [
            {
               "output" : "/actions/default/in/pose",
               "path" : "/user/head/pose/raw"
            }
         ],
         "skeleton" : [],
         "sources" : [
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/default/in/headsetonhead"
                  }
               },
               "mode" : "button",
               "path" : "/user/head/proximity"
            }
         ]
      }
   },
   "controller_type" : "indexhmd",
   "description" : "",
   "name" : "index defaults",
   "options" : {},
   "simulated_actions" : []
} ```

**Comment by Mahallon** [comment]
Also before you ask yes I have verified that the proximity sensor is working by using the input debugger in the binding UI and I have run the SteamVr input Live view while the program is running and it stays yellow the whole time

**Comment by Mahallon** [comment]
This may be unrelated but these errors spam every frame BUT ONLY the first time that I run our code in the editor, every time after that these errors are not present. I believe this started happening after I stopped using the built in interaction system and replaced them with my own actions.

![firsttimeErrors](https://user-images.githubusercontent.com/13002995/63983655-d33d1400-ca84-11e9-8c18-f7bfb15b2fa2.PNG)

**Comment by Mahallon** [comment]
https://github.com/ValveSoftware/openvr/issues/1096#issue-434103183

**Comment by zite** [comment]
sounds like your controller type should read index_hmd. We'll try and get this fixed for the next release.
