### ISSUE TITLE
KeyNotFoundException in SteamVR_Input line 471

### ISSUE THREAD

**Issue by matches81** [ValveSoftware/steamvr_unity_plugin#520]
Not entirely sure whether an issue is the right place to report this, so: Sorry, if I'm wrong here.

I ran into a slight issue in my current project that really doesn't seem to affect functionality (as far as I can tell), but reports a KeyNotFoundException every time I open the project.
It's thrown in line 471 of SteamVR_Input, so I checked that out.
The line is
`return actionsByPath[loweredPath];`
After checking where these dictionaries are filled, it seems to me this should really be
`return actionsByPathLowered[loweredPath];`

After changing that line, the exception wasn't thrown again.

**Comment by zite** [comment]
Thanks for reporting. I'll get this fixed for the next version.

**Comment by zite** [comment]
I believe this has been fixed since this post was made. If not, please create a new issue with the repro steps and ideally an example project to replicate the issue. Thanks!
