### ISSUE TITLE
Physics based hands

### ISSUE THREAD

**Issue by alexander-clarke** [ValveSoftware/steamvr_unity_plugin#521]
With the new physics interactions in the labs, with physics based hands, would it be possible for them to be added into this plugin? As it does have stuff from the lab it would make sense for them to be added alongside the other interactions.

**Comment by alexander-clarke** [comment]
It seems that this is being worked on:  https://twitter.com/MrZulubo/status/1170054934147895296 which is great

**Comment by zite** [comment]
This is being added to version 2.4.0. You can test a beta release here if you like: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.4.0b
