### ISSUE TITLE
ItemPackageSpawner.cs and HandHoverUpdate

### ISSUE THREAD

**Issue by David-S-Hunsicker** [ValveSoftware/steamvr_unity_plugin#522]
Hi all.
[Valve Index]
I was working in the ItemPackageSpawner inside the HandHoverUpdate method and I was trying to pick up and put down the bow in the System interaction scene. I found that even when I checked the 'requiredReleaseActionToReturn' boolean I still don't get the section of the code to take the item back to work.

Has anyone else had any issues with hand.IsGrabEnding( ) related issues or this method not functioning the way we might presume it would and if so have you found any solutions/ helpful advice?

**Comment by kisak-valve** [comment]
Hello @David-S-Hunsicker, please check if #246 helps.

**Comment by David-S-Hunsicker** [comment]
@kisak-valve 
Thanks for the quick reply.

My issue is specifically with the HandHoverUpdate method.

As I said before when I have the boolean true for RequireReleaseActionToReturn and I attempt to return the bow in the interaction system scene I don't see the clause evaluate to true.

**Comment by zite** [comment]
Can you describe more about how you're trying to get the package spawner to take the item back? Controllers used, where you're releasing, etc

**Comment by David-S-Hunsicker** [comment]
I'm putting my hand back in the collider and releasing the grip. What's
wrong with this is that the boolean that checks for release grip required
doesn't change grip based enum. So grabtype.scripted isn't usable in the
scenario where the user wants to require grab to pickup and require release
to let go of the item

**Comment by zite** [comment]
I believe this has been fixed since this post was made. If not, please create a new issue with the repro steps and ideally an example project to replicate the issue. Thanks!
