### ISSUE TITLE
SteamVR_Event "OnDeviceEnterStandby" triggers two times

### ISSUE THREAD

**Issue by Corneliusbg** [ValveSoftware/steamvr_unity_plugin#523]
Putting a Listener on the Event "OnDeviceEnterStandby", for example:

`SteamVR_Events.System(EVREventType.VREvent_EnterStandbyMode).Listen(OnDeviceEnterStandby);`

The method OnDeviceEnterStandby is executed two times.

I am using the htc vive. Is it a known issue or am i doing something wrong?

**Comment by Corneliusbg** [comment]
It appears, that this always happens when the headset goes into standby. Even with other Events like `EVREventType.VREvent_TrackedDeviceUserInteractionStarted` . (When the timer for standby is the same as the timer for the iUserInteraction Event)
So you have to program your way out of it.

**Comment by zite** [comment]
Do you somehow have two instances of SteamVR_Render running?

**Comment by Corneliusbg** [comment]
I dont think it is possible to have more than one instance of SteamVR_Render and I haven't messed with it so I shouldn't have two. 
I did not subscribe twice, I double checked that already before submitting this issue.
I basically have a blank project only with the Camera_Rig (and SteamVR Plugin ofc) and a script that sets a listener to the event.

**Comment by zite** [comment]
I believe this has been fixed since this post was made. If not, please create a new issue with the repro steps and ideally an example project to replicate the issue. Thanks!
