### ISSUE TITLE
Dynamically change action's binding while in play mode

### ISSUE THREAD

**Issue by QihaP** [ValveSoftware/steamvr_unity_plugin#524]
Hello, for a week now I have been trying to change bindings ingame. I had a perfectly fine system before upgrading to SteamVR 2.0 and now i really don't know how i could do it.
I already tried several things where i change the binding in the json (bindings_vive_controller.json) and then do a bunch of stuff but the binding aren't taken until i manually change them in binding ui.
I'd really appreciate if someone has a clue about that.

Best regards,
QihaP

**Comment by zite** [comment]
There currently isn't a way to change bindings from code. The intention is to let users change their bindings and take that out of the game's hands. Can you explain a bit more about your context so we can better understand your scenario?

**Comment by QihaP** [comment]
Hi @keithbradner, ty for your answer. I solved my problem without having to changes the action's binding.
But I found out anyway that you could "rebind" actions while playing by modifying the full path to this action, which result is strange but works, for instance at launch, my grabPinch action is :         public SteamVR_Action_Boolean grabPinchAction = SteamVR_Input.GetAction<SteamVR_Action_Boolean>("GrabPinch"); which is set on the trigger

If i want to have the grabPinchAction on the trackpad, i change it whenever i want to
        public SteamVR_Action_Boolean grabPinchAction = SteamVR_Input.GetAction<SteamVR_Action_Boolean>("Teleport");
So my action is now bind to the teleport binding which is bind to the trackpad in the binding ui, and it grabs object.
It's super counterintuitive but it works, i didn't need it but i'm just sharing it in case it's usefull to someone.

Btw just changing the jsons while in play doesn't work, it works if you change the binding from binding ui most of the time but not always.

Best regards,
QihaP
