### ISSUE TITLE
No Input Sources for Knees and Elbows

### ISSUE THREAD

**Issue by JashanChittesh** [ValveSoftware/steamvr_unity_plugin#527]
You have InputSources for feet and even shoulders, which is cool - but how about elbows and knees?

I'm actually much more likely to attach trackers to my knees and/or elbows than to my shoulders. What I'll probably do in Holodance for now, is (ab)use Left Shoulder and Right Shoulder for either knees or elbows depending on where they are located during calibration.

But it would be much better if we could *properly* assign those ~~two~~ four joints. I believe with head, left hand, right hand, left foot, right foot, waist, left elbow, right elbow, left knee, right knee, chest, you have everything covered (in that order of importance). Left/Right Shoulder is nice to have (IMHO), so keep it.

**Comment by zite** [comment]
This is old, but probably also outside the scope of this github. Thanks for the suggestion
