### ISSUE TITLE
RenderModel needs to be seperated from interaction model

### ISSUE THREAD

**Issue by Veguard** [ValveSoftware/steamvr_unity_plugin#53]
Currently the SteamVR_RenderModel loads the 3d models for SteamVR and handles the animation of the meshes. However the script is both rather hacky and breaks quite often in a more complex project (Refresh() in controller manager doesn't always carry on being called until everything is in place). 

I appreciate the sentiment of wanting to allow users to customize their controller but most of the time we want to put our own controllers in the app, and this would be made much easier if there were some prefabs that replicate the various typical controllers (oculus and vive) with a simpler option to replace the meshes and materials, and allow the user to load their own only when we and they choose to do so.

The better way in this case is to let unity prefabs do loading with the pivots already set up and then allow steam vr to load custom controllers only when we want to allow it.

**Comment by aleiby** [comment]
You can select any of the currently shipping SteamVR render models using the ModelOverride dropdown in the inspector.  You can then create a prefab from that by dragging it into your Project.

The purpose of the render model system is to support hardware that does not exist at the time you ship your product.  For example, many SteamVR games shipped before Oculus Touch was released.  By using the render model system, those games are able to display the Oculus Touch models for those users.  See also Windows MR.
