### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by filipanton** [ValveSoftware/steamvr_unity_plugin#531]
When I click on an object inside of the editor that message keeps showing up a bunch of times 

NullReferenceException: Object reference not set to an instance of an object
Valve.VR.SteamVR_Action_Boolean.GetState (Valve.VR.SteamVR_Input_Sources inputSource) (at Assets/SteamVR/Input/SteamVR_Action_Boolean.cs:94)
Valve.VR.InteractionSystem.Hand.IsGrabbingWithType (Valve.VR.InteractionSystem.GrabTypes type) (at Assets/SteamVR/InteractionSystem/Core/Scripts/Hand.cs:1517)
Valve.VR.InteractionSystem.Hand.IsGrabEnding (UnityEngine.GameObject attachedObject) (at Assets/SteamVR/InteractionSystem/Core/Scripts/Hand.cs:1496)
Valve.VR.InteractionSystem.Throwable.HandAttachedUpdate (Valve.VR.InteractionSystem.Hand hand) (at Assets/SteamVR/InteractionSystem/Core/Scripts/Throwable.cs:212)
UnityEngine.GameObject:SendMessage(String, Object, SendMessageOptions)
Valve.VR.InteractionSystem.Hand:Update() (at Assets/SteamVR/InteractionSystem/Core/Scripts/Hand.cs:1083)

I literally have not changed anything, I just downloaded the plugin. What is causing this?

**Comment by Giantbean** [comment]
A few questions; What version of SteamVR? What version of Unity? Are the controllers on before SteamVR is launched? You say you have not done anything other then download the plug in, can you go to the Unity file menu under Windows>SteamVR Input; select Save and Generate at the bottom of that window to see if the errors subside.

**Comment by filipanton** [comment]
> A few questions; What version of SteamVR? What version of Unity? Are the controllers on before SteamVR is launched? You say you have not done anything other then download the plug in, can you go to the Unity file menu under Windows>SteamVR Input; select Save and Generate at the bottom of that window to see if the errors subside.

Seems like there was a problem with getting Steam VR to reconize it. It works fine now!
