### ISSUE TITLE
When launching a Unreal app from a Unity app I get a hung compositor

### ISSUE THREAD

**Issue by rgjones33** [ValveSoftware/steamvr_unity_plugin#54]
I am trying to develop my own VR program launcher in Unity. When I launch a Unity app via SteamVR_LoadLevel.cs all works fine for the launch. When I try to run an Unreal app it mostly works, I can see the app on desktop responding to the headset and I hear audio but seem to be stuck in compositor limbo land. I have to reboot the headset in order to recover.

Any suggestions on how to debug this one?

**Comment by zite** [comment]
Hi, thanks for the report. Can you test with modern versions of everything and let me know if this is still an issue?

**Comment by rgjones33** [comment]
Hi I had a lighthouse and a controller fail. Have not been able to replace them yet due to funds, so I could not test or recreate this issue.
