### ISSUE TITLE
Build behaves differently between Vive HMDs

### ISSUE THREAD

**Issue by craigsimpson13** [ValveSoftware/steamvr_unity_plugin#541]
I have published a build from Unity 2019.1.0f2 running on the Vive Pro.
The build has various UI HUDs that appear during the game. These canvasses are set "Screen Space - Camera" and Render Camera is the Steam "VR Camera".
This runs perfectly from the Unity editor and also in the published build.
When I run this on the Vive (not Pro) the UIs do not appear.
Debugging back in Unity shows the UIs to be in a closer space to the Vive, so nothing appears. Plug the Vive Pro back in and all is good?

With the Vive Pro plugged in the canvas originates at Z0.994. At runtime this moves to Z-5.264.
With the Vive plugged in the canvas again originates at Z0.994. At runtime this only moves to Z-1.066!
So, the issue is somehow the recognition of the different headset and the amount the canvas moves.

Attached screenshots are from Unity editor. The only difference is changing between the Vive and the Vive Pro, then restarting the headset in SteamVR. No other settings are changed.
The Z length difference between the UI and the VR camera is noticeable.

![Vive_distance_error](https://user-images.githubusercontent.com/49899642/66117435-88a34000-e5cc-11e9-94c4-c5e80e3c7504.jpg)
![Vive_Pro_distance_error](https://user-images.githubusercontent.com/49899642/66117453-8e992100-e5cc-11e9-9d04-80a9a26f8c16.jpg)

.

**Comment by zite** [comment]
They have different resolutions. If you're positioning elements absolutely
it may be off the screen in the vive.

**Comment by craigsimpson13** [comment]
@keithbradner Thank you.
I have changed the canvas scaler to maintain UI size and tested on different headsets, now okay.
