### ISSUE TITLE
Error when launching Simple Sample scene

### ISSUE THREAD

**Issue by chengnay** [ValveSoftware/steamvr_unity_plugin#544]
Anyone upgrades to latest SteamVR Plugin (v2.4.3) from Unity Asset Store experiencing below error message?
[SteamVR] No pose action set for this component
UnityEngine.Debug:LogError(Object)
Valve.VR.SteamVR_Behaviour_Pose:Start() (at Assets/SteamVR/Input/SteamVR_Behaviour_Pose.cs:76)

And, Interactions_Example scene black out due to Player > SteamVRObjects is disabled while playing.
![image](https://user-images.githubusercontent.com/33050705/66376102-6c930a80-e9e1-11e9-9335-6dfc1c55718a.png)

I am using Unity Editor 2019.2.0f1, I follow the quick start from [GitHub](https://github.com/ValveSoftware/steamvr_unity_plugin/releases), but it turns on Simulator? How could I turn it off?
![image](https://user-images.githubusercontent.com/33050705/66388207-3319c980-e9f8-11e9-80c7-2555d87fa297.png)

**Comment by limaoscar1** [comment]
@chengnay  I had the same issue at runtime, switch off no steam Vr fallback, and turn on Steam Vr object this worked for me.



![test image](https://user-images.githubusercontent.com/15261422/66390055-b79d2580-e9c1-11e9-98a2-4ced9171a580.PNG)

**Comment by ellerychan** [comment]
Here's an additional datapoint:  I'm also having trouble with 2.4.3.  I am having issues even in a totally new Unity project.  Things were working for me with the previous plugin (version 2.3.2), so I don't suspect a system or hardware issue.

Environment:
* Windows 10
* Unity 2019.2.5f1
* Unity Hub 2.1.2
* SteamVR 1.7.15
* SteamVR Unity Plugin 2.4.3 from Unity Asset Store (downloaded 2019-10-08)
* HTC Vive headset and controllers

Procedure:
1. Created new 3D Unity project in Unity Hub
2. Opened new project in Unity
3. Imported SteamVR from Unity Asset Store
4. Opened SteamVR Input window, clicked *Save and Generate*
5. Selected *SteamVR/Simple Sample* as current scene
6. Pressed *Play* in Editor

Observed:
* Bouncing ball is visible in headset
* Controllers/hands are not visible
* Console displays:
  ```
  [SteamVR] Interface Not Found (105)
  [SteamVR] Interface Not Found (105)
  ```
  ![image](https://user-images.githubusercontent.com/6425759/66413232-fd0f2200-e9c4-11e9-8f95-2bc4e5225851.png)

Other observations:
* When I run the *Interactions_Example*, I get the WASD fallback, no image in the headset, and three *105* messages:
  ```
  [SteamVR] Interface Not Found (105)
  [SteamVR] Interface Not Found (105)
  [SteamVR] Interface Not Found (105)
  ```
With the *Interactions_Example* scene I tried what @limaoscar1 said, and I did get a VR headset display, but still no controllers.

**Comment by local306** [comment]
I'm getting the same behaviour where it reports that **[SteamVR] Interface Not Found (105)** and my Vive is not tracking in the same (SteamVRObjects disables).

**Comment by zite** [comment]
This is a version mismatch issue with openvr. We’ll get it fixed and a new
version up in a couple hours.

**Comment by zite** [comment]
Fix should be up with version 2.4.5. Let me know if there's still an issue.

**Comment by spro1976** [comment]
Hello, 
I have switched form 2.3 to 2.45 and today to 2.5 of the SteamVR Plugin. 
For development I use currently a mixed reality setup. 
With 2.3 there was no problem. However now I also get the error "Interface not found (105)", if I use the Player prefab. 
The sample Scene (onyl camera rig) however is working? 
Anybody has the same Problem?

Best regards

**Comment by zite** [comment]
Interface Not Found means you’re probably running an older version of
SteamVR. Make sure you’re on at least 1.8.19.

**Comment by damic** [comment]
Still see this exact same issue

Running Unity 2018.4.25f1
SteamVR 1.15.19
OpenVR package 1.0.5

**Comment by kechiao** [comment]
+1 on the same issue. Was working yesterday, but today, when importing the "Player" prefab and clicking "Play", I get the fallback with "WASD" controls in the "Play" preview.

Running Unity 2019.4.18f1
SteamVR Unity Plugin v. 2.7.2
SteamVR Version 1.15.19

Would updating to steamVR beta branch help?

**Comment by Giantbean** [comment]
This is still happening. Steam VR 1.9.16, Unity 2019.4.3+ and plugin 2.7.+ tests have all shown this issue. I had to go back to Unity 20198.4.3 and plugin 2.2.0 to get it working.

**Comment by zite** [comment]
You'll need to use the latest version of SteamVR, we don't support using versions that are not available through Steam.

**Comment by Giantbean** [comment]
I can't use the latest because its not currently approved for enterprise use on a closed network at my workplace. It would be great to have a list of compatibility with software versions between SteamVR Unity and the SteamVR Plugin.
