### ISSUE TITLE
MismatchedActionManifest after updating plugin to 2.4.3

### ISSUE THREAD

**Issue by MadLab34** [ValveSoftware/steamvr_unity_plugin#547]
Updated the Unity plugin to v2.4.3, now I cannot play the project as I get the following error:

[SteamVR] Error loading action manifest into SteamVR: MismatchedActionManifest
UnityEngine.Debug:LogError(Object)

This is the new folder layout:
https://imgur.com/a/3eRibHI

SteamVR Settings:
https://imgur.com/a/wKL3BlJ

I have tried:

- Regenerating input bindings
- Deleting all SteamVR folders (SteamVR, SteamVR_Input, SteamVR_Resources, StreamingAssets) and re-importing the plugin from the Store, but still this error persists. 
- Deleting unityProject.vrmanifest from project root folder

This error occurs when opening my scene, opening the default Interactions Examples scene and when trying to open the Binding UI.

**Comment by pixelivore** [comment]
I had the same error.
I fixed it by changing the path of the action.json file in unityProject.vrmanifest (it was still pointing to the root folder instead of StreamingAssets/SteamVR  folder)

But now i'm stuck with this issue  #546  :(

**Comment by MadLab34** [comment]
> 
> 
> I had the same error.
> I fixed it by changing the path of the action.json file in unityProject.vrmanifest (it was still pointing to the root folder instead of StreamingAssets/SteamVR folder)
> 
> But now i'm stuck with this issue #546 :(

I tried that but it keeps changing it back to the root folder. Did you just change this line in the unityProject.vrmanifest file?

"action_manifest_path": "C:\\Users\\Mike\\Documents\\Unity Projects\\SteamVR_Upg\\actions.json",

I changed it to

"action_manifest_path": "C:\\Users\\Mike\\Documents\\Unity Projects\\SteamVR_Upg\\Assets\\StreamingAssets\\SteamVR\\actions.json",

Does that look right to you?

**Comment by zite** [comment]
Whoop, that’s our fault. Will get this fixed and a new version out in a
couple hours.

**Comment by zite** [comment]
Fix should be up as version 2.4.5

**Comment by MadLab34** [comment]
> 
> 
> Fix should be up as version 2.4.5

OK I tested it and it works great now, thanks for the fast turn around!

**Comment by MadLab34** [comment]
Error no longer present after upgrading.
