### ISSUE TITLE
Skeleton_Poser editor is broken

### ISSUE THREAD

**Issue by RavStark** [ValveSoftware/steamvr_unity_plugin#552]
Hi,
With the update 2.4.5, the size of VR_Skeleton_Poser editor is broken and I can't display the right hand.
![skeleton_poser](https://user-images.githubusercontent.com/5956599/66692342-85165580-ec6b-11e9-8811-6d002ba09fe8.jpg)
I'm not familiar with the custom editor. Any way to fix this?

Thank you

**Comment by JayPeet** [comment]
I have the exact same issue after upgrading to the 2.4.5 plugin.

**Comment by ataylor09** [comment]
@RavStark I came here to report the same issue but fund your one.

I've created a work around if anyone is interested. Bear in mind that I am also unfamiliar with custom editors, so there may be a better way of doing this.

Essentially what I did was edit the `SteamVR_Skeleton_PoserEditor` (found in SteamVR/Input/Editor). Using the code snippet [here](https://docs.unity3d.com/ScriptReference/EditorGUILayout.BeginScrollView.html) I wrapped the Pose Editor box with a horizontal scroll view. It doesn't solve the issue, but at least it allows you to manipulate all of the GUI elements that you need to.

Some specifics if you need them:

1. At around line 47, create a private Vector2 variable called scrollPos:
`private Vector2 scrollPos;`

2. At around line 485 (before the line: `GUILayout.BeginVertical("box")` ) insert the following:
`scrollPos = EditorGUILayout.BeginScrollView(scrollPos);`

3. At around line 749 (after the line: `GUILayout.EndVertical();`) insert the following:
`EditorGUILayout.EndScrollView();`

**Comment by RavStark** [comment]
Simple and nice workaround ! Thank you.

**Comment by alapparikh** [comment]
Thanks! That worked for me. I'm facing another issue now though: the "Copy x pose to y hand" buttons remain permanently greyed out. Anyone face this? 

![SteamVR_pose_editor_2](https://user-images.githubusercontent.com/8562013/67776234-10725200-fa86-11e9-9163-7076dfda13e8.png)

![SteamVR_pose_editor_1](https://user-images.githubusercontent.com/8562013/67776256-19632380-fa86-11e9-8fed-be609281c83f.png)

Attached some screenshots.

**Comment by diegodaly** [comment]
Thank you! It was driving me crazy

**Comment by zite** [comment]
Thanks for the report and work around. What version(s) of Unity are you all seeing this issue on?

**Comment by RavStark** [comment]
Hey Keith, I'm using Unity 2019.2.9f1 Personal

**Comment by ataylor09** [comment]
> Thanks for the report and work around. What version(s) of Unity are you all seeing this issue on?

I'm using Unity 2019.2.0f1

**Comment by alapparikh** [comment]
2019.2.3f1

**Comment by zite** [comment]
We'll have a beta out with a fix soon but for now you can fix it by moving line 255 in the poser editor to line 260 (after the editorguilayout.propertyfield call

https://github.com/ValveSoftware/steamvr_unity_plugin/blob/master/Assets/SteamVR/Input/Editor/SteamVR_Skeleton_PoserEditor.cs#L255

https://github.com/ValveSoftware/steamvr_unity_plugin/blob/master/Assets/SteamVR/Input/Editor/SteamVR_Skeleton_PoserEditor.cs#L260

**Comment by zite** [comment]
Thanks again for the report and info everyone! This should be fixed in the 2.5.0 release on the asset store or here: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.5.0
