### ISSUE TITLE
SteamVR_LoadLevel doesn't work

### ISSUE THREAD

**Issue by dpggit** [ValveSoftware/steamvr_unity_plugin#556]
I am using Unity 2018.3 and SteamVR 2.0.1. I have tried to use SteamVR load scene script but doesnt work at all, just shows the skybox or background color but doesnt show any loading bar, i set the textures for everything but doesnt show anything. After a second with the skybox or background color shows the compositor with the default texture of the mountains and also usually doesnt load the scene successfully. I tried to just loadsceneasync from unity but doesnt work, goes to compositor and doesnt let me show Unity UI. Anyone knows how to solve this?? I have seen videos en youtube about this but none solves anything

**Comment by dpggit** [comment]
I have downloaded the last version and replaced the SteamVR_LoadLevel but doesnt work anyways, makes Unity stop running the application

**Comment by zite** [comment]
Was this fixed when you upgraded versions of the plugin?

**Comment by dpggit** [comment]
Got it working in last and previous versions, dont remember what i did to fix it
