### ISSUE TITLE
"Player" prefab issue after upgrading to v2.4.5

### ISSUE THREAD

**Issue by ChisChris** [ValveSoftware/steamvr_unity_plugin#558]
Hi there,
After upgrading* to the latest SteamVR plugin (2.4.5) whenever I use the player prefab, at runtime, the SteamVRObjects go automatically off and the WASD menu appears on the screen, while "Virtual Reality Supported" is activated.
Only by manually activating the SteamVRObjects in play mode, I manage to have VR on.
I didn't have this problem with a previous version of SteamVR.
I am using Unity 2019.2.0f1.

Any idea how to fix this?

*As instructed, I deleted the SteamVR folder before upgrading to the new version.

**Comment by zite** [comment]
Are there any errors in unity when this happens?

**Comment by zite** [comment]
The warnings above this seem to indicate that SteamVR is not being recognized. Are you on the latest version of the SteamVR client?

**Comment by mohitj2007** [comment]
If for some reason, I cannot upgrade to latest version of SteamVR client, is there any way of understanding which version of plugin to use for which version of client?
(I also have the same problem on trying the Player prefab. I get IVR_ errors. My camera is working but controllers are not getting displayed even in the CameraRig prefab)

**Comment by zite** [comment]
In the latest versions of the plugin we started appending the sdk version to the plugin version. So 2.4.5 (1.17.15) means you need at least SteamVR 1.7.15 for the plugin to work.

**Comment by mohitj2007** [comment]
yes, I saw that. My problem is that I cannot upgrade SteamVR version. Is there some way to figure out compatible SteamVR version for an old release of plugin? I would try that old release of the plugin. Also, is there some way to fetch the plugin version information from the package contents?

**Comment by zite** [comment]
Unfortunately not for these older versions. If you tell me what version of SteamVR you're targeting I can probably tell you what version of the plugin you'd need. 
What is your scenario in which you can't upgrade SteamVR?

**Comment by ChisChris** [comment]
> The warnings above this seem to indicate that SteamVR is not being recognized. Are you on the latest version of the SteamVR client?

Totally right, I was not... Working now, thank you!
