### ISSUE TITLE
SteamVR Oculus HDR Mode issue

### ISSUE THREAD

**Issue by ktmlleska** [ValveSoftware/steamvr_unity_plugin#56]
Hello, 

I have a game developed with Unity and steamVR working for HTC vive. I would like to add a compatibility with Oculus Rift, as as far as I understood steamVR should be compatible with it.

Trying it I have found a couple of issues that I' appreciate if you could help me to solve or maybe they are a limitations of the plugin.

The first thing I tried is to simply connect the oculus and try the same build I had working for vive, and it was working, but I had a poor image quality as the default HDR Mode is not R11G11B10, so finding how to solve the problem I found that I had to do the following:
- Add the oculus sdk on the "player settings" and before the OpenVR sdk.
- Then I had to download and install the "oculus integration" plugin form the asset store, and add an script to my steamVR [CameraRig] object with the following line to enable the R11G11B10 mode. "OVRManager.eyeTextureFormat = OVRManager.EyeTextureFormat.R11G11B10_FP;"

Well with this I solved the problem with the image quality, but now since the oculus SDK is in the first position my controllers are not working and the camera appears to be upside down.

So my questions are, is there anyway to solve this problem? or to activate the R11G11B10 mode without having to add the oculus SDK on the player settings? If it is possible to solve, will this be able to be published on oculus store or it has to have the oculus SDK?

If it isn't possible, then the way to proceed is to have a different camera setup for each headset as well as different builds?

Thank you very much.
Cheers.

**Comment by bddckr** [comment]
Once you use the Oculus plugin/SDK you aren't using SteamVR anymore.

On the question of whether R11G11B10 is supported in OpenVR's Oculus driver you're probably better off asking in the [OpenVR repo](https://github.com/ValveSoftware/openvr/).

**Comment by ktmlleska** [comment]
Ok thank you.

**Comment by zite** [comment]
Hi, thanks for the report. Can you test with modern versions of everything and let me know if this is still an issue?
