### ISSUE TITLE
Locking hand pose to an object

### ISSUE THREAD

**Issue by ataylor09** [ValveSoftware/steamvr_unity_plugin#560]
Hi All,

Wondering if it is possible using the Skeleton Poser to lock the hand position to an object. 

My use case for this is a handle on a rotational drive. When the user grabs the handle, I want to blend to a pose that is fixed to the handle. Even if the hand strays from that position, I want to render the hand still gripped onto the handle.

Hopefully that makes sense!

**Comment by zite** [comment]
The Linear Drive in the example scene should be an example of this type of action. I believe you want the Interactable component's HandFollowTransform checkbox.
