### ISSUE TITLE
Cannot track vive cosmos controllers

### ISSUE THREAD

**Issue by blai30** [ValveSoftware/steamvr_unity_plugin#561]
The inputs work just fine. Opening input window and generating the inputs, then opening binding UI and mapping the bindings. I am able to move my character with the joystick and spawn objects with the trigger, and the haptics work as well.

However, the controllers themselves are not being tracked. Their positions do not change when i move the controllers around. I am using the CameraRig and I'm on the latest version of the plugin.

I have tried to delete the asset, deleted all the bindings, deleted everything related to SteamVR and reimporting the asset again. I have also tried restarting SteamVR, Steam, Vive Console, rebooted my PC, reimporting the project, making a new scene, disabling and enabling XR support.

Is tracking for the Vive Cosmos controllers supported yet? I appreciate any tips.

**Comment by zite** [comment]
Vive Cosmos should be supported. Are you on version 2.4.5 (readme.txt) and are you getting any errors in unity?

**Comment by blai30** [comment]
I found the issue, my controllers did not have skeleton or pose assigned in the binding UI for some reason. I created the skeleton and poses then assigned them to the controllers in the binding UI and the controllers are now tracking!

This is on the latest version of SteamVR (2.4.5).

Thanks!
