### ISSUE TITLE
v2.4.5 Binding UI wont open

### ISSUE THREAD

**Issue by HappyOrDead** [ValveSoftware/steamvr_unity_plugin#562]
So i couldnt open binding UI window yesterday (17th of October). Every time i try it would show me "This site can't be reached". I decided to upgrade to the newest version, but it didnt solve the issue. I still cant open binding UI. Steam doesnt write any errors, steamVR is on and running, headset is connected, controllers are on, internet connection is good. I couldnt find ppl with same issue on forums, and i have no idea why it could occur, since everything worked few days ago.
![image](https://user-images.githubusercontent.com/55687169/67084404-33a32480-f19d-11e9-8a26-40755b220311.png)

**Comment by zite** [comment]
Unfortunately the port has changed. You can either manually change the port in the url to 27062, or open the binding ui through the steamvr menu (SteamVR -> Menu -> Controller Settings) You may need to be running your app to change bindings.

This will be fixed soon

**Comment by ataylor09** [comment]
or... if you open the script `SteamVR.cs` on line 372 there is a hard coded string called `bindingurl` 
Changing the port number in this string fixed the issue for me

**Comment by Zakur1** [comment]
I am trying to connect to http://localhost:27062/dashboard/controllerbinding.html?app=application.generated.unity.testproj.exe as well as to the default 8998 port  but at no avail. Also the controller settings from the steamvr menu just shows a darker overlay when I am trying to edit controller settings. I am using unity 2019.1.5f1 on win10.

**Comment by zite** [comment]
Changing the port in the script as @ataylor09 is probably the best solution for right now, a beta is coming soon to address this.

**Comment by zite** [comment]
Thanks again for the report! This has been fixed with a proper api in the new 2.5.0 release on the asset store and here: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.5.0

**Comment by AdamBebko** [comment]
still having this problem on 2.5.0 (sdk 1.8.19)
