### ISSUE TITLE
Get VIVE trackers speed and angularSpeed

### ISSUE THREAD

**Issue by davidguerreiro** [ValveSoftware/steamvr_unity_plugin#564]
Since SteamVR plugin has been updated to version 2.0 I'm unable to get the vive trackers speed and angular speed. I have seen around internet how to do it for older versions but not for this one. Is there anybody who knows how to achieve this? ( I'm using SteamVR plugin in Unity ). Many  #thanks.

**Comment by zite** [comment]
The pose should have velocity and angularVelocity members. You'll need to use pose actions to get this data now. You can find some examples in the Throwable.cs file in the interaction system.
