### ISSUE TITLE
Incorrect action set behavior on asymmetric bindings with priority on SteamVR 1.8.14 beta

### ISSUE THREAD

**Issue by koochyrat** [ValveSoftware/steamvr_unity_plugin#565]
Using SteamVR 1.8.14 beta:
1. Go to Window.. Steam VR Input, and set the platformer action set to 'per hand'
2. Save and generate, then open Binding UI
3. Select Vive binding, then go to platformer action set
4. Remove all actions for right controller only, leave the left one alone.
5. Go to Interactable.cs, line 277. Change the action set priority to 1:
`activateActionSetOnAttach.Activate(hand.handType, 1);`
6. Run Interactions_Example scene.
7. Grab the JoeJeff controller with your right hand. Since it has no actions, it will revert to default action set with teleport and snap turn working. This is reflected correctly in the SteamVR Input Live View even though it does not work in the scene.
8. While still holding the JoeJeff controller, note that your left hand's default action set now does NOT work. Teleport and snap turning do not work, this is confirmed in SteamVR Input Live View.This is incorrect as only the right hand has the platformer action set active whereas the left one is still on the default action set.
9. EXPECTED RESULT: Left hand teleport and snap turning should work (CORRECT)
OBSERVED RESULT: Left hand teleport and snap turning not working (WRONG)

STEAMVR 1.7.15
1-8. Perform same steps as above
9. EXPECTED RESULT: Left hand teleport and snap turning should work (CORRECT)
OBSERVED RESULT: Left hand teleport and snap turning is working (CORRECT)

[Assets.zip](https://github.com/ValveSoftware/steamvr_unity_plugin/files/3762422/Assets.zip)

**Comment by JoeLudwig** [comment]
Does the behavior change between 1.7 and 1.8?

**Comment by koochyrat** [comment]
Yes, 1.7 works. It's a SteamVR 1.8 bug, not a bug with this plugin. I have a published game on Steam that will be affected by this with a 'handgun' action set using such a binding.

**Comment by JoeLudwig** [comment]
This will be fixed in SteamVR 1.8.16. Thanks for the report.
