### ISSUE TITLE
If one hand hovers over object, second hand cannot interact

### ISSUE THREAD

**Issue by sinfiery** [ValveSoftware/steamvr_unity_plugin#567]
When I have one hand hover over an object, if the other hand starts to hover over the same object, the second hand cannot grab the object until the first hand is no longer hovering over the object. 

Unity 2018.3.5f1
Version 2.2 of the plugin and the latest 2.4.5
Index and also Odyssey previously 
Happens in interaction demo scene as well. 

Edit: Separately, the highlighting hand script for the left hand doesn't work properly. It essentially renders the left hand highlighted outline as if the option "none" was selected in the "Mirroring" option on the Steam_VR_Behavior_Skeleton script on the left hand. The error comes from the changes to the Steam_VR_Behavior_Skeleton script

**Comment by zite** [comment]
Thanks for the report. I thought we fixed this in 2.4.5 but I'll double check that code got in.

**Comment by zite** [comment]
Looks like it didn't get in to 2.4.5. It'll be coming in the next release.

**Comment by zite** [comment]
Got this into 2.5.0 on the asset store or here: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.5.0
