### ISSUE TITLE
SteamVR_Action_List does not exist 

### ISSUE THREAD

**Issue by dpggit** [ValveSoftware/steamvr_unity_plugin#568]
I get the error "The type or namespace name 'SteamVR_Action_List' does not exist in the namespace 'Valve.VR'" after installing the latest SteamVR version in the Unity asset store and generate the actions, i use Unity 2018.3.13f1

**Comment by zite** [comment]
When upgrading did you delete the steamvr and steamvr_input folders and reimport?

**Comment by dpggit** [comment]
I have already solved the problem, just deleted everything and moved the steamvr folder from an empty project where i installed steamvr 2.4.5
