### ISSUE TITLE
Cant access external classes in 2.2 version

### ISSUE THREAD

**Issue by dpggit** [ValveSoftware/steamvr_unity_plugin#569]
When i used 2.0.1 i could access from Arrow class other classes in my project, but with 2.2 now SteamVR is in a different assembly and i cannot access classes from the CSharp assembly. I dont know any way to do it, and my project already have code inside Arrow class which acccess other classes i made. I want for instance execute a code when ArrowReleased method is invoked in Arrow script. You change everything from a version to another making the code made unusable, SteamVR is a nightmare

**Comment by zite** [comment]
Sorry to hear the plugin has been causing issues but I appreciate you creating separate posts for each one. This change was made partly to increase compile times in large project and partly to discourage people from using the interaction system while in the SteamVR folder as it is prone to upgrades. If you'd like to stick with one version of it you'll need to copy the interaction system folder out of the SteamVR folder and rename the namespace. Visual Studio has an option to do this easily in the right click context menu (Rename). 

Alternatively, if you don't want to copy it out you can delete all the assembly definition files in the project (though one is generated when you generate actions). Search for *.asmdef
