### ISSUE TITLE
GetActionOrigins failed and source map null

### ISSUE THREAD

**Issue by dpggit** [ValveSoftware/steamvr_unity_plugin#570]
**I tried steamvr 2.4.5 with Unity 2018.3.13f1 and i get several errors of this type :**
GetActionOrigins failed! action=/actions/htc_viu/in/viu_axis_3xy error=InvalidHandle
UnityEngine.Debug:LogError(Object)
HTC.UnityPlugin.VRModuleManagement.ActionArray`1:ResetOrigins(CVRInput) (at Assets/HTC.UnityPlugin/VRModule/Modules/SteamVRv2Module.cs:92)
HTC.UnityPlugin.VRModuleManagement.SteamVRModule:UpdateDeviceInput() (at Assets/HTC.UnityPlugin/VRModule/Modules/SteamVRv2Module.cs:491)
Valve.VR.SteamVR_Input:UpdateNonVisualActions() (at Assets/SteamVR/Input/SteamVR_Input.cs:381)
Valve.VR.SteamVR_Input:Update() (at Assets/SteamVR/Input/SteamVR_Input.cs:239)
Valve.VR.SteamVR_Behaviour:Update() (at Assets/SteamVR/Scripts/SteamVR_Behaviour.cs:235)

The method which triggers the error is method ResetOrigins and the lines
                var error = vrInput.GetActionOrigins(s_actionSetHandle, CurrentHandle, s_actionOrigins);
                if (error != EVRInputError.None)
                {
                    Debug.LogError("GetActionOrigins failed! action=" + CurrentPath + " error=" + error);
                }

**Also get the error** 
NullReferenceException: Object reference not set to an instance of an object
Valve.VR.SteamVR_Action`2[SourceMap,SourceElement].get_Item (Valve.VR.SteamVR_Input_Sources inputSource) (at Assets/SteamVR/Input/SteamVR_Action.cs:42)
Valve.VR.SteamVR_Behaviour_Pose.get_isActive () (at Assets/SteamVR/Input/SteamVR_Behaviour_Pose.cs:29)
Valve.VR.InteractionSystem.Hand.get_isActive () (at Assets/SteamVR/InteractionSystem/Core/Scripts/Hand.cs:145)
Valve.VR.InteractionSystem.Hand.UpdateHovering () (at Assets/SteamVR/InteractionSystem/Core/Scripts/Hand.cs:860)

The line which triggers the error is 
return sourceMap[inputSource];

**Comment by dpggit** [comment]
I got it working when i clicked on accept the recommend settings of Vive Input Utility application. It included all the default actions which i had deleted and replaced for others, i think SteamVR needs the default actions untouched

**Comment by zite** [comment]
It shouldn't need the default actions but it would need to regenerate as a lot of the underlying systems have changed from the version you're upgrading from. We recommend you delete the steamvr / steamvr_input folders and reimport as unity can leave some files leftover otherwise.
