### ISSUE TITLE
Interactions example scene doesnt work with steamvr 2.4.5 in Unity 

### ISSUE THREAD

**Issue by dpggit** [ValveSoftware/steamvr_unity_plugin#571]
I tried interactions example scene and teleport doesnt work, i cant do anything in the scene, no button does anything, i get no errors. Can you make a steamvr app that works for once? i am really fed up of steamvr

**Comment by zite** [comment]
I'm seeing errors in your other issue posts are those not related to this?

**Comment by zite** [comment]
Can you try to play the scene and then send me a steamvr system report? Something should be producing warnings or errors in unity but if not the steamvr system report will have it. You can email it to me at keithb@valvesoftware.com

**Comment by dpggit** [comment]
I got it working copying steamvr from an empty project
