### ISSUE TITLE
Using SteamVR Skeleton Poser but can't pick up objects 

### ISSUE THREAD

**Issue by diegodaly** [ValveSoftware/steamvr_unity_plugin#573]
I don't know where I'm going wrong here, this is what I've done:
- Import SteamVR
- Save and generate inputs
- Drag player prefab to scene, test hands and all working ok
- Imported interactable prefabs from lab scene demo, they work in my scene.
- Create 3d object (cube)
- Add interactable script, rigidbody, steamvr_skeleton_poser and edited pose for grabbing with both hands.
- Save pose

When I hit play, I can manipulate and grab the prefabs imported from the demo scene, but my own object is not grabbable.

Anything I'm missing here? Help!

**Comment by zite** [comment]
Are you getting any warnings or errors when trying to do this?
