### ISSUE TITLE
[Bug] teleport_marker_mesh layer is not set. TeleportPoint prefab does not work in new scenes.

### ISSUE THREAD

**Issue by mertkura** [ValveSoftware/steamvr_unity_plugin#574]
**Unity Version :** 2019.2.10f1 (Tested in all of 2019.2.X versions)
**Plugins :** Odin Inspector, Demigant Dotween, SteamVR(2.4.5 (sdk 1.7.15))

**Main Issue :** Teleport does not working after duplicating or changing transform in new scene.

**Issue steps:**
   Installation: Clean install any Unity 2019.2.X versions.
1. Open Interactions_Example scene.
2. Test teleports.(working)
3. Create new empty scene. (Changed new scene name as DemoScene)
4. Add Player, Teleporting, Teleport prefabs from project folder (or copy Player and Teleport gameobjects from Interaction_Example scene) in new scene.
5. Test teleports in DemoScene.(working)
6. Change teleport positions (with/without duplicating)
7. Save DemoScene.
8. Test teleports (not working).

**Workaround fix 1:**
1. Check TeleportPoint prefab items.
![resim](https://user-images.githubusercontent.com/20698762/68007487-d030f080-fc8c-11e9-9dfe-cf0626220272.png)
2. Check layer of teleport_marker_mesh
![resim](https://user-images.githubusercontent.com/20698762/68007530-ee96ec00-fc8c-11e9-9a40-b2f53798c164.png)
3. If it's empty layer as attached image below. It wont work.
4. Change layer of teleport_marker_mesh to default or anything in layer list. It will work.

**Workaround fix 2:**
When i checked prefab in text editor (unity serialize project objects in YAML format), i see TeleportPoint prefab uses layer no: 21. 
![resim](https://user-images.githubusercontent.com/20698762/68007732-88f72f80-fc8d-11e9-822c-d906aac7b42a.png)
1. Add something in 21st layer.
![resim](https://user-images.githubusercontent.com/20698762/68007709-7250d880-fc8d-11e9-99d0-c908aab40b74.png)
2. Check if teleport_marker_mesh layer is set.
![resim](https://user-images.githubusercontent.com/20698762/68007773-b17f2980-fc8d-11e9-8f0a-fb4ec660788e.png)
3. Go to Teleporting gameobject and check new layer in Trace Layer Mask layer selection checkbox list.
![resim](https://user-images.githubusercontent.com/20698762/68007834-ef7c4d80-fc8d-11e9-8d19-bbf533c754ce.png)
4. Teleports will work again.

**My foresight about this bug.**
First of all, i did not test installing SteamVR to Unity from github/package manager as submodule.

i. SteamVR installation from Unity Asset Store does not configure project layers(and its dependencies) correctly.
ii. As result of my research, after fresh installation, Trace Layer Mask value is set to "Everything", so there's no filtering on layers even if it's empty. So, teleports are working in unchanged Interaction_Example scene. 
![resim](https://user-images.githubusercontent.com/20698762/68008114-d627d100-fc8e-11e9-9d05-a83f327d8a0f.png)
But when i change something in scene, it turns out "Mixed" but checks all of listed layers in editor.
![resim](https://user-images.githubusercontent.com/20698762/68008209-2b63e280-fc8f-11e9-9d40-dc36fc3932cd.png)
![resim](https://user-images.githubusercontent.com/20698762/68008227-3f0f4900-fc8f-11e9-9a5d-becc5dbf46bf.png)
In case of that, Unity workflow breaks SteamVR workflow and teleports does not work.
I am going to open issue in Unity Issue Tracker about this problem. I have got same "Everything but mixed" bug in Unity PostProcessing Stack V2 too.

**Comment by mertkura** [comment]
As i checked Unity Issue Tracker, they labeled related issue as "Wont Fix"
_Source: https://issuetracker.unity3d.com/issues/physics-show-layers-dropdown-doesnt-display-everything-as-selected-when-all-options-are-checked_

**Comment by mertkura** [comment]
Also found same report in steam community.
https://steamcommunity.com/app/358720/discussions/0/1778262124955645767/

**Comment by zite** [comment]
Thanks for the detailed report. This was an artifact of integrating changes from The Lab. We'll get this fixed in the next version.

**Comment by zite** [comment]
This should be fixed in the 2.5.0 release. https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.5.0
