### ISSUE TITLE
How to determine which hand generated input event?

### ISSUE THREAD

**Issue by iangiblin** [ValveSoftware/steamvr_unity_plugin#575]
I have a VR game with guns, working in Unity, C#. The guns subscribe to a button event. The gun knows which hand it is being held in:

```cs           if (currentlyAttachedToHand) {
                gunTriggerOneHanded.AddOnChangeListener(OnShootOneHandedActionChange, hand);
                attachmentParentName = interactable.GetComponentInParent<Hand>().name;
                Debug.Log("Attached to " + attachmentParentName);
```
But when I get an event, **I can't tell which controller was used**, so if you're holding a gun in your left hand and you pull the right trigger, it still shoots.

```cs
        // THIS DOES NOT WORK ... JUST SAYS "ANY"
        Debug.Log("SteamVR_Input_Source = " + inputSource);

        if (inputSource == SteamVR_Input_Sources.LeftHand) {
            Debug.Log("LEFT hand shooting");
        } else if (inputSource == SteamVR_Input_Sources.RightHand) {
            Debug.Log("RIGHT hand shooting");
        }
```

I thought of adding left and right trigger pull events but then my script has to subscribe to both and that seems very inefficient. So what's the correct way to tell if the event happened on the controller I'm currently parented to?

Thanks in advance.

P.S. There are so many redirections for "where to ask for help with SteamVR 2.X" that I may be posting in the wrong place; if so please redirect me.

**Comment by ataylor09** [comment]
Not sure I understand  how you've defined the variable: `inputSource`

If it helps, this is how I handle it in my projects: 

1. Declare a public variable where you can define the input action you wish to respond to:

`public SteamVR_Action_Boolean myAction;`

2. Declare another public variable to define the type of hand you are interested in:

`SteamVR_Input_Sources source`

3. Then you can listen for events like so:

`myAction.GetStateDown(source)`

**Comment by zite** [comment]
Is the **hand** parameter you're passing into AddOnChangeListener left or right hand? If it's Any you will always get Any out.

**Comment by iangiblin** [comment]
**ataylor09**, thanks for the reply.

> Not sure I understand how you've defined the variable: `inputSource`

This comes back from the subscribed event. I was hoping it would carry some extra information, so even if I subscribe to "Any" hand, the actual input source might tell me which one generated the event, ideally the gameObject itself, then I could compare to the hand holding the pistol without the left/right distinction appearing in my code. Also if humans develop third hands or, uh, tentacles, the code would still work.

FYI this is the function which receives the inputSource, although it's unable to tell where the inputSource was:

```cs
    private void OnShootOneHandedActionChange(SteamVR_Action_Boolean actionIn,
                                              SteamVR_Input_Sources inputSource,
                                              bool newValue) {

        // should never be true because we deregister when not attached
        if (interactable.attachedToHand == null) { return; }

        // trigger not being pulled, do nothing
        if (!newValue) { return; }

        Shoot();
```
> 
> If it helps, this is how I handle it in my projects:
> ...

That actually does look fairly straightforward, but am I right in saying your gun (where this script is sitting) still needs code to see which hand it is being held in? So you need to set source to left or right hand based on that before calling myAction.GetStateDown() ... I think. So, it would work. The code looks a bit unfamiliar to me because I was working from the "planting" tutorial in the SteamVR documentation, which is all about those AddOnChangeListeners.

**Comment by iangiblin** [comment]
@keithbradner thanks for the reply.

> Is the **hand** parameter you're passing into AddOnChangeListener left or right hand? If it's Any you will always get Any out.

That may be the solution - it was indeed set to Any and I expected to get more information back. I'll test this later and close the issue if it works. I'm a bit disappointed that I can't make my code agnostic to the number of limbs/appendages or (joking aside) controllers the player has, as explained in the previous comment, but thanks for spotting that.

**Comment by iangiblin** [comment]
Sorry didn't mean to close the issue. Will close if the issue is resolved.

**Comment by iangiblin** [comment]
OK, confirmed working; this can probably be refined if the InputSource enum is available through the attachment Parent but for now it does exactly what I was trying to to.

Thank you very much for the help. For the record here is the relevant code which is called when we (the pistol) are attached to a new parent (assumed to be a hand), plus the equivalent weAreNotAttached method.

```cs
    private void weAreAttached() {

        // to what are we attached?
        attachmentParentName = interactable.GetComponentInParent<Hand>().name;
        Debug.Log("Attached to " + attachmentParentName);

        // if left hand, subscribe to left hand events
        if (attachmentParentName == "LeftHand") {
            Debug.Log("Listening to LEFT HAND");
            hand = SteamVR_Input_Sources.LeftHand;

        // if right hand, subscribe to right hand events
        } else if (attachmentParentName == "RightHand") {
            Debug.Log("Listening to RIGHT HAND");
            hand = SteamVR_Input_Sources.RightHand;

        // otherwise default to "any hand" and try to figure it out later!
        } else {
            Debug.Log("Listening to ANY HAND");
            hand = SteamVR_Input_Sources.Any;
        }
        gunTriggerOneHanded.AddOnChangeListener(OnShootOneHandedActionChange, hand);       
    }

    private void weAreNotAttached() {
        Debug.Log("Not attached to hand; detaching events from " + attachmentParentName);

        // the time for half measures and talk is over. Also, listening.
        gunTriggerOneHanded.RemoveOnChangeListener(OnShootOneHandedActionChange, hand);
    }

```
