### ISSUE TITLE
No option in Unity to disable "Automatically Enable VR" option

### ISSUE THREAD

**Issue by dpggit** [ValveSoftware/steamvr_unity_plugin#576]
Using Unity if i chose the Preferences option i could chose to activate or deactivate the "Automatically Enable VR" but now i cant see that option anymore, there is not even the SteamVR option

**Comment by zite** [comment]
Like most settings this has moved to the SteamVR_Settings asset. Depending on what version of the plugin you're using this is either in /Assets/SteamVR/Resources/SteamVR_Settings.asset or /Assets/SteamVR_Resources/Resources/SteamVR_Settings.asset
