### ISSUE TITLE
Several SteamVR errors i got after updating SteamVR

### ISSUE THREAD

**Issue by dpggit** [ValveSoftware/steamvr_unity_plugin#577]
I didnt change anything in my Unity project and when i opened it today i am getting several SteamVR reasons. The only thing i did was disable OpenVR in editor and then enable it again.
I get these errors :
NullReferenceException: Object reference not set to an instance of an object
Valve.VR.InteractionSystem.Hand.OnEnable () (at Assets/SteamVR/InteractionSystem/Core/Scripts/Hand.cs:1083)
The line which triggers the null error is  :             inputFocusAction.enabled = true;
NullReferenceException: Object reference not set to an instance of an object
Valve.VR.InteractionSystem.ControllerButtonHints.OnEnable () (at Assets/SteamVR/InteractionSystem/Hints/Scripts/ControllerButtonHints.cs:108)
The line which triggers the null error is  :             renderModelLoadedAction.enabled = true;

**Comment by dpggit** [comment]
When i try to open the input bindings the browser gives me an error saying cant connect to that address

**Comment by dpggit** [comment]
Looks like SteamVr app has been updated today, maybe that created the errors?

**Comment by dpggit** [comment]
I see my hand devices now dont appear as active in the steamvr app

**Comment by nenadcvele** [comment]
Same, binding UI can't be opened from unity. i can open it if i change port to 27062. But there are more bugs (left hand model appears broken)

**Comment by dpggit** [comment]
I am exhausted with SteamVR, i am working much more time to fix Steamvr than working in my game

**Comment by ellerychan** [comment]
> I see my hand devices now dont appear as active in the steamvr app

Could your issue possibly be related to this:  Issue #578 ?

**Comment by dpggit** [comment]
i dont even use render model prefab in my app

**Comment by dpggit** [comment]
I just commented the errors and the app started working again

**Comment by zite** [comment]
Those actions should never be null, did you change the hand script at all? Does this happen immediately on play?

**Comment by dpggit** [comment]
Yes, i had commented the renderModelInstance instantiation, but before didnt get any error, just with this STeamvr update

**Comment by dpggit** [comment]
I had a full body VR and didnt want any hand model

**Comment by zite** [comment]
you can uncheck the box @ellerychan refers to instead of commenting the instance. Other things may check that and throw errors like you're describing
