### ISSUE TITLE
Hand/controller interaction "broken" in 2.4.5; defaults changed

### ISSUE THREAD

**Issue by ellerychan** [ValveSoftware/steamvr_unity_plugin#578]
When I upgraded from SteamVR 2.3.2 to 2.4.5 my hand stopped grabbing the controller correctly.  It took me some time to track down the cause.  Some of the default values in the `RightRenderModel Slim` prefab and the `Controller (right)` prefab had changed with the upgrade.

This is the "broken" 2.4.5 behavior:

![F5E355D1-553B-48B4-B6A3-BD5D35540799](https://user-images.githubusercontent.com/6425759/68309992-4cf10f80-007d-11ea-9534-bae5e7d551d0.png)

![32531978-C743-4282-9B69-C80E197BE52F](https://user-images.githubusercontent.com/6425759/68310088-6b570b00-007d-11ea-9d03-5b25e4d838f7.png)

This is how it was in 2.3.2:

![E9C95BE9-44E0-422C-AAD2-0C549CA8AB2C](https://user-images.githubusercontent.com/6425759/68310167-888bd980-007d-11ea-8c8c-f790009971bd.png)

I tracked it down to a couple of default values in the hand model that had changed from 2.3.2 to 2.4.5.  Here are the settings that put it back to the way it was in 2.3.2:

![312ED23A-BE08-465D-9318-5632FDBAEA18](https://user-images.githubusercontent.com/6425759/68310370-e3253580-007d-11ea-80dd-7e6908048795.png)

![A2AE3F4F-0F5B-4958-AE40-4C35076203D0](https://user-images.githubusercontent.com/6425759/68310404-f3d5ab80-007d-11ea-8af5-b9f035522973.png)

![DA953529-9C5B-4805-8FB3-E4439778ED03](https://user-images.githubusercontent.com/6425759/68310424-fd5f1380-007d-11ea-8a46-351f696f7793.png)

**Comment by zite** [comment]
This is correct, it's an effect of us adding physics to the hands. Since SteamVR accepts any controller model from a driver it's tricky to dynamically create accurate bounds around the controller, so we opted to turn the model off by default.

**Comment by zite** [comment]
Reminder, if you want to use some functionality of the plugin long term you should copy it out of the plugin so you can customize it and not have it overwritten by updates
