### ISSUE TITLE
Binding UI - Loading Error

### ISSUE THREAD

**Issue by KevinBold** [ValveSoftware/steamvr_unity_plugin#579]
Hi, i'm unable to open the Binding UI in my Webbrowser.
It's saying: Firefox can't get a connection to localhost:8998

I also tried different webbrowsers, but still the same error message.

There is no other program using this port.

Attached you find the system report of SteamVR.

[SteamVR-2019-11-06-PM_10_45_35.txt](https://github.com/ValveSoftware/steamvr_unity_plugin/files/3816878/SteamVR-2019-11-06-PM_10_45_35.txt)

**Comment by kisak-valve** [comment]
Hello @KevinBold, this issue is already being tracked at #562. Closing in favor of the existing issue report.
