### ISSUE TITLE
SteamVR doesnt work with Unity 2019 and postprocess V2

### ISSUE THREAD

**Issue by dpggit** [ValveSoftware/steamvr_unity_plugin#581]
I am using Unity 2019.2.11f1, SteamVR 2.4.5 and HTC VIVE shows a black screen when Unity post process layer has activated "Directly to camera target" and when is disabled the VR image is very distorted.

**Comment by dpggit** [comment]
Doesnt work either with postprocess V1

**Comment by zite** [comment]
Thanks for the report but unfortunately this is a Unity XR issue, not a SteamVR Plugin issue. I'd recommend posting on their unity answers forum: https://answers.unity.com/
