### ISSUE TITLE
controller bindings not working for controllers i dont have

### ISSUE THREAD

**Issue by twillitwilli** [ValveSoftware/steamvr_unity_plugin#586]
I tried to publish a test game and asked some people to try testing controller bindings, and for oculus it worked, which is what i have, but for vive it didnt work. Is there any way i can look at controller bindings for controllers i dont have on the steam controller settings?

**Comment by twillitwilli** [comment]
nevermind im dumb and didnt realize this was a button https://i.gyazo.com/6bc7da60bf582ec926a09b40576b0728.gif

**Comment by kisak-valve** [comment]
Closing per the last comment.
