### ISSUE TITLE
Samsung odyssey- Interactions Not Working

### ISSUE THREAD

**Issue by taggrath** [ValveSoftware/steamvr_unity_plugin#589]
Samsung Odyssey , in the interactions example, the teleport works fine, however the interactions themselves aren't working correctly; there is no highlighting of the objects and the actions aren't doing anything to cause any sort of interaction with the objects. This is with unity build 2019.2.12f and the Steam VR plug in version 2.5.0

Please help

**Comment by zite** [comment]
Are you seeing any errors in the log?

**Comment by taggrath** [comment]
The interactions are working now; after downloading unity build 2.13 and re-importing the vr plug in to a new project, the interactions worked.

Thank you!
