### ISSUE TITLE
Companion window resolution/aspect ratio problem when rendering two windows on two screens of different sizes.

### ISSUE THREAD

**Issue by Zamahra** [ValveSoftware/steamvr_unity_plugin#59]
I'm experiencing strange behaviours of the companion window while building an Unity VR-application with an additional desktop UI. What I want to have: An UI on the first display, the view of the VR Player on the second.
When the second display is smaller than the first display, the companion window gets horizontally stretched. When I Switch both windows from one display to another, the companion window works properly. When the first display is smaller than the second display, the companion window just uses a small portion of the second display. I prepared a test project which reproduces the error. 

Companion window on the right is stretched
<img width="3200" alt="unbenannt" src="https://user-images.githubusercontent.com/10512416/32830968-2609e6b2-c9f7-11e7-9e8d-5c496795a9fe.png">
After switching window to the left display in runtime it's rendering correctly
<img width="3200" alt="unbenannt2" src="https://user-images.githubusercontent.com/10512416/32830920-05d9dfdc-c9f7-11e7-88ea-a72ed44e3c92.png">

[MultipleDisplayBug.zip](https://github.com/ValveSoftware/steamvr_unity_plugin/files/1474244/MultipleDisplayBug.zip)

**Comment by zite** [comment]
This sounds like an issue with Unity itself, not the valve plugin. I also believe this should have been fixed on recent versions of Unity.
