### ISSUE TITLE
How to access hmd proximity sensor?

### ISSUE THREAD

**Issue by dpggit** [ValveSoftware/steamvr_unity_plugin#591]
I see in Player.cs script there is in the Update method code to access it but doesnt work. I tried creating the HeadsetOnHead action in another action set but doesnt work either. I just can create actions for the hand controllers, not for the hmd. I use Steamvr 2.5.0

            if (SteamVR.initializedState != SteamVR.InitializedStates.InitializeSuccess)
                return;
            if (headsetOnHead != null)
            {
                if (headsetOnHead.GetStateDown(SteamVR_Input_Sources.Head))
                {
                    Debug.Log("<b>SteamVR Interaction System</b> Headset placed on head");
                }
                else if (headsetOnHead.GetStateUp(SteamVR_Input_Sources.Head))
                {
                    Debug.Log("<b>SteamVR Interaction System</b> Headset removed");
                }
            }

**Comment by dpggit** [comment]
This is how is my hmd binding_index_hmd.json 

{
  "controller_type": "index_hmd",
  "description": "",
  "name": "index hmd defaults",
  "bindings": {
    "/actions/default": {
      "chords": [],
      "sources": [
        {
          "path": "/user/head/proximity",
          "mode": "button",
          "parameters": {},
          "inputs": {
            "click": {
              "output": "/actions/default/in/headsetonhead"
            }
          }
        }
      ],
      "poses": [],
      "haptics": [],
      "skeleton": []
    }
  }
}

**Comment by zite** [comment]
Unfortunately there was a bug in the index hmd binding prior to 2.5.0. The controller_type is "indexhmd" not "index_hmd". If you take the underscore out of the binding file and the relevant part of your actions file it should work.

**Comment by dpggit** [comment]
It doesnt work changing it to binding_indexhmd

**Comment by dpggit** [comment]
Changed it to   "controller_type": "indexhmd", and doesnt work

**Comment by zite** [comment]
Did you change the controller type in both the actions.json and the binding
file?

**Comment by dpggit** [comment]
Yes, i changed it in actions.js and the binding file and doesnt work

**Comment by zite** [comment]
If you can run your app, put on the headset, verify it doesn't trigger the proximity sensor and then create a steamvr system report and send it to me I can better debug. keithb@valvesoftware.com

**Comment by dpggit** [comment]
Dont find any SteamVR -> Menu

**Comment by zite** [comment]
![image](https://user-images.githubusercontent.com/198704/69453511-eb859d80-0d18-11ea-9551-c65109e539ad.png)

**Comment by dpggit** [comment]
I have just sent you the email with the report

**Comment by zite** [comment]
Thanks, it looks like your headsetonhead action is not getting bound. When you sent me the report you had a vive plugged in, not an index. Can you check your binding_vive.json for the proximity binding?

**Comment by dpggit** [comment]
Yes, i dont have a vive index, just a file i opened with the name binding_index_hmd. This is what i have in Binding_index.json

{
  "controller_type": "vive",
  "description": "",
  "name": "vive defaults",
  "bindings": {
    "/actions/default": {
      "chords": [],
      "sources": [
        {
          "path": "/user/head/proximity",
          "mode": "button",
          "parameters": {},
          "inputs": {
            "click": {
              "output": "/actions/default/in/headsetonhead"
            }
          }
        }
      ],
      "poses": [],
      "haptics": [],
      "skeleton": []
    },
    "/actions/htc_viu": {
      "chords": [],
      "sources": [
        {
          "path": "/user/head/proximity",
          "mode": "button",
          "parameters": {},
          "inputs": {
            "click": {
              "output": "/actions/htc_viu/in/viu_press_31"
            }
          }
        }
      ],
      "poses": [],
      "haptics": [],
      "skeleton": []
    }
  }
}

**Comment by dpggit** [comment]
I got to solve it using viu_press_31

**Comment by dpggit** [comment]
I found a problem. When you already have the hmd on your head before the app starts the getstatedown doesnt trigger, you need to remove the hmd and put it on again

**Comment by zite** [comment]
Ideally the name of your binding file should relate to the device it is binding to. Otherwise it may cause confusion to your users.

GetStateDown is not triggered because the state is not changing from false to true when your application starts with the headset already on your head. You may want to check GetState instead of GetStateDown.

**Comment by dpggit** [comment]
I had already tried GetState but it is always true even when you didnt put the headset yet
