### ISSUE TITLE
Moving the Player with high velocity causes the hand models to lag behind the current position

### ISSUE THREAD

**Issue by troyspencer** [ValveSoftware/steamvr_unity_plugin#593]
My game has an element where you can accelerate yourself to high speeds and launch across open stretches of space. Due to the issue mentioned in the title, I have had to limit the maximum velocity of the player in order for the hand models to catch up (any velocity above 5 makes this very noticeable). Ideally, the velocity should be unbounded by this, so that even ludicrous speeds represent the hands smoothly relative to the player. I'm looking for one of several solutions. 

- Have hand models render in the reference frame of the player, tracking velocity and angular velocity (ideal, scales to any situation; seems like this is done to some degree but currently fails when beyond normal human speeds)
- Have hand models update position more frequently (not ideal, will eventually be outscaled by some velocity)
- Simulate player velocity in another way which does not trigger this effect (not ideal, does not take advantage of orthogonal design elements and standard library in a natural way)

**Comment by zite** [comment]
The example Interaction System included with the plugin uses a physics based approach to hand movement. That's unlikely to work well with high velocities by design. 
The basic camera rig that is included may fit your situation better.
