### ISSUE TITLE
HMD InverseTransformPoint reports invalid negative values

### ISSUE THREAD

**Issue by jeffdepascale** [ValveSoftware/steamvr_unity_plugin#6]
Reference a controller relative to the HMD using transform.InverseTransformPoint (part of SteamVR_Utils), then move the controller in any negative direction on x/y/z planes and monitor the values - they will report correct until around -0.2, then jump to -1.0 to around -1.2, then continue correctly from -0.3 on. Is this a known issue? A quick glance didn't show a duplicate issue. plugin v1.2.

**Comment by aleiby** [comment]
I don't see anything obvious with the existing implementation.  Maybe Unity isn't normalizing their quaternions after inverse?  They don't proved a normalize interface, so I would expect them to handle that internally.  Let me know if you figure what's going on there.
