### ISSUE TITLE
Unity Steam VR Oculus Touch disabling on Start with latest unity version 2017.2

### ISSUE THREAD

**Issue by Nukron** [ValveSoftware/steamvr_unity_plugin#60]
I have really no clue anymore, i checked everything, searched the internet for solutions and have no idea what the problem is. As the title says already my both controllers get disabled when i press play in unity, i deleted the main camera put the camera rig from the assets inside and they just get disabled when i press play. Anyone knows this issue and has maybe a solution to it?

**Comment by Benjaminhaesemeyer** [comment]
I'm having the same issue with vive controllers. using Unity 5.6 and SteamVR 1.2.3

**Comment by zite** [comment]
Thanks for the report. I believe this issue was fixed with the latest versions of SteamVR and the Unity Plugin released today. Let me know if it's still an issue and I'll reopen.
