### ISSUE TITLE
Hand Hovering doesnt work when SteamVR_Behaviour_Pose is enabled

### ISSUE THREAD

**Issue by dpggit** [ValveSoftware/steamvr_unity_plugin#601]
I need to have SteamVR_Behaviour_Pose component disabled in Unity as otherwise hovering doesnt work and i cannot attach objects

**Comment by dpggit** [comment]
This worked in previous versions i updated to 2.5 and doesnt work

**Comment by zite** [comment]
It sounds like you are also using Vive Input Utility which may be causing the issues you are seeing. Can you verify you see this behavior in a new project?

**Comment by dpggit** [comment]
I dont use VIU, i deleted it some time ago, i just made my onw trackvelocity method

**Comment by kisak-valve** [comment]
Closing pending feedback if this behavior is reproducible with a new project.
