### ISSUE TITLE
BlendToPoser leftHand (again)

### ISSUE THREAD

**Issue by Jordo76** [ValveSoftware/steamvr_unity_plugin#605]
Hello, I've recently started using the SteamVR skeleton & skeleton poser on my app and I've noticed that if I do not use SteamVR's interactables and instead BlendToPoser myself, any finger that is not set to static on the left hand will have their animation mirrored (fingers going in the opposite way as if they were on the right hand instead). Now do note this works fine with the right hand.

This is indeed the exact same issue encoutered by @dpankowski in his issue dated May 2019 here which was resolved in 2.3b1, therefore his screenshots on his first post are still relevant :
https://github.com/ValveSoftware/steamvr_unity_plugin/issues/427

Since this issue has been marked as fixed and someone experiencing the issue in October and commenting did not seem to draw any reaction from the development team, I figured it might've been due to a lack of visiblity and created a new issue on the return of this bug.

Furthermore, judging from that comment in October, the bug has returned since at least 2.4.1b, I can confirm that it is still present in 2.5.0, which is what I am using.

After a few tests, I've come to the conclusion that there is definitely *something* counteracting the fingers mirroring when grabbing an object in the left hand in the 'Hand' or 'Interactable' script that only triggers itself if you grab an object using their methods.
This is demonstrated by the fact that picking up the same object using the same Player prefab but one with Interactable and the other with a custom script calling BlendToPoser made the Interactable one grab just fine but the custom script one inverted the non-static fingers on the left hand.

**Comment by kisak-valve** [comment]
Hello @Jordo76, thanks for the feedback. There's no value in fragmenting the discussion between multiple issue reports, so I've dropped the fixed in next release label and transferred this issue report to https://github.com/ValveSoftware/steamvr_unity_plugin/issues/427#issuecomment-562563299.
