### ISSUE TITLE
TeleportAreaVisible - Shader is pink

### ISSUE THREAD

**Issue by Lukaris** [ValveSoftware/steamvr_unity_plugin#61]
I am using Unity 2017.2.0f3 Personal. and the Shader of the teleport Area is pink for the Higlight and the SeeThru ..  which makes it very irritation to work on the scenes.

<img width="312" alt="bildschirmfoto 2017-11-28 um 00 08 06" src="https://user-images.githubusercontent.com/26258216/33294331-6ecf0e62-d3d0-11e7-8cd8-98c41c386a00.png">

any idea how to get rid of it ?  or is it because of the new Unity version. Just started to work on SteamVR

**Comment by zite** [comment]
Thanks for the report, I believe this issue has been fixed in the version of the plugin released today. Let me know if it's still an issue and I'll reopen.

**Comment by jgwinner** [comment]
This seems to work OK but I'm getting consistent issues with the Steam controller code, the Vive models always look pink. I'll open a separate issue.
