### ISSUE TITLE
How to add a Steam Browser feature into a VR game?

### ISSUE THREAD

**Issue by castana1962** [ValveSoftware/steamvr_unity_plugin#610]
Hi
I am building VR Video Games for Health problems with Valve Index and I need to add Browser feature into these one( and not through Standard Browsers like Chrome) to can access additional info( for example a Blog), for it. Are there any metod to do it? Please If anybody know some similar way to do it, I am willing to heard it......
Thanks for your time
Alejandro

**Comment by zite** [comment]
Sorry this is not a feature of the SteamVR Unity Plugin. I'd recommend posting here: https://steamcommunity.com/app/250820/discussions/7/

**Comment by castana1962** [comment]
Hi @keithbradner
Sorry but I just to see your answer.
I will post it in this place
Thanks for your support
Best Regards
Alejandro
