### ISSUE TITLE
SteamVR_RenderModel doesn't initialise if Time.timescale is 0

### ISSUE THREAD

**Issue by onimitch** [ValveSoftware/steamvr_unity_plugin#62]
We have our game paused on start to show a menu, while in the background the game (and thus VR components) initialise.

With time.timeScale = 0, it breaks the spawning of the controllers. They track correctly, however the models do not appear in the world.

We tracked down the cause to the use of `yield return new WaitForSeconds(0.1f);` in SteamVR_RenderModel.SetModelAsync. Changing this to `WaitForSecondsRealtime` fixed the issue.

**Comment by aleiby** [comment]
I've made this change for Unity 5.4 and newer.  Older versions of Unity do not have WaitForSecondsRealtime.  I'll post the update after we rev the SDK later this month.

**Comment by talha171** [comment]
my  both  controllers are not showing when me run my project in steam uesd unity
