### ISSUE TITLE
Adding UI actions to SteamVR actions

### ISSUE THREAD

**Issue by yschuurmans** [ValveSoftware/steamvr_unity_plugin#620]
I have been toying around with this plugin for a bit now, and have almost completely been able to map everything comfortably to my Valve Index controllers. The only thing I am a bit lost on is how to properly use the UI, preferable without holo buttons. I have been trying to configure the plugin using the joystick, which kind of seems to work. The only real limitation I am encountering is the fact that there are no different SteamVR actions for the separate UI actions from within the cockpit(or other boolean buttons) outside of the primary/secondary/alt buttons. If it is possible I think it would be of great help to all the joystick-using users if you could add separate POV actions for us to configure(just like you have the Menu Buttons set up right now).

**Comment by yschuurmans** [comment]
accidentally placed in the wrong repo, sorry!

**Comment by kisak-valve** [comment]
Hello @yschuurmans, was this intended for the SteamVR Unreal plugin?
