### ISSUE TITLE
Cannot open binding UI

### ISSUE THREAD

**Issue by wumingzhidewu** [ValveSoftware/steamvr_unity_plugin#621]
I went through the Open binding UI at the bottom of the SteamVR input window, but couldn't link, and reported that Firefox could not establish a connection to the localhost: 8998 server.
why?

**Comment by zite** [comment]
We've got a sticky issue that explains the problem: https://github.com/ValveSoftware/steamvr_unity_plugin/issues/562

Basically you'll need to make some code changes or upgrade your version of the plugin.
