### ISSUE TITLE
Input not working and controllers not showing up in build

### ISSUE THREAD

**Issue by Saticmotion** [ValveSoftware/steamvr_unity_plugin#633]
I have 3 computers to test with, and I have the following HMDs: Rift, Rift S and Vive. The same issue is present in all configurations of computer/HMD. In the editor my bindings are working fine and all poses are tracked. In a build however, the controllers and hands don't show up and no input is registered in my app. The only thing that works is head tracking.

In a build I get constant stream of Invalid Handle errors (see [Player.log](https://github.com/ValveSoftware/steamvr_unity_plugin/files/4090319/Player.log)). The log file also indicates that my bindings are loaded just fine, and all hardware is found correctly.

I can also confirm that I've generated actions, and that they're included in my project:
![Capture](https://user-images.githubusercontent.com/5888357/72794306-166a7000-3c3c-11ea-8b76-891c3163e309.PNG)

Their contents look fine to me, but you can check them here (changed extension to txt so I can attach them here): 
[actions.txt](https://github.com/ValveSoftware/steamvr_unity_plugin/files/4090340/actions.txt)
[bindings_oculus_touch.txt](https://github.com/ValveSoftware/steamvr_unity_plugin/files/4090341/bindings_oculus_touch.txt)

When I run a built version of my app, the controller binding UI doesn't show the default binding. Instead it suggests I edit the _Legacy_ bindings: 
![Capture](https://user-images.githubusercontent.com/5888357/72795208-81687680-3c3d-11ea-948d-4372d6983521.PNG)

My software versions are the following:
Windows 10
Unity 2019.2.18f1
SteamVR plugin 2.5.0
SteamVR Beta 1.10.4

All VR device drivers/firmware are up to date as well.

And finally my Unity packages:
![Capture](https://user-images.githubusercontent.com/5888357/72794811-e2437f00-3c3c-11ea-8eb3-f72a0198b114.PNG)

**Comment by Kyloman** [comment]
i have the exact same problem with the Vive. i think the file location where the action sets and manifest files are supposed to be have changed. let me know if you figure it out, i'll be working on it this weekend

**Comment by Saticmotion** [comment]
This has suddenly been solved, and I don't know how. I made no code changes, nor updated any of the software in the chain.
