### ISSUE TITLE
Example scene for v1.0.12 has controllers/lighthouses fixed at (0, 0, 0)

### ISSUE THREAD

**Issue by petethor** [ValveSoftware/steamvr_unity_plugin#65]
When running the example scene the headset is moving but no controllers/lighthouses appear in the correct places. They are fixed at (0, 0, 0). The controllers are disabled when running.

Using:
SteamVR build 9 jan 19.33 (1515522829)
Unity 5.6.3p4
SteamVR Plugin 1.2.3

In Unity 2017.3.0f3 it works though.

**Comment by Benjaminhaesemeyer** [comment]
When using the [CameraRig] in SteamVR>Prefabs the Controller (Left) and Controller (Right) GameObject's become inactive on play in any scene. This issue started occurring after the update to the SteamVR Plugin to version 1.2.3.

I'm using unity 5.4, 5.5, and 5.6 and the issues is happening in all versions. 

I had an old project with a copy of SteamVR Plugin version 1.2.2. So for now i'm just going to revert all the 1.2.3 version back to that.

**Comment by jonthelin** [comment]
I have the same issue in Unity 5.6.1p1 and SteamVR Plugin 1.2.3. I dragged the CameraRig into an open scene and the controllers never become enabled when I play the scene.

**Comment by aleiby** [comment]
See my comment in #49.

**Comment by petethor** [comment]
Commenting out the suggested row helped. Hope you find a proper fix in the future. Cheers.
