### ISSUE TITLE
GetPoseActionData error

### ISSUE THREAD

**Issue by aenima2** [ValveSoftware/steamvr_unity_plugin#663]
When I try to start our (Unity) builds for Steam our logs are spammed with messages like these:

_[SteamVR] GetPoseActionData error (/actions/default/in/Pose): InvalidHandle Handle: 1152985224741651024. Input source: LeftHand
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

[SteamVR] GetPoseActionData error (/actions/default/in/Pose): InvalidHandle Handle: 1152985224741651024. Input source: RightHand_

Input works as it should in the editor and when I build for Viveport we don't have any issues with input either.

There seems to have been a lot of issues like this in the past (#203 or #110) but they're supposedly should be fixed now.

Any help would be much appreciated.

**Comment by chris-redbeed** [comment]
@aenima2 Did you found a fix for that? I have the same issue.

**Comment by aenima2** [comment]
I honestly can't remember sadly and I have no way of testing it either because I'm no longer working with VR. Sorry, hope it sorts itself out.
