### ISSUE TITLE
Issue with custom hands.

### ISSUE THREAD

**Issue by ataylor09** [ValveSoftware/steamvr_unity_plugin#672]
I'm having an issue trying to implement custom hands using the Interaction system. I have rigged my hand model in Maya using the rig provided (as detailed [here](https://github.com/ValveSoftware/openvr/wiki/Hand-Skeleton))

I have imported my hand mesh and created a prefab which mimics the existing vr_glove_right prefab:
![custom_glove](https://user-images.githubusercontent.com/5655773/76567735-459eae80-6514-11ea-8e41-bc1d9812a0c7.png)

here is the original glove prefab that I have coppied:
![original_glove](https://user-images.githubusercontent.com/5655773/76567749-50594380-6514-11ea-9858-dc392f1ae9e4.png)

Then I created a render model prefab and used my custom glove model as the hand prefab:
![render model prefab](https://user-images.githubusercontent.com/5655773/76567915-aa5a0900-6514-11ea-94bf-9c8d3ac04a0c.png)

And applied this render model to the right hand in the player prefab:;
![Player Right hand](https://user-images.githubusercontent.com/5655773/76567996-da091100-6514-11ea-9154-585257aebca6.png)

However, when I run the game in the editor, I get weird hand behavior on my custom hand:
![hand error](https://user-images.githubusercontent.com/5655773/76568081-045ace80-6515-11ea-9f2d-92ad959b70a4.png)

The fingers seem to curl OK when I pull the trigger or grip trigger (using Rift-S controllers in my case). But as you can see, the skinned mesh renderer is all over the place!

I have verified that the rig is skinned correctly by manually rotating all the bones in the prefab editor window... No issues there as the hand seems to animate just fine.

Any ideas how to fix this? Would really appreciate help with this.

**Comment by ataylor09** [comment]
Ok, I seem to have gotten around this by copying the way that the Alien hands are implemented.

Just in case someone else comes across this who's interested in implementing their own custom hands, I recommend using this approach. There is a helper script in there called CustomSkeletonHelper, which allows you to map a custom skeleton to the one that the SDK uses.  

The script is very basic, but it worked for me!

**Comment by kwea123** [comment]
Have you tested hands with fingers less than 5 joints? I tested on my hand with fingers with 3 joints but it doesn't work.

**Comment by ataylor09** [comment]
@kwea123 look at the alien hand in the steam room samples, it’s a 3 fingered hand
