### ISSUE TITLE
Car Virtual Reality Showrrom Design, please help !!!

### ISSUE THREAD

**Issue by castana1962** [ValveSoftware/steamvr_unity_plugin#68]
Hi All 
I am tring to do some similar to this
https://youtu.be/12-Y-6ilMbw
I guess that the steamVR plugin already comes with everything you need to interact with cars but since my English is little, Could anybody help me to find Steam VR plugin for Unity to make VR UI to select differents cars models or change its color?
Thanks for your time
Castana62

**Comment by zite** [comment]
Sorry this is more of a general unity question than a SteamVR specific thing. Try the forums here: https://steamcommunity.com/app/250820/discussions/
