### ISSUE TITLE
SteamVR_Controller.Device "valid" property's "get" does not call Update()

### ISSUE THREAD

**Issue by JeffBail** [ValveSoftware/steamvr_unity_plugin#70]
It looks like just about all the properties in SteamVR_Controller.Device have get accessors which call Update()  with the exception of "valid". Since Update() is what actually sets valid it seems like this would be especially important here.

**Comment by SnugglePilot** [comment]
We worked around this problem by checking ".connected" first (which forces the update), but this has been the core source of a long-time bug of ours. Just tracked it down today thanks to this Issue item. Thanks!

**Comment by zite** [comment]
This has been removed in the new input system. Will leave this open until I merge beta to main
