### ISSUE TITLE
Unable to import Valve.VR namespace into my Unity 2019.3 script

### ISSUE THREAD

**Issue by BenderJacob** [ValveSoftware/steamvr_unity_plugin#709]
Unity Version: 2019.3.12f1
SteamVR Plugin Version: 2.5.0 (sdk 1.8.19)

What happens is I create a new project, Import the valve vr plugin from the unity asset store, Create a new CS script and then try adding `using Valve.VR;`to the top of my script in the imports but then I get an error saying  "The type or namespace name 'VR' does not exist in the namespace 'Valve'".

The only namespace in the Valve namespace is "Newtonsoft" so it sees the Valve namespace but not anything in the valve namespace

**Comment by CyrilSarov** [comment]
I had a similar problem yesterday, [here's a link to my post with my workaround](https://github.com/ValveSoftware/steamvr_unity_plugin/issues/707). There seems to be something wrong with 2019.3, because it works with 2018.4 and 2020.1.

**Comment by zite** [comment]
This is apparently strictly a Unity 2019.3.12f1 issue. It does not happen with 2019.3.11f1. I'd recommend downgrading to that: https://unity3d.com/get-unity/download/archive

**Comment by zidik** [comment]
Thanks, @keithbradner for the pointer!
I can confirm, that the specific version Unity 2019.3.12f1 was the culprit. Upgrading to 2019.3.13f1 resolved it for me.
