### ISSUE TITLE
Unable to use SteamVR on MacOS with the Unity Editor and the Unity Plugin

### ISSUE THREAD

**Issue by alexeystrakh** [ValveSoftware/steamvr_unity_plugin#710]
Hi Steam!

I'm trying to use SteamVR on my MacBook Pro 2019 to run SteamVR for my Oculus Quest device. I know that this works on Windows, but I wasn't able to run it on Mac OS. The device itself is connected via Oculus Link cable and I can see it via `adb devices` terminal command:

```
adb devices
List of devices attached
1PASH9AK4CXXXX device
```

Also, I can deploy apps there (APK) without any issues. But the SteamVR when run is crashing with the following error:

```
Headset is not detected, make sure your headset is connected, then reboot it by clicking below.
```

I've followed all the suggestions from the troubleshooting section here (https://support.steampowered.com/kb_article.php?ref=8566-SDZC-9326#headset) - nothing helps :

1. restart device
2. try different usb port
3. restart mac
4. update steam/steamvr

Could you please confirm that I can run SteamVR on Mac OS and use my connected (wired) Oculus Quest with it?

**Comment by zite** [comment]
Unfortunately, both Oculus and SteamVR do not currently support MacOS.
