### ISSUE TITLE
Have they open sourced the room setup?

### ISSUE THREAD

**Issue by KellanHiggins** [ValveSoftware/steamvr_unity_plugin#711]
So I've found I've had to redo my setup every single time I boot my 2016 OG Vive. The room set up is okay, but I'd love to have a super quick version.

1. You start it up with your headset sitting on the ground. As soon as it boots, it checks for floor. Once the floor is confirmed, it goes to the next step.
2. You pick up your controller and aim towards the screen. As soon as you pull the trigger, it switches to room layout which remembers if you want normal or advanced mode.
3. You lay out your room however you'd like and then click any other button except the trigger and it finishes and the layout is done.

I know that the setup uses Unity. I wonder if that code is out there for someone to modify? I would be happy to do it.

**Comment by zite** [comment]
Having to redo your room setup every time sounds super annoying. One thing you can do is use the controller to progress through the screens by pressing on the right/left side of the touchpad. The room setup is unfortunately not open source. You may have better luck talking about this in the SteamVR Dev forums here: https://steamcommunity.com/app/250820/discussions/7/

**Comment by KellanHiggins** [comment]
Appreciate the response! And I did not know about that shortcut. That is handy. Thanks :).
