### ISSUE TITLE
Immediate crash when new OpenXR plugin is used

### ISSUE THREAD

**Issue by 1runeberg** [ValveSoftware/steamvr_unity_plugin#712]
> > > > Hi,
> > > > I am having the same issue. Here is a link to the unity editor log and the steamvr system report: [link](https://drive.google.com/open?id=14REanCw8SJTf9gCWXN_DIJR_ZCTMe7ZD)
> > > > I am using Unity 2019.3.3f1 and tried using the new Open XR plugin with legacy steam vr input. I also have Oculus XR Plugin installed. I am also using the old, standard/built-in render pipeline. No URP or HDRP. I am running the application in Linear Color space. I also noticed that a known issue in wiki is that "OpenVR Mirror View Mode (default) can cause black screens in the game view". I tried setting it to None, but no difference in the Editor.
> > > > Whenever I try to play in editor, it crashes. It seems that the unity process does get connected to the steam vr application, however as soon as the game becomes playable (it does render a frame or more) it crashes. It also does not matter if there is a XR rig or even a camera in a scene or no. It still crashes.
> > > > When I create a Windows build and execute it, the application just has a black screen on my computer monitor and nothing happens, no matter how long I wait. It seems the SteamVR does not even try to start the application and it still stays in Steam Home. Though the FPS in Steam Home (while looking through the Vive headset) is dropped significantly while the malfunctioning executable is running.
> > > > I hope this gets fixed asap, otherwise without having the ability to test in editor nor the build, this plugin is simply unusable.
> > > 
> > > 
> > > Hi @mikson60 - setting it to None should stop any rendering in the Editor, are you still getting a preview even with this setting?
> > 
> > 
> > Not sure if I get the preview. It crashes anyways. It crashes even when the scene is empty and I hit play. I can check tomorrow if the first few frames are rendered before the crash.
> 
> hmm.. this could be something different/unrelated. are you able to share some logs here or if there's any sensitive info you dont want to share in public, you can send them to [runeb@valvesoftware.com](mailto:runeb@valvesoftware.com)

It probably is related. Because if I remove the OpenXR package, the problem goes away. The link in my first comment has 2 logs: unity editor log with crash at the end and the steamvr system log.

_Originally posted by @mikson60 in https://github.com/ValveSoftware/steamvr_unity_plugin/issues/704#issuecomment-624267428_

**Comment by 1runeberg** [comment]
Hi @mikson60 - want to investigate this a bit further, as there shouldnt be any imemdiate crashes especially when setting the rendering to None.

I noticed your project uses single pass... is it using DirectX or Vulkan?

**Comment by mikson60** [comment]
> Hi @mikson60 - want to investigate this a bit further, as there shouldnt be any imemdiate crashes especially when setting the rendering to None.
> 
> I noticed your project uses single pass... is it using DirectX or Vulkan?

I already removed the package but I think it was Direct3D11. I have not changed it explicitly so it should have the default value, which I believe is not Vulkan.

**Comment by msuencksen** [comment]
Over here, XR (Unity 2020.1b7) crashed immediately while using the **SteamVR version 1.9.16**. I do not run the Steam client in the background. After updating SteamVR this went away. From the Editor.log:

```
[XR] VR_Init initError: VRInitError_Init_InterfaceNotFound

and

========== OUTPUTTING STACK TRACE ==================

0x00000251BA587A92 (XRSDKOpenVR) XRSDKPreInit
  ERROR: SymGetSymFromAddr64, GetLastError: 'Es wurde versucht, auf eine unzulässige Adresse zuzugreifen.' (Address: 00000251BA5820D5)
0x00000251BA5820D5 (XRSDKOpenVR) (function-name not available)
0x00007FF757AD8F27 (Unity) UnityXRDisplayGraphicsThreadProvider_5::Adapt_PopulateNextFrameDesc
0x00007FF757ACA784 (Unity) XRDisplaySubsystem::GfxDeviceCallback_FrameBoundary
0x00007FF75949A7BA (Unity) GfxDeviceWorker::RunCommand
0x00007FF7594A209C (Unity) GfxDeviceWorker::RunExt
0x00007FF7594A2488 (Unity) GfxDeviceWorker::RunGfxDeviceWorker
0x00007FF7573FE190 (Unity) Thread::RunThreadWrapper
0x00007FFB7F5D7BD4 (KERNEL32) BaseThreadInitThunk
0x00007FFB7FF6CE51 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

```

**Comment by 1runeberg** [comment]
> > Hi @mikson60 - want to investigate this a bit further, as there shouldnt be any imemdiate crashes especially when setting the rendering to None.
> > I noticed your project uses single pass... is it using DirectX or Vulkan?
> 
> I already removed the package but I think it was Direct3D11. I have not changed it explicitly so it should have the default value, which I believe is not Vulkan.
> 
> I am using Auto Graphic API for Windows.

Hi @mikson60 - is this the only project you've tried with the new plugin? The crash report seems to be happening in Odin for some reason.

**Comment by 1runeberg** [comment]
Hi @mikson60 - just following up on this. if you're still encoutnering hte issue in your project after checking odin - can you send us a dump file fo the crash:

Can you get a dump (.dmp) file for us to review?
https://docs.unity3d.com/Manual/WindowsDebugging.html

It'll help us in our investigation.

**Comment by mikson60** [comment]
> Hi @mikson60 - just following up on this. if you're still encoutnering hte issue in your project after checking odin - can you send us a dump file fo the crash:
> 
> Can you get a dump (.dmp) file for us to review?
> https://docs.unity3d.com/Manual/WindowsDebugging.html
> 
> It'll help us in our investigation.

Hey! Yes, I could help. I am busy the following days though. Perhaps I can do it on the weekend. If not then the other half of the next week.

**Comment by 1runeberg** [comment]
Just a short update - we're working on a new release thatll help us isolate this. Will ping here when we have that ready. Sorry for the delay.

**Comment by eyalfx** [comment]
I'm getting similar issue on Unity2019.4LTS . if I have OpenXR loaded by default in project settings then Unity (editor and build) crash right away with similar log to the one above.

**Comment by zite** [comment]
This should be fixed now in the latest previews. https://steamcommunity.com/app/250820/discussions/7/2790493983190548289/

If it isn't please create an issue here: https://github.com/ValveSoftware/unity-xr-plugin/issues/
