### ISSUE TITLE
OpenVR XR Plugin Crashes Unity on Play

### ISSUE THREAD

**Issue by Extrys** [ValveSoftware/steamvr_unity_plugin#716]
I was using oculus XR pluggin and everything went well, then i added the new XR Plugin for OpenVR and disabled oculus, i seet the mirror mode to None,
this problem fixes when i disable OpenVR XR Plugin
there are the error logs
[Editor.log](https://github.com/ValveSoftware/steamvr_unity_plugin/files/4594401/Editor.log)
[error.log](https://github.com/ValveSoftware/steamvr_unity_plugin/files/4594402/error.log)

**Comment by 1runeberg** [comment]
Hi @Extrys - thanks for reaching out. 

Can you get a dump (.dmp) file for us to review?
https://docs.unity3d.com/Manual/WindowsDebugging.html

We're unable to replicate so we need to dig a little bit deeper into the issue.

**Comment by Extrys** [comment]
Of course!
I've also researching a bit and seems that Disabling the "Initialize XR on Startup"
an then via code starting the subsystems, it does not crash
 until i press some input, for example, "primary button" wich is Generic for XR or "menu button" 
some seems to work but most doesnt or crashes the application
im also using the new input systems for unity 

im strugling my head to see what i can do to make it compatible with steam VR right now,
my game was compatible before but due to the future deprecation to OpenVR Desktop Standalone
i decided to switch to the XR Plugin for unity, i have been working with the Oculus XR Plugin and it works nice! but i have to submit my game for the steam spring games festival and my game is not playable right now with HTC Vive nor Index

[Crash_2020-05-07_180555793.zip](https://github.com/ValveSoftware/steamvr_unity_plugin/files/4597259/Crash_2020-05-07_180555793.zip)

**Comment by 1runeberg** [comment]
Just a short update - we're working on a new release thatll help us isolate this. Will ping here when we have that ready. Sorry for the delay.

**Comment by Evryway** [comment]
I have had the editor crash on entering Play mode with the XR plugin - not reliably reproducible for me, though. Happy to test a release to help isolate.

**Comment by dumbgamedev** [comment]
I can reproduce this error. If I close steamVR AND unplug my Vive OG (pull out the power plug on the link box), it will crash when I load my game.

This is my setup:

Setup:
Unity: 2019.3.14f1
SteamVR: 1.11.13
Steam Unity Plugin Package: Latest version
Device: Vive OG
OS: Windows 10, PC

Test project (source) and build here: https://github.com/dumbgamedev/ExampleProject

I also have an open issue here about a black screen when starting a build (with steamVR open and VR device plugged in). Same build. https://github.com/ValveSoftware/steamvr_unity_plugin/issues/742

**Comment by alloystorm** [comment]
I'm also having this issue on both 2019.3.15 and 2020.1.0b11, every time when it attempts to initialize the loader. 

It appear to have something to do with "Mirror View Mode", when I set it to "None" it's not happening any more.

**Comment by alloystorm** [comment]
However, it works in editor but not in standalone player. 

It seems certain things are not supported in IL2CPP:

[Subsystems] Loading plugin XRSDKOpenVR for subsystem OpenVR Display...
[Subsystems] Failed to initialize subsystem OpenVR Display [error: 1]
[Subsystems] Loading plugin XRSDKOpenVR for subsystem OpenVR Input...
[Subsystems] Failed to initialize subsystem OpenVR Input [error: 1]
Uploading Crash Report
NotSupportedException: IL2CPP does not support marshaling delegates that point to instance methods to native code. The method we're attempting to marshal is: Unity.XR.OpenVR.OpenVRLoader::TickCallback
  at Unity.XR.OpenVR.OpenVRLoader.Initialize () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.XR.Management.XRManagerSettings.InitializeLoaderSync () [0x00000] in <00000000000000000000000000000000>:0 
  at PMXL.SceneController.OnRuntimeMethodLoad () [0x00000] in <00000000000000000000000000000000>:0

**Comment by gkapellmann** [comment]
I am getting a constant crashing of Unity with the latest release of SteamVR when trying to play in Editor. 

I am using the URP and Unity 2020.2, and it crashes 4 or 5 times before running once. I have not be able to detect a constant.
