### ISSUE TITLE
Unity XR plugin: Unable to detect any buttons

### ISSUE THREAD

**Issue by shapesim** [ValveSoftware/steamvr_unity_plugin#727]
No button works for me

List<InputFeatureUsage> usages = new List<InputFeatureUsage>();
device.TryGetFeatureUsages(usages);

Debug.Log( "" + usages.Count ); // this is always 0. It should be non-zero

This is on a Vive Cosmos. Thanks

**Comment by shapesim** [comment]
Any thought on this or are we doing anything wrong? 

head + hand tracking otherwise do work

**Comment by Vertimyst** [comment]
Having the same issue with the latest version.

**Comment by zite** [comment]
The SteamVR Unity Plugin is not compatible with Unity XR Input. Please see this thread for more info: https://github.com/ValveSoftware/unity-xr-plugin/issues/16
