### ISSUE TITLE
Controllers (bindings) not showing when launched from steam (published app)

### ISSUE THREAD

**Issue by flightCrazed** [ValveSoftware/steamvr_unity_plugin#733]
Hi,

All controllers show up in the editor and and in the build. However as soon as I publish to steam (steamworks) and update the game and launch it, controllers do not show up, because the bindings are not there.

What am I missing here? Is there anything especial I need to do during build or publish?

Thanks!
![nobindings](https://user-images.githubusercontent.com/48101354/82683214-7c283200-9c05-11ea-95ec-687313a5e2db.PNG)

**Comment by flightCrazed** [comment]
I have narrowed this down, it is not that controllers do not show up (if I create a new binding it works) but the "developer bindings" does not seem to activate.

**Comment by itzikpel** [comment]
Hi, did you manage to solve this?

**Comment by bmbmjmdm** [comment]
+1 also having this problem

**Comment by zite** [comment]
For developers having similar symptoms I would recommend going into your actions.json and binding files and deleting the line that specifies an app key. That may resolve your issue. If not please open a new ticket as this one is not related.
