### ISSUE TITLE
Unity.XR.OpenVR no "knuckles" "grip" values

### ISSUE THREAD

**Issue by AVOlight** [ValveSoftware/steamvr_unity_plugin#739]
same code working with Vive and Oculus controllers
not working with "OpenVR Controller(Knuckles Left/Right)"
all default custom legacy bindings

```

device.TryGetFeatureValue(CommonUsages.grip, out float pull)
device.TryGetFeatureValue(CommonUsages.gripButton, out bool pressed)

```

**Comment by AVOlight** [comment]
i'd really appreciate a workaround 

does anyone know what raw axis value we can get?
unfortunately i don't have index controllers

tried rAxis3.x
of VRControllerState_t 
feedback is that it's still not working

**Comment by frederickjjoubert** [comment]
I checked some discord forums and confirmed myself that this just isn't working with knuckles grip at the moment. 

Per this unity forum `https://forum.unity.com/threads/any-example-of-the-new-2019-1-xr-input-system.629824/` post it looks like unity has it set up on their side but steam vr still needs to report the correct values to unity xr toolkit.

**Comment by josiahpadula** [comment]
Has there been any updates or workarounds found for this yet?

**Comment by zite** [comment]
The OpenVR Unity Plugin no longer supports input via our legacy pipeline. To get input now you'll need to use the SteamVR Unity Plugin https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.6.0b3 . If you're upgrading you'll want to delete the steamvr folder and remove the OpenVR XR Plugin package first, then install from the link above. We're focusing our efforts on OpenXR, you can read more here: https://steamcommunity.com/games/250820/announcements/detail/2522527900755718764

**Comment by AVOlight** [comment]
hi, sorry if this is a silly question, but can you please clarify if that means Valve isn't supporting a package compatible with the Unity XR Plug-in Management package?

really hoping the Version 1.0.0-preview.2 is getting an update that fixes this issue

**Comment by AVOlight** [comment]
is there no longer support for the super easy cross platform Unity API method TryGetFeatureValue(CommonUsages.grip, out float pull) with the "com.valvesoftware.unity.openvr" package?

**Comment by zite** [comment]
There is no longer support for that API. We're focusing our efforts on OpenXR.

**Comment by AVOlight** [comment]
Thank you for the info @keithbradner
