### ISSUE TITLE
Control mappings are a total black box

### ISSUE THREAD

**Issue by AdamFrisby** [ValveSoftware/steamvr_unity_plugin#74]
Hi there, 

There's no controller mappings listed anywhere for this - knowing what each EVRButtonId actually maps to (including the Axis ones!) on various controllers would be extremely useful.

Also there is no way besides checking manufacturer device strings to determine which controllers are in use - this is making life needlessly "fun".

**Comment by AdamFrisby** [comment]
I started filling in some of the ones I know (and are using) here, but there are a large number of ???s: https://github.com/ValveSoftware/steamvr_unity_plugin/wiki/Control-Mappings

**Comment by zite** [comment]
Thanks for the report, we also felt this was an issue but came up with a different way to fix it. The new input system and rebindings! I'm going to close this as obsolete with the new input system when I merge beta to main.

**Comment by AdamFrisby** [comment]
If I can make a counterargument - the defaults still in an application do still matter. A little documentation wouldn't hurt. ;)

**Comment by zite** [comment]
With the new version of the plugin released today there should be no Valve created defaults anymore. Developers create actions and assign buttons to those actions. This enum still exists but is deprecated. See this post for more info: https://steamcommunity.com/games/250820/announcements/detail/1696059027982397407
