### ISSUE TITLE
Unity Editor crashes on play with OpenVR plugin

### ISSUE THREAD

**Issue by bigfluffycookie** [ValveSoftware/steamvr_unity_plugin#762]
Hello! I am working with the new XR Plugin system in Unity. Now I am currently mainly using the Mock HMD loader plugin and the OpenVR loader (https://github.com/ValveSoftware/steamvr_unity_plugin/tree/UnityXRPlugin). 

Working on Windows 10 with Unity version 2019.3.10f1 and the newest OpenVR version.

Now the issue is as stated in the title it constantly crashes. I don't even get a crash report. It just closes the editor and from the looks of the editor.log it seems like its always around the time when its going through the OpenVR settings.  I have no idea why it crashes sometimes and sometimes it doesn't but generally it crashes more often than not. 

The only thing I have noticed it that it always crashes when the vive cosmos headset is standing by. The thing is assuring that its not standing by still can lead to a crash sometimes. 
 
If any more information is needed I'll be happy to provide.

**Comment by halfpasttense** [comment]
I'm experiencing the exact same thing with Unity version 2019.4.0f1. I'm testing on a Valve Index.
It started when I updated the plugin from preview2 to preview4. Had to go back to preview2.

**Comment by bigfluffycookie** [comment]
I have a small update, so maybe it will help someone, I have now updated my projected to 2019.4.0f1 and I have found out that if you uncheck "initialize on start" in the XR Plugin manager settings and then initialize the loader yourself by script it barely ever crashes. Also you need to make sure that the headset is active at the time of pressing play. It seems the plugin just initializes it too early and thats why it crashes.

**Comment by zite** [comment]
This should be fixed now in the latest previews. https://steamcommunity.com/app/250820/discussions/7/2790493983190548289/

If it isn't please create an issue here: https://github.com/ValveSoftware/unity-xr-plugin/issues/
