### ISSUE TITLE
XR Plugin, HDRP +2019.4 - Screen position out of view frustum 

### ISSUE THREAD

**Issue by flightCrazed** [ValveSoftware/steamvr_unity_plugin#765]
I keep getting this message with the XR plugin. 

This happens in editor and build. 

Screen position out of view frustum (screen pos 840.000000, 0.000000, 1000.000000) (Camera rect 0 0 840 560)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by hookmanuk** [comment]
I get this error too, though it doesn't stop anything working. I'm not sure why, as it happens regardless of where my headset is within the virtual room space.

**Comment by zite** [comment]
Thanks for the report. Closing as we're tracking this issue here: https://github.com/ValveSoftware/unity-xr-plugin/issues/6
