### ISSUE TITLE
No input on build

### ISSUE THREAD

**Issue by flipwon** [ValveSoftware/steamvr_unity_plugin#768]
Just running a simple build and input is not recognized. Works fine in editor

My input here:

![image](https://user-images.githubusercontent.com/46760654/85598566-b4160100-b619-11ea-831a-6a1d6c3bbcc7.png)

None of these, nor Unity's XR Interaction managers default grab input are working. Ideas?

**Comment by flipwon** [comment]
Tried with a fresh project with just an XR grab interactable and same deal, unity's built in XR grab inputs aren't working in builds.

**Comment by zite** [comment]
We're in the process of moving towards OpenXR and are no longer supporting legacy input modes (Unity XR Input) in new plugins. For now we recommend using the SteamVR Unity Plugin for input. For more information check out these posts: https://steamcommunity.com/app/250820/discussions/7/2574319296475936754/
https://steamcommunity.com/games/250820/announcements/detail/2522527900755718764

**Comment by flipwon** [comment]
This includes unity's new input system? I was unaware that was considered legacy.

**Comment by flipwon** [comment]
Also may want to change the readme, as it says otherwise.

**Comment by hookmanuk** [comment]
I had this issue with 2.6.0b1 of this plugin, where using OpenXR Grab worked fine in the editor, but not when built.

I've now upgraded to 2.6.0b2 and now no inputs work either in the editor or when built.

I'm unsure what input you're recommending we use? If I want to use Unity 2019 with OpenXR and my Index controllers (without finger tracking) then which versions of which plugins should I be using?

**Comment by hookmanuk** [comment]
So I went back to 2.6.0b1 and had another go at working out why the inputs worked in my editor, but not at runtime.

The issue was the bindings used by Steam VR. They were entirely different in the editor compared to at runtime.

I took screenshots (attached below) of the default bindings that worked in the editor. When I set them up like this at runtime too everything works! 
Note that I had to enable several of the bindings under the custom actions tab by show actions. for them to be visible to bind.

I seem to have another issue running 2.6.0b2 now, that doesn't render anything anywhere. Not too sure why... but I'm happy enough I can at least publish a build now.

![LegacyDefaults+0](https://user-images.githubusercontent.com/18605432/85952578-3ed06600-b962-11ea-9b1c-ce068ff19314.JPG)
![LegacyDefaults+1](https://user-images.githubusercontent.com/18605432/85952580-4132c000-b962-11ea-8f4e-c5720fab09ba.JPG)

**Comment by zite** [comment]
> This includes unity's new input system? I was unaware that was considered legacy.

The way we implemented Unity XR Input was through the SteamVR legacy input pipeline, as it agrees the most with unity's new input system. However, there were significant incompatibilities and we're now looking to devote our efforts towards OpenXR as it should provide more future facing compatibility.

**Comment by hookmanuk** [comment]
Just tried upgrading to 2.6.0b3, but I have the same problem as 2.6.0b2. No inputs on my Index controllers work, no matter what custom bindings or inputs in the unity input manager are set up.

It just seems entirely broken. The only version I can working is 2.6.0b1 using the custom controller config as above.

Is this going to be fixed before a full release? Are there any instructions working with the latest version on how to actually bind controllers through steam to OpenXR inputs?

**Comment by zite** [comment]
The OpenVR XR Plugin currently does not provide input. We recommend using SteamVR Input via the SteamVR Unity Plugin. We hope this will eventually get consolidated with OpenXR.

**Comment by hookmanuk** [comment]
The input compatibility is really confusing at the moment.
10 days ago you said Unity XR Input is through the SteamVR legacy input pipeline (which I agree with, that mostly works fine in 2.6.0b1 for me).
However now you're saying OpenVR XR Plugin doesn't provide input.

When writing a potentially cross platform game, it would be much easier if we could just use the previously described and working XR input. Has this legacy code been removed from recent versions, or I am just missing some settings for why it works in b1 but not in b2 or b3 for me?

**Comment by hookmanuk** [comment]
Looking further into this, I see the release notes on Steam for 2.6.0b2 actually mentioned switching from legacy support to steamvr.

Someone asked the question whether this meant legacy support is now removed and if that was a permanent change, no-one replied though.

https://steamcommunity.com/app/250820/discussions/7/2574319296475936754/

**Comment by flipwon** [comment]
Yeah, I just gave up on it. I don't care to have 5 different plugins to get one thing to work as intended. It's way too much work for simple input.

I'll come back to it when it's complete.

**Comment by zite** [comment]
Legacy support being removed is a permanent change for the OpenVR plugin. We're now focusing efforts on OpenXR.
