### ISSUE TITLE
Interactable Button Event trigger ALL scripts in scene.

### ISSUE THREAD

**Issue by eobet** [ValveSoftware/steamvr_unity_plugin#77]
See this linked example project:

https://www.dropbox.com/s/v9p6spa74jn7qv1/InteractionTest.zip?dl=0

https://imgur.com/WZDUqCy

**Comment by eobet** [comment]
Not the fault of SteamVR, but rather the nature of Unity's Animation Controller.

**Comment by eobet** [comment]
Nope, sorry. Still blaming Interactable Button Event for this after all.

**Comment by zite** [comment]
Thanks for the report eobet. I believe this issue should be fixed in the most recent version of the plugin released today. Let me know if it's still an issue and I'll reopen.
