### ISSUE TITLE
Cannot Enable VR With VirtualRealitySupported Check Box

### ISSUE THREAD

**Issue by huntyboy102** [ValveSoftware/steamvr_unity_plugin#771]
I am unable to enable VR in my Unity project because 'PlayerSettings.virtualRealitySupported' is obsolete and requires XR Management package to handle VR instead.

**Comment by TrickyHandz** [comment]
@huntyboy102 what version of Unity are you using. This behavior is expected in 2018.4 and later.  You'll need to follow the [Quick Start [section](https://github.com/ValveSoftware/steamvr_unity_plugin)] to enable OpenVR through the XR Management System for 2018.4 and later by loading the plugin via the Unity Package Manager.

**Comment by huntyboy102** [comment]
@TrickyHandz current unity version is 2020.2.0a15, I have tried loading it through package manager and the error I get is 
> [SteamVR] Initialization failed. VR may be disabled in player settings. Go to player settings in the editor and check the 'Virtual Reality Supported' checkbox'. OpenVR is not in your list of supported virtual reality SDKs. Add it to the list in player settings. To force OpenVR initialization call SteamVR.Initialize(true).
and
> [SteamVR] Not Initialized (109)

**Comment by chengnay** [comment]
@huntyboy102 Which version of SteamVR Unity Package you are using?
And, could you try switching your SteamVR to beta version and try again?
![image](https://user-images.githubusercontent.com/33050705/86756172-c6aa2480-c074-11ea-9e18-c8b33cb608b2.png)

**Comment by huntyboy102** [comment]
@chengnay already on SteamVR beta, currently using the latest beta version of the package

**Comment by carperbr** [comment]
I seem to be encountering this as well. I'm using Unity 2020.1.0b14.4034, have opted into SteamVR beta, and am attempting to use SteamVR Unity Plugin v2.6.0b2.

The exact error I get is "Initialization failed. VR may be disabled in player settings. Go to player settings in the editor and check the 'Virtual Reality Supported' checkbox'. OpenVR is not in your list of supported virtual reality SDKs. Add it to the list in player settings. To force OpenVR initialization call SteamVR.Initialize(true)", though forcing it to initialize does nothing as well.

**Comment by zite** [comment]
@huntyboy102 you'll need to enable the OpenVR Loader in the XR Management section of Project Settings. Let me know if this doesn't fix your issue.
