### ISSUE TITLE
[Question] Is there an ability to gesture with fingerCurls[] ?

### ISSUE THREAD

**Issue by Oyshoboy** [ValveSoftware/steamvr_unity_plugin#778]
Hi, I found a very usefull variable array, where sotred all finger curles, called **fingerCurls[]**. I want to know, is there any ability to gesture using it? I found some usage of it in **UpdateAdditiveAnimation** ( SteamVR_Skeleton_Poser.cs ), but haven't found any direct usage of it.

**Comment by zite** [comment]
Sorry, this forum is for bugs, you're welcome to post your question on the steamvr developer forums here: https://steamcommunity.com/app/250820/discussions/7/
