### ISSUE TITLE
Textures of RenderModels are black when using .NET 4.6 scripting runtime version

### ISSUE THREAD

**Issue by JashanChittesh** [ValveSoftware/steamvr_unity_plugin#78]
Since Unity 2017.1, there is an option in the Player Settings under "Other Settings" to switch from "Stable (.NET 3.5 Equivalent)" to "Experimental (.NET 4.6 Equivalent)". This mostly works really well - but apparently there is a change that causes the textures to load all black. It's very easy to reproduce when using one of the custom models with colorful textures (like the half-life one ;-) ). With 3.5 active, it works flawlessly. With 4.6, the controllers are all black. At first, I thought loading the custom models was the problem - but reviewing the loaded texture in Unity reveals that it's all black.

This could also be a bug in Unity's 4.6 implementation - I'll file a report with them, too.

**Comment by bddckr** [comment]
For more info see
https://github.com/ValveSoftware/openvr/issues/638

(There's multiple others on the OpenVR repo, too.)

**Comment by zite** [comment]
Thanks for the report and fix guys. I've fixed this in the beta and will close when I merge beta to main. You can check it out on the releases page.
