### ISSUE TITLE
OpenVR Unity XR plugin link is dead

### ISSUE THREAD

**Issue by EEviston** [ValveSoftware/steamvr_unity_plugin#783]
https://github.com/ValveSoftware/steamvr_unity_plugin/tree/UnityXRPlugin

Cannot find download for plugin that allows OpenVR to work with Unity XR

**Comment by kisak-valve** [comment]
Hello @EEviston, the XR plugin has moved to its own repo: https://github.com/ValveSoftware/unity-xr-plugin
