### ISSUE TITLE
Errors when importing SteamVR

### ISSUE THREAD

**Issue by gkapellmann** [ValveSoftware/steamvr_unity_plugin#784]
I have just imported SteamVR and I am trying to use it with the OpenVR XR plugin.

As soon as the package is imported, I got these 2 errors:

1) Asset Packages/com.valvesoftware.unity.openvr/Runtime/x64/XRSDKOpenVR.ilk has no meta file, but it's in an immutable folder. The asset will be ignored

2) Assets\SteamVR\Scripts\SteamVR_Menu.cs(175,36): error CS1061: 'CVRSystem' does not contain a definition for 'ResetSeatedZeroPose' and no accessible extension method 'ResetSeatedZeroPose' accepting a first argument of type 'CVRSystem' could be found (are you missing a using directive or an assembly reference?)

I cant find a solution to this, any ideas?

Thanks!

**Comment by zite** [comment]
Hi! Did you download beta 3 from the releases page? Or what version did you import?

**Comment by gkapellmann** [comment]
Ok, what I installed was: SteamVR Unity Plugin v2.6.0b2 (sdk 1.12.5)

I just saw the release of SteamVR Unity Plugin v2.6.0b3 (sdk 1.13.10), probably that's it, but I will test as soon as I'm back and let you know.

Thank you!

**Comment by gkapellmann** [comment]
Ok, I have now installed this version: 
SteamVR Unity Plugin v2.6.0b3 (sdk 1.13.10)

And I am getting multiple messages of:
Asset Packages/com.valvesoftware.unity.openvr/Runtime/x86/XRSDKOpenVR.ilk has no meta file, but it's in an immutable folder. The asset will be ignored.

And at the very end this one:
Assets\SteamVR\Editor\SteamVR_AutoEnableVR.cs(78,68): error CS0117: 'VREditor' does not contain a definition for 'GetVREnabledDevicesOnTargetGroup'

**Comment by zite** [comment]
You can fix the .ilk errors by updating the OpenVR XR Plugin in the Package Manager window. Latest should be preview-9.

That editor error is strange, if it doesn't go away when you update can you tell me what version of Unity are you running?

**Comment by gkapellmann** [comment]
Ok, so I did the update.

No I got 9 errors! Got multiplied :)

Still these, with x86 and x64 errors:

1) Asset Packages/com.valvesoftware.unity.openvr/Runtime/x64/openvr_api.pdb has no meta file, but it's in an immutable folder. The asset will be ignored.
2) Asset Packages/com.valvesoftware.unity.openvr/Runtime/x64/XRSDKOpenVR.pdb has no meta file, but it's in an immutable folder. The asset will be ignored.

When I click "Clear" all the errors leave, except for this one again:
9) Assets\SteamVR\Editor\SteamVR_AutoEnableVR.cs(78,68): error CS0117: 'VREditor' does not contain a definition for 'GetVREnabledDevicesOnTargetGroup'

I have restarted unity after upgrading the package, and still the same.

The Unity version I am trying to use is 2020.2.0a18 (I need to use the Articulated Bodies).

![UnityErrors](https://user-images.githubusercontent.com/7535220/88242831-bdcd6b80-cc8e-11ea-9c2b-4cebeae6ab75.png)

**Comment by zite** [comment]
Okay, looks like two issues. Try upgrading to preview.10 of the OpenVR XR Plugin, and download this preview of beta4: https://drive.google.com/file/d/1G9OV-_sQ0D2qjlEoE7tiiNI18WTsd4Di/view?usp=sharing

**Comment by gkapellmann** [comment]
Ok, interesting, the update of SteamVR beta 4 detected that the old package of "SteamVR Desktop" was installed. Which I never installed manually, so it must have been downloaded with an update or somewhere in the process.

Now I got also the XR plugin preview 10. 

It seems that thee changes did the trick, not even a single warning!

Thank you for the help :)

**Comment by zite** [comment]
Great to hear!
