### ISSUE TITLE
Are there any plans to support the Unity XR Interaction Toolkit?

### ISSUE THREAD

**Issue by kendrome** [ValveSoftware/steamvr_unity_plugin#785]
It seems overly complicated to have to implement separate input system for SteamVR vs all other VR systems. The OpenXR Plugin works great for headset and controller locations, but it would be nice to also support the Unity Input system. Especially with VRTK 3 being so outdated and VRTK 4 just downright broken, there is no good cross platform support outside of Unity's XR Interaction Toolkit. Any responses would be great, even it's just stating there are no current plans.

**Comment by kisak-valve** [comment]
Hello @kendrome, the developer response at https://github.com/ValveSoftware/unity-xr-plugin/issues/16#issuecomment-662708512 applies to this question.

**Comment by dariol** [comment]
> It seems overly complicated to have to implement separate input system for SteamVR vs all other VR systems. The OpenXR Plugin works great for headset and controller locations, but it would be nice to also support the Unity Input system. Especially with VRTK 3 being so outdated and VRTK 4 just downright broken, there is no good cross platform support outside of Unity's XR Interaction Toolkit. Any responses would be great, even it's just stating there are no current plans.
There's also VIU.
