### ISSUE TITLE
Assets\SteamVR_Input\ActionSetClasses\SteamVR_Input_ActionSet_mixedreality.cs(24,40): error CS0117: 'SteamVR_Actions' does not contain a definition for 'mixedreality_ExternalCamera'

### ISSUE THREAD

**Issue by hanbin07** [ValveSoftware/steamvr_unity_plugin#786]
![problem](https://user-images.githubusercontent.com/31065548/88284128-d5a4fe00-cd27-11ea-8d44-2c9c06f4e1c6.JPG)

I want to run SRWorks demo.

What is the cause of the error?

I use Unity 2019.4.0f

**Comment by zite** [comment]
I'm not sure what would cause that error. Possibly that you haven't generated actions (Window -> SteamVR Input -> Generate & Save). But you should probably look to get support from HTC's SRWorks or VIU team. They would better know what's going on here.
