### ISSUE TITLE
Vive Tracker (1.0) not working with OpenVr XR Plugin (editor or build modes affected)

### ISSUE THREAD

**Issue by charlicopter** [ValveSoftware/steamvr_unity_plugin#789]
Turning a Vive tracker (1.0) on or off during runtime (editor or build) throws the exception: 
[XRInputSubsystem] A device disconnection with the id 3 has been reported but no device with that id was connected.
If the tracker is powered on and detected by SteamVR during launch of the application (editor or build), there is no error, but the tracker is not registered by Unity, and stopping the application throws the same error.

**Comment by kisak-valve** [comment]
Closing in favor of https://github.com/ValveSoftware/unity-xr-plugin/issues/20.
