### ISSUE TITLE
SteamVR tries to enable OpenVR support and Unity 2020 continuously disables it

### ISSUE THREAD

**Issue by alexeystrakh** [ValveSoftware/steamvr_unity_plugin#790]
I'm unable to open my Unity VR project after Unity 2020.1 upgrade. This update disables old XR settings in project settings and requires to use new XR Plug-in Management:

![image](https://user-images.githubusercontent.com/3697084/88885710-dd641700-d1ed-11ea-8415-98e5d5f8915a.png)

```
<b>[SteamVR Setup]</b> Enabled virtual reality support in Player Settings. (you can disable this by unchecking Assets/SteamVR/SteamVR_Settings.autoEnableVR)
UnityEngine.Debug:Log(Object)
Valve.VR.SteamVR_AutoEnableVR:Update() (at Assets/SteamVR/Editor/SteamVR_AutoEnableVR.cs:56)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

<b>[SteamVR Setup]</b> Added OpenVR to supported VR SDKs list.
UnityEngine.Debug:Log(Object)
Valve.VR.SteamVR_AutoEnableVR:Update() (at Assets/SteamVR/Editor/SteamVR_AutoEnableVR.cs:91)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

XR SDK Provider detected in project. Disabling VR Device settings for Standalone
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
```

I'm unable to open the settings file to disable the auto import settings so I went to `SteamVR_AutoEnableVR` and commented the whole `Update` method. After this I'm able to run my project but it crashes on start with missing `openvr` dll error

Can I use `steamvr` unity plugin with the new XR Plug-ing Management unity system?

**Comment by zite** [comment]
Unfortunately the XR Management system is now required because unity depreciated the VR system we used previously. Good news is we're closing in on a final release for our xr management plugin. If you update your OpenVR XR Plugin to preview-12 and/or download the latest SteamVR Unity Plugin Beta (b4 / RC1) this should be fixed. https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.6.0b4

**Comment by kisak-valve** [comment]
Closing pending feedback.
