### ISSUE TITLE
Assets\_VRHands\Scripts\HandAnimator.cs(8,12): error CS0246: The type or namespace name 'steamVR_Action_single' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by fy415** [ValveSoftware/steamvr_unity_plugin#792]
Hello. I am a korean student studying unity.
An error message occurred while creating the handanimator.cs script to implement hand animation in the VR environment. 

**Assets\_VRHands\Scripts\HandAnimator.cs(8,12): error CS0246: The type or namespace name 'steamVR_Action_single' could not be found (are you missing a using directive or an assembly reference?)**

I think the valve.vr namespace is not working....... What should I do?

*unity version: 2019.4.4f1
*steam VR version: 2.5.0 (sdk 1.8.19)
*samsung odyssey HMD 

[
![11111111](https://user-images.githubusercontent.com/12667404/89033585-0dd4be00-d372-11ea-88fa-e3764a19e485.PNG)
](url)

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Valve.VR;

public class HandAnimator : MonoBehaviour
{
    public steamVR_Action_single m_GrabAction = null;

    private Animator m_Animator = null;
    private SteamVR_Behaviour_Pose m_Pose = null;


    private void Awake()
    {
        m_Animator = GetComponent<Animator>();
        m_Pose = GetComponentInparent<SteamVR_Behaviour_Pose>();

        m_GrabAction[m_Pose.inputSource].onChange += Grab;

    }

    private void OnDestroy()
    {
        m_GrabAction[m_Pose.inputsource].onChange += Grab;
    }

    private void OnTriggerEnter(Collider other)
    {
        m_Animator.SetBool("point", true);
    }

    private void OnTriggerExit(Collider other)
    {
        m_Animator.SetBool("point",false);
    }

    private void Grab (SteamVR_Action_Single action, SteamVR_Input_Sources source, float axis, float delta)
    {
        m_Animator.SetFloat("GrabBlend", axis);
    }
}
```

**Comment by zite** [comment]
Looks like you just have a typo on line 8. It should be `SteamVR_Action_Single`, not `steamVR_Action_Single`. Note the capital S. :)

**Comment by fy415** [comment]
> Looks like you just have a typo on line 8. It should be SteamVR_Action_Single, not steamVR_Action_single. Note the two capital S. :)

Oh, I was a fool! It works well. Thank you so much for your reply!!!

**Comment by kisak-valve** [comment]
Closing per the last comment.
