### ISSUE TITLE
Importing loop with unity 2020.1 ad 2019.4

### ISSUE THREAD

**Issue by josh-65** [ValveSoftware/steamvr_unity_plugin#795]
It will show me the import all option and then the recommend settings to change. After that it will show "importing xr.openvr.standalone" and just stay on that until I force quit.

![SharedScreenshot](https://user-images.githubusercontent.com/26977075/89218323-c2b2e900-d5c5-11ea-8b66-8c2b17994f80.jpg)

**Comment by zite** [comment]
Is this with SteamVR Unity Plugin beta 4? Are there any errors that show up?

**Comment by josh-65** [comment]
Don't think so I Downloaded it from the asset store how would i get the beta and no errors other that what's in the image i have let it run for about 30 min.

**Comment by zite** [comment]
Ah, the version in the asset store is not currently compatible with Unity 2020.1 or XR Management. You'll need to downlaod the beta for that: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.6.0b4

**Comment by josh-65** [comment]
Ok i will give that ago thanks.
