### ISSUE TITLE
Some items appear in left eye, but not in right eye -- valve index

### ISSUE THREAD

**Issue by stonebits** [ValveSoftware/steamvr_unity_plugin#809]
Took me a bit to figure out what was going on here,  but for some reason items render in the left stereo eye, but not in the right one

The screenshots are below, so I assume it's not a hardware problem. There's a number of objects in the scene like this they're all cloth. They work fine in Unity 2018, but some bugs in the handling of cloth constraints in Unity 2019 made the dynamics unworkable.
![Screenshot_Thu_Aug_13_16-15-54_2020_VR](https://user-images.githubusercontent.com/10538557/90198245-1a5c0c00-dd9f-11ea-9373-1e35d122fc7f.png)
![Screenshot_Thu_Aug_13_16-15-54_2020](https://user-images.githubusercontent.com/10538557/90198249-2051ed00-dd9f-11ea-9f7d-89dceecea756.png)
Here's the inspector for that object
<img width="676" alt="Screen Shot 2020-08-13 at 7 50 31 PM" src="https://user-images.githubusercontent.com/10538557/90198333-6313c500-dd9f-11ea-968f-ce81d5ccb318.png">

Unity 2020.1.2f1, Steam VR 2.6.1

The console shows no errors

Any ideas?

**Comment by nhf75** [comment]
Try to set OpenVr Stereo Rendering Mode to Multi Pass and Mirror View Mode to None.

**Comment by stonebits** [comment]
> 
> 
> Try to set OpenVr Stereo Rendering Mode to Multi Pass and Mirror View Mode to None.

That solved it, Thanks!
