### ISSUE TITLE
SteamVR_Overlay displaying objects around it

### ISSUE THREAD

**Issue by Gotcab** [ValveSoftware/steamvr_unity_plugin#81]
There is a problem with SteamVR_Overlay on the Player prefab. It displays some object that are close to it. They appear as if on a 2d screen. For example, I have a throwable cube in my scene and I see it in 2d on the overlay. Unchecking AA and High Quality resolve this but I took me a while to find the problem. Am I alone with this problem?

**Comment by zite** [comment]
Thanks for the report. I believe this issue has been fixed in the most recent version of the plugin released today. Let me know if this is still an issue and I'll reopen.
