### ISSUE TITLE
Project Settings for OpenVR Plugin revert after one test

### ISSUE THREAD

**Issue by milovincent** [ValveSoftware/steamvr_unity_plugin#814]
I need to use Multi-Pass stereo rendering to see one of my shaders in both eyes, but when i set the plugin to use it, I can only test my app once, after which the settings revert. 
[Here](https://twitter.com/DocNum4/status/1295215801931370501?s=20) is a video of the issue occurring, and my reaction to it after over an hour of trying to fix it.

**Comment by zite** [comment]
This is indeed a strange issue. It seems to only reproduce while the settings window is open! This leads us to think this is an odd Unity bug. We're tracking it here: https://github.com/ValveSoftware/unity-xr-plugin/issues/31

**Comment by milovincent** [comment]
wow, that's pretty dumb, glad you could reproduce it and I wasn't just going insane though! good to know there's a solution as well.
