### ISSUE TITLE
UI displayed only in the left eye. XR + Unity 2020 + HDRP

### ISSUE THREAD

**Issue by AnriEU** [ValveSoftware/steamvr_unity_plugin#816]
Hi!
XR plugin + Unity 2020.1.1f1 + HDRP
UI displayed only in the left eye
Tested in Vive Cosmos and Oculus
What could be the problem?

**Comment by zite** [comment]
What sort of UI? Could it be the shader you're using? Do you have a simple example project we could test?

**Comment by AnriEU** [comment]
Standard UI from SteamVR demo scene
![Untitled-3](https://user-images.githubusercontent.com/37102945/90424171-f7429c80-e0bd-11ea-9eeb-996a074cf549.jpg)

**Comment by AnriEU** [comment]
1. Start zero HDRP project 2020.1.1f1
2. Install steamvr_2_6_1.unitypackage
3. Save and Generate StaeamVR input
4. Open Interactions_Example scene
5. Upgrade project materials to HDRP materials
6. Press Play and close left eye

simple example project:
https://drive.google.com/file/d/1WaOOVfsoaHkAenPJAifyW_ifH5mS6efn/view?usp=sharing

**Comment by AnriEU** [comment]
P.S. In the URP problem does not exist

**Comment by AnriEU** [comment]
Will be great if you create HDRP shaders the same way as you created URP.
Some of the developers say - "HDRP not good for VR".
It is not true. 
Quality is great and no problems with FPS, if you know how to optimize project...

**Comment by kinacho2** [comment]
That is because you need a custom material for UI on HDRP. This works for me. Add the material to all UI components with Image.
![image](https://user-images.githubusercontent.com/12003830/91084214-01b2e800-e622-11ea-8f67-486b540a6748.png)

**Comment by kinacho2** [comment]
I forgot the Input, sorry, Use the same reference names.
![image](https://user-images.githubusercontent.com/12003830/91084312-2c9d3c00-e622-11ea-9a97-71328ceca0fe.png)

**Comment by AnriEU** [comment]
Can you please share your UIHDRP shader?

**Comment by kinacho2** [comment]
Yes I can. Yesterday I founded an issue, this shader doesn't work with Text, I did other shader for it.

https://drive.google.com/drive/folders/1M3qkrKR9nKLebf2VJ2EvWuSZ1iyhLcxl?usp=sharing

**Comment by AnriEU** [comment]
Great! Many thanks! Both is works perfect!

Script to change:

```
public Shader hdrpShader;
Canvas.GetDefaultCanvasMaterial().shader = hdrpShader;
```

**Comment by Jiangyuguo99999** [comment]
hi, I also encountered this problem in 2022.3.0. I used your method, but the ui picture background could not be displayed normally. Is there something wrong with my method?
![image](https://github.com/ValveSoftware/steamvr_unity_plugin/assets/126705509/07cdeb85-3251-4a85-b641-6d6830b29ba7)
