### ISSUE TITLE
Unity 2020 + SteamVR Unity Plugin v2.6.0b4 + OpenGL = Blank Game Window + Mountains in headset

### ISSUE THREAD

**Issue by mnbvcxzlkjhgfds** [ValveSoftware/steamvr_unity_plugin#817]
Unity is nagging me to switch to VR Plugins as the old system is deprecated, so trying to updating my which is reliant on OpenGL (uses VTK in external rendering to show medical data) Importing SteamVR Unity Plugin v2.6.0b4 into an otherwise empty project works with DirectX, but not OpenGL rendering. I may have overlooked something obvious - if so please tell me, but I've tried to systematically get it working for some time now.

Update:

* The same behaviour in Unity 2019.3.5, installing the OpenVR PLugin first and then the SteamVR plugin
* Checked colour space is linear
* Attempted to disable mirror mode - but it just kept resetting
* Attempted to use Multi-pass rendering (this is what was being successfully used before) and it just kept resetting to single pass instanced
* I'll post the logs when I get a chance to test this again

Original post:

Observed Behaviour:

* Game window is blank and headset just shows the mountains in the distance

Expected Behaviour:

* Simple Scene and Interaction Example should render in both window and headset, like OpenGL

Steps to reproduce:

* Create new project in Unity 2020 an have it empty
* Download SteamVR Unity Plugin v2.6.0b4 from https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.6.0b4
* Install Everything into open, empty Unity Project
* In Project Settings\Player\Other Settings\Graphics Settings for Windows select on DirectX11
* Open SteamVR\Simple Scene or SteamVR\Interaction System\Samples\Interactions_Example
    * Observe: Scene renders in Game window and headset as expected
* In Project Settings\Player\Other Settings\Graphics Settings for Windows select on OpenGlCore
* Open SteamVR\Simple Scene or SteamVR\Interaction System\Samples\Interactions_Example
    * Observe: Game window is blank and headset just shows the mountains in the distance
* Set Project Settings\Stereo Render Mode to Multi Pass 
    * Observe: Game window is blank and headset just shows the mountains in the distance

Notes:

* SteamVR 1.13.10
* Vive Headset
* It did seem to work briefly yesterday, so problem may be intermittent, or I have have got settings muddled
* Graphics card is nVidia 1070Ti with game drivers 445.75.
* Unity 2019 + Steam VR Unity Plugin 2.5 work fine
* I'm not sure if this is Unity or SteamVr sdk, but our OpenGl rendering pipeline still works in Unity 2020 when we're not using VR, which has led me to start here

**Comment by kinacho2** [comment]
I don't know how VTK works on unity but maybe it is an initialization problem, here: https://github.com/ValveSoftware/steamvr_unity_plugin/issues/793#issuecomment-668295263 this user fix an important bug between unity 2020 and the last version of steam VR beta

**Comment by 1runeberg** [comment]
Hi @mnbvcxzlkjhgfds - In Unity 2020 and this version of the plugin, our Unity XR Plugin would've been installed and used for rendering, where we only support DirectX and Vulkan. You should be able to verify this in the Unity Editor Log with an entry saying "[OpenVR] [Error] Unsupported graphics api! Only DirectX and Vulkan are supported at this time."

Current future efforts are focused on OpenXR however, so no OpenGL support is slated for Unity XR, here's our announcement about this:

https://steamcommunity.com/games/250820/announcements/detail/2522527900755718764

**Comment by mnbvcxzlkjhgfds** [comment]
Hi @1runeberg , apologies for my slow reply, I've been sidetracked into several other issues. However, thank you for clarify that OpenGL will not work and that the future is Vulkan. It will save me banging my head against a brick wall trying to get OpenGL to work. So we will stick to old Unity + OpenGL, keep a weather eye on VTK developments, while we decide what best to do.
