### ISSUE TITLE
OpenVR MRTK demo, Can't see controllers

### ISSUE THREAD

**Issue by cysneros** [ValveSoftware/steamvr_unity_plugin#821]
I'm trying to run the MRTK v2 demo with the new XR Plug-in Manager in Unity.  It did not work because I needed to download the OpenVR-XR-Plugin and SteamVR 2.6.0b4 plugin to get OpenVR support working. 

I downloaded them both and followed the setup instructions.  The steam interaction demo is working but not the MRTK demo.  The controllers are never visible but everything else seems to be working ok.   Does this mean that the MRTK is not supported with the current OpenVR-XR-Plugin and I need to stick to the Legacy XR  method if I want to use MRTK?  

Thank you for the clarification.

Unity 2019.4.0f1
SteamVR 1.13.10
Steam VR Unity Plugin v2.6.0b4

**Comment by kisak-valve** [comment]
Hello @cysneros, that is correct. th e Unity-XR plugin does not have support for Input via the new interface. (See https://github.com/ValveSoftware/unity-xr-plugin/issues/16)
