### ISSUE TITLE
Unity2019.4.0f1+SteamVR+HDRP 7.3.1, cant lanch with Warnings!

### ISSUE THREAD

**Issue by nongzhang** [ValveSoftware/steamvr_unity_plugin#830]
Virtual Reality SDK OpenVR failed to initialize.
[SteamVR] Initialization failed. VR may be disabled in player settings. Go to player settings in the editor and check the 'Virtual Reality Supported' checkbox'. To force OpenVR initialization call SteamVR.Initialize(true).

**Comment by Oyshoboy** [comment]
I have the same issue:
`[SteamVR] Initialization failed. VR may be disabled in player settings. Go to player settings in the editor and check the 'Virtual Reality Supported' checkbox'. To force OpenVR initialization call SteamVR.Initialize(true). `

But it's only a warning, when I'm enabling/disabling poser hand on a object, and everything is works good.

**Comment by nongzhang** [comment]
@Oyshoboy  no, i cant.

**Comment by nongzhang** [comment]
![XR](https://user-images.githubusercontent.com/24870308/93575307-0faf1b00-f9cc-11ea-89d0-8983de44c85f.png)

**Comment by nongzhang** [comment]
![XR](https://user-images.githubusercontent.com/24870308/93575405-2c4b5300-f9cc-11ea-8918-a12cf6db4fc0.png)

**Comment by nongzhang** [comment]
dont use D3D12,use D3D11. in this way, you can use most features of HDRP except Ray tracking.  hold and darg up!



![D3D11](https://user-images.githubusercontent.com/24870308/100492737-fd8aef00-3169-11eb-9a1b-0fc94a50f5ef.png)

**Comment by Oyshoboy** [comment]
Thanks @nongzhang

**Comment by Chu-XiaoYao** [comment]
现在行了吗？
