### ISSUE TITLE
Unity 2020.1 XR Input System not receiving Vive controller inputs

### ISSUE THREAD

**Issue by NilsBernatzki** [ValveSoftware/steamvr_unity_plugin#844]
Unity 2020.1.7f1
Input System 1.0.0
XR Interaction Toolkit 0.94 (preview)
XR Plugin Management 3.2.16

SteamVR 1.14.16
SteamVR Plugin 2.6.1
HTC Vive

Check 1: SteamVR environment -> Inputs work
After setting up a new Unity project and importing the mentioned plugins, I can generate the SteamVR controller actions and start the Interaction Sample scene. Tracking and inputs are doing fine.

Check 2: Unity XR Input System
Create a new empty scene and place a XRRig in the hierarchy. Create an empty GameObject and add a script with the following code:

    protected List<InputDevice> leftHandDevices = new List<InputDevice>();
    protected List<InputDevice> rightHandDevices = new List<InputDevice>();

    private void Update()
    {
        InputDevices.GetDevicesAtXRNode(XRNode.LeftHand, leftHandDevices);
        InputDevices.GetDevicesAtXRNode(XRNode.RightHand, rightHandDevices);

        bool isPressed;

        Debug.Log(leftHandDevices.Count);

        if(leftHandDevices.Count >= 1)
        {
            if(leftHandDevices[0].TryGetFeatureValue(CommonUsages.triggerButton, out isPressed))
            {
                Debug.Log("Left Trigger Pressed");
            }
        }

        if (rightHandDevices.Count >= 1)
        {
            if (rightHandDevices[0].TryGetFeatureValue(CommonUsages.triggerButton, out isPressed))
            {
                Debug.Log("Right Trigger Pressed");
            }
        }
    }

Expected:
Console writes "1" because Unity XR System detects one left controller device.
Console writes "Left/Right Trigger Pressed" once the trigger button on the correct Vive controller gets pressed completely.

Behaviour:
While the first Debug.Log writes "1" in the console as expected, the trigger input is not noticed by the new Unity input system.

What could cause this issue?

**Comment by NilsBernatzki** [comment]
I also checked the Input Debug and there is no changes of "value" once I press the trigger:

![image](https://user-images.githubusercontent.com/22767116/95499695-f8999280-09a5-11eb-9a4a-106fb8d922fb.png)

I noticed that all the controller buttons and states don't even appear in the XR interaction Debugger. Is that normal?

![image](https://user-images.githubusercontent.com/22767116/95500024-7a89bb80-09a6-11eb-8460-cc75f802f064.png)

**Comment by kisak-valve** [comment]
Hello @NilsBernatzki, please see the discussion on https://github.com/ValveSoftware/unity-xr-plugin/issues/16#issuecomment-662708512, Unity XR Input is not supported. There are some other options discussed on that issue report.
