### ISSUE TITLE
Actions not active unless application/unity editor launches SteamVR

### ISSUE THREAD

**Issue by nocanwin** [ValveSoftware/steamvr_unity_plugin#846]
Unity 2019.4, SteamVR beta 1.15.4, steamvr_unity_plugin v2.6.1, OpenVR Desktop

This issue seems to happen for the editor and builds. If I don't have SteamVR running and hit play in the editor or run a build, SteamVR launches and in the input debugger my actions are set to Active: true. If I launch SteamVR then hit play in the editor or run a build then in the input debugger the Action Set is active, but under Actions, Active: false.

**Comment by zite** [comment]
Is this causing a problem? I wonder if it's just a UI bug.

**Comment by nocanwin** [comment]
It's causing issues. I use custom action binding files to get input via pogo pins on trackers. I stopped getting input from them when SteamVR is launched manually before the application is launched. That's when I looked at the input debugger and noticed Active: false.

**Comment by zite** [comment]
Can you try these steps:
1) launch steamvr
2) turn a controller on
3) turn controller off
4) turn tracker(s) on
5) hit play in editor

**Comment by nocanwin** [comment]
Sorry, retested the issue and I no longer get it in SteamVR 1.15.8
