### ISSUE TITLE
Controllers seem to have an offset on Quest 2 Link

### ISSUE THREAD

**Issue by PixHammer** [ValveSoftware/steamvr_unity_plugin#850]
Noticed this after moving a project of mine to Unity 2020.1.9f1 and updated to SteamVR Plugin 2.6.1, figured it could be something with my set up, so tested on a new project with just the steamVR plugin installed running on the Quest 2 link:
![image](https://user-images.githubusercontent.com/14236751/96565630-ea604600-12c4-11eb-9ed4-417e8be274ff.png)
![image](https://user-images.githubusercontent.com/14236751/96565672-f8ae6200-12c4-11eb-9d1a-f6adfa8a21b3.png)

The controllers in the steamVR UI and Oculus UI are offset with those inside Unity, tried to figure out approximately how far off these vectors are but it doesn't seem consistent  and is relative to the head rotation/position, which would imply there's something funky going on, seems like everything is offset by some small vector, facing forward in my play space with my hands in front of me they seem to have an offset of about (0, -0.02, 0.05) in world space to get them to realign, but facing the other way this offset doesn't seem correct.

I tested on a Rift S also, and this issue does not occur, controllers seem aligned as they should be.

**Comment by kisak-valve** [comment]
Closing in favor of https://github.com/ValveSoftware/unity-xr-plugin/issues/63. In the future, please just ask to have an issue report moved instead of creating a duplicate.
