### ISSUE TITLE
Oculus Quest / Oculus Touch skeletal input not working - no finger bending?

### ISSUE THREAD

**Issue by guiglass** [ValveSoftware/steamvr_unity_plugin#851]
Hi, I do not own Oculus gear myself, however I have released a game and my community is reporting that noone with Oclulus Quest is able to see fingers bending. 

I have done my best to create bindings for oculus_touch and I believe the button mapping is working correctly, however I am unsure how to enable skeletal input.

Is it possible to enable skeletal input (finger bending) from a Oculus quest or Oclulus touch controllers for my Unity game?

Thank you very much!!

[edit]
I am currently using Unity 2019.4.9f1 and SteamVR plugin 2.0.

**Comment by zite** [comment]
Hi! What was your resolution?
