### ISSUE TITLE
Universal Render Pipeline 

### ISSUE THREAD

**Issue by admjackson1981** [ValveSoftware/steamvr_unity_plugin#855]
Switching materials on hover and Simple (built in) Hover highlighting not working for me. 

URP 7.3.1
SteamrVR - asset store version AND the Beta github latest version.

Replicate issue... Simply create new 2019.4 (LTS) project -> Add URP -> Add Either SteamVR Plugin -> Run Interactable Example.

Non of the Throwable Cubes have yellow highlighted shader AND swapping materials looks broken, barely make out material. Spent all morning trying to figure if it was my dodgy scripting that broke it.... but nope... usual stuff..... The most used Render Pipeline in Unity is not compatible with Steam. Not really sure the point in working with Steam if its always 12 months behind. Back to XR-Integration.

**Comment by admjackson1981** [comment]
Second to this. Just tested the controller hints using a script. Hand.showgrabhint(). Works fine in standard or scriptabel pipeline but not URP. Another pointless few mins of my life. Thank you so much.

**Comment by zite** [comment]
Unfortunately, Unity does not provide a clean way to support multiple render pipelines in one plugin. As Standard is still the default, that is the main one we support. As with most projects, you can auto-convert the materials in the project to your targeted pipeline using the helpers in the menu options.
