### ISSUE TITLE
SteamVR_2_6_0b4 not finding XRSDKOpenVR.dll

### ISSUE THREAD

**Issue by AlanNZAndersen** [ValveSoftware/steamvr_unity_plugin#856]
After installing the SteamVR_2_6_0b4 unity package, the XRSDKOpenVR.dll was not found even though, it is where it is supposed to be. I have installed and uninstalled the package multiple times with the same result. I have created a new/virgin project where I have also installed and uninstalled the package multiple times and there the package has always worked, even though I have the same configuration, settings and package imports as in the other project. Due to work it is essential to import the project in the  the first project (where it is not working) and even though 2 developers have tried to fix the issue, no body could actually fix the probelm. Please let me know about your resolution.

![image](https://user-images.githubusercontent.com/26567892/98553595-10637f80-22a0-11eb-89bd-5cc35315af4a.png)

**Comment by zite** [comment]
Sounds like a Unity issue, but you might try deleting your Library folder. It may have caches off a broken version.

**Comment by AlanNZAndersen** [comment]
Thank you, it might well, be I have uninstalled and re-installed the beta plugin many times, until suddenly it started to work. Sadly, I can't really say what the issue was, but that I get it always after just installing Open VR, but now after I restart unity/ or the whole system and it starts the Editor update, then it works.

**Comment by zite** [comment]
Good to hear! You should probably also upgrade to the latest version on the asset store (2.6.1)
