### ISSUE TITLE
Looking for assistance binding controllers. (Paid)

### ISSUE THREAD

**Issue by TerraSame** [ValveSoftware/steamvr_unity_plugin#863]
Hello... I am in need of assistance. 
Uning Unity 2019.4 LTS with latest SteamVR Plugin Version 2.6.1
The project is all set up and working but the linkage for shooting and teleporting needs to be addressed for multiple HMD's and controllers. This work will of course be paid but I am only willing to work directly with a developer, not through a corporation.
If you know how to set this up, we can work together and there will be more work adding new functionality to the project if you care to continue.
Thanks

**Comment by zite** [comment]
Hi, unfortunately this is not a job board. Please find somewhere else to post this.

**Comment by TerraSame** [comment]
Will do...

**Comment by TerraSame** [comment]
Hey Keith... If you know where I might find assistance with the SreamVR
Plugin Version 2.6.1, I will be most grateful for any direction...
Thanks
Paul
