### ISSUE TITLE
Cannot build webgl on multiplatform project

### ISSUE THREAD

**Issue by theDoubi125** [ValveSoftware/steamvr_unity_plugin#869]
I work on a project where I must build a VR version using steamVR, and a webgl version that uses keyboard + mouse. The problem is that once I import the steamVR package, it adds automatically openVR, which is not handled in webgl but unity still tries to include it. The problem comes from the fact that the elements in the Runtime folder (openvr_api, ucrtbased, XRSDKOpenVR) from the openVR package do not exclude the WebGL platform, and as it is in a scoped package, the user cannot change it.

**Comment by zite** [comment]
Thanks for the report. Give this a try: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.7.1RC

**Comment by kisak-valve** [comment]
Closing pending feedback.
