### ISSUE TITLE
Teleport area does not draw outline like in The Lab

### ISSUE THREAD

**Issue by Gotcab** [ValveSoftware/steamvr_unity_plugin#87]
I am implementing a teleport area in a shape that is not square and I would like to display the outline like in The Lab. It is a thick outline following the mesh's border. 

Like this:
![image](https://user-images.githubusercontent.com/18290502/40445685-d881398e-5e9a-11e8-8a65-ec965173b490.png)

But when I use Teleport area in my application there is no such outline. Is it on purpose? Is it because it was not made in Unity and it is not implemented? Also, we can see that the inner texture is less bright, except the big squares. Is it possible with SteamVR?

**Comment by visedo95** [comment]
I'm interesting in teleport with area limitation. How i do?
