### ISSUE TITLE
The correct way for setting up body and head colliders?

### ISSUE THREAD

**Issue by wuannetraam** [ValveSoftware/steamvr_unity_plugin#870]
I am having a hard time with Steam VR and setting up the player mechanics. I have added a capsule collider to the player and a head collider to the camera. I made it also that the position of the body is always in sync with the position of the head. Now the problem we run in to is that when you try to bend over to grab some objects from a table the body is pushed away from the table making it almost impossible to grab the object. I have reduced the radius of the capsule collider but that does not fix the problem.

Any examples that have this done correctly?

**Comment by zite** [comment]
There are a couple packages on the unity asset store that do this, but you could take a look at the way the hands work in the interaction system. For further questions I'll have to direct you to the SteamVR Developers forum as it is a more appropriate place to ask questions like this: https://steamcommunity.com/app/250820/discussions/7/
