### ISSUE TITLE
Player Prefab Duplicates on New Scene

### ISSUE THREAD

**Issue by spatial-lc** [ValveSoftware/steamvr_unity_plugin#871]
I have a scene that has the Player prefab in it. When I load a new scene, the prefab is duplicated. I know that is because it's tagged DontDestroyOnLoad. I've looked at the Player.cs file and see the singleton setup, but there is no code to destroy if a duplicate exists. How should I proceed?

**Comment by zite** [comment]
The interaction system is meant as an example, not a complete solution. I'd recommend destroying it yourself when you want to

**Comment by zite** [comment]
There's also a checkbox on the Player prefab for DoNotDestroy
