### ISSUE TITLE
How do you do action inputs

### ISSUE THREAD

**Issue by josh-65** [ValveSoftware/steamvr_unity_plugin#872]
I have  **if (SteamVR_Actions._default.Pause)**  in the code and i just get  **Assets\_Scripts\pauseMenu.cs(42,13): error CS0029: Cannot implicitly convert type 'Valve.VR.SteamVR_Action_Boolean' to 'bool'.**   I have tried looking but everyone just give different things with no explanation of what there doing or assigning.

![image](https://user-images.githubusercontent.com/26977075/101815049-dc85af00-3b16-11eb-9eba-d715b94b3863.png)

**Comment by zite** [comment]
You'll also need to specify what type of value you want from it, and a hand. For example:
SteamVR_Actions._default.Pause[SteamVR_Input_Sources.LeftHand].stateDown
This would return true on the frame the button was pressed down on the left hand.

**Comment by josh-65** [comment]
ok il try this thanks
