### ISSUE TITLE
VR Hands not updating position HDRP

### ISSUE THREAD

**Issue by josh-65** [ValveSoftware/steamvr_unity_plugin#877]
VR hand wont update their positions and end up just staying at 0 0 0. I have tried multiple projects and it worked once right after upgrading from URP to HDRP but then didn't after re playing the scene

Versions:
Unity 2020.16f1 HDRP pipeline
Steam VR 2.6.1 SDK 1.13.10

**Comment by zite** [comment]
Are there errors in the scene when this is occuring? This plugin doesn't really support HDRP at this point as it isn't optimized for VR.

**Comment by josh-65** [comment]
no

**Comment by josh-65** [comment]
This is still an issue with latest unity and SteamVR versions.

**Comment by josh-65** [comment]
Turn out the skeleton and pose option in steam VR input were not set.
