### ISSUE TITLE
UI and partials only working on left eye HDRP

### ISSUE THREAD

**Issue by josh-65** [ValveSoftware/steamvr_unity_plugin#878]
The UI and partials will only show on the left eye in HDRP

Versions:
Unity 2020.16f1 HDRP pipeline
Steam VR 2.6.1 SDK 1.13.10

**Comment by zite** [comment]
Did this get resolved?

**Comment by josh-65** [comment]
yes with latest unity and steamVR versions

**Comment by zite** [comment]
Great, thanks
