### ISSUE TITLE
Can't build with v2.7.0b

### ISSUE THREAD

**Issue by shiena** [ValveSoftware/steamvr_unity_plugin#879]
target: https://github.com/ValveSoftware/steamvr_unity_plugin/tree/bc86c9dd82c33b432c6d0b63870ea4b96b9e46a7

- Build error in SteamVR_Input.cs as the platform of json.dll is only editor selected
- Build error because the code to be built refers to Unity Editor

**Comment by zite** [comment]
Thanks for the report, give this a try: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.7.1RC

**Comment by shiena** [comment]
I tried 2.7.1RC but the settings in Valve.Newtonsoft.Json.dll have not been modified.

- Valve.Newtonsoft.Json.dll after importing 2.7.1RC  
  <img src="https://user-images.githubusercontent.com/1295639/102680292-40d0fe80-41fa-11eb-9f39-089d6b5a3690.png" width="50%">
- Valve.Newtonsoft.Json.dll after importing 2.6.1  
  <img src="https://user-images.githubusercontent.com/1295639/102680295-4e868400-41fa-11eb-9ac6-900c03212511.png" width="50%">

**Comment by zite** [comment]
Newtonsoft actually shouldn't be included in builds. It is only meant as an editor time thing. We changed the editor only code to #ifdef the unity editor. Give the build a try again and lemme know if you hit the same issue.

**Comment by shiena** [comment]
The script still uses Valve.Newtonsoft.Json.dll.

Steps to reproduce

1. Create a unity2019.4.16f1 project
2. Import https://github.com/ValveSoftware/steamvr_unity_plugin/releases/download/2.7.1RC/steamvr_unity_plugin-2.7.1RC.unitypackage
3. Open SteamVR Input Window and generate SteamVR Input classes
4. Add Interactions_Example scene to Build Settings
5. Build

![image](https://user-images.githubusercontent.com/1295639/102864307-4424ee00-4477-11eb-8f15-7d5c230c3022.png)

**Comment by libaolin51** [comment]
I have the same problem

**Comment by rockround** [comment]
I also do. Unity 2020.2, same errors.

**Comment by zite** [comment]
Okay give the proper 2.7.1 release a go: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.7.1

**Comment by shiena** [comment]
Thank you. It worked fine in 2.7.1.

**Comment by kisak-valve** [comment]
Closing as fixed.
