### ISSUE TITLE
Vive trackers are not working with controllers off

### ISSUE THREAD

**Issue by acrilexstudio** [ValveSoftware/steamvr_unity_plugin#88]
Hello,

In the current state of SteamVR_ControllerManager.cs, the right and left controllers are prioritized over the following SteamVR_Tracked_Object(s). 

A known fix for this implies removing the "if" statement at line 255, because it instructs the controllermanager to assign additional Tracked objects only after both controllers. This should not be the case, as it is possible and legitimate to need to have trackers without controllers. 

Also, we face a problem that when a controller is disabled (lost battery or disconnected), the trackers (or other tracked objects) are also disabled. This should obviously not be the case, as it makes these tracked objects unusable. The suggested fix for this is to comment out lines 233-250 and 271.

I think this should be fixed, as it is not normal for the users of the asset to have to patch it in order to use it.

**Comment by zite** [comment]
This issue should be fixed with the new input system and the SteamVR Plugin 2.0 RC3. You're welcome to try that if you like or wait until it gets merged from beta to main. I'll keep this issue open until that happens.

**Comment by Aranir** [comment]
@zite Could you elaborate a little on how to bind a tracker to the new input system?

As currently, I can only select `Any`, `Left Hand`, `Right Hand` as the input source of a `Steam VR_Behaviour_Pose`

Also in the input bindings, the trackers don't show up for me (currently on the latest version of the beta branch.)

Any advice would be appreciated
