### ISSUE TITLE
Writing text directly to the headset

### ISSUE THREAD

**Issue by TheLazyHatGuy** [ValveSoftware/steamvr_unity_plugin#883]
I am wondering if it is possible to write the text "Step Back" directly to the HMD while using the SteamVR_Fade.View() effect or do I need to try something completely different.

**Comment by zite** [comment]
I don't think the fade script supports text. But you should try posting in the steamvr developer forums instead, this is a place for problems with the plugin. https://steamcommunity.com/app/250820/discussions/7/
