### ISSUE TITLE
Tracked Pose Driver [New Input System] Not working for HDM Tracking Data

### ISSUE THREAD

**Issue by Kinami37** [ValveSoftware/steamvr_unity_plugin#886]
It would not track my HMD at all (Valve Index)

Using the old Tracked Pose Driver fixed the issue, no matter what "position action" or rotation action i would use, no tracking for the HMD.

**Comment by SplunkyDev** [comment]
@Kinami37 my controller and HMD seems to update the position but not rotation. I have already setup an XR Rig using old Trackedpose Driver, I was hoping to switch to the Action Based setup.
my reference: https://www.youtube.com/watch?v=UlqdHrfXppo 
I want to have a XR rig that could be used with keyboard and mouse, this setup seemed time saving and doable. The keyboard mouse works but when I connect the rift only position updates not the rotation.
