### ISSUE TITLE
Crash when using OpenGL

### ISSUE THREAD

**Issue by DrummerB** [ValveSoftware/steamvr_unity_plugin#89]
Using the SteamVR Unity plugin (1.2.3) crashes the Unity Editor (2018.1 - 2018.2.0b10) when using the OpenGLCore graphics API and the Player prefab from SteamVR's interaction system.

How to reproduce:
1. Start a new project using Unity (version 2018.1)
2. Import the SteamVR Unity plugin from the Asset Store (version 1.2.3)
3. Add the Player prefab to the scene (Assets\SteamVR\InteractionSystem\Core\Prefabs\Player.prefab)
4. Change the graphics API to OpenGLCore (Edit > Project Settings > Player > Other Settings > Graphics APIs for Windows)
5. Press play.

This doesn't seem to happen when using DirectX or not using the Player prefab. But with OpenGL, the Player prefab causes a crash 100% of times.

**Comment by DrummerB** [comment]
The crash seems to be caused by the overlay system. If [this line](https://github.com/ValveSoftware/steamvr_unity_plugin/blob/fad02abee8ed45791993e92e420b340f63940aca/Assets/SteamVR/Scripts/SteamVR_Render.cs#L165) is commented out (and the enclosing if statement), the editor no longer crashes on play. I'm not exactly sure which part of the UpdateOverlay() function is causing the crash, since the function can be stepped through without an immediate crash. However, this function sets up a texture for the overlay system to use, including information about the texture type (OpenGL, DirectX etc), so I assume that in the case of an OpenGL texture, something unexpected happens with the overlay texture in the openvr lib.

**Comment by zite** [comment]
This should be fixed in the latest RC, which you can get from the releases page. I'll leave this open until I merge beta to main.
