### ISSUE TITLE
Error: Interface Not Found (105) after updating to 2.7.2

### ISSUE THREAD

**Issue by Shii2** [ValveSoftware/steamvr_unity_plugin#901]
After updating from 2.7.1 to 2.7.2 getting two errors in console: [SteamVR] Interface Not Found (105) and controllers does not appear anymore after launching Simple Sample scene. Tested with Oculus CV1 and Valve Index.
Interactions_Example does not work at all in 2.7.2
Using Unity 2019.4.18f1 and Legacy VR mode.
To verify I made two clean projects with same settings. Imported 2.7.1 into first project and 2.7.2 into second project. First project works fine when second throwing this error. Tested with SteamVR 1.15.19

Full error text:
> UnityEngine.Debug:LogWarning(Object)
> Valve.VR.SteamVR:ReportError(EVRInitError) (at Assets/SteamVR/Scripts/SteamVR.cs:244)
> Valve.VR.SteamVR:CreateInstance() (at Assets/SteamVR/Scripts/SteamVR.cs:182)
> Valve.VR.SteamVR:Initialize(Boolean) (at Assets/SteamVR/Scripts/SteamVR.cs:103)
> Valve.VR.SteamVR_Behaviour_Pose:OnEnable() (at Assets/SteamVR/Input/SteamVR_Behaviour_Pose.cs:88)

**Comment by ict-ryahata** [comment]
I get the same error in my test scene as well as Interaction_Example not working (displays the VR simulator view). Haven't tried downgrading to 2.7.1.

Using Unity 2019.4.19f1 in Legacy VR mode, SteamVR 1.15.19.

**Comment by zite** [comment]
This should be fixed now as of 2.7.3. Sorry about the wait.
