### ISSUE TITLE
Error when using Player Prefab -- Always defaults to fallback

### ISSUE THREAD

**Issue by kechiao** [ValveSoftware/steamvr_unity_plugin#907]
Using the Player prefab was working yesterday, but today, when importing the "Player" prefab and clicking "Play", I get the fallback with "WASD" controls in the "Play" preview.

This does NOT happen when using the [CameraRig] Prefab.

Running Unity 2019.4.18f1
SteamVR Unity Plugin v. 2.7.2
SteamVR Version 1.15.19

Would updating to steamVR beta branch help?

_Originally posted by @kechiao in https://github.com/ValveSoftware/steamvr_unity_plugin/issues/544#issuecomment-773923758_

**Comment by kechiao** [comment]
![image](https://user-images.githubusercontent.com/20604968/107018046-cbdb6900-6754-11eb-8463-5f0bc9871458.png)
![image](https://user-images.githubusercontent.com/20604968/107018071-d269e080-6754-11eb-8845-48f02ac32933.png)
![image](https://user-images.githubusercontent.com/20604968/107018108-dd247580-6754-11eb-8caf-a3e3c22d2776.png)

**Comment by skibitsky** [comment]
We have encountered exactly the same issue. The sample project can be found [here](https://github.com/skibitsky/steamworks-callback-test/tree/steamvr-issue) (branch `steamvr-issue`). Tested on two machines.

OS: Windows 10
Unity: 2019.4.15 LTS and 2019.4.14 LTS
SteamVR; 1.15.19 (1610416788)
SteamVR Unity Plugin: v2.7.2 (sdk 1.14.15)

**Comment by kechiao** [comment]
@skibitsky I'm using SteamVR Unity Plugin v.2.7.1 as a temporary stopgap. Hopefully it helps your project as well. Let's hope they address this issue soon!

**Comment by skibitsky** [comment]
Thank you, @kechiao! Unfortunately, SteamVR Unity Plugin v.2.7.1 didn't work for us.

**Comment by ryan-motive** [comment]
It's possible I'm hitting the same issue: we have our own custom Player prefab, but when we run with the Player prefab in the scene we get the "Not Initialized" error. Interestingly if I unpack the Player prefab it works fine. I tracked it down to an "OnValidate" call in one of the components--if I stub this call out then everything works fine. Very bizarre set of behaviour.

**Comment by kechiao** [comment]
@skibitsky @ryan-motive Unrelated, but when your SteamVR plugins were working, did any of you run into weird issues with either Unity or an editor (I'm using Rider) throwing all sorts of reference / Namespace issues out of nowhere? 

I'm currently running into an issue where line 43 "private MediaTypeNames.Text titleText;" in TeleportPoint.cs throws an error and the only workaround I'm using is to just comment out all usages of this.

**Comment by ryan-motive** [comment]
Haven't seen that, just the not-loading issue.

**Comment by manaliveadam** [comment]
Glad to know it's not just me!  And thanks for the tip, switching to 2.7.1 worked for me.  FWIW I'm on 2019.4, using a Vive Cosmos.

**Comment by Giantbean** [comment]
This is still happening in v2.7.3 with Unity 2019.4.19f1 Using Legacy or XR settings.

**Comment by zite** [comment]
This issue has become a catch all. If you're still experiencing similar issues please create a new issue and include all errors in the console log along with what versions of SteamVR, Unity, SteamVR Unity Plugin you're using
