### ISSUE TITLE
Open Binding UI page Almost Entirely Blank

### ISSUE THREAD

**Issue by cscox21** [ValveSoftware/steamvr_unity_plugin#910]
Hello,

I am working on a new VR project in Unity 2019.4.19f and using the most up-to-date SteamVR asset. I am able to get it working and have tested things out in a new scene i created and the interactable scene too. My issue is trying to create my own ActionSet and then clicking Open Binding UI. When i click that it goes to an almost blank page:

![image](https://user-images.githubusercontent.com/37886273/107249806-504e1600-69f9-11eb-9d8a-d847617ea34e.png)

Typing it in my browser does the same thing. I have tried solutions from these posts:

https://github.com/ValveSoftware/steamvr_unity_plugin/issues/562

https://forum.unity.com/threads/ste...u-port-was-changed-from-8998-to-27062.773162/

However, the lines they say to change it on are different (since this is a newer version of course) and I cannot find the line they are referencing in the SteamVR.cs file. I tried Ctrl-F the bindingurl variable, 8998 and 27062 the pages mention and it still comes up emtpy.

I have tried reimporting SteamVR, I have tried doing another new Project. All of my Google efforts have found a similar issue but cannot seem to solve mine. Any help is greatly appreciated.

**Comment by Giantbean** [comment]
I'm having this issue and it is showing port 27062 in use. What was the solution that led to this being closed please?
