### ISSUE TITLE
defaultIsFullScreen deprecation notice in Unity 2018.1

### ISSUE THREAD

**Issue by dantman** [ValveSoftware/steamvr_unity_plugin#92]
Using SteamVR in Unity 2018.1 gives the following warnings:

> Assets/SteamVR/Editor/SteamVR_Settings.cs(601,21): warning CS0618: &grave; UnityEditor.PlayerSettings.defaultIsFullScreen' is obsolete: &grave; defaultIsFullScreen is deprecated, use fullScreenMode instead'
> Assets/SteamVR/Editor/SteamVR_Settings.cs(614,21): warning CS0618: `UnityEditor.PlayerSettings.d3d11FullscreenMode' is obsolete: `d3d11FullscreenMode is deprecated, use fullScreenMode instead'
> ...

**Comment by zite** [comment]
This should be fixed by the RC for 2.0 but I'll leave this comment open until I merge beta to main. If you'd like to test that check out the releases page.
