### ISSUE TITLE
SteamVR_Settings Input/Pose Update Mode are inversed

### ISSUE THREAD

**Issue by jcrapsey** [ValveSoftware/steamvr_unity_plugin#93]
While messing with the settings I noticed that the options for Input and Pose Update Mode were inversed.

https://github.com/ValveSoftware/steamvr_unity_plugin/blob/f17a611ad5fd5cd93a8583bf33b457ef49853740/Assets/SteamVR/Scripts/SteamVR_Settings.cs#L62-L69

Possible solution could be something like
`return (inputUpdateMode & tocheck) == tocheck;`

**Comment by zite** [comment]
Thanks! I'll fix it in the next RC
