### ISSUE TITLE
Plugin not compiling in Unity 2018.3.14f1

### ISSUE THREAD

**Issue by anepher** [ValveSoftware/steamvr_unity_plugin#945]
After creating a fresh project in Unity 2018.3.14f1, enable OpenVR desktop from package manager, having installed steam and steam VR and installing steamvr unity plugin version Version 2.7.3 I get 3 errors in console and the plugin does not work at all:

Assembly has reference to non-existent assembly 'Unity.XR.OpenVR' (Assets/SteamVR/Input/Editor/SteamVR_Input_Editor.asmdef)
Assembly has reference to non-existent assembly 'Unity.XR.OpenVR' (Assets/SteamVR/Editor/SteamVR_Editor.asmdef)
Assembly has reference to non-existent assembly 'Unity.XR.OpenVR' (Assets/SteamVR/SteamVR.asmdef)

**Comment by anepher** [comment]
After two days no response, is this plugin dead?
For those interested as a workaround I found that version SteamVR_v220 is working without errors. Strange because for the latest patch/release on February it is stated that the backwards compatibility is fixed with Unity 2019 and 2018.

**Comment by zite** [comment]
I would not recommend using version 2.2 as it is quite old and unsupported at this point. That is an odd error you're getting though. Is it possible to upgrade your version of unity to 2018.4?

**Comment by anepher** [comment]
> I would not recommend using version 2.2 as it is quite old and unsupported at this point. That is an odd error you're getting though. Is it possible to upgrade your version of unity to 2018.4?

Thank you very much for your response and advice! I have to assess the implications for upgrading unity to 2018.4 and I will definitely do the upgrade at some point. For the moment this version of plugin is ok because I could map the actions to controllers, teleport/hands are working fine, and I don't have any other integrations with steam VR.
