### ISSUE TITLE
No VIVE controller input or tracking, bindings not saving/applying/doing anything

### ISSUE THREAD

**Issue by Mouledoux** [ValveSoftware/steamvr_unity_plugin#947]
I know it's been posted here many times before, but I can't get the VIVE controllers to appear in my Unity build
Unity 2019.4.21
OpenVR Desktop 2.0.5
SteamVR SDK 2.7.3
SteamVR 1.10.26

I've generated the actions.json
I've checked that the app key has been consistent
I've manually added the build's vrmanifest to Steam>config
I've manually added the actions.json path to the vrmanifest (action in StreamingAssets, vrmanifest next to the build exe)
I cannot rebind them after I launch the app, because who knows, I just can't
If I manually edit the binding it does generate, it still does nothing and no input comes through

I DO get HMD tracking, but even that is finicky sometimes.

I suspect in my case, this could be for 2 reasons:
1. The dev/build machine doesn't have a HMD plugged in, just Steam and SteamVR installed
2. The deploy/test machine has secured write privileges (but the account is an admin w/ access)

Please help, I have been trying to resolve this for literal weeks, and even an empty project with only the SteamVR asset pack WILL NOT WORK

**Comment by Mouledoux** [comment]
More information, just because
I've tried building Mono and IL2CPP
.NET 2.0 and 4.X

I had read that IL2CPP and 4.X only work on low/none asset stripping, but I don't think I've had it work at all.
Mono + 4.X seems to work, but haven't tested much
No combination has ever worked

**Comment by zite** [comment]
You'll need to update your version of SteamVR for it to work. Unfortunately we can't support old versions.

**Comment by Mouledoux** [comment]
Interesting. How far back could I go and it still work?
I can't find it again, but I had a pop up one saying that 1.9.something was the minimum.

Let me try updating

**Comment by zite** [comment]
I'd say you should stick with whatever the latest version on steam is. Is there a reason you're using older versions?

**Comment by Mouledoux** [comment]
It's not by choice. For security reasons, internet access has been restricted on the deployment machines.

Hypothetically though, would an older version of steamvr_untiy_plugin work with an older SteamVR?

**Comment by zite** [comment]
Ah, I see. That's likely a significant part of your issues. Yes, an older version of steamvr unity plugin should work with older steamvr. These days we've been including the version of the sdk that we're shipping with. So for the current version of the SteamVR Unity Plugin (2.7.3) we ship with SDK (SteamVR version) 1.14.15. It's possible it will work with versions prior to that, but that's our target version.

**Comment by Mouledoux** [comment]
Can confirm, updating SteamVR fixed the controllers not appearing, but I still can't save custom bindings.
