### ISSUE TITLE
Beta plugin wrong hand model rotation and wrong controller model with Oculus Touch

### ISSUE THREAD

**Issue by seiferth** [ValveSoftware/steamvr_unity_plugin#95]
Hi,
I'm experimenting with the beta plugin for Unity (steamvr_beta_1_3_b08), I'm on the current beta branch of SteamVR as well. I'm using an Oculus + Touch controllers. When I try the Interactions_Example, there are a couple of bugs:
1) The displayed hand model is rotated compared to the controller and compared to the real world.
2) The displayed controller model is the left handed one for both hands.
3) While the hand seems to be correctly animated (apart from the overall rotation), the controllers themselves are not animated (so when I pul the trigger for example the index finger of the hand moves, but not the trigger on the controller rendermodel).

I've attached an image where you can see the bug:
![openvr unity beta bug](https://user-images.githubusercontent.com/2724494/42871059-bdbd2cb0-8a79-11e8-886a-9b6cafa68312.png)

Cheers,
Hagen

**Comment by jordanvr** [comment]
Hi Hagen,

I had the same issue with the flipped models, and solved it by adding:

`this.transform.localRotation = Quaternion.Euler(0.0f, 180f, 0.0f);`

to Awake() in l\SteamVR\Input\SteamVR_Input_Skeleton.cs

Its a bit hacky, but I'm sure there is a much deeper reason for the error that will be cleared up at some stage, but these seems to work as a temp fix.

**Comment by seiferth** [comment]
I've tried the current Unity plugin v1.3b10, and the problem seems to be gone, so I'm closing this issue.
