### ISSUE TITLE
When I load New Scene With SteamVR_LoadLevel Controllers Freezing

### ISSUE THREAD

**Issue by erolerme** [ValveSoftware/steamvr_unity_plugin#959]
Hey i am working on VR application with unity. I have got some scenes in my project. Everythings are fine first scenes. There is a level i am using a "Player" prefab and when i start a load new scene with SteamVR_LoadLevel .Begin function, next scene loading finely and my HMD running good but the controllers freeze. I am CameraRig in next scene and i destroy Player [SteamVR] gameobject before scene with checkbox (unchecked) inside of inspector. 

I was try Unity SceneManagement, or other things but i can not find a solution. By the way if i run that scene directly, every controller working fine.

Waiting your answers thank you.

**Comment by zite** [comment]
Are there any errors in your console when this happens?

**Comment by erolerme** [comment]
No, just in game controllers freezing. Accualy i was pass this error, because i can not find a solution. I was delete CameraRig object and add a new Player prefab. Whan i did it, then everything is fine. Before this, i check DontDestroyObjects because of maybe there is another vr object. But hierarchy was clear for vr objects. I don't know, maybe there is a bug. By the way, @keithbradner thanks for response.
