### ISSUE TITLE
[Feature Request] Add package.json and add compatibility with unity package manager

### ISSUE THREAD

**Issue by tunbridgep** [ValveSoftware/steamvr_unity_plugin#962]
It should only be a small amount of work to make this compatible with the unity package manager, and should make it a lot easier to update and add to new projects.

More information here:
https://docs.unity3d.com/Manual/CustomPackages.html

**Comment by zite** [comment]
Do you just want those files without a repo that holds them? Unity prefers developers to not use scoped registries in their package manager.

**Comment by tunbridgep** [comment]
Really? I was under the impression that the package manager was effectively
becoming the de-facto standard for distributing plugins and other "library"
style assets.

I guess I could make and use these files privately if needed, I just
thought including them would help out the project, but if Unity doesn't
like it, then it's probably a bad idea.

**Comment by zite** [comment]
We'll keep looking at solutions for better integration, but for now this is the best one.
