### ISSUE TITLE
Access from Teleport script to other game scripts

### ISSUE THREAD

**Issue by JMoreno97** [ValveSoftware/steamvr_unity_plugin#965]
Hello, I need to know when the user teleport to save some data. To do that I need to tell my GameController when the user is teleporting but I can't access my GameController script from the Teleport script. I was looking for some info and I see that is because of the compilation order. Is there any way to solve this?

Thanks!

**Comment by zite** [comment]
If you need to modify the teleport script our recommendation would be to make a copy of it and rename it so it doesn't get overwritten in the future. You can remove the namespace line too.

**Comment by JMoreno97** [comment]
> If you need to modify the teleport script our recommendation would be to make a copy of it and rename it so it doesn't get overwritten in the future. You can remove the namespace line too.

I have tried to duplicate "Teleport", "TeleportArea", "TeleportArc" and "TeleportURPHelper" (as my project is an URP one)and I have removed the namespaces but  I am having the following error:
"Material 'URPTeleportAreaVisible' with Shader 'Universal Render Pipeline/Particles/Unlit' doesn't have a color property '_TintColor'"
I think this is comming from this line of code:
`#if UNITY_URP
		tintColorId = Shader.PropertyToID( "_BaseColor" );
#else
		tintColorId = Shader.PropertyToID("_TintColor");
#endif`
The else part of the code is beeing executed but I am using URP so the first part of the if should be executed. This does not happen with the Teleport prefab that is provided. Also, in my code, the first part of the if is like commented (gray color)
