### ISSUE TITLE
How do I grab action information with minimal setup?

### ISSUE THREAD

**Issue by KellanHiggins** [ValveSoftware/steamvr_unity_plugin#966]
I've set up my actions and they are fine.

I want to set up a simple MonoBehaviour that keeps a current update on whatever the inputs are. I've looked at `SteamVR_Action_Single` but this seems overly complex for what I need.

Ideally, all I need is to call on:

`SteamVR_Action_Single triggerAction` <- assign in inspector.

`float triggerPress = TriggerAction.GetFloat();` and that is it. I can do what I want with the trigger press now.

Is this possible? I've looked at a lot of the documentation over the years and I can't find out how to easily do this.

**Comment by zite** [comment]
That should work as you describe it. You just have to do the generate actions bits in the editor first. And if you don't have a pose behavior in the scene you'll need to initialize SteamVR with SteamVR.Initialize();

**Comment by KellanHiggins** [comment]
I've decided to use another 3rd party open source tool that integrates every possible headset into Unitys XR system. I got it up and running within 5 minutes with zero issues.

I am not trying to come off as a jerk and it's clearly you are working your ass off on this, but I think you need to tell your bosses that the SteamVR plugin is not working as I think you intended it. I think it would be helpful to get someone who is a good game developer but new to VR development to do user testing for using this API. The API is very hard to figure out and throws a lot of errors often. 

I've owned a Vive since 2016, been programming in Unity exclusively since 2014, created 3 or 4 VR prototypes and I found is incredibly difficult to use this. To get it working back in 2019, I had to do some hacks just to get inputs associated. You can see my frustrations from a year ago as well around the hand pose manager and a few other things.

Hope you don't take this as a personal attack. I really want to see SteamVR continue to dominate the PC VR market and I don't want PC VR to die due to difficult APIs.

Happy to discuss more if you want. Please make sure someone managing overall SteamVR (unless that is you of course) to read this.
