### ISSUE TITLE
SteamVR_Input._default.inActions no longer generated in Beta 08 and 09

### ISSUE THREAD

**Issue by jcrapsey** [ValveSoftware/steamvr_unity_plugin#97]
SteamVR_Input._default no longer has inActions reference? Am I missing a change in the documentation? I haven't been able to upgrade to latest beta because of the missing generated inActions code. 

https://steamcommunity.com/sharedfiles/filedetails/?id=1416820276

I was able to reproduce the missing inActions reference by downloading Beta 09, installing it in a new Unity 2018.2.0f2 project and clicking "Save and generate". 

using the following code after adding it in the SteamVR Input UI in unity:
`SteamVR_Input._default.inActions.TrackpadTouch.GetStateDown(SteamVR_Input_Input_Sources.LeftHand);`
I get a null reference for inActions

**Comment by zite** [comment]
Thanks! I'll fix this in the next RC
