### ISSUE TITLE
OpenGL support missing in some SteamVR shaders

### ISSUE THREAD

**Issue by DrummerB** [ValveSoftware/steamvr_unity_plugin#99]
Some of the shaders that are used in the Interaction system explicitly require a DirectX or Vulkan renderer and don't work with OpenGL.

This is how the Interaction demo scene looks like when the graphics API is set to OpenGL:
![](https://i.imgur.com/uBomoWs.png)

Is there a reason for this? Does the interaction system not support OpenGL? It seems like simply enabling the OpenGL renderer in these shaders works just fine. But I wonder why it was disabled in the first place.

Workaround:

Change
 ```#pragma only_renderers d3d11 vulkan```
 to 
```#pragma only_renderers d3d11 vulkan glcore``` 
in the shaders that are affected.

**Comment by zite** [comment]
Thanks! I'll fix this in the next RC
