### ISSUE TITLE
SteamVR_LoadLevel cannot fade to any colors other than black or gray

### ISSUE THREAD

**Issue by lukeng** [ValveSoftware/steamvr_unity_plugin#992]
Hi,
I tried with the script to change scene, but no matter what color I set, the HMD will only fades to black or gray color.

I also tried with the function in OpenVR.Compositor, which has the same result as SteamVR_LoadLevel.cs
```
compositor.FadeToColor(0.5f, backgroundColor.r, backgroundColor.g, backgroundColor.b, backgroundColor.a, true);
```

**Comment by zite** [comment]
You may need to multiply those color values by 255. Can you give that a try and let us know if it works?

**Comment by kisak-valve** [comment]
Closing pending feedback.
